// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../device.dart';
import '../../../error.dart';
import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `filter_wheel_status_poll_states`, `get_sim_filterwheel`, `poll_filter_wheel_position`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FilterWheelStatusPollState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// Get filter wheel status
Future<FilterWheelStatus> apiGetFilterwheelStatus({required String deviceId}) =>
    RustLib.instance.api
        .crateApiDevicesSimulationFilterWheelApiGetFilterwheelStatus(
          deviceId: deviceId,
        );

/// Set filter wheel position
Future<void> apiFilterwheelSetPosition({
  required String deviceId,
  required int position,
}) => RustLib.instance.api
    .crateApiDevicesSimulationFilterWheelApiFilterwheelSetPosition(
      deviceId: deviceId,
      position: position,
    );

/// Get filter names
Future<List<String>> apiFilterwheelGetNames({required String deviceId}) =>
    RustLib.instance.api
        .crateApiDevicesSimulationFilterWheelApiFilterwheelGetNames(
          deviceId: deviceId,
        );

/// Set filter by name
Future<void> apiFilterwheelSetByName({
  required String deviceId,
  required String name,
}) => RustLib.instance.api
    .crateApiDevicesSimulationFilterWheelApiFilterwheelSetByName(
      deviceId: deviceId,
      name: name,
    );

/// Set filter names on a filter wheel
/// This pushes user-defined filter names from the equipment profile to the hardware driver.
Future<void> apiFilterwheelSetFilterNames({
  required String deviceId,
  required List<String> names,
}) => RustLib.instance.api
    .crateApiDevicesSimulationFilterWheelApiFilterwheelSetFilterNames(
      deviceId: deviceId,
      names: names,
    );

class SimulatedFilterWheel {
  final FilterWheelStatus status;

  const SimulatedFilterWheel({required this.status});

  static Future<SimulatedFilterWheel> default_() => RustLib.instance.api
      .crateApiDevicesSimulationFilterWheelSimulatedFilterWheelDefault();

  @override
  int get hashCode => status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimulatedFilterWheel &&
          runtimeType == other.runtimeType &&
          status == other.status;
}
