// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../device.dart';
import '../../../error.dart';
import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `advance_sim_slew`, `angular_separation_deg`, `begin_sim_slew`, `cancel_sim_slew`, `get_sim_mount`, `interpolate_ra`, `pier_side_after_slew_to`, `sim_local_sidereal_time`, `sim_park_position`, `sim_slew_duration_secs`, `sim_slew_in_flight`, `sim_slew`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SimSlew`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Get mount status
Future<MountStatus> apiGetMountStatus({required String deviceId}) => RustLib
    .instance
    .api
    .crateApiDevicesSimulationMountApiGetMountStatus(deviceId: deviceId);

/// Slew mount to coordinates
Future<void> apiMountSlewToCoordinates({
  required String deviceId,
  required double ra,
  required double dec,
}) => RustLib.instance.api
    .crateApiDevicesSimulationMountApiMountSlewToCoordinates(
      deviceId: deviceId,
      ra: ra,
      dec: dec,
    );

/// Sync mount to coordinates
Future<void> apiMountSyncToCoordinates({
  required String deviceId,
  required double ra,
  required double dec,
}) => RustLib.instance.api
    .crateApiDevicesSimulationMountApiMountSyncToCoordinates(
      deviceId: deviceId,
      ra: ra,
      dec: dec,
    );

/// Park the mount
Future<void> apiMountPark({required String deviceId}) => RustLib.instance.api
    .crateApiDevicesSimulationMountApiMountPark(deviceId: deviceId);

/// Unpark the mount
Future<void> apiMountUnpark({required String deviceId}) => RustLib.instance.api
    .crateApiDevicesSimulationMountApiMountUnpark(deviceId: deviceId);

/// Set mount tracking
Future<void> apiMountSetTracking({
  required String deviceId,
  required int enabled,
}) => RustLib.instance.api.crateApiDevicesSimulationMountApiMountSetTracking(
  deviceId: deviceId,
  enabled: enabled,
);

/// Slew mount to alt/az coordinates (simulator handler)
Future<void> apiMountSlewAltAz({
  required String deviceId,
  required double altitude,
  required double azimuth,
}) => RustLib.instance.api.crateApiDevicesSimulationMountApiMountSlewAltAz(
  deviceId: deviceId,
  altitude: altitude,
  azimuth: azimuth,
);

/// Find mount home position (simulator handler)
Future<void> apiMountFindHome({required String deviceId}) => RustLib
    .instance
    .api
    .crateApiDevicesSimulationMountApiMountFindHome(deviceId: deviceId);

/// Pulse guide the mount in a direction for a duration
Future<void> apiMountPulseGuide({
  required String deviceId,
  required String direction,
  required int durationMs,
}) => RustLib.instance.api.crateApiDevicesSimulationMountApiMountPulseGuide(
  deviceId: deviceId,
  direction: direction,
  durationMs: durationMs,
);

class SimulatedMount {
  final MountStatus status;

  const SimulatedMount({required this.status});

  static Future<SimulatedMount> default_() => RustLib.instance.api
      .crateApiDevicesSimulationMountSimulatedMountDefault();

  @override
  int get hashCode => status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimulatedMount &&
          runtimeType == other.runtimeType &&
          status == other.status;
}
