/// Authoritative catalog of every public HTTP endpoint the headless
/// server exposes.
///
/// Extracted from `system_handlers.dart` so the (large) hand-maintained
/// route list lives apart from the info/self-test handler logic that
/// consumes it. Surfaced in two places:
///   * the `endpoints` array on `GET /api/info`,
///   * the OpenAPI route list driving `GET /api/openapi.json`.
///
/// The headless-API contract audit
/// (`tools/production/headless_api_contract_audit.dart`) scans this
/// list and the actual `router.get/post/…` registrations and fails CI
/// if the two drift apart, so any new endpoint must be added here in
/// the same commit that registers it.
library;

/// Returns the authoritative, ordered list of every advertised endpoint.
List<String> availableHeadlessEndpoints() {
  return const [
    // Core
    'GET /api/info',
    'GET /api/status',
    'GET /api/self-test',
    'GET /api/openapi.json',
    'POST /api/pairing/start',
    'POST /api/pairing/verify',
    'POST /api/pairing/lan-claim',
    // admin-only diagnostic listing currently-valid pairing
    // codes so a headless operator on a paired admin client can
    // retrieve the code without watching stdout.
    'GET /api/pairing/active',
    'POST /api/ws/ticket',
    'POST /api/auth/cookie',
    'GET /api/auth/csrf',
    'POST /api/auth/logout',
    'GET /api/collaboration/state',
    'POST /api/collaboration/viewers/join',
    'POST /api/collaboration/viewers/leave',
    'POST /api/collaboration/preview',
    'POST /api/collaboration/chat',
    'POST /api/collaboration/annotations',
    'GET /api/session-handoff',
    'POST /api/session-handoff',
    'DELETE /api/session-handoff',
    'GET /api/devices',
    'GET /api/devices/discover-indi',
    'GET /api/devices/discover-alpaca',
    'GET /api/devices/connected',
    'POST /api/devices/connect',
    'POST /api/devices/disconnect',
    'POST /api/devices/rescan',
    // Camera
    'POST /api/camera/expose',
    'POST /api/camera/abort',
    'GET /api/camera/last-image',
    'GET /api/camera/last-image/jpeg',
    'GET /api/camera/live-view/frame',
    // push-based live-view streaming. Listed alongside the pull
    // endpoint so OpenAPI consumers see both options.
    'WS /ws/live-view',
    // WebRTC datachannel live-view signalling. Operator
    // POSTs an SDP offer, server replies with answer; ICE candidates
    // trickle via POST and an SSE replay channel; DELETE tears down.
    'POST /api/webrtc/live-view/offer',
    'POST /api/webrtc/live-view/ice/<sessionId>',
    'GET /api/webrtc/live-view/ice/<sessionId>/events',
    'DELETE /api/webrtc/live-view/<sessionId>',
    'POST /api/camera/cooling',
    'GET /api/camera/cooling',
    'GET /api/camera/readout-modes',
    'POST /api/camera/readoutMode',
    'POST /api/camera/gain',
    'POST /api/camera/offset',
    'GET /api/camera/recommended-settings',
    // Mount
    'POST /api/mount/slew',
    'POST /api/mount/sync',
    'POST /api/mount/park',
    'POST /api/mount/unpark',
    'POST /api/mount/tracking',
    'POST /api/mount/pulse-guide',
    'POST /api/mount/abort',
    'GET /api/mount/status',
    'POST /api/mount/set-tracking-rate',
    'POST /api/mount/move-axis',
    'POST /api/mount/slew-alt-az',
    'POST /api/mount/find-home',
    // Focuser
    'POST /api/focuser/move-to',
    'POST /api/focuser/move-relative',
    'POST /api/focuser/halt',
    'POST /api/focuser/autofocus/start',
    'POST /api/focuser/autofocus/cancel',
    // Filter Wheel
    'POST /api/filter-wheel/position',
    'GET /api/filter-wheel/position',
    'GET /api/filter-wheel/names',
    'POST /api/filter-wheel/names',
    'POST /api/filter-wheel/set-by-name',
    // Rotator
    'POST /api/rotator/move-to',
    'POST /api/rotator/move-relative',
    'GET /api/rotator/status',
    'POST /api/rotator/halt',
    'POST /api/rotator/sync',
    'POST /api/rotator/set-reverse',
    // PHD2
    'GET /api/phd2/running',
    'GET /api/phd2/probe',
    'POST /api/phd2/connect',
    'POST /api/phd2/disconnect',
    'POST /api/phd2/start-guiding',
    'POST /api/phd2/stop-guiding',
    'POST /api/phd2/dither',
    'GET /api/phd2/status',
    'POST /api/phd2/pause',
    'POST /api/phd2/clear-calibration',
    'POST /api/phd2/flip-calibration',
    'POST /api/phd2/get-calibration-data',
    'POST /api/phd2/find-star',
    'POST /api/phd2/set-lock-position',
    'GET /api/phd2/lock-position',
    'POST /api/phd2/loop',
    'POST /api/phd2/deselect-star',
    'GET /api/phd2/star-image',
    'GET /api/phd2/algo-params',
    'GET /api/phd2/algo-param',
    'POST /api/phd2/algo-param',
    // Generic Guider
    'POST /api/guider/start-guiding',
    'POST /api/guider/stop-guiding',
    'POST /api/guider/dither',
    'POST /api/guider/loop',
    'POST /api/guider/find-star',
    'POST /api/guider/set-lock-position',
    'GET /api/guider/lock-position',
    'POST /api/guider/deselect-star',
    'GET /api/guider/star-image',
    'GET /api/builtin-guider/config',
    'POST /api/builtin-guider/config',
    // Broadcast
    'GET /api/broadcast/info',
    'GET /api/broadcast/live-stack',
    'GET /api/broadcast/sse',
    // Plate Solving
    'POST /api/plate-solve',
    // Plate Solver Setup (host-owned detect/verify/config for remote clients)
    'GET /api/plate-solver/detect',
    'POST /api/plate-solver/verify',
    'GET /api/plate-solver/config',
    'POST /api/plate-solver/config',
    // Sequencer
    'GET /api/sequencer/status',
    'GET /api/sequencer/editor-sequence',
    'POST /api/sequencer/start',
    'POST /api/sequencer/stop',
    'POST /api/sequencer/pause',
    'POST /api/sequencer/resume',
    'POST /api/sequencer/skip',
    'POST /api/sequencer/skip-to-node',
    'POST /api/sequencer/plugin-node-finished',
    'POST /api/sequencer/reset',
    'POST /api/sequencer/load',
    'POST /api/sequencer/load-and-start',
    'POST /api/sequencer/simulation',
    'POST /api/sequencer/devices',
    'POST /api/sequencer/safety-fail-mode',
    'POST /api/sequencer/safety-check-interval',
    'POST /api/sequencer/save-path',
    'POST /api/sequencer/active-sequence-run-id',
    'POST /api/sequencer/decision-logging-enabled',
    // Replay Debug — remote read/write of the host decision log + retention.
    'GET /api/sequencer/replay-debug/decisions',
    'GET /api/sequencer/replay-debug/decisions/count',
    'GET /api/sequencer/replay-debug/settings',
    'POST /api/sequencer/replay-debug/settings/enabled',
    'POST /api/sequencer/replay-debug/settings/retention',
    'POST /api/sequencer/replay-debug/clear',
    'POST /api/sequencer/update-dither-config',
    'POST /api/sequencer/update-meridian-flip-config',
    'POST /api/sequencer/update-location',
    'POST /api/sequencer/update-filter-offsets',
    'POST /api/sequencer/update-pending-integration-carry-over',
    'POST /api/sequencer/update-autofocus-interval',
    'POST /api/sequencer/update-autofocus-config',
    'POST /api/sequencer/update-default-quality-check',
    'POST /api/sequencer/update-reject-folder-path',
    'POST /api/sequencer/update-observer-profile',
    'POST /api/sequencer/update-sky-brightness',
    'POST /api/sequencer/update-default-adaptive-exposure',
    'POST /api/sequencer/clear-default-adaptive-exposure',
    'POST /api/sequencer/checkpoint/dir',
    'GET /api/sequencer/checkpoint/has',
    'GET /api/sequencer/checkpoint/info',
    'POST /api/sequencer/checkpoint/resume',
    'POST /api/sequencer/checkpoint/discard',
    'POST /api/sequencer/checkpoint/save',
    'POST /api/sequencer/recovery/try-now',
    'POST /api/sequencer/recovery/abort',
    'POST /api/sequencer/recovery/update-config',
    'GET /api/sequencer/recovery/current',
    'GET /api/sequencer/recovery/history',
    'POST /api/sequencer/update-cloud-motion',
    'GET /api/sequencer/cloud-motion',
    'POST /api/sequencer/update-conditions-score',
    'GET /api/sequencer/adaptive-swap',
    'POST /api/sequencer/meridian-flip',
    'POST /api/sequencer/update-weather-verdict',
    // Secondary rig (dual-rig dither coordination)
    'GET /api/sequencer/secondary-rig',
    'POST /api/sequencer/secondary-rig/start',
    'POST /api/sequencer/secondary-rig/stop',
    // Equipment Status
    'GET /api/equipment/camera/status',
    'GET /api/equipment/mount/status',
    'GET /api/equipment/focuser/status',
    'GET /api/equipment/filter-wheel/status',
    'GET /api/equipment/rotator/status',
    // Equipment Capabilities
    'GET /api/equipment/camera/capabilities',
    'GET /api/equipment/mount/capabilities',
    'GET /api/equipment/focuser/capabilities',
    'GET /api/equipment/filter-wheel/capabilities',
    'GET /api/equipment/rotator/capabilities',
    // Device Health
    'POST /api/device/heartbeat/start',
    'POST /api/device/heartbeat/stop',
    'GET /api/device/health/<deviceId>',
    // Profiles
    'GET /api/profiles',
    'POST /api/profiles',
    'POST /api/profiles/reorder',
    'POST /api/profiles/default/clear',
    'DELETE /api/profiles/<profileId>',
    'POST /api/profiles/<profileId>/load',
    'POST /api/profiles/<profileId>/default',
    'GET /api/profiles/active',
    // Settings
    'GET /api/settings',
    'POST /api/settings',
    'GET /api/settings/meridian-flip',
    'POST /api/settings/meridian-flip',
    'GET /api/settings/home-assistant',
    'POST /api/settings/home-assistant',
    'GET /api/settings/location',
    'POST /api/settings/location',
    'GET /api/location',
    // Imaging
    'POST /api/imaging/stats',
    'POST /api/imaging/stretch',
    'GET /api/imaging/star-crops',
    'POST /api/imaging/debayer',
    'GET /api/imaging/raw-data',
    'POST /api/imaging/save-fits',
    'POST /api/imaging/save-fits-from-capture',
    'POST /api/imaging/calibrate-file',
    'DELETE /api/imaging/device-image/<deviceId>',
    // Polar Alignment
    'POST /api/polar-alignment/start',
    'POST /api/polar-alignment/all-sky/start',
    'POST /api/polar-alignment/stop',
    // Session Images
    'GET /api/sessions/<sessionId>/images',
    'GET /api/images',
    'GET /api/images/recent',
    'GET /api/images/standalone',
    'POST /api/images',
    'GET /api/images/<imageId>',
    'PUT /api/images/<imageId>',
    'GET /api/images/<imageId>/thumbnail',
    // thumbnail cache management.
    'POST /api/images/backfill-thumbnails',
    'POST /api/images/<imageId>/regenerate-thumbnail',
    'GET /api/images/<imageId>/download',
    'GET /api/sessions/<sessionId>/export/json',
    'GET /api/sessions/<sessionId>/export/csv',
    'GET /api/sessions/<sessionId>/export/html',
    'GET /api/sessions/<sessionId>/export/<format>',
    // Targets
    'GET /api/targets',
    'GET /api/targets/favorites',
    'GET /api/targets/search',
    'GET /api/targets/by-type',
    'GET /api/targets/by-priority',
    'GET /api/targets/<id>',
    'POST /api/targets',
    'PUT /api/targets/<id>',
    'DELETE /api/targets/<id>',
    'POST /api/targets/<id>/favorite',
    'PUT /api/targets/<id>/progress',
    // Sequence Management
    'GET /api/sequence-management/list',
    'GET /api/sequence-management/list-full',
    'GET /api/sequence-management/templates-full',
    'POST /api/sequence-management/save-full',
    'GET /api/sequence-management/summaries',
    'GET /api/sequence-management/versions/<versionId>',
    'GET /api/sequence-management/<id>/full',
    'GET /api/sequence-management/templates',
    'GET /api/sequence-management/<id>',
    'GET /api/sequence-management/<id>/nodes',
    'GET /api/sequence-management/<id>/nodes/<parentNodeId>/children',
    'GET /api/sequence-management/<id>/versions',
    'POST /api/sequence-management',
    'PUT /api/sequence-management/<id>',
    'DELETE /api/sequence-management/<id>',
    'POST /api/sequence-management/<id>/duplicate',
    'PUT /api/sequence-management/<id>/tags',
    'POST /api/sequence-management/<id>/favorite',
    'POST /api/sequence-management/<id>/versions',
    'POST /api/sequence-management/<id>/nodes',
    'PUT /api/sequence-management/nodes/<nodeId>',
    'DELETE /api/sequence-management/nodes/<nodeId>',
    'POST /api/sequence-management/<id>/reorder',
    'POST /api/sequence-management/nodes/<nodeId>/enabled',
    // Flat Wizard
    'POST /api/flat-wizard/calibrate',
    'POST /api/flat-wizard/calibrate-multi',
    'POST /api/flat-wizard/generate-sequence',
    'POST /api/flat-wizard/quick-calibrate',
    // Mosaic
    'POST /api/mosaic/generate-panels',
    'POST /api/mosaic/generate-sequence',
    'POST /api/mosaic/calculate-area',
    'POST /api/mosaic/validate',
    'POST /api/mosaic/estimate-time',
    'GET /api/mosaic/recommended-exposure',
    // Collaborative mosaics (Collaborative Sky WS2) — an unattended rig
    // discovers open collaborative projects, publishes/joins one, claims +
    // uploads a panel master, and drives central assembly + output.
    'GET /api/mosaic/collaborative',
    'GET /api/mosaic/collaborative/<mosaicId>',
    'POST /api/mosaic/projects/<projectId>/publish',
    'POST /api/mosaic/projects/<projectId>/join',
    'GET /api/mosaic/projects/<projectId>/status',
    // A participant with no local project joins by hub mosaic id; the
    // project-scoped join above only LINKS a project the caller already has,
    // which a participant by definition does not.
    'POST /api/mosaic/collaborative/<mosaicId>/join',
    'POST /api/mosaic/projects/<projectId>/panels/<panelIndex>/claim',
    // Self-release, so a mis-claimed panel is not squatted for its full 12h
    // TTL. Distinct from force-release below, which is owner-only.
    'POST /api/mosaic/projects/<projectId>/panels/<panelIndex>/release',
    'POST /api/mosaic/projects/<projectId>/panels/<panelIndex>/force-release',
    'POST /api/mosaic/projects/<projectId>/panels/<panelIndex>/upload',
    'POST /api/mosaic/projects/<projectId>/assemble',
    'POST /api/mosaic/projects/<projectId>/output',
    // Live co-imaging (Collaborative Sky WS3) — N rigs share one target,
    // reporting to the combined accounting and driving the longitude baton.
    'GET /api/coimaging/sessions',
    'POST /api/coimaging/sessions',
    'GET /api/coimaging/sessions/<sessionId>',
    'POST /api/coimaging/sessions/<sessionId>/join',
    'POST /api/coimaging/sessions/<sessionId>/leave',
    'POST /api/coimaging/sessions/<sessionId>/close',
    'POST /api/coimaging/sessions/<sessionId>/contribute',
    'GET /api/coimaging/sessions/<sessionId>/framing-offset',
    'POST /api/coimaging/sessions/<sessionId>/sub-complete',
    'POST /api/coimaging/sessions/<sessionId>/baton/auto',
    'POST /api/coimaging/sessions/<sessionId>/baton/claim',
    'POST /api/coimaging/sessions/<sessionId>/baton/release',
    // Sessions & Analytics
    'GET /api/sessions',
    'GET /api/sessions/active',
    'GET /api/sessions/recent',
    'GET /api/sessions/<id>',
    'GET /api/sessions/<id>/stats',
    'GET /api/sessions/<id>/psf-tiles',
    'GET /api/sessions/<id>/residuals',
    'GET /api/sessions/target/<targetId>',
    'POST /api/sessions',
    'PUT /api/sessions/<id>',
    'POST /api/sessions/<id>/end',
    'DELETE /api/sessions/<id>',
    'GET /api/files/browse',
    'POST /api/files/validate',
    // Science
    'GET /api/science/session/<sessionId>/bundle',
    'GET /api/science/sessionless/recent',
    'GET /api/science/settings',
    'POST /api/science/settings',
    'GET /api/smart-night/settings',
    'POST /api/smart-night/settings',
    'GET /api/science/session/<sessionId>/config',
    'POST /api/science/session/<sessionId>/config',
    'GET /api/science/transforms',
    'POST /api/science/calibration/image/<imageId>/match-stars',
    'POST /api/science/calibration/compute-transform',
    'POST /api/science/calibration/save-transform',
    'POST /api/science/session/<sessionId>/generate-line-ratios',
    'POST /api/science/session/<sessionId>/export/aavso',
    'GET /api/science/session/<sessionId>/report/pdf',
    'GET /api/analytics/summary',
    'GET /api/analytics/integration-time',
    'GET /api/analytics/target-statistics/<targetId>',
    'GET /api/analytics/untracked-targets/count',
    'POST /api/analytics/untracked-targets/remove',
    // Live stacking (EAA real-time integration)
    'POST /api/stacking/start',
    'POST /api/stacking/add-frame',
    'POST /api/stacking/config',
    'POST /api/stacking/reset',
    'POST /api/stacking/stop',
    'GET /api/stacking/status',
    'GET /api/stacking/stats',
    'GET /api/stacking/result',
    'GET /api/stacking/preview',
    'GET /api/stacking/results',
    'GET /api/stacking/results/<resultId>',
    'GET /api/stacking/results/<resultId>/preview',
    // Post-session integration / finishing ("finish last night")
    'GET /api/post-session/settings',
    'POST /api/post-session/settings',
    'POST /api/post-session/integrate',
    'POST /api/post-session/drizzle',
    'POST /api/post-session/analyze-night',
    'POST /api/post-session/build-master-flat',
    'POST /api/post-session/color-calibrate',
    'POST /api/post-session/detect-stars',
    'POST /api/post-session/extract-background',
    'POST /api/post-session/combine-channels',
    'POST /api/post-session/master-accumulate',
    // Imaging / calibration host-compute helpers
    'GET /api/imaging/fits-dimensions',
    'GET /api/calibration/settings',
    'POST /api/calibration/settings',
    'POST /api/calibration/match-dark',
    'POST /api/calibration/defect-maps/build',
    'POST /api/calibration/defect-maps/apply',
    // Weather
    'GET /api/weather/radar',
    'GET /api/weather/forecast',
    'GET /api/weather/alerts',
    'GET /api/weather/cloud-cover',
    'GET /api/weather/settings',
    'POST /api/weather/settings',
    'GET /api/weather/safe-imaging',
    'GET /api/weather/current',
    'POST /api/weather/clear-cache',
    // Suggestions
    'GET /api/suggestions/tonight',
    'GET /api/suggestions/config',
    'GET /api/suggestions/score/<targetId>',
    // Transients
    'GET /api/transients',
    'GET /api/transients/settings',
    'POST /api/transients/settings',
    'GET /api/transients/queued',
    'GET /api/transients/states',
    'DELETE /api/transients/states',
    'POST /api/transients/<id>/queue',
    'POST /api/transients/<id>/dismiss',
    'POST /api/transients/<id>/state',
    'POST /api/transients/refresh',
    // First Light (Pillar B — difference-imaging transient discovery)
    'GET /api/firstlight/candidates',
    'GET /api/firstlight/near',
    'GET /api/firstlight/<id>/crops/<stage>',
    'POST /api/firstlight/<id>/review',
    'POST /api/firstlight/<id>/dismiss',
    'POST /api/firstlight/<id>/submit/tns',
    'POST /api/firstlight/<id>/export/aavso',
    'POST /api/firstlight/<id>/export/mpc',
    // Sky atlas (Pillar A — "Your Sky")
    'GET /api/atlas/regions',
    'POST /api/atlas/regions',
    'GET /api/atlas/coverage',
    'GET /api/atlas/region/<id>',
    'GET /api/atlas/region/<id>/cutout',
    'GET /api/atlas/region/<id>/timeline',
    // Backup
    'GET /api/backup/list',
    'POST /api/backup/create',
    'POST /api/backup/restore',
    'POST /api/backup/auto-save',
    'POST /api/backup/upload-restore',
    'GET /api/backup/<id>/metadata',
    'GET /api/backup/<id>/download',
    'DELETE /api/backup/<id>',
    // Framing
    'POST /api/framing/slew-to-target',
    'POST /api/framing/center-on-target',
    'POST /api/framing/sync',
    'GET /api/framing/current-position',
    'POST /api/framing/rotate-to',
    'POST /api/framing/abort-slew',
    'POST /api/framing/park',
    'POST /api/framing/unpark',
    'POST /api/framing/set-target',
    'POST /api/framing/save',
    // Planetarium (remote client support)
    'GET /api/planetarium/mount-position',
    'GET /api/planetarium/fov-config',
    'POST /api/planetarium/slew-to',
    'POST /api/planetarium/center-on',
    'POST /api/planetarium/sync-to',
    'GET /api/planetarium/catalog/search',
    'GET /api/planetarium/catalog/region',
    'GET /api/planetarium/catalog/object/<objectId>',
    'GET /api/planetarium/subscribe-info',
    'GET /api/planetarium/location',
    // Observing lists (host-backed favorites/lists subsystem)
    'GET /api/observing-lists',
    'GET /api/observing-lists/items',
    'GET /api/observing-lists/listed-catalog-ids',
    'GET /api/observing-lists/containing',
    'POST /api/observing-lists',
    'POST /api/observing-lists/update',
    'DELETE /api/observing-lists',
    'POST /api/observing-lists/duplicate',
    'POST /api/observing-lists/items',
    'DELETE /api/observing-lists/items',
    'POST /api/observing-lists/items/update-notes',
    // Dome
    'POST /api/dome/open',
    'POST /api/dome/close',
    'POST /api/dome/slew',
    'POST /api/dome/sync',
    'POST /api/dome/park',
    'POST /api/dome/home',
    'POST /api/dome/halt',
    'GET /api/dome/status',
    'GET /api/dome/capabilities',
    // Night Narrator (read-only feed for remote clients)
    'GET /api/narrator/feed',
    'GET /api/narrator/recent',
    // Safety Monitor
    'GET /api/safety/status',
    'GET /api/safety/settings',
    'POST /api/safety/settings',
    'POST /api/safety/acknowledge',
    'POST /api/safety/cancel-acknowledgement',
    // Switch
    'GET /api/switch/status',
    'POST /api/switch/set',
    // Cover Calibrator
    'GET /api/cover/status',
    'POST /api/cover/open',
    'POST /api/cover/close',
    'POST /api/cover/brightness',
    'POST /api/cover/calibrator-on',
    'POST /api/cover/calibrator-off',
    // Intelligent Scheduler
    'GET /api/scheduler/preview',
    'GET /api/scheduler/state',
    'POST /api/scheduler/control',
    'POST /api/scheduler/config',
    'GET /api/scheduler/altitude',
    'GET /api/scheduler/transit-time',
    'GET /api/scheduler/rise-set',
    'GET /api/scheduler/hours-above-horizon',
    'POST /api/scheduler/optimize-targets',
    'GET /api/scheduler/twilight-times',
    'GET /api/scheduler/moon-info',
    // Planner/scheduler data tables (host -> slave mirror + slave writes)
    'GET /api/integration-goals',
    'GET /api/integration-goals/captured-count',
    'POST /api/integration-goals',
    'DELETE /api/integration-goals',
    'GET /api/target-constraints',
    'POST /api/target-constraints',
    'POST /api/target-constraints/update',
    'POST /api/target-constraints/set-enabled',
    'DELETE /api/target-constraints',
    'GET /api/scheduler/removed-targets',
    'POST /api/scheduler/removed-targets',
    'DELETE /api/scheduler/removed-targets',
    'GET /api/horizon-profiles',
    'GET /api/projects',
    'GET /api/projects/targets',
    'GET /api/projects/progress',
    // Focus Model
    'GET /api/focus-model/data',
    'POST /api/focus-model/add-point',
    'DELETE /api/focus-model/clear',
    'GET /api/focus-model/model',
    'GET /api/focus-model/predict',
    'GET /api/focus-model/filter-offsets',
    'POST /api/focus-model/filter-offsets',
    'GET /api/focus-model/should-refocus',
    'GET /api/focus-model/export',
    'POST /api/focus-model/import',
    'GET /api/focus-model/predictive',
    'POST /api/focus-model/predictive/config',
    'POST /api/focus-model/predictive/clear-samples',
    'GET /api/focus-model/predictive/export',
    // Long-running operation jobs
    'GET /api/jobs',
    'GET /api/jobs/<jobId>',
    'POST /api/jobs/<jobId>/cancel',
    'DELETE /api/jobs/<jobId>',
    // Session ownership
    'GET /api/session/owner',
    'GET /api/session/status',
    'POST /api/session/claim',
    'POST /api/session/take-over',
    'POST /api/session/release',
    // System / OTA update endpoints
    'GET /api/system/version',
    'GET /api/system/disk-space',
    'POST /api/system/update/check',
    'GET /api/system/update/status',
    'POST /api/system/update/download',
    'POST /api/system/update/apply',
    'POST /api/system/update/abort',
    'POST /api/system/update/rollback',
    'GET /api/system/update/staged',
    'DELETE /api/system/update/staged',
    // WebSocket
    'WS /api/ws',
    'WS /events',
    // Run-Watch (phone/tablet monitoring SPA)
    'GET /api/run-watch/snapshot',
    'GET /api/run-watch/frame-thumbnail',
    'GET /api/run-watch/events',
    // Remote log retrieval / tail
    'GET /api/logs',
    'GET /api/logs/recent',
    'GET /api/logs/files/<filename>/download',
    'GET /api/logs/tail',
    'POST /api/logs/clear',
    'POST /api/logs/test-entry',
    // Remote calibration library management
    'GET /api/calibration/darks',
    'POST /api/calibration/darks',
    'POST /api/calibration/darks/upload',
    'POST /api/calibration/darks/find-match',
    'POST /api/calibration/darks/backfill-sizes',
    'GET /api/calibration/darks/settings',
    'POST /api/calibration/darks/settings',
    'POST /api/calibration/darks/create-master',
    'POST /api/calibration/darks/clean-orphans',
    'POST /api/calibration/darks/clear',
    'POST /api/calibration/darks/delete-group',
    'GET /api/calibration/darks/<id>',
    'GET /api/calibration/darks/<id>/download',
    'DELETE /api/calibration/darks/<id>',
    'GET /api/calibration/flats',
    'POST /api/calibration/flats',
    'GET /api/calibration/flats/recommendation',
    'GET /api/calibration/flats/<id>',
    'DELETE /api/calibration/flats/<id>',
    'GET /api/calibration/defect-maps',
    'POST /api/calibration/defect-maps',
    'GET /api/calibration/defect-maps/status',
    'GET /api/calibration/defect-maps/settings',
    'POST /api/calibration/defect-maps/settings',
    'POST /api/calibration/defect-maps/clear',
    'POST /api/calibration/defect-maps/sequencer-apply',
    'GET /api/calibration/defect-maps/<id>',
    'DELETE /api/calibration/defect-maps/<id>',
    'POST /api/calibration/defect-maps/<id>/regenerate',
    // v46 — unified Calibration Library Manager (hyphenated prefix so it
    // does not collide with the per-table /api/calibration/ surface).
    'GET /api/calibration-library',
    'POST /api/calibration-library/match',
    'POST /api/calibration-library/accept',
    'POST /api/calibration-library/publish',
    'POST /api/calibration-library/retract',
    'PUT /api/calibration-library/<type>/<id>/tags',
    'DELETE /api/calibration-library/<type>/<id>',
    // Mobile push token registry + per-device preferences
    'POST /api/push/register-token',
    'DELETE /api/push/token',
    'GET /api/push/preferences',
    'PUT /api/push/preferences',
    'GET /api/push/targets',
    // Cloud sync
    'GET /api/sync/status',
    'POST /api/sync/push',
    // Catalog management (download / upload / verify / etc.)
    'GET /api/catalog/status',
    'GET /api/catalog/available',
    'POST /api/catalog/download',
    'POST /api/catalog/upload',
    'POST /api/catalog/verify',
    'POST /api/catalog/reload',
    'DELETE /api/catalog/<name>',

    // Read-only DB endpoints (paginated)
    'GET /api/sequence-runs',
    // session replay scrubber: per-run detail + paginated events
    // + paginated frames. Order in registration matters (specific paths
    // before catch-all) but the advertised set is unordered.
    'GET /api/sequence-runs/<runId>',
    'GET /api/sequence-runs/<runId>/events',
    'GET /api/sequence-runs/<runId>/frames',
    'GET /api/notes-journal',
    'POST /api/notes-journal',
    'DELETE /api/notes-journal/<id>',
    'DELETE /api/notes-journal',
    'GET /api/db/notes',
    'POST /api/db/notes',
    'PUT /api/db/notes/<id>',
    'DELETE /api/db/notes/<id>',
    'GET /api/guide-rms-history',
    'GET /api/polar-alignment-history',
    'GET /api/db/dark-library',
    'GET /api/db/flat-history',

    // Plugin management
    'GET /api/plugins',
    'POST /api/plugins/upload',
    'POST /api/plugins/<pluginId>/enable',
    'POST /api/plugins/<pluginId>/disable',
    'DELETE /api/plugins/<pluginId>',
  ];
}
