// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One-shot batch integration of a sub list into a linear FITS master.
///
/// Pipeline: optional calibration (dark/flat/bias) + cosmetic correction →
/// star-based registration to a reference → per-channel normalization →
/// per-sub quality weighting → batch integration with pixel rejection →
/// 16-bit/float linear FITS master + stretched preview PNG.
///
/// `args_json` is an [`IntegrateSessionArgs`]; the result is an
/// [`IntegrateSessionResult`]. All failure modes (no subs, unreadable frame,
/// no consistent geometry, write failure) surface as `Err(String)` — never a
/// silent partial stack.
Future<String> apiIntegrateSession({required String argsJson}) => RustLib
    .instance
    .api
    .crateApiPostSessionEntrypointsApiIntegrateSession(argsJson: argsJson);

/// Multi-night accumulating master. `op` selects the operation:
///
/// * `create`   `{ op, referencePath, sidecarPath, masterFitsPath?, settings?, filter?, target? }`
/// * `add`      `{ op, sidecarPath, lightPaths[], exposuresSec?, calibration?, settings? }`
/// * `finalize` `{ op, sidecarPath, masterFitsPath, previewPngPath? }`
/// * `info`     `{ op, sidecarPath }`
///
/// Returns a [`MasterAccumulateResult`]. The running accumulator state lives in
/// the `.nsmaster` sidecar; the FITS is the shareable artifact written on
/// `finalize` (and re-finalizable after more `add`s).
Future<String> apiMasterAccumulate({required String argsJson}) => RustLib
    .instance
    .api
    .crateApiPostSessionEntrypointsApiMasterAccumulate(argsJson: argsJson);

/// Build a unit-mean master flat from raw flats (+ optional bias / dark-flat
/// pedestal) and write it as a FITS master, wrapping
/// [`build_master_flat`](nightshade_imaging::calibration_masters::build_master_flat).
///
/// `args_json` is a [`BuildMasterFlatArgs`]; the result is a
/// [`BuildMasterFlatResult`].
Future<String> apiBuildMasterFlat({required String argsJson}) => RustLib
    .instance
    .api
    .crateApiPostSessionEntrypointsApiBuildMasterFlat(argsJson: argsJson);

/// Re-export an in-memory pixel buffer as a 16-bit or float FITS master with
/// provenance. The integration paths already write the FITS natively, so this
/// is for re-export from Dart-held buffers.
///
/// `args_json` is a [`SaveFitsMasterArgs`]; the result is a
/// [`SaveFitsMasterResult`].
Future<String> apiSaveFitsMaster({required String argsJson}) => RustLib
    .instance
    .api
    .crateApiPostSessionEntrypointsApiSaveFitsMaster(argsJson: argsJson);
