//! The recipe wire format, the image/context an operation sees, and the
//! [`DarkroomOp`] trait every operation implements.
//!
//! A recipe is *data*: an ordered list of `{opId, opVersion, params, enabled}`
//! records over a named base master. Rendering it replays the operations; the
//! recipe itself never holds pixels, so nothing interpretive is baked into a
//! file the user can lose work in.
//!
//! # Wire format
//!
//! JSON, `camelCase`, versioned by [`RECIPE_SCHEMA_VERSION`]. The same bytes are
//! stored in the Dart-side database, written as a `.nsrecipe` sidecar, and
//! embedded in FITS `HISTORY` cards, so field names are a contract: renaming one
//! breaks recipes already on disk.
//!
//! # Determinism
//!
//! For a fixed `(op_id, op_version, params, input pixels)` an operation produces
//! byte-identical output. That forbids clock reads, randomness without a
//! recipe-carried seed, and any iteration over an unordered collection that
//! reaches pixel values. Improving an algorithm ships a new version and leaves
//! the old one registered.

use std::collections::BTreeMap;
use std::fmt;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};

use crate::fits::FitsHeader;
use crate::wcs_sip::SipWcs;
use crate::{ImageData, PixelType};

/// The only recipe schema version this build reads and writes.
pub const RECIPE_SCHEMA_VERSION: u32 = 1;

/// The pixel budget between cancel polls inside an operation's inner loops.
///
/// An operation that walks more than this many pixels without returning calls
/// [`OpContext::check_cancel`] at least once per this many pixels, so a dawn job
/// aborts at safing instead of running the shutdown budget out.
pub const CANCEL_POLL_PIXELS: usize = 65_536;

// ---------------------------------------------------------------------------
// Recipe model
// ---------------------------------------------------------------------------

/// Who authored a recipe. The morning draft is `autopilot` until the user edits
/// it; the distinction drives "this is a first draft" affordances in the editor.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum RecipeAuthor {
    /// Generated by the dawn autopilot.
    Autopilot,
    /// Created or last authored by the user.
    User,
}

impl RecipeAuthor {
    /// The `camelCase` wire token.
    pub fn as_wire(&self) -> &'static str {
        match self {
            RecipeAuthor::Autopilot => "autopilot",
            RecipeAuthor::User => "user",
        }
    }
}

/// The branch link: a recipe derived from another one, diverging after
/// `divergence_index` steps.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RecipeParent {
    /// Id of the recipe this one branched from.
    pub recipe_id: String,
    /// Number of leading steps shared with the parent. `0` means the branch
    /// diverges immediately; `steps.len()` means it is a pure extension.
    pub divergence_index: usize,
}

/// One operation invocation in a recipe.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RecipeStep {
    /// Registry id of the operation (`background_extract`, `stretch`, ...).
    pub op_id: String,
    /// Registry version of the operation. A recipe keeps rendering with the
    /// version it was written with.
    pub op_version: u32,
    /// Operation parameters, validated by the operation's own
    /// [`DarkroomOp::validate_params`]. Carried opaquely so a recipe written by
    /// a newer op version round-trips through an older reader unchanged.
    #[serde(default = "empty_params")]
    pub params: Value,
    /// `false` renders as if the step were absent; the step and its parameters
    /// survive so the toggle is non-destructive.
    pub enabled: bool,
}

fn empty_params() -> Value {
    Value::Object(Map::new())
}

impl RecipeStep {
    /// A step with an empty parameter object, enabled.
    pub fn new(op_id: impl Into<String>, op_version: u32) -> Self {
        Self {
            op_id: op_id.into(),
            op_version,
            params: empty_params(),
            enabled: true,
        }
    }

    /// The same step with the given parameters.
    pub fn with_params(mut self, params: Value) -> Self {
        self.params = params;
        self
    }

    /// The same step with the given enablement.
    pub fn with_enabled(mut self, enabled: bool) -> Self {
        self.enabled = enabled;
        self
    }
}

/// A non-destructive edit stack over one linear master.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Recipe {
    /// Stable identity of this recipe (the database row id).
    pub id: String,
    /// Wire schema version; see [`RECIPE_SCHEMA_VERSION`].
    pub schema_version: u32,
    /// Identifies the base master's pixels. Two bases that render differently
    /// have different refs — the render cache keys on this string, so reusing a
    /// ref for different pixels serves the wrong image.
    pub base_master_ref: String,
    /// Author of the current step list.
    pub created_by: RecipeAuthor,
    /// Branch link, absent for a root recipe.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent: Option<RecipeParent>,
    /// Operations in application order.
    #[serde(default)]
    pub steps: Vec<RecipeStep>,
}

impl Recipe {
    /// A root recipe with no steps at the current schema version.
    pub fn new(
        id: impl Into<String>,
        base_master_ref: impl Into<String>,
        created_by: RecipeAuthor,
    ) -> Self {
        Self {
            id: id.into(),
            schema_version: RECIPE_SCHEMA_VERSION,
            base_master_ref: base_master_ref.into(),
            created_by,
            parent: None,
            steps: Vec::new(),
        }
    }

    /// Decode a recipe from its wire JSON.
    ///
    /// The schema version is read before the struct is decoded, so a recipe
    /// from a future build reports [`RecipeError::UnsupportedSchemaVersion`]
    /// rather than an unknown-field message.
    pub fn from_json(json: &str) -> Result<Self, RecipeError> {
        let value: Value =
            serde_json::from_str(json).map_err(|e| RecipeError::Decode(e.to_string()))?;
        let found = value
            .get("schemaVersion")
            .and_then(Value::as_u64)
            .ok_or_else(|| RecipeError::Decode("recipe is missing schemaVersion".to_string()))?;
        let found = u32::try_from(found)
            .map_err(|_| RecipeError::UnsupportedSchemaVersion { found: u32::MAX })?;
        if found != RECIPE_SCHEMA_VERSION {
            return Err(RecipeError::UnsupportedSchemaVersion { found });
        }
        serde_json::from_value(value).map_err(|e| RecipeError::Decode(e.to_string()))
    }

    /// Encode a recipe to its wire JSON.
    pub fn to_json(&self) -> Result<String, RecipeError> {
        serde_json::to_string(self).map_err(|e| RecipeError::Encode(e.to_string()))
    }

    /// The canonical form of the step prefix `0..=upto`, restricted to enabled
    /// steps: the string the render cache and the provenance fingerprint agree
    /// on. Object keys are sorted at every depth, so two logically equal
    /// parameter objects always produce the same bytes.
    pub fn canonical_prefix(&self, upto: usize) -> String {
        let end = upto.min(self.steps.len().saturating_sub(1));
        let mut out = String::from("[");
        let mut first = true;
        if !self.steps.is_empty() {
            for step in self.steps.iter().take(end + 1).filter(|s| s.enabled) {
                if !first {
                    out.push(',');
                }
                first = false;
                out.push_str(&canonical_json(&serde_json::json!({
                    "opId": step.op_id,
                    "opVersion": step.op_version,
                    "params": step.params,
                })));
            }
        }
        out.push(']');
        out
    }

    /// Index of the last step, or `None` for an empty recipe.
    pub fn last_index(&self) -> Option<usize> {
        self.steps.len().checked_sub(1)
    }
}

// ---------------------------------------------------------------------------
// Canonical JSON + fingerprint
// ---------------------------------------------------------------------------

/// Render a JSON value with object keys sorted at every depth and no
/// insignificant whitespace.
///
/// Determinism depends on this: `serde_json::Map` iteration order follows the
/// crate's feature configuration, and a cache key built from unsorted keys makes
/// an identical recipe miss (or, with a hash, collide) depending on how the
/// value was constructed.
pub fn canonical_json(value: &Value) -> String {
    let mut out = String::new();
    write_canonical(value, &mut out);
    out
}

fn write_canonical(value: &Value, out: &mut String) {
    match value {
        Value::Null => out.push_str("null"),
        Value::Bool(true) => out.push_str("true"),
        Value::Bool(false) => out.push_str("false"),
        Value::Number(n) => out.push_str(&n.to_string()),
        Value::String(s) => write_json_string(s, out),
        Value::Array(items) => {
            out.push('[');
            for (i, item) in items.iter().enumerate() {
                if i > 0 {
                    out.push(',');
                }
                write_canonical(item, out);
            }
            out.push(']');
        }
        Value::Object(map) => {
            let mut keys: Vec<&String> = map.keys().collect();
            keys.sort_unstable();
            out.push('{');
            for (i, key) in keys.iter().enumerate() {
                if i > 0 {
                    out.push(',');
                }
                write_json_string(key, out);
                out.push(':');
                if let Some(v) = map.get(key.as_str()) {
                    write_canonical(v, out);
                }
            }
            out.push('}');
        }
    }
}

fn write_json_string(s: &str, out: &mut String) {
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
}

const FNV_OFFSET_128: u128 = 0x6c62_272e_07bb_0142_62b8_2175_6295_c58d;
const FNV_PRIME_128: u128 = 0x0000_0000_0100_0000_0000_0000_0000_013b;

/// A 128-bit FNV-1a digest of `bytes`, rendered as 32 lowercase hex digits.
///
/// Used for display and provenance (`HISTORY` cards, log lines). The render
/// cache keys on the canonical string itself, never on this digest, so a digest
/// collision can never serve the wrong cached image.
pub fn fingerprint_hex(bytes: &[u8]) -> String {
    let mut hash = FNV_OFFSET_128;
    for &b in bytes {
        hash ^= b as u128;
        hash = hash.wrapping_mul(FNV_PRIME_128);
    }
    format!("{hash:032x}")
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/// Faults an operation reports to the engine. Every variant names the caller
/// mistake or the missing capability; none of them describe a degraded result
/// that was applied anyway.
#[derive(Debug, Clone, PartialEq, thiserror::Error)]
pub enum OpError {
    /// The parameter payload is not a JSON object.
    #[error("{op_id}@{op_version}: parameters must be a JSON object, found {found}")]
    ParamsNotObject {
        /// Operation id.
        op_id: &'static str,
        /// Operation version.
        op_version: u32,
        /// JSON type of what was supplied.
        found: &'static str,
    },
    /// A parameter key the operation version does not define.
    #[error("{op_id}@{op_version}: unknown parameter '{key}'")]
    UnknownParam {
        /// Operation id.
        op_id: &'static str,
        /// Operation version.
        op_version: u32,
        /// The offending key.
        key: String,
    },
    /// A parameter with no default was not supplied.
    #[error("{op_id}@{op_version}: missing required parameter '{key}'")]
    MissingParam {
        /// Operation id.
        op_id: &'static str,
        /// Operation version.
        op_version: u32,
        /// The missing key.
        key: String,
    },
    /// A parameter has the wrong JSON type.
    #[error("{op_id}@{op_version}: parameter '{key}' must be {expected}, found {found}")]
    ParamType {
        /// Operation id.
        op_id: &'static str,
        /// Operation version.
        op_version: u32,
        /// The offending key.
        key: String,
        /// The type the operation requires.
        expected: &'static str,
        /// The type that was supplied.
        found: &'static str,
    },
    /// A parameter is outside the range the operation accepts.
    #[error("{op_id}@{op_version}: parameter '{key}' = {value} is outside {range}")]
    ParamRange {
        /// Operation id.
        op_id: &'static str,
        /// Operation version.
        op_version: u32,
        /// The offending key.
        key: String,
        /// The rejected value, rendered.
        value: String,
        /// The accepted range, rendered.
        range: String,
    },
    /// The image has zero width, height, or channels, or carries no pixels.
    #[error("image is empty (zero width/height/channels or no pixel data)")]
    EmptyImage,
    /// The declared geometry and the pixel buffer disagree.
    #[error("pixel buffer holds {found} samples, {width}x{height}x{channels} needs {expected}")]
    GeometryMismatch {
        /// Image width in pixels.
        width: u32,
        /// Image height in pixels.
        height: u32,
        /// Channel count.
        channels: u32,
        /// Samples the geometry requires.
        expected: usize,
        /// Samples the buffer holds.
        found: usize,
    },
    /// The source buffer's pixel type has no defined linear reading.
    #[error(
        "unsupported pixel type {found:?} for the recipe engine; linear masters are F32 and U16 is carried as ADU"
    )]
    UnsupportedPixelType {
        /// The pixel type that was supplied.
        found: PixelType,
    },
    /// The operation does not define a result for this channel layout.
    #[error(
        "{op_id}@{op_version}: unsupported channel layout: a {channels}-channel image, {expected}"
    )]
    UnsupportedChannels {
        /// Operation id.
        op_id: &'static str,
        /// Operation version.
        op_version: u32,
        /// Channel count supplied.
        channels: u32,
        /// What the operation requires, in words.
        expected: &'static str,
    },
    /// A capability the operation needs is absent on this install. The engine
    /// records the step as explicitly skipped with this reason and passes the
    /// image through unchanged; it never reports the step as applied.
    #[error("{op_id}@{op_version}: unavailable: {reason}")]
    Unavailable {
        /// Operation id.
        op_id: &'static str,
        /// Operation version.
        op_version: u32,
        /// Why the capability is absent, in the words the user reads.
        reason: String,
    },
    /// The cancel flag was raised while the operation was running.
    #[error("cancelled")]
    Cancelled,
    /// The operation ran and failed for a reason of its own.
    #[error("{op_id}@{op_version}: {reason}")]
    Failed {
        /// Operation id.
        op_id: &'static str,
        /// Operation version.
        op_version: u32,
        /// The underlying failure, already user-readable.
        reason: String,
    },
}

/// Faults the recipe engine reports for a recipe, independent of any one
/// operation's own failures.
#[derive(Debug, Clone, PartialEq, thiserror::Error)]
pub enum RecipeError {
    /// The recipe JSON does not decode.
    #[error("recipe decode failed: {0}")]
    Decode(String),
    /// The recipe does not encode.
    #[error("recipe encode failed: {0}")]
    Encode(String),
    /// The recipe was written by a schema this build does not read.
    #[error(
        "unsupported recipe schema version {found}; this build reads version {RECIPE_SCHEMA_VERSION}"
    )]
    UnsupportedSchemaVersion {
        /// Schema version found in the payload.
        found: u32,
    },
    /// No operation is registered under this id and version.
    #[error("step {index}: no operation registered as {op_id}@{op_version}")]
    UnknownOp {
        /// Step index in the recipe.
        index: usize,
        /// Operation id requested.
        op_id: String,
        /// Operation version requested.
        op_version: u32,
    },
    /// The step's parameters failed the operation's own validation.
    #[error("step {index} ({op_id}@{op_version}) has invalid parameters: {source}")]
    InvalidParams {
        /// Step index in the recipe.
        index: usize,
        /// Operation id.
        op_id: String,
        /// Operation version.
        op_version: u32,
        /// The operation's parameter fault.
        source: Box<OpError>,
    },
    /// A linear-stage operation sits after a stretched-stage operation.
    #[error(
        "step {index} ({op_id}@{op_version}) is a linear-stage operation but step {blocking_index} ({blocking_op_id}) already left the linear stage"
    )]
    StageOrder {
        /// Index of the misplaced linear-stage step.
        index: usize,
        /// Operation id of the misplaced step.
        op_id: String,
        /// Operation version of the misplaced step.
        op_version: u32,
        /// Index of the earliest stretched-stage step.
        blocking_index: usize,
        /// Operation id of that step.
        blocking_op_id: String,
    },
    /// The branch link points past the end of the step list, or at itself.
    #[error("invalid parent link: {reason}")]
    InvalidParent {
        /// What is wrong with the link.
        reason: String,
    },
    /// A render was asked to stop after a step the recipe does not have.
    #[error("step index {index} is out of range; the recipe's step count is {step_count}")]
    StepIndexOutOfRange {
        /// The index that was requested.
        index: usize,
        /// Number of steps in the recipe.
        step_count: usize,
    },
    /// A preview was asked for a pyramid level that was not built.
    #[error("pyramid level {level} is out of range; the pyramid's level count is {level_count}")]
    LevelOutOfRange {
        /// The level that was requested.
        level: u32,
        /// Number of levels the pyramid holds.
        level_count: u32,
    },
    /// The base image is not usable as a render input.
    #[error("base image is not renderable: {source}")]
    BaseImage {
        /// The image fault.
        source: Box<OpError>,
    },
    /// An operation failed while the recipe was rendering.
    #[error("step {index} failed: {source}")]
    Step {
        /// Step index in the recipe.
        index: usize,
        /// The operation's fault.
        source: Box<OpError>,
    },
    /// The cancel flag was raised during the render.
    #[error("cancelled")]
    Cancelled,
}

// ---------------------------------------------------------------------------
// OpImage
// ---------------------------------------------------------------------------

/// The image an operation reads and writes: linear-or-stretched F32 samples plus
/// the FITS header they came with.
///
/// Samples are row-major and channel-interleaved, matching [`ImageData`]: index
/// `(y * width + x) * channels + c`. The header travels with the pixels through
/// the whole stack so astrometry, `DATE-OBS`, `EXPTIME`, `FILTER` and `OBJECT`
/// survive to export. An operation that changes geometry updates the header's
/// geometry keywords; an operation that does not, leaves the header untouched.
#[derive(Debug, Clone)]
pub struct OpImage {
    width: u32,
    height: u32,
    channels: u32,
    data: Vec<f32>,
    header: FitsHeader,
}

impl OpImage {
    /// Build from raw samples. The buffer length must equal
    /// `width * height * channels`.
    pub fn new(
        width: u32,
        height: u32,
        channels: u32,
        data: Vec<f32>,
        header: FitsHeader,
    ) -> Result<Self, OpError> {
        if width == 0 || height == 0 || channels == 0 || data.is_empty() {
            return Err(OpError::EmptyImage);
        }
        let expected = (width as usize) * (height as usize) * (channels as usize);
        if data.len() != expected {
            return Err(OpError::GeometryMismatch {
                width,
                height,
                channels,
                expected,
                found: data.len(),
            });
        }
        Ok(Self {
            width,
            height,
            channels,
            data,
            header,
        })
    }

    /// Read an [`ImageData`] as a render input.
    ///
    /// `F32` samples carry over verbatim. `U16` samples carry over as their ADU
    /// value with no rescaling, so a 16-bit master and a float master of the same
    /// exposure hold the same numbers. Any other pixel type is
    /// [`OpError::UnsupportedPixelType`] — silently reinterpreting the bytes is
    /// how a `U16` reader once ate an `F32` master.
    pub fn from_image_data(image: &ImageData, header: FitsHeader) -> Result<Self, OpError> {
        if image.is_empty() || image.channels == 0 {
            return Err(OpError::EmptyImage);
        }
        let data: Vec<f32> = match image.pixel_type {
            PixelType::F32 => image.data.chunks_exact(4).map(read_le_f32).collect(),
            PixelType::U16 => image
                .data
                .chunks_exact(2)
                .map(|c| u16::from_le_bytes([c[0], c[1]]) as f32)
                .collect(),
            other => return Err(OpError::UnsupportedPixelType { found: other }),
        };
        Self::new(image.width, image.height, image.channels, data, header)
    }

    /// Write the samples back out as an `F32` [`ImageData`].
    pub fn to_image_data(&self) -> ImageData {
        ImageData::from_f32(self.width, self.height, self.channels, &self.data)
    }

    /// Image width in pixels.
    pub fn width(&self) -> u32 {
        self.width
    }

    /// Image height in pixels.
    pub fn height(&self) -> u32 {
        self.height
    }

    /// Channel count (1 = mono, 3 = RGB).
    pub fn channels(&self) -> u32 {
        self.channels
    }

    /// Samples, row-major and channel-interleaved.
    pub fn data(&self) -> &[f32] {
        &self.data
    }

    /// Samples, mutable and in place.
    pub fn data_mut(&mut self) -> &mut [f32] {
        &mut self.data
    }

    /// Number of samples (`width * height * channels`).
    pub fn len(&self) -> usize {
        self.data.len()
    }

    /// Whether the image holds no samples. Never true for a constructed
    /// `OpImage`; present so `len` reads naturally.
    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    /// Number of pixels (`width * height`), independent of channel count.
    pub fn pixel_count(&self) -> usize {
        (self.width as usize) * (self.height as usize)
    }

    /// Heap footprint of the samples, for the render cache's byte budget.
    pub fn byte_size(&self) -> usize {
        self.data.len() * std::mem::size_of::<f32>()
    }

    /// The FITS header travelling with these pixels.
    pub fn header(&self) -> &FitsHeader {
        &self.header
    }

    /// The FITS header, mutable. Used by operations that must keep a geometry or
    /// provenance keyword truthful.
    pub fn header_mut(&mut self) -> &mut FitsHeader {
        &mut self.header
    }

    /// Replace the header wholesale.
    pub fn set_header(&mut self, header: FitsHeader) {
        self.header = header;
    }

    /// A new image with the same geometry and header and different samples.
    pub fn with_data(&self, data: Vec<f32>) -> Result<Self, OpError> {
        Self::new(
            self.width,
            self.height,
            self.channels,
            data,
            self.header.clone(),
        )
    }

    /// A new image with different geometry, carrying this header forward with
    /// `NAXIS1`/`NAXIS2`/`NAXIS3` updated to match.
    ///
    /// Astrometry is *not* adjusted here: a crop also calls
    /// [`OpImage::translate_reference_pixel`], and a resample also scales `CD`,
    /// `CRPIX` and any SIP coefficients.
    pub fn with_geometry(
        &self,
        width: u32,
        height: u32,
        channels: u32,
        data: Vec<f32>,
    ) -> Result<Self, OpError> {
        let mut header = self.header.clone();
        if header.get("NAXIS1").is_some() {
            header.set_int("NAXIS1", width as i64);
        }
        if header.get("NAXIS2").is_some() {
            header.set_int("NAXIS2", height as i64);
        }
        if header.get("NAXIS3").is_some() {
            header.set_int("NAXIS3", channels as i64);
        }
        Self::new(width, height, channels, data, header)
    }

    /// Move the WCS reference pixel by a crop origin of `(dx, dy)` pixels, so a
    /// cropped image keeps pointing at the same sky.
    pub fn translate_reference_pixel(&mut self, dx: f64, dy: f64) {
        if let Some(crpix1) = self.header.get_float("CRPIX1") {
            self.header.set_float("CRPIX1", crpix1 - dx);
        }
        if let Some(crpix2) = self.header.get_float("CRPIX2") {
            self.header.set_float("CRPIX2", crpix2 - dy);
        }
    }

    /// The astrometry carried in the header, if it holds a complete `CRVAL` +
    /// `CRPIX` + `CD` set. SIP terms are read when `A_ORDER`/`B_ORDER` are
    /// present and default to a CD-only solution otherwise.
    pub fn wcs(&self) -> Option<SipWcs> {
        wcs_from_header(&self.header)
    }
}

fn read_le_f32(chunk: &[u8]) -> f32 {
    f32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]])
}

/// Read a [`SipWcs`] out of a FITS header.
///
/// Returns `None` unless `CRVAL1/2`, `CRPIX1/2` and all four `CD` terms are
/// present and the CD matrix is non-degenerate, so a caller never folds a frame
/// whose astrometry cannot be inverted.
pub fn wcs_from_header(header: &FitsHeader) -> Option<SipWcs> {
    let crval1 = header.get_float("CRVAL1")?;
    let crval2 = header.get_float("CRVAL2")?;
    let crpix1 = header.get_float("CRPIX1")?;
    let crpix2 = header.get_float("CRPIX2")?;
    let cd1_1 = header.get_float("CD1_1")?;
    let cd1_2 = header.get_float("CD1_2")?;
    let cd2_1 = header.get_float("CD2_1")?;
    let cd2_2 = header.get_float("CD2_2")?;
    let det = cd1_1 * cd2_2 - cd1_2 * cd2_1;
    if !det.is_finite() || det == 0.0 {
        return None;
    }
    let a_order = header.get_int("A_ORDER").unwrap_or(0).max(0) as u32;
    let b_order = header.get_int("B_ORDER").unwrap_or(0).max(0) as u32;
    let ap_order = header.get_int("AP_ORDER").unwrap_or(0).max(0) as u32;
    let bp_order = header.get_int("BP_ORDER").unwrap_or(0).max(0) as u32;
    Some(SipWcs {
        crval1,
        crval2,
        crpix1,
        crpix2,
        cd1_1,
        cd1_2,
        cd2_1,
        cd2_2,
        a_order,
        b_order,
        a_coeffs: read_sip_coeffs(header, "A", a_order),
        b_coeffs: read_sip_coeffs(header, "B", b_order),
        ap_order,
        bp_order,
        ap_coeffs: read_sip_coeffs(header, "AP", ap_order),
        bp_coeffs: read_sip_coeffs(header, "BP", bp_order),
    })
}

/// SIP coefficients for one polynomial, packed row-major as `i*(order+1)+j`.
/// Absent terms are zero, which is the FITS convention for an omitted card.
fn read_sip_coeffs(header: &FitsHeader, prefix: &str, order: u32) -> Vec<f64> {
    if order == 0 {
        return Vec::new();
    }
    let n = (order + 1) as usize;
    let mut coeffs = vec![0.0_f64; n * n];
    for i in 0..n {
        for j in 0..n {
            if let Some(v) = header.get_float(&format!("{prefix}_{i}_{j}")) {
                coeffs[i * n + j] = v;
            }
        }
    }
    coeffs
}

// ---------------------------------------------------------------------------
// Catalog handle
// ---------------------------------------------------------------------------

/// One catalogue star with genuine photometry, in degrees.
///
/// `b_minus_v` is a catalogue measurement. A value derived from the frame's own
/// instrumental magnitude makes the colour fit circular and is never supplied
/// here; a star without a real `B − V` is left out of the result.
#[derive(Debug, Clone, PartialEq)]
pub struct CatalogStar {
    /// Right ascension in degrees.
    pub ra_deg: f64,
    /// Declination in degrees.
    pub dec_deg: f64,
    /// Johnson V magnitude.
    pub v_mag: f64,
    /// Johnson `B − V` colour index.
    pub b_minus_v: f64,
}

/// Faults a photometric catalogue reports.
#[derive(Debug, Clone, PartialEq, thiserror::Error)]
pub enum CatalogError {
    /// No catalogue data covers this field on this install.
    #[error("photometric catalog unavailable: {reason}")]
    Unavailable {
        /// Why no catalogue is usable, in the words the user reads.
        reason: String,
    },
    /// The catalogue was reachable and the query failed.
    #[error("photometric catalog query failed: {reason}")]
    QueryFailed {
        /// The underlying failure.
        reason: String,
    },
}

/// The photometry source an operation queries.
///
/// The shipped photometry is Johnson B and V (HYG `ci`, APASS DR9); there is no
/// Gaia BP/RP and no filter-transmission database, so an implementation returns
/// `B − V` only.
pub trait PhotometryCatalog: Send + Sync {
    /// Stars with genuine `B − V` inside `radius_deg` of `(ra_deg, dec_deg)`,
    /// down to `mag_limit` in V.
    ///
    /// The order of the returned stars is part of the determinism contract: an
    /// implementation returns them in a stable order for a fixed query.
    fn cone_search(
        &self,
        ra_deg: f64,
        dec_deg: f64,
        radius_deg: f64,
        mag_limit: f64,
    ) -> Result<Vec<CatalogStar>, CatalogError>;

    /// A short, stable digest of the star data this catalogue answers from.
    ///
    /// [`OpContext::identity`] carries it into the render cache key verbatim, so
    /// two catalogues whose answers differ key differently and neither can be
    /// served a boundary the other produced. Two handles that would answer every
    /// query alike return the same string; anything that can reach a pixel —
    /// a star added, a magnitude corrected, a colour index revised — changes it.
    ///
    /// It is a digest rather than the data itself because the key is stored as a
    /// string: an implementation over a million stars returns a fingerprint of
    /// them, not the list.
    fn identity(&self) -> String;
}

// ---------------------------------------------------------------------------
// OpContext
// ---------------------------------------------------------------------------

/// Everything an operation needs beyond its image and parameters.
///
/// The context is read-only to an operation: it carries handles and the render's
/// scale, never a channel back to the engine. Two renders of the same recipe
/// with equivalent contexts produce identical pixels.
#[derive(Clone)]
pub struct OpContext {
    cancel: Arc<AtomicBool>,
    catalog: Option<Arc<dyn PhotometryCatalog>>,
    wcs: Option<SipWcs>,
    level: u32,
}

impl Default for OpContext {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Debug for OpContext {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("OpContext")
            .field("cancel_requested", &self.cancel_requested())
            .field("catalog", &self.catalog.is_some())
            .field("wcs", &self.wcs.is_some())
            .field("level", &self.level)
            .finish()
    }
}

impl OpContext {
    /// A context with no cancel raised, no catalogue, no plate solve, at full
    /// resolution.
    pub fn new() -> Self {
        Self {
            cancel: Arc::new(AtomicBool::new(false)),
            catalog: None,
            wcs: None,
            level: 0,
        }
    }

    /// Share an externally owned cancel flag. The owner raises it at safing; the
    /// engine and every operation poll it.
    pub fn with_cancel(mut self, cancel: Arc<AtomicBool>) -> Self {
        self.cancel = cancel;
        self
    }

    /// Attach a photometric catalogue. Operations that need one and find none
    /// return [`OpError::Unavailable`], which the engine records as an explicit
    /// skip.
    pub fn with_catalog(mut self, catalog: Arc<dyn PhotometryCatalog>) -> Self {
        self.catalog = Some(catalog);
        self
    }

    /// Attach the base master's plate solve. Absent when the master carries no
    /// astrometry.
    pub fn with_wcs(mut self, wcs: SipWcs) -> Self {
        self.wcs = Some(wcs);
        self
    }

    /// The pyramid level this render runs at.
    pub fn at_level(mut self, level: u32) -> Self {
        self.level = level;
        self
    }

    /// The shared cancel flag, for handing to a nested worker.
    pub fn cancel_flag(&self) -> Arc<AtomicBool> {
        Arc::clone(&self.cancel)
    }

    /// Whether cancellation has been requested.
    pub fn cancel_requested(&self) -> bool {
        self.cancel.load(Ordering::Relaxed)
    }

    /// Raise the cancel flag.
    pub fn request_cancel(&self) {
        self.cancel.store(true, Ordering::Relaxed);
    }

    /// `Err(OpError::Cancelled)` once cancellation has been requested. Called at
    /// least once per [`CANCEL_POLL_PIXELS`] pixels inside a long loop.
    pub fn check_cancel(&self) -> Result<(), OpError> {
        if self.cancel_requested() {
            Err(OpError::Cancelled)
        } else {
            Ok(())
        }
    }

    /// The photometric catalogue, if one is attached.
    pub fn catalog(&self) -> Option<&Arc<dyn PhotometryCatalog>> {
        self.catalog.as_ref()
    }

    /// The base master's astrometry, if it is known.
    pub fn wcs(&self) -> Option<&SipWcs> {
        self.wcs.as_ref()
    }

    /// The pyramid level: `0` is full resolution, `n` is a `2^n` downsample.
    pub fn level(&self) -> u32 {
        self.level
    }

    /// Linear size of a rendered pixel relative to the base master: `1 / 2^level`.
    /// An operation whose parameters are in pixels (radii, kernel widths, sample
    /// grid spacing) multiplies them by this so a preview looks like the full
    /// render.
    pub fn scale(&self) -> f64 {
        1.0 / (1u64 << self.level.min(63)) as f64
    }

    /// The parts of the context that can reach a pixel value, as a stable
    /// string. The render cache carries it, so changing the plate solve, the
    /// pyramid level, or the photometry invalidates the boundaries that
    /// depended on it.
    ///
    /// A catalogue contributes [`PhotometryCatalog::identity`], not merely its
    /// presence: a handle whose stars changed keys differently, so no caller has
    /// to clear the cache to keep one star list's colours out of another's
    /// render.
    pub fn identity(&self) -> String {
        let mut out = match &self.catalog {
            None => format!("L{}|cat:0", self.level),
            Some(catalog) => format!("L{}|cat:1:{}", self.level, catalog.identity()),
        };
        match &self.wcs {
            None => out.push_str("|wcs:0"),
            Some(w) => {
                let full = format!(
                    "{},{},{},{},{},{},{},{},{},{},{},{},{:?},{:?},{:?},{:?}",
                    w.crval1,
                    w.crval2,
                    w.crpix1,
                    w.crpix2,
                    w.cd1_1,
                    w.cd1_2,
                    w.cd2_1,
                    w.cd2_2,
                    w.a_order,
                    w.b_order,
                    w.ap_order,
                    w.bp_order,
                    w.a_coeffs,
                    w.b_coeffs,
                    w.ap_coeffs,
                    w.bp_coeffs,
                );
                out.push_str(&format!("|wcs:1:{}", fingerprint_hex(full.as_bytes())));
            }
        }
        out
    }
}

// ---------------------------------------------------------------------------
// The operation trait
// ---------------------------------------------------------------------------

/// The pixel domain an operation *emits*.
///
/// A `Linear` operation reads and writes linear data. A `Stretched` operation
/// emits display-domain data: `stretch` is `Stretched` because it leaves the
/// linear stage, and `curves`/`saturation` are `Stretched` because they work
/// there. The engine enforces one ordering rule from this: no `Linear` operation
/// may sit after a `Stretched` one.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum OpStage {
    /// Emits linear data.
    Linear,
    /// Emits stretched (display-domain) data.
    Stretched,
}

impl OpStage {
    /// The `camelCase` wire token.
    pub fn as_wire(&self) -> &'static str {
        match self {
            OpStage::Linear => "linear",
            OpStage::Stretched => "stretched",
        }
    }
}

/// What one application of an operation produced: the image, and anything the
/// operation solved on the way to it.
///
/// The measurement exists because some operations compute a number the caller
/// must be able to read back — `color_calibrate@1` fits per-channel scales that
/// a draft then pins into the step, so every later preview replays the balance
/// instead of re-fitting at a level that holds too few stars. Without a slot for
/// it the fit would have to be repeated outside the render to be seen.
#[derive(Debug, Clone)]
pub struct OpApplied {
    /// The image the operation produced.
    pub image: OpImage,
    /// What the operation solved while it ran, as the step report's detail, or
    /// `None` when its parameters already describe its result in full.
    ///
    /// It is derived from the same work that produced the pixels, so it obeys
    /// the same determinism contract: a fixed `(version, params, image)` reports
    /// the same measurement on every run.
    pub measurement: Option<Value>,
}

impl OpApplied {
    /// An application that measured nothing beyond its own parameters.
    pub fn plain(image: OpImage) -> Self {
        Self {
            image,
            measurement: None,
        }
    }

    /// An application carrying `measurement` for the render report.
    pub fn measured(image: OpImage, measurement: Value) -> Self {
        Self {
            image,
            measurement: Some(measurement),
        }
    }
}

/// One interpretation operation.
///
/// An implementation is pure: for a fixed `(version, params, image)` it produces
/// byte-identical output on every run, on every thread count. It reads no clock,
/// draws no randomness that is not seeded from `params`, and iterates no
/// unordered collection on a path that reaches a pixel value.
pub trait DarkroomOp: Send + Sync {
    /// Registry id, stable across versions (`background_extract`, `stretch`).
    fn id(&self) -> &'static str;

    /// Registry version. A behaviour change ships a new version; the old
    /// implementation stays registered so existing recipes keep rendering.
    fn version(&self) -> u32;

    /// Accept or reject a parameter payload without touching pixels.
    ///
    /// Rejects unknown keys, wrong types and out-of-range values. Every
    /// parameter the operation reads in [`DarkroomOp::apply`] is either checked
    /// here or has a documented default, so `apply` never has to decide what a
    /// malformed payload means.
    fn validate_params(&self, params: &Value) -> Result<(), OpError>;

    /// Apply the operation.
    ///
    /// `params` has already passed [`DarkroomOp::validate_params`]. Returning
    /// [`OpError::Unavailable`] records the step as explicitly skipped with the
    /// given reason and passes the image through; every other error aborts the
    /// render.
    fn apply(&self, image: &OpImage, params: &Value, ctx: &OpContext) -> Result<OpImage, OpError>;

    /// Apply the operation and report what it solved while doing so.
    ///
    /// This is what the engine calls, and its image is
    /// [`DarkroomOp::apply`]'s image: an operation that measures something the
    /// caller reads back implements this one and defines `apply` in terms of it,
    /// so the solve runs once and the two entry points cannot drift. The default
    /// measures nothing, which is the truthful answer for an operation whose
    /// parameters already describe its result.
    fn apply_measured(
        &self,
        image: &OpImage,
        params: &Value,
        ctx: &OpContext,
    ) -> Result<OpApplied, OpError> {
        Ok(OpApplied::plain(self.apply(image, params, ctx)?))
    }

    /// The pixel domain this operation emits.
    fn stage(&self) -> OpStage;
}

/// A registry lookup key, ordered so iteration is stable.
pub(crate) type OpKey = (String, u32);

/// Registered operations, keyed by `(id, version)`.
pub(crate) type OpMap = BTreeMap<OpKey, Arc<dyn DarkroomOp>>;

#[cfg(test)]
#[path = "model_tests.rs"]
mod model_tests;
