import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

class NightshadeLocalizations {
  final Locale locale;

  NightshadeLocalizations(this.locale);

  static const supportedLocales = [
    Locale('en'),
    Locale('es'),
  ];

  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates = [
    _NightshadeLocalizationsDelegate(),
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ];

  static NightshadeLocalizations of(BuildContext context) {
    final localizations = Localizations.of<NightshadeLocalizations>(
      context,
      NightshadeLocalizations,
    );
    return localizations ?? NightshadeLocalizations(const Locale('en'));
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appTitle': 'Nightshade',
      'cancel': 'Cancel',
      'clearGoal': 'Clear Goal',
      'closeAnyway': 'Close Anyway',
      'closeNightshadeBody':
          'A capture session is in progress. Are you sure you want to close the application? The current capture will be aborted.',
      'closeNightshadeTitle': 'Close Nightshade?',
      'collapse': 'Collapse',
      'connect': 'Connect',
      'dashboardTitle': 'Dashboard',
      'dashboardTourDescription':
          'Learn about the dashboard controls and status displays.',
      'dashboardTourTitle': 'Dashboard Tour',
      'disconnectedBanner': 'Error: not connected to server',
      'generalAutoConnect': 'Auto-connect equipment',
      'generalAutoConnectDesc': 'Connect to last used devices on startup',
      'generalAutoSaveSequences': 'Auto-save sequences',
      'generalAutoSaveSequencesDesc': 'Automatically save sequence changes',
      'generalBehavior': 'Behavior',
      'generalConfirmBeforeClosing': 'Confirm before closing',
      'generalConfirmBeforeClosingDesc':
          'Show confirmation when closing during capture',
      'generalDescription': 'Basic application settings',
      'generalLanguage': 'Language',
      'generalLanguageDesc': 'Choose the language used for app chrome',
      'generalStartMinimized': 'Start minimized',
      'generalStartMinimizedDesc': 'Launch app minimized to system tray',
      'generalStartup': 'Startup',
      'generalTitle': 'General',
      'languageEnglish': 'English',
      'languageSpanish': 'Spanish',
      'mobileEnterIp': 'Enter IP',
      'mobileErrorLoadingApp': 'Error Loading App',
      'mobileHowToConnect': 'How to Connect',
      'mobileHowToConnectSteps':
          '1. Make sure Nightshade is running in headless mode on Windows or Raspberry Pi\n2. Ensure both devices are on the same network\n3. Tap "Search for Server" or wait for automatic discovery\n4. The full desktop UI will load automatically',
      'mobileNotConnected': 'Not Connected',
      'mobileRetry': 'Retry',
      'mobileScanQr': 'Scan QR',
      'mobileSearchingForServer': 'Searching for server...',
      'mobileServerIpAddress': 'Server IP Address',
      'mobileSkipConnection': 'Skip Connection (View UI Only)',
      'navAnalytics': 'Analytics',
      'navAnalyticsDesc': 'Session stats',
      'navDashboard': 'Dashboard',
      'navDashboardDesc': 'Overview & status',
      'navEquipment': 'Equipment',
      'navEquipmentDesc': 'Connect devices',
      'navFlatWizard': 'Flat Wizard',
      'navFlatWizardDesc': 'Calibration',
      'navFraming': 'Framing',
      'navFramingDesc': 'Plan shots',
      'navGuiding': 'Guiding',
      'navGuidingDesc': 'PHD2 control',
      'navImaging': 'Imaging',
      'navImagingDesc': 'Capture & focus',
      'navPlanetarium': 'Planetarium',
      'navPlanetariumDesc': 'Sky view',
      'navSequencer': 'Sequencer',
      'navSequencerDesc': 'Automation',
      'navWeather': 'Weather',
      'navWeatherDesc': 'Cloud radar',
      'navPlanner': 'Plan Tonight',
      'navPlannerDesc': 'Session optimizer',
      'navMore': 'More',
      'navMoreDesc': 'Additional tools',
      'save': 'Save',
      'searchForServer': 'Search for Server',
      'settingsAbout': 'About',
      'settingsAnnotations': 'Annotations',
      'settingsAppearance': 'Appearance',
      'settingsAutofocus': 'Autofocus',
      'settingsCalibration': 'Calibration',
      'settingsCatalogs': 'Catalogs',
      'settingsConnection': 'Connection',
      'settingsDarkLibrary': 'Dark Library',
      'settingsEquipmentProfiles': 'Equipment Profiles',
      'settingsFilePaths': 'File Paths',
      'settingsGeneral': 'General',
      'settingsHelpTutorials': 'Help & Tutorials',
      'settingsImaging': 'Imaging',
      'settingsLocation': 'Location',
      'settingsNotifications': 'Notifications',
      'settingsPhd2Guiding': 'PHD2 Guiding',
      'settingsPlateSolving': 'Plate Solving',
      'settingsPlugins': 'Plugins',
      'settingsRemoteAccess': 'Remote Access',
      'settingsScience': 'Science',
      'settingsSequencer': 'Sequencer',
      'settingsLogs': 'Logs',
      'settingsAutoSave': 'Auto-Save',
      'settingsObservationLog': 'Observation Log',
      'settingsObservingLists': 'Observing Lists',
      'settingsTitle': 'Settings',
      'settingsTourDescription':
          'Learn how to configure your Nightshade preferences.',
      'settingsTourTitle': 'Settings Tour',
      'settingsWeatherSafety': 'Weather Safety',
      'share': 'Share',
      'analyticsAllTargets': 'All Targets',
      'analyticsAllTime': 'All Time',
      'analyticsAvgHfr': 'Avg HFR',
      'analyticsAvgRms': 'Avg RMS',
      'analyticsCapturedImages': 'Captured Images',
      'analyticsClearGoal': 'Clear Goal',
      'analyticsComplete': 'Complete',
      'analyticsCurrentSession': 'Current Session',
      'analyticsCustomTarget': 'Custom target',
      'analyticsDiagnostics': 'Diagnostics',
      'analyticsDuration': 'Duration',
      'analyticsEditGoal': 'Edit Goal',
      'analyticsEquipmentStats': 'Equipment Stats',
      'analyticsExposures': 'Exposures',
      'analyticsExportCsv': 'Export to CSV',
      'analyticsExportHtml': 'Export HTML report',
      'analyticsExportJson': 'Export to JSON',
      'analyticsFailed': 'Failed',
      'analyticsFrames': 'Frames',
      'analyticsGoal': 'Goal',
      'analyticsGoalDialogTitle': 'Set integration goal for {target}',
      'analyticsGoalHours': 'Goal integration (hours)',
      'analyticsHistory': 'History',
      'analyticsImages': 'Images ({count})',
      'analyticsIntegrated': 'Integrated',
      'analyticsIntegration': 'Integration',
      'analyticsLastImaged': 'Last imaged {time}',
      'analyticsNoActiveSession': 'No Active Session',
      'analyticsNoProjects': 'No targets available for project tracking yet.',
      'analyticsNoSessionHistory': 'No session history',
      'analyticsNoSessionHistoryDesc':
          'Complete an imaging session to see history here',
      'analyticsNoSessionInProgress': 'No session in progress',
      'analyticsNotSet': 'Not set',
      'analyticsProjects': 'Projects',
      'analyticsQualityAdvisory':
          'Quality labels are advisory only. No frames are deleted or auto-rejected.',
      'analyticsQuickCapture': 'Quick Capture',
      'analyticsQuickCaptureSubtitle':
          'Standalone snapshots taken outside sequences',
      'analyticsRemaining': 'Remaining',
      'analyticsSave': 'Save',
      'analyticsScience': 'Science',
      'analyticsSearchSessions': 'Search sessions...',
      'analyticsSession': 'Session',
      'analyticsSessionInProgress': 'Session in progress',
      'analyticsSessions': 'Sessions',
      'analyticsSetGoal': 'Set Goal',
      'analyticsStarted': 'Started: {time}',
      'analyticsStatistics': 'Statistics',
      'analyticsSuccessful': 'Successful',
      'analyticsThisMonth': 'This Month',
      'analyticsThisYear': 'This Year',
      'analyticsTotalExposures': 'Total Exposures',
      'analyticsTourDescription':
          'Learn how to analyze your imaging data and session statistics.',
      'analyticsTourTitle': 'Analytics Tour',
      'analyticsUnnamedSession': 'Unnamed Session',
      'weatherSafetyActions': 'Safety Actions',
      'weatherSafetyAlertDistance': 'Alert distance',
      'weatherSafetyAlertDistanceDesc':
          'Generate radar alerts within this distance of your site',
      'weatherSafetyAlertTiming': 'Alert Timing',
      'weatherSafetyAutoPark': 'Auto-park mount',
      'weatherSafetyAutoParkDesc':
          'Park automatically when the safety monitor trips',
      'weatherSafetyAutoResume': 'Auto-resume after clear',
      'weatherSafetyAutoResumeDesc':
          'Resume once all weather sources return safe',
      'weatherSafetyDescription':
          'Tune radar alerts and hardware safety thresholds for your site.',
      'weatherSafetyEnable': 'Enable weather safety',
      'weatherSafetyEnableDesc':
          'Pause imaging when unsafe weather is detected',
      'weatherSafetyHardware': 'Hardware Thresholds',
      'weatherSafetyLeadTime': 'Lead time',
      'weatherSafetyLeadTimeDesc':
          'Warn this many minutes before weather reaches the site',
      'weatherSafetyMaxCloud': 'Max cloud cover',
      'weatherSafetyMaxCloudDesc': 'Pause when cloud cover exceeds this amount',
      'weatherSafetyMaxHumidity': 'Max humidity',
      'weatherSafetyMaxHumidityDesc':
          'Pause when sensor humidity exceeds this value',
      'weatherSafetyMaxWind': 'Max wind speed',
      'weatherSafetyMaxWindDesc': 'Pause when wind exceeds this speed',
      'weatherSafetyTitle': 'Weather Safety',
      'mount': 'Mount',
      'ra': 'RA',
      'dec': 'Dec',
      'pier': 'Pier',
      'rate': 'Rate',
      'unpark': 'Unpark',
      'park': 'Park',
      'track': 'Track',
      'stop': 'Stop',
      'abortSlew': 'Abort Slew',
      'capturing': 'Capturing',
      'idle': 'Idle',
      'temp': 'Temp',
      'focus': 'Focus',
      'hfr': 'HFR',
      'rms': 'RMS',
      'livePreview': 'Live Preview',
      'noImage': 'No Image',
      'noCameraConnected': 'No Camera Connected',
      'takeSnapshotOrStartSequence': 'Take a snapshot or start a sequence',
      'connectCameraInEquipment': 'Connect a camera in Equipment',
      'guiding': 'Guiding',
      'disconnected': 'Disconnected',
      'stopping': 'Stopping...',
      'starting': 'Starting...',
      'clickStartToBegin': 'Click Start to begin',
      'connectGuider': 'Connect guider',
      'ok': 'OK',
      'off': 'Off',
      'moveFocuserToSeeHistory': 'Move focuser to see history',
      'autofocus': 'Autofocus',
      'useFocusTabForAutofocus': 'Use Focus tab for autofocus',
      'sensor': 'Sensor',
      'start': 'Start',
      'slewing': 'Slewing',
      'parked': 'Parked',
      'tracking': 'Tracking',
      'pos': 'Pos',
      'noData': 'No data',
      'remoteAccessTitle': 'Remote Access',
      'remoteAccessDescription':
          'Configure the web dashboard and remote control server.',
      'remoteAccessWebServer': 'Web Server',
      'remoteAccessEnableTitle': 'Enable Remote Access',
      'remoteAccessEnableDesc':
          'Serve the dashboard and control API for authenticated LAN access.',
      'remoteAccessPortTitle': 'Server Port',
      'remoteAccessPortDesc':
          'Port for the remote-access server. Changes rebind the server automatically.',
      'remoteAccessStatusTitle': 'Status',
      'remoteAccessServerStatus': 'Server Status',
      'remoteAccessRunning': 'Running',
      'remoteAccessStopped': 'Stopped',
      'remoteAccessAuth': 'Authentication',
      'remoteAccessAuthRequired': 'Paired devices required remotely',
      'remoteAccessAuthNotRequired': 'Not required',
      'remoteAccessScope': 'Access Scope',
      'remoteAccessScopeLocal': 'Local machine only',
      'remoteAccessScopeLan': 'Local machine and LAN',
      'remoteAccessDashboard': 'Dashboard',
      'remoteAccessDashboardAvailable': 'Available',
      'remoteAccessDashboardMissing': 'Static files missing',
      'remoteAccessLocalUrl': 'Local URL',
      'remoteAccessLanUrl': 'LAN URL',
      'remoteAccessActiveViewers': 'Active Viewers',
      'remoteAccessLastError': 'Last Error',
      'remoteAccessNoErrors': 'None',
      'remoteAccessPairTitle': 'Pair Remote Browsers',
      'remoteAccessPairDesc':
          'Generate a short-lived pairing code and review paired devices.',
      'remoteAccessManagePairing': 'Manage Pairing',
      'remoteAccessInfoBody':
          'Desktop remote access serves the same dashboard locally and on your LAN. Localhost stays frictionless for this machine, while non-local clients must pair before they can control the app.',
      'remoteAccessCopiedUrl': 'Copied {url} to clipboard',
      'remoteAccessInvalidPort': 'Enter a valid port between 1024 and 65535.',
      'remoteAccessIssueTitle': 'Remote access needs attention',
      'remoteAccessIssueBody':
          'Nightshade ran into a remote-access problem. Check the connection details below before sharing the dashboard.',
      'remoteAccessLocalActionTitle': 'Open on this computer',
      'remoteAccessLocalActionBody':
          'Use this link from the same machine to confirm the dashboard is working before sharing it elsewhere.',
      'remoteAccessLanActionTitle': 'Share on your network',
      'remoteAccessLanActionBodyPaired':
          'Share this link with a paired device on your local network.',
      'remoteAccessLanActionBodyOpen':
          'Share this link with another device on your local network.',
      'remoteAccessDisabledTitle': 'Remote access is off',
      'remoteAccessDisabledBody':
          'Turn it on when you want to open the dashboard locally or share it on your network.',
      'remoteAccessStartingTitle': 'Starting remote access',
      'remoteAccessStartingBody':
          'Nightshade is bringing the dashboard online. Your local and LAN links will appear here when it is ready.',
      'remoteAccessDetailsTitle': 'Connection details',
      'remoteAccessDetailsBody':
          'Open this section when you need viewer counts, authentication state, or the last runtime error.',
      'remoteAccessOpenLocal': 'Open Local Dashboard',
      'remoteAccessCopyLink': 'Copy Link',
      'remoteAccessCopyLan': 'Copy LAN Link',
      'remoteAccessOpenLink': 'Open Link',
      'remoteAccessOpenFailed':
          'Nightshade could not open the link, so it copied it instead.',
      'pairingTitle': 'Remote Connection Pairing',
      'pairingNewDeviceTitle': 'Pair New Device',
      'pairingStartDesc':
          'Start pairing mode to allow a new device to connect. The pairing code will be valid for 5 minutes.',
      'pairingStartButton': 'Start Pairing Mode',
      'pairingEnterCode': 'Enter this code on your device:',
      'pairingCopyCode': 'Copy code',
      'pairingCodeCopied': 'Pairing code copied to clipboard',
      'pairingExpiresIn': 'Expires in {minutes}:{seconds}',
      'pairingCancel': 'Cancel Pairing',
      'pairingDevicesTitle': 'Paired Devices',
      'pairingRefresh': 'Refresh',
      'pairingNoDevices': 'No paired devices',
      'pairingNoDevicesDesc': 'Start pairing mode to connect a device',
      'pairingPairedAt': 'Paired: {time}',
      'pairingLastConnected': 'Last connected: {time}',
      'pairingJustNow': 'Just now',
      'pairingMinutesAgo': '{count}m ago',
      'pairingHoursAgo': '{count}h ago',
      'pairingDaysAgo': '{count}d ago',
      'pairingRevokeAccess': 'Revoke Access',
      'pairingDeleteDevice': 'Delete Device',
      'pairingRevokeTitle': 'Revoke Device Access',
      'pairingRevokeBody':
          'Are you sure you want to revoke access for "{name}"? This device will no longer be able to connect until it is paired again.',
      'pairingDeleteTitle': 'Delete Device',
      'pairingDeleteBody':
          'Are you sure you want to permanently delete "{name}"? This action cannot be undone.',
      'pairingDismissError': 'Dismiss',
      'pairingErrorStart':
          'Nightshade could not start pairing mode. Try again.',
      'pairingErrorLoad': 'Nightshade could not load your paired devices.',
      'pairingErrorRevoke':
          'Nightshade could not revoke access for that device.',
      'pairingErrorDelete': 'Nightshade could not delete that paired device.',
      'plannerTitle': 'Plan Tonight',
      'plannerLoading': 'Analyzing tonight\'s conditions...',
      'plannerCreateSequence': 'Create Sequence',
      'plannerReviewInSequencer': 'Review in Sequencer',
      'plannerReviewHint':
          'Nightshade will create a draft sequence and take you to Sequencer so you can review exposure, filters, and safety checks before running it.',
      'plannerAlternateTargets': 'Alternate Targets',
      'plannerAlternateTargetsSubtitle': '{count} additional option{suffix}',
      'plannerRiskFactors': 'Risk Factors',
      'plannerRiskFactorsSubtitle': 'Conditions that may affect your session',
      'plannerRationale': 'Rationale',
      'plannerRationaleSubtitle': 'Why this plan was chosen',
      'plannerSequenceCreated':
          'Created sequence with {target} ({exposure}s recommended)',
      'plannerDraftCreated':
          'Draft sequence created for {target}. Review it in Sequencer before running.',
      'plannerLocationMissingTitle': 'Location not configured',
      'plannerLocationMissingBody':
          'Set your observing latitude and longitude in Settings before using the planner.',
      'plannerPlanFailedTitle': 'Failed to generate plan',
      'plannerPlanFailedBody':
          'Nightshade could not generate tonight\'s plan. Try again or review your observing settings and saved targets.',
      'plannerOpenSettings': 'Open Settings',
      'plannerRetry': 'Retry',
      'plannerNoTargetsTitle': 'No targets for tonight',
      'plannerNoTargetsBody':
          'The planner could not find a target that clears the current filters and observing window. Review the active constraints, add or select targets, then refresh the plan.',
      'plannerConstraintAltitude': 'Altitude >= {value}\u00B0',
      'plannerConstraintScore': 'Score >= {value}',
      'plannerConstraintMoon': 'Moon <= {value}\u00B0',
      'plannerConstraintMoonAny': 'Any moon distance',
      'plannerConstraintTypes': 'Types: {value}',
      'plannerConstraintTypesAny': 'any',
      'plannerTryThis': 'Next steps',
      'plannerTryPlanetarium':
          'Use Planetarium to find targets that are actually up from your location tonight.',
      'plannerTryFraming':
          'Use Framing to confirm field of view, rotation, and mosaic fit before sequencing.',
      'plannerOpenPlanetarium': 'Open Planetarium',
      'plannerOpenFraming': 'Open Framing',
      'plannerUserOverride': 'USER OVERRIDE',
      'plannerSelected': 'Selected',
      'plannerSelect': 'Select',
      'plannerMagnitude': 'Mag {value}',
      'plannerPeak': 'Peak {value}\u00B0',
      'plannerVisible': '{value}h visible',
      'plannerMoon': 'Moon {value}\u00B0',
      'plannerExposure': '{value}s exp',
      'plannerEstimatedIntegration': 'Estimated integration: {value}',
      'diagnosticsTitle': 'Optical Train Diagnostics',
      'diagnosticsLoadSessionsFailed': 'Could not load sessions',
      'diagnosticsNoSessions': 'No sessions available',
      'diagnosticsSelectSession': 'Select session',
      'diagnosticsNoSessionTitle': 'Select an imaging session to analyze',
      'diagnosticsNoSessionBody':
          'Optical diagnostics require plate-solved frames with PSF and residual data.',
      'diagnosticsFailedTitle': 'Diagnostics unavailable',
      'diagnosticsFailedBody':
          'Nightshade could not compute diagnostics for this session.',
      'diagnosticsRetry': 'Retry',
      'diagnosticsTilt': 'Tilt',
      'diagnosticsCollimation': 'Collimation',
      'diagnosticsLowHfr': 'Low HFR',
      'diagnosticsMedium': 'Medium',
      'diagnosticsHighHfr': 'High HFR',
      'diagnosticsMean': 'Mean',
      'diagnosticsMin': 'Min',
      'diagnosticsMax': 'Max',
      'equipmentProfilesLoadFailedTitle': 'Failed to load profiles',
      'equipmentProfilesLoadFailedBody':
          'Nightshade could not load your saved equipment profiles.',
    },
    'es': {
      'appTitle': 'Nightshade',
      'cancel': 'Cancelar',
      'clearGoal': 'Borrar meta',
      'closeAnyway': 'Cerrar de todos modos',
      'closeNightshadeBody':
          'Hay una sesi\u00F3n de captura en curso. \u00BFSeguro que deseas cerrar la aplicaci\u00F3n? La captura actual se cancelar\u00E1.',
      'closeNightshadeTitle': '\u00BFCerrar Nightshade?',
      'collapse': 'Contraer',
      'connect': 'Conectar',
      'dashboardTitle': 'Panel',
      'dashboardTourDescription':
          'Aprende los controles y estados del panel principal.',
      'dashboardTourTitle': 'Tour del panel',
      'disconnectedBanner': 'Error: sin conexi\u00F3n al servidor',
      'generalAutoConnect': 'Conectar equipo autom\u00E1ticamente',
      'generalAutoConnectDesc':
          'Conectar los \u00FAltimos dispositivos usados al iniciar',
      'generalAutoSaveSequences': 'Guardar secuencias autom\u00E1ticamente',
      'generalAutoSaveSequencesDesc':
          'Guardar los cambios de secuencia de forma autom\u00E1tica',
      'generalBehavior': 'Comportamiento',
      'generalConfirmBeforeClosing': 'Confirmar antes de cerrar',
      'generalConfirmBeforeClosingDesc':
          'Mostrar confirmaci\u00F3n al cerrar durante una captura',
      'generalDescription':
          'Configuraci\u00F3n b\u00E1sica de la aplicaci\u00F3n',
      'generalLanguage': 'Idioma',
      'generalLanguageDesc': 'Elegir el idioma de la interfaz principal',
      'generalStartMinimized': 'Iniciar minimizada',
      'generalStartMinimizedDesc':
          'Abrir la aplicaci\u00F3n minimizada en la bandeja del sistema',
      'generalStartup': 'Inicio',
      'generalTitle': 'General',
      'languageEnglish': 'Ingl\u00E9s',
      'languageSpanish': 'Espa\u00F1ol',
      'mobileEnterIp': 'Ingresar IP',
      'mobileErrorLoadingApp': 'Error al cargar la aplicaci\u00F3n',
      'mobileHowToConnect': 'C\u00F3mo conectar',
      'mobileHowToConnectSteps':
          '1. Aseg\u00FArate de que Nightshade est\u00E9 ejecut\u00E1ndose en modo headless en Windows o Raspberry Pi\n2. Verifica que ambos dispositivos est\u00E9n en la misma red\n3. Toca "Buscar servidor" o espera el descubrimiento autom\u00E1tico\n4. La interfaz completa se cargar\u00E1 autom\u00E1ticamente',
      'mobileNotConnected': 'Sin conexi\u00F3n',
      'mobileRetry': 'Reintentar',
      'mobileScanQr': 'Escanear QR',
      'mobileSearchingForServer': 'Buscando servidor...',
      'mobileServerIpAddress': 'Direcci\u00F3n IP del servidor',
      'mobileSkipConnection': 'Omitir conexi\u00F3n (solo ver la interfaz)',
      'navAnalytics': 'Anal\u00EDtica',
      'navAnalyticsDesc': 'Estad\u00EDsticas',
      'navDashboard': 'Panel',
      'navDashboardDesc': 'Resumen y estado',
      'navEquipment': 'Equipo',
      'navEquipmentDesc': 'Conectar dispositivos',
      'navFlatWizard': 'Asistente de Flats',
      'navFlatWizardDesc': 'Calibraci\u00F3n',
      'navFraming': 'Encuadre',
      'navFramingDesc': 'Planificar tomas',
      'navGuiding': 'Guiado',
      'navGuidingDesc': 'Control de PHD2',
      'navImaging': 'Captura',
      'navImagingDesc': 'Captura y enfoque',
      'navPlanetarium': 'Planetario',
      'navPlanetariumDesc': 'Vista del cielo',
      'navSequencer': 'Secuenciador',
      'navSequencerDesc': 'Automatizaci\u00F3n',
      'navWeather': 'Clima',
      'navWeatherDesc': 'Radar de nubes',
      'navPlanner': 'Plan Nocturno',
      'navPlannerDesc': 'Optimizador de sesiones',
      'navMore': 'Mas',
      'navMoreDesc': 'Herramientas adicionales',
      'save': 'Guardar',
      'searchForServer': 'Buscar servidor',
      'settingsAbout': 'Acerca de',
      'settingsAnnotations': 'Anotaciones',
      'settingsAppearance': 'Apariencia',
      'settingsAutofocus': 'Autoenfoque',
      'settingsCalibration': 'Calibraci\u00F3n',
      'settingsCatalogs': 'Cat\u00E1logos',
      'settingsConnection': 'Conexi\u00F3n',
      'settingsDarkLibrary': 'Biblioteca de darks',
      'settingsEquipmentProfiles': 'Perfiles de equipo',
      'settingsFilePaths': 'Rutas de archivo',
      'settingsGeneral': 'General',
      'settingsHelpTutorials': 'Ayuda y tutoriales',
      'settingsImaging': 'Captura',
      'settingsLocation': 'Ubicaci\u00F3n',
      'settingsNotifications': 'Notificaciones',
      'settingsPhd2Guiding': 'Guiado PHD2',
      'settingsPlateSolving': 'Resoluci\u00F3n de placas',
      'settingsPlugins': 'Plugins',
      'settingsRemoteAccess': 'Acceso remoto',
      'settingsScience': 'Ciencia',
      'settingsSequencer': 'Secuenciador',
      'settingsLogs': 'Registros',
      'settingsAutoSave': 'Auto-guardado',
      'settingsObservationLog': 'Registro de observacion',
      'settingsObservingLists': 'Listas de observacion',
      'settingsTitle': 'Ajustes',
      'settingsTourDescription':
          'Aprende a configurar tus preferencias de Nightshade.',
      'settingsTourTitle': 'Tour de ajustes',
      'settingsWeatherSafety': 'Seguridad meteorol\u00F3gica',
      'share': 'Compartir',
      'analyticsAllTargets': 'Todos los objetivos',
      'analyticsAllTime': 'Todo el tiempo',
      'analyticsAvgHfr': 'HFR prom.',
      'analyticsAvgRms': 'RMS prom.',
      'analyticsCapturedImages': 'Im\u00E1genes capturadas',
      'analyticsClearGoal': 'Borrar meta',
      'analyticsComplete': 'Completado',
      'analyticsCurrentSession': 'Sesi\u00F3n actual',
      'analyticsCustomTarget': 'Objetivo personalizado',
      'analyticsDiagnostics': 'Diagn\u00F3stico',
      'analyticsDuration': 'Duraci\u00F3n',
      'analyticsEditGoal': 'Editar meta',
      'analyticsEquipmentStats': 'Equipo',
      'analyticsExposures': 'Exposiciones',
      'analyticsExportCsv': 'Exportar a CSV',
      'analyticsExportHtml': 'Exportar informe HTML',
      'analyticsExportJson': 'Exportar a JSON',
      'analyticsFailed': 'Fallidas',
      'analyticsFrames': 'Frames',
      'analyticsGoal': 'Meta',
      'analyticsGoalDialogTitle':
          'Definir meta de integraci\u00F3n para {target}',
      'analyticsGoalHours': 'Meta de integraci\u00F3n (horas)',
      'analyticsHistory': 'Historial',
      'analyticsImages': 'Im\u00E1genes ({count})',
      'analyticsIntegrated': 'Integrado',
      'analyticsIntegration': 'Integraci\u00F3n',
      'analyticsLastImaged': '\u00DAltima captura {time}',
      'analyticsNoActiveSession': 'Sin sesi\u00F3n activa',
      'analyticsNoProjects':
          'Todav\u00EDa no hay objetivos disponibles para seguimiento.',
      'analyticsNoSessionHistory': 'Sin historial de sesiones',
      'analyticsNoSessionHistoryDesc':
          'Completa una sesi\u00F3n para ver el historial aqu\u00ED',
      'analyticsNoSessionInProgress': 'No hay una sesi\u00F3n en curso',
      'analyticsNotSet': 'Sin definir',
      'analyticsProjects': 'Proyectos',
      'analyticsQualityAdvisory':
          'Las etiquetas de calidad son solo informativas. No se eliminan ni rechazan cuadros autom\u00E1ticamente.',
      'analyticsQuickCapture': 'Captura r\u00E1pida',
      'analyticsQuickCaptureSubtitle':
          'Instant\u00E1neas hechas fuera de las secuencias',
      'analyticsRemaining': 'Restante',
      'analyticsSave': 'Guardar',
      'analyticsScience': 'Ciencia',
      'analyticsSearchSessions': 'Buscar sesiones...',
      'analyticsSession': 'Sesi\u00F3n',
      'analyticsSessionInProgress': 'Sesi\u00F3n en curso',
      'analyticsSessions': 'Sesiones',
      'analyticsSetGoal': 'Definir meta',
      'analyticsStarted': 'Inicio: {time}',
      'analyticsStatistics': 'Estad\u00EDsticas',
      'analyticsSuccessful': 'Exitosas',
      'analyticsThisMonth': 'Este mes',
      'analyticsThisYear': 'Este a\u00F1o',
      'analyticsTotalExposures': 'Exposiciones totales',
      'analyticsTourDescription':
          'Aprende a analizar tus datos y estad\u00EDsticas de captura.',
      'analyticsTourTitle': 'Tour de anal\u00EDtica',
      'analyticsUnnamedSession': 'Sesi\u00F3n sin nombre',
      'weatherSafetyActions': 'Acciones de seguridad',
      'weatherSafetyAlertDistance': 'Distancia de alerta',
      'weatherSafetyAlertDistanceDesc':
          'Generar alertas de radar dentro de esta distancia',
      'weatherSafetyAlertTiming': 'Tiempo de alerta',
      'weatherSafetyAutoPark': 'Aparcar la montura',
      'weatherSafetyAutoParkDesc':
          'Aparcar autom\u00E1ticamente cuando se active la seguridad',
      'weatherSafetyAutoResume': 'Reanudar al despejar',
      'weatherSafetyAutoResumeDesc':
          'Reanudar cuando todas las fuentes vuelvan a estado seguro',
      'weatherSafetyDescription':
          'Ajusta alertas de radar y umbrales de seguridad del hardware.',
      'weatherSafetyEnable': 'Activar seguridad meteorol\u00F3gica',
      'weatherSafetyEnableDesc':
          'Pausar la captura cuando el clima sea inseguro',
      'weatherSafetyHardware': 'Umbrales del hardware',
      'weatherSafetyLeadTime': 'Anticipaci\u00F3n',
      'weatherSafetyLeadTimeDesc':
          'Avisar tantos minutos antes de que llegue el clima',
      'weatherSafetyMaxCloud': 'Nubosidad m\u00E1xima',
      'weatherSafetyMaxCloudDesc':
          'Pausar cuando la nubosidad supere este valor',
      'weatherSafetyMaxHumidity': 'Humedad m\u00E1xima',
      'weatherSafetyMaxHumidityDesc':
          'Pausar cuando la humedad supere este valor',
      'weatherSafetyMaxWind': 'Viento m\u00E1ximo',
      'weatherSafetyMaxWindDesc':
          'Pausar cuando el viento supere esta velocidad',
      'weatherSafetyTitle': 'Seguridad meteorol\u00F3gica',
      'mount': 'Montura',
      'ra': 'AR',
      'dec': 'Dec',
      'pier': 'Pilar',
      'rate': 'Velocidad',
      'unpark': 'Desaparcar',
      'park': 'Aparcar',
      'track': 'Seguir',
      'stop': 'Detener',
      'abortSlew': 'Cancelar giro',
      'capturing': 'Capturando',
      'idle': 'Inactivo',
      'temp': 'Temp',
      'focus': 'Enfoque',
      'hfr': 'HFR',
      'rms': 'RMS',
      'livePreview': 'Vista en vivo',
      'noImage': 'Sin imagen',
      'noCameraConnected': 'Sin c\u00E1mara conectada',
      'takeSnapshotOrStartSequence': 'Toma una captura o inicia una secuencia',
      'connectCameraInEquipment': 'Conecta una c\u00E1mara en Equipo',
      'guiding': 'Guiado',
      'disconnected': 'Desconectado',
      'stopping': 'Deteniendo...',
      'starting': 'Iniciando...',
      'clickStartToBegin': 'Haz clic en Iniciar para comenzar',
      'connectGuider': 'Conectar guiado',
      'ok': 'OK',
      'off': 'Apagado',
      'moveFocuserToSeeHistory': 'Mueve el enfocador para ver historial',
      'autofocus': 'Autoenfoque',
      'useFocusTabForAutofocus': 'Usa la pesta\u00F1a Enfoque para autoenfoque',
      'sensor': 'Sensor',
      'start': 'Iniciar',
      'slewing': 'Girando',
      'parked': 'Aparcada',
      'tracking': 'Siguiendo',
      'pos': 'Pos',
      'noData': 'Sin datos',
      'remoteAccessTitle': 'Acceso remoto',
      'remoteAccessDescription':
          'Configura el panel web y el servidor de control remoto.',
      'remoteAccessWebServer': 'Servidor web',
      'remoteAccessEnableTitle': 'Activar acceso remoto',
      'remoteAccessEnableDesc':
          'Sirve el panel y la API de control para acceso autenticado por LAN.',
      'remoteAccessPortTitle': 'Puerto del servidor',
      'remoteAccessPortDesc':
          'Puerto del servidor de acceso remoto. Los cambios vuelven a enlazar el servidor automaticamente.',
      'remoteAccessStatusTitle': 'Estado',
      'remoteAccessServerStatus': 'Estado del servidor',
      'remoteAccessRunning': 'En ejecucion',
      'remoteAccessStopped': 'Detenido',
      'remoteAccessAuth': 'Autenticacion',
      'remoteAccessAuthRequired':
          'Se requieren dispositivos emparejados remotamente',
      'remoteAccessAuthNotRequired': 'No requerida',
      'remoteAccessScope': 'Alcance de acceso',
      'remoteAccessScopeLocal': 'Solo equipo local',
      'remoteAccessScopeLan': 'Equipo local y LAN',
      'remoteAccessDashboard': 'Panel',
      'remoteAccessDashboardAvailable': 'Disponible',
      'remoteAccessDashboardMissing': 'Faltan archivos estaticos',
      'remoteAccessLocalUrl': 'URL local',
      'remoteAccessLanUrl': 'URL LAN',
      'remoteAccessActiveViewers': 'Visores activos',
      'remoteAccessLastError': 'Ultimo error',
      'remoteAccessNoErrors': 'Ninguno',
      'remoteAccessPairTitle': 'Emparejar navegadores remotos',
      'remoteAccessPairDesc':
          'Genera un codigo temporal de emparejamiento y revisa los dispositivos emparejados.',
      'remoteAccessManagePairing': 'Gestionar emparejamiento',
      'remoteAccessInfoBody':
          'El acceso remoto de escritorio sirve el mismo panel localmente y en tu LAN. Localhost sigue siendo directo para esta maquina, mientras que los clientes no locales deben emparejarse antes de poder controlar la aplicacion.',
      'remoteAccessCopiedUrl': 'Se copio {url} al portapapeles',
      'remoteAccessInvalidPort':
          'Introduce un puerto valido entre 1024 y 65535.',
      'remoteAccessIssueTitle': 'El acceso remoto necesita atencion',
      'remoteAccessIssueBody':
          'Nightshade encontro un problema de acceso remoto. Revisa los detalles de conexion antes de compartir el panel.',
      'remoteAccessLocalActionTitle': 'Abrir en este equipo',
      'remoteAccessLocalActionBody':
          'Usa este enlace desde esta misma maquina para confirmar que el panel funciona antes de compartirlo.',
      'remoteAccessLanActionTitle': 'Compartir en tu red',
      'remoteAccessLanActionBodyPaired':
          'Comparte este enlace con un dispositivo emparejado en tu red local.',
      'remoteAccessLanActionBodyOpen':
          'Comparte este enlace con otro dispositivo en tu red local.',
      'remoteAccessDisabledTitle': 'El acceso remoto esta apagado',
      'remoteAccessDisabledBody':
          'Activalo cuando quieras abrir el panel localmente o compartirlo en tu red.',
      'remoteAccessStartingTitle': 'Iniciando acceso remoto',
      'remoteAccessStartingBody':
          'Nightshade esta poniendo el panel en linea. Los enlaces local y LAN apareceran aqui cuando este listo.',
      'remoteAccessDetailsTitle': 'Detalles de conexion',
      'remoteAccessDetailsBody':
          'Abre esta seccion cuando necesites recuento de visores, estado de autenticacion o el ultimo error.',
      'remoteAccessOpenLocal': 'Abrir panel local',
      'remoteAccessCopyLink': 'Copiar enlace',
      'remoteAccessCopyLan': 'Copiar enlace LAN',
      'remoteAccessOpenLink': 'Abrir enlace',
      'remoteAccessOpenFailed':
          'Nightshade no pudo abrir el enlace, asi que lo copio.',
      'pairingTitle': 'Emparejamiento de conexion remota',
      'pairingNewDeviceTitle': 'Emparejar nuevo dispositivo',
      'pairingStartDesc':
          'Inicia el modo de emparejamiento para permitir que un nuevo dispositivo se conecte. El codigo sera valido durante 5 minutos.',
      'pairingStartButton': 'Iniciar emparejamiento',
      'pairingEnterCode': 'Introduce este codigo en tu dispositivo:',
      'pairingCopyCode': 'Copiar codigo',
      'pairingCodeCopied': 'Codigo copiado al portapapeles',
      'pairingExpiresIn': 'Caduca en {minutes}:{seconds}',
      'pairingCancel': 'Cancelar emparejamiento',
      'pairingDevicesTitle': 'Dispositivos emparejados',
      'pairingRefresh': 'Actualizar',
      'pairingNoDevices': 'No hay dispositivos emparejados',
      'pairingNoDevicesDesc':
          'Inicia el modo de emparejamiento para conectar un dispositivo',
      'pairingPairedAt': 'Emparejado: {time}',
      'pairingLastConnected': 'Ultima conexion: {time}',
      'pairingJustNow': 'Ahora mismo',
      'pairingMinutesAgo': 'hace {count}m',
      'pairingHoursAgo': 'hace {count}h',
      'pairingDaysAgo': 'hace {count}d',
      'pairingRevokeAccess': 'Revocar acceso',
      'pairingDeleteDevice': 'Eliminar dispositivo',
      'pairingRevokeTitle': 'Revocar acceso del dispositivo',
      'pairingRevokeBody':
          '¿Seguro que quieres revocar el acceso de "{name}"? Este dispositivo no podra conectarse hasta que vuelva a emparejarse.',
      'pairingDeleteTitle': 'Eliminar dispositivo',
      'pairingDeleteBody':
          '¿Seguro que quieres eliminar permanentemente "{name}"? Esta accion no se puede deshacer.',
      'pairingDismissError': 'Cerrar',
      'pairingErrorStart':
          'Nightshade no pudo iniciar el modo de emparejamiento. Intentalo de nuevo.',
      'pairingErrorLoad':
          'Nightshade no pudo cargar tus dispositivos emparejados.',
      'pairingErrorRevoke':
          'Nightshade no pudo revocar el acceso de ese dispositivo.',
      'pairingErrorDelete':
          'Nightshade no pudo eliminar ese dispositivo emparejado.',
      'plannerTitle': 'Planificar esta noche',
      'plannerLoading': 'Analizando las condiciones de esta noche...',
      'plannerCreateSequence': 'Crear secuencia',
      'plannerReviewInSequencer': 'Revisar en secuenciador',
      'plannerReviewHint':
          'Nightshade creara una secuencia borrador y te llevara al secuenciador para revisar exposicion, filtros y comprobaciones de seguridad antes de ejecutarla.',
      'plannerAlternateTargets': 'Objetivos alternativos',
      'plannerAlternateTargetsSubtitle':
          '{count} opcion{suffix} adicional{suffix}',
      'plannerRiskFactors': 'Factores de riesgo',
      'plannerRiskFactorsSubtitle': 'Condiciones que pueden afectar tu sesion',
      'plannerRationale': 'Motivo',
      'plannerRationaleSubtitle': 'Por que se eligio este plan',
      'plannerSequenceCreated':
          'Se creo una secuencia con {target} ({exposure}s recomendados)',
      'plannerDraftCreated':
          'Se creo una secuencia borrador para {target}. Revisala en el secuenciador antes de ejecutarla.',
      'plannerLocationMissingTitle': 'Ubicacion no configurada',
      'plannerLocationMissingBody':
          'Configura tu latitud y longitud de observacion en Ajustes antes de usar el planificador.',
      'plannerPlanFailedTitle': 'No se pudo generar el plan',
      'plannerPlanFailedBody':
          'Nightshade no pudo generar el plan de esta noche. Intentalo de nuevo o revisa tus ajustes y objetivos guardados.',
      'plannerOpenSettings': 'Abrir ajustes',
      'plannerRetry': 'Reintentar',
      'plannerNoTargetsTitle': 'No hay objetivos para esta noche',
      'plannerNoTargetsBody':
          'El planificador no encontro un objetivo que cumpla los filtros y la ventana de observacion actuales. Revisa las restricciones activas, agrega o selecciona objetivos y actualiza el plan.',
      'plannerConstraintAltitude': 'Altitud >= {value}\u00B0',
      'plannerConstraintScore': 'Puntuacion >= {value}',
      'plannerConstraintMoon': 'Luna <= {value}\u00B0',
      'plannerConstraintMoonAny': 'Cualquier distancia lunar',
      'plannerConstraintTypes': 'Tipos: {value}',
      'plannerConstraintTypesAny': 'cualquiera',
      'plannerTryThis': 'Siguientes pasos',
      'plannerTryPlanetarium':
          'Usa Planetario para encontrar objetivos visibles desde tu ubicacion esta noche.',
      'plannerTryFraming':
          'Usa Encuadre para confirmar campo de vision, rotacion y mosaico antes de secuenciar.',
      'plannerOpenPlanetarium': 'Abrir planetario',
      'plannerOpenFraming': 'Abrir encuadre',
      'plannerUserOverride': 'ANULACION DEL USUARIO',
      'plannerSelected': 'Seleccionado',
      'plannerSelect': 'Seleccionar',
      'plannerMagnitude': 'Mag {value}',
      'plannerPeak': 'Pico {value}\u00B0',
      'plannerVisible': '{value}h visible',
      'plannerMoon': 'Luna {value}\u00B0',
      'plannerExposure': '{value}s exp',
      'plannerEstimatedIntegration': 'Integracion estimada: {value}',
      'diagnosticsTitle': 'Diagnostico del tren optico',
      'diagnosticsLoadSessionsFailed': 'No se pudieron cargar las sesiones',
      'diagnosticsNoSessions': 'No hay sesiones disponibles',
      'diagnosticsSelectSession': 'Seleccionar sesion',
      'diagnosticsNoSessionTitle':
          'Selecciona una sesion de imagen para analizar',
      'diagnosticsNoSessionBody':
          'El diagnostico optico requiere imagenes resueltas con datos de PSF y residuales.',
      'diagnosticsFailedTitle': 'Diagnostico no disponible',
      'diagnosticsFailedBody':
          'Nightshade no pudo calcular el diagnostico para esta sesion.',
      'diagnosticsRetry': 'Reintentar',
      'diagnosticsTilt': 'Inclinacion',
      'diagnosticsCollimation': 'Colimacion',
      'diagnosticsLowHfr': 'HFR bajo',
      'diagnosticsMedium': 'Medio',
      'diagnosticsHighHfr': 'HFR alto',
      'diagnosticsMean': 'Media',
      'diagnosticsMin': 'Min',
      'diagnosticsMax': 'Max',
      'equipmentProfilesLoadFailedTitle': 'No se pudieron cargar los perfiles',
      'equipmentProfilesLoadFailedBody':
          'Nightshade no pudo cargar tus perfiles de equipo guardados.',
    },
  };

  String text(String key, {Map<String, String> params = const {}}) {
    final languageCode = _localizedValues.containsKey(locale.languageCode)
        ? locale.languageCode
        : 'en';
    var value = _localizedValues[languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
    params.forEach((paramKey, paramValue) {
      value = value.replaceAll('{$paramKey}', paramValue);
    });
    return value;
  }
}

class _NightshadeLocalizationsDelegate
    extends LocalizationsDelegate<NightshadeLocalizations> {
  const _NightshadeLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => NightshadeLocalizations.supportedLocales
      .any((supported) => supported.languageCode == locale.languageCode);

  @override
  Future<NightshadeLocalizations> load(Locale locale) async {
    return NightshadeLocalizations(locale);
  }

  @override
  bool shouldReload(_NightshadeLocalizationsDelegate old) => false;
}

extension NightshadeLocalizationsContext on BuildContext {
  NightshadeLocalizations get l10n => NightshadeLocalizations.of(this);
}
