// Mocks generated by Mockito 5.4.4 from annotations
// in nightshade_core/test/services/device_disconnect_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:typed_data' as _i10;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nightshade_bridge/src/api.dart' as _i2;
import 'package:nightshade_core/src/backend/nightshade_backend.dart' as _i3;
import 'package:nightshade_core/src/models/equipment_profile.dart' as _i9;
import 'package:nightshade_core/src/models/imaging/imaging_models.dart' as _i7;
import 'package:nightshade_core/src/models/phd2_models.dart' as _i4;
import 'package:nightshade_core/src/models/settings/app_settings.dart' as _i6;
import 'package:nightshade_core/src/providers/settings_provider.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAutofocusResultApi_0 extends _i1.SmartFake
    implements _i2.AutofocusResultApi {
  _FakeAutofocusResultApi_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePhd2Status_1 extends _i1.SmartFake implements _i3.Phd2Status {
  _FakePhd2Status_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePhd2StarImage_2 extends _i1.SmartFake implements _i2.Phd2StarImage {
  _FakePhd2StarImage_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePhd2CalibrationData_3 extends _i1.SmartFake
    implements _i4.Phd2CalibrationData {
  _FakePhd2CalibrationData_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlateSolveResult_4 extends _i1.SmartFake
    implements _i3.PlateSolveResult {
  _FakePlateSolveResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSequencerStatus_5 extends _i1.SmartFake
    implements _i3.SequencerStatus {
  _FakeSequencerStatus_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocationSettings_6 extends _i1.SmartFake
    implements _i5.LocationSettings {
  _FakeLocationSettings_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppSettings_7 extends _i1.SmartFake implements _i6.AppSettings {
  _FakeAppSettings_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImageStats_8 extends _i1.SmartFake implements _i7.ImageStats {
  _FakeImageStats_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NightshadeBackend].
///
/// See the documentation for Mockito's code generation for more information.
class MockNightshadeBackend extends _i1.Mock implements _i3.NightshadeBackend {
  MockNightshadeBackend() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<_i3.NightshadeEvent> get eventStream => (super.noSuchMethod(
        Invocation.getter(#eventStream),
        returnValue: _i8.Stream<_i3.NightshadeEvent>.empty(),
      ) as _i8.Stream<_i3.NightshadeEvent>);

  @override
  _i8.Stream<Map<String, dynamic>> get polarAlignmentEvents =>
      (super.noSuchMethod(
        Invocation.getter(#polarAlignmentEvents),
        returnValue: _i8.Stream<Map<String, dynamic>>.empty(),
      ) as _i8.Stream<Map<String, dynamic>>);

  @override
  _i8.Future<List<_i3.DeviceInfo>> discoverDevices(
          _i3.DeviceType? deviceType) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverDevices,
          [deviceType],
        ),
        returnValue: _i8.Future<List<_i3.DeviceInfo>>.value(<_i3.DeviceInfo>[]),
      ) as _i8.Future<List<_i3.DeviceInfo>>);

  @override
  _i8.Future<List<_i3.DeviceInfo>> discoverIndiAtAddress(
    String? host,
    int? port,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverIndiAtAddress,
          [
            host,
            port,
          ],
        ),
        returnValue: _i8.Future<List<_i3.DeviceInfo>>.value(<_i3.DeviceInfo>[]),
      ) as _i8.Future<List<_i3.DeviceInfo>>);

  @override
  _i8.Future<List<_i3.DeviceInfo>> discoverAlpacaAtAddress(
    String? host,
    int? port,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverAlpacaAtAddress,
          [
            host,
            port,
          ],
        ),
        returnValue: _i8.Future<List<_i3.DeviceInfo>>.value(<_i3.DeviceInfo>[]),
      ) as _i8.Future<List<_i3.DeviceInfo>>);

  @override
  _i8.Future<void> connectDevice(
    _i3.DeviceType? deviceType,
    String? deviceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectDevice,
          [
            deviceType,
            deviceId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> disconnectDevice(
    _i3.DeviceType? deviceType,
    String? deviceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #disconnectDevice,
          [
            deviceType,
            deviceId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i3.DeviceInfo>> getConnectedDevices() => (super.noSuchMethod(
        Invocation.method(
          #getConnectedDevices,
          [],
        ),
        returnValue: _i8.Future<List<_i3.DeviceInfo>>.value(<_i3.DeviceInfo>[]),
      ) as _i8.Future<List<_i3.DeviceInfo>>);

  @override
  _i8.Future<void> cameraStartExposure({
    required String? deviceId,
    required double? exposureTime,
    required _i7.FrameType? frameType,
    required int? gain,
    required int? offset,
    int? binX = 1,
    int? binY = 1,
    int? x,
    int? y,
    int? width,
    int? height,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cameraStartExposure,
          [],
          {
            #deviceId: deviceId,
            #exposureTime: exposureTime,
            #frameType: frameType,
            #gain: gain,
            #offset: offset,
            #binX: binX,
            #binY: binY,
            #x: x,
            #y: y,
            #width: width,
            #height: height,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cameraAbortExposure(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #cameraAbortExposure,
          [deviceId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i3.CapturedImageResult?> cameraGetLastImage(String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cameraGetLastImage,
          [deviceId],
        ),
        returnValue: _i8.Future<_i3.CapturedImageResult?>.value(),
      ) as _i8.Future<_i3.CapturedImageResult?>);

  @override
  _i8.Future<List<int>> getLastRawImageData() => (super.noSuchMethod(
        Invocation.method(
          #getLastRawImageData,
          [],
        ),
        returnValue: _i8.Future<List<int>>.value(<int>[]),
      ) as _i8.Future<List<int>>);

  @override
  _i8.Future<void> saveFitsFile({
    required String? filePath,
    required int? width,
    required int? height,
    required List<int>? data,
    required _i2.FitsWriteHeader? headerData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFitsFile,
          [],
          {
            #filePath: filePath,
            #width: width,
            #height: height,
            #data: data,
            #headerData: headerData,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cameraSetCooling({
    required String? deviceId,
    required bool? enabled,
    double? targetTemp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cameraSetCooling,
          [],
          {
            #deviceId: deviceId,
            #enabled: enabled,
            #targetTemp: targetTemp,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cameraSetGain(
    String? deviceId,
    int? gain,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cameraSetGain,
          [
            deviceId,
            gain,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cameraSetOffset(
    String? deviceId,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cameraSetOffset,
          [
            deviceId,
            offset,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> mountSlewToCoordinates(
    String? deviceId,
    double? ra,
    double? dec,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #mountSlewToCoordinates,
          [
            deviceId,
            ra,
            dec,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> mountSync(
    String? deviceId,
    double? ra,
    double? dec,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #mountSync,
          [
            deviceId,
            ra,
            dec,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> mountPark(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #mountPark,
          [deviceId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> mountUnpark(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #mountUnpark,
          [deviceId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> mountSetTracking(
    String? deviceId,
    bool? enabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #mountSetTracking,
          [
            deviceId,
            enabled,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> mountPulseGuide({
    required String? deviceId,
    required String? direction,
    required int? durationMs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #mountPulseGuide,
          [],
          {
            #deviceId: deviceId,
            #direction: direction,
            #durationMs: durationMs,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> mountAbort(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #mountAbort,
          [deviceId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<dynamic> mountGetStatus(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #mountGetStatus,
          [deviceId],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  _i8.Future<void> mountSetTrackingRate(
    String? deviceId,
    int? rate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #mountSetTrackingRate,
          [
            deviceId,
            rate,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> mountMoveAxis(
    String? deviceId,
    int? axis,
    double? rate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #mountMoveAxis,
          [
            deviceId,
            axis,
            rate,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> focuserMoveTo(
    String? deviceId,
    int? position,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #focuserMoveTo,
          [
            deviceId,
            position,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> focuserMoveRelative(
    String? deviceId,
    int? delta,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #focuserMoveRelative,
          [
            deviceId,
            delta,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> focuserHalt(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #focuserHalt,
          [deviceId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i2.AutofocusResultApi> autofocusStart({
    required String? deviceId,
    required String? cameraId,
    required double? exposureTime,
    required int? stepSize,
    required int? stepsOut,
    String? method = r'VCurve',
    int? binning = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #autofocusStart,
          [],
          {
            #deviceId: deviceId,
            #cameraId: cameraId,
            #exposureTime: exposureTime,
            #stepSize: stepSize,
            #stepsOut: stepsOut,
            #method: method,
            #binning: binning,
          },
        ),
        returnValue:
            _i8.Future<_i2.AutofocusResultApi>.value(_FakeAutofocusResultApi_0(
          this,
          Invocation.method(
            #autofocusStart,
            [],
            {
              #deviceId: deviceId,
              #cameraId: cameraId,
              #exposureTime: exposureTime,
              #stepSize: stepSize,
              #stepsOut: stepsOut,
              #method: method,
              #binning: binning,
            },
          ),
        )),
      ) as _i8.Future<_i2.AutofocusResultApi>);

  @override
  _i8.Future<void> autofocusCancel() => (super.noSuchMethod(
        Invocation.method(
          #autofocusCancel,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> filterWheelSetPosition(
    String? deviceId,
    int? position,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterWheelSetPosition,
          [
            deviceId,
            position,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<String>> filterWheelGetNames(String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterWheelGetNames,
          [deviceId],
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  _i8.Future<void> filterWheelSetByName(
    String? deviceId,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterWheelSetByName,
          [
            deviceId,
            name,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> rotatorMoveTo(
    String? deviceId,
    double? angle,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #rotatorMoveTo,
          [
            deviceId,
            angle,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> rotatorMoveRelative(
    String? deviceId,
    double? delta,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #rotatorMoveRelative,
          [
            deviceId,
            delta,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<double> rotatorGetAngle(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #rotatorGetAngle,
          [deviceId],
        ),
        returnValue: _i8.Future<double>.value(0.0),
      ) as _i8.Future<double>);

  @override
  _i8.Future<void> rotatorHalt(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #rotatorHalt,
          [deviceId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> phd2Connect({
    String? host = r'localhost',
    int? port = 4400,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #phd2Connect,
          [],
          {
            #host: host,
            #port: port,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> phd2Disconnect() => (super.noSuchMethod(
        Invocation.method(
          #phd2Disconnect,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> phd2StartGuiding({
    double? settlePixels = 1.0,
    double? settleTime = 10.0,
    double? settleTimeout = 60.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #phd2StartGuiding,
          [],
          {
            #settlePixels: settlePixels,
            #settleTime: settleTime,
            #settleTimeout: settleTimeout,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> phd2StopGuiding() => (super.noSuchMethod(
        Invocation.method(
          #phd2StopGuiding,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> phd2Dither({
    double? amount = 5.0,
    bool? raOnly = false,
    double? settlePixels = 1.0,
    double? settleTime = 10.0,
    double? settleTimeout = 60.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #phd2Dither,
          [],
          {
            #amount: amount,
            #raOnly: raOnly,
            #settlePixels: settlePixels,
            #settleTime: settleTime,
            #settleTimeout: settleTimeout,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i3.Phd2Status> phd2GetStatus() => (super.noSuchMethod(
        Invocation.method(
          #phd2GetStatus,
          [],
        ),
        returnValue: _i8.Future<_i3.Phd2Status>.value(_FakePhd2Status_1(
          this,
          Invocation.method(
            #phd2GetStatus,
            [],
          ),
        )),
      ) as _i8.Future<_i3.Phd2Status>);

  @override
  _i8.Future<_i2.Phd2StarImage> phd2GetStarImage({int? size = 50}) =>
      (super.noSuchMethod(
        Invocation.method(
          #phd2GetStarImage,
          [],
          {#size: size},
        ),
        returnValue: _i8.Future<_i2.Phd2StarImage>.value(_FakePhd2StarImage_2(
          this,
          Invocation.method(
            #phd2GetStarImage,
            [],
            {#size: size},
          ),
        )),
      ) as _i8.Future<_i2.Phd2StarImage>);

  @override
  _i8.Future<List<String>> phd2GetAlgoParamNames({required String? axis}) =>
      (super.noSuchMethod(
        Invocation.method(
          #phd2GetAlgoParamNames,
          [],
          {#axis: axis},
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  _i8.Future<double> phd2GetAlgoParam({
    required String? axis,
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #phd2GetAlgoParam,
          [],
          {
            #axis: axis,
            #name: name,
          },
        ),
        returnValue: _i8.Future<double>.value(0.0),
      ) as _i8.Future<double>);

  @override
  _i8.Future<void> phd2SetAlgoParam({
    required String? axis,
    required String? name,
    required double? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #phd2SetAlgoParam,
          [],
          {
            #axis: axis,
            #name: name,
            #value: value,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> phd2SetPaused(bool? paused) => (super.noSuchMethod(
        Invocation.method(
          #phd2SetPaused,
          [paused],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> phd2ClearCalibration({String? which = r'both'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #phd2ClearCalibration,
          [],
          {#which: which},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> phd2FlipCalibration() => (super.noSuchMethod(
        Invocation.method(
          #phd2FlipCalibration,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.Phd2CalibrationData> phd2GetCalibrationData() =>
      (super.noSuchMethod(
        Invocation.method(
          #phd2GetCalibrationData,
          [],
        ),
        returnValue: _i8.Future<_i4.Phd2CalibrationData>.value(
            _FakePhd2CalibrationData_3(
          this,
          Invocation.method(
            #phd2GetCalibrationData,
            [],
          ),
        )),
      ) as _i8.Future<_i4.Phd2CalibrationData>);

  @override
  _i8.Future<(double, double)> phd2FindStar() => (super.noSuchMethod(
        Invocation.method(
          #phd2FindStar,
          [],
        ),
        returnValue: _i8.Future<(double, double)>.value((0.0, 0.0)),
      ) as _i8.Future<(double, double)>);

  @override
  _i8.Future<void> phd2SetLockPosition({
    required double? x,
    required double? y,
    bool? exact = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #phd2SetLockPosition,
          [],
          {
            #x: x,
            #y: y,
            #exact: exact,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<(double, double)> phd2GetLockPosition() => (super.noSuchMethod(
        Invocation.method(
          #phd2GetLockPosition,
          [],
        ),
        returnValue: _i8.Future<(double, double)>.value((0.0, 0.0)),
      ) as _i8.Future<(double, double)>);

  @override
  _i8.Future<void> phd2Loop() => (super.noSuchMethod(
        Invocation.method(
          #phd2Loop,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> phd2DeselectStar() => (super.noSuchMethod(
        Invocation.method(
          #phd2DeselectStar,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i3.PlateSolveResult> plateSolve({
    required String? imagePath,
    double? ra,
    double? dec,
    double? fovDegrees,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #plateSolve,
          [],
          {
            #imagePath: imagePath,
            #ra: ra,
            #dec: dec,
            #fovDegrees: fovDegrees,
          },
        ),
        returnValue:
            _i8.Future<_i3.PlateSolveResult>.value(_FakePlateSolveResult_4(
          this,
          Invocation.method(
            #plateSolve,
            [],
            {
              #imagePath: imagePath,
              #ra: ra,
              #dec: dec,
              #fovDegrees: fovDegrees,
            },
          ),
        )),
      ) as _i8.Future<_i3.PlateSolveResult>);

  @override
  _i8.Future<void> sequencerStart() => (super.noSuchMethod(
        Invocation.method(
          #sequencerStart,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> sequencerStop() => (super.noSuchMethod(
        Invocation.method(
          #sequencerStop,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> sequencerPause() => (super.noSuchMethod(
        Invocation.method(
          #sequencerPause,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> sequencerResume() => (super.noSuchMethod(
        Invocation.method(
          #sequencerResume,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> sequencerLoadJson(String? json) => (super.noSuchMethod(
        Invocation.method(
          #sequencerLoadJson,
          [json],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i3.SequencerStatus> sequencerGetStatus() => (super.noSuchMethod(
        Invocation.method(
          #sequencerGetStatus,
          [],
        ),
        returnValue:
            _i8.Future<_i3.SequencerStatus>.value(_FakeSequencerStatus_5(
          this,
          Invocation.method(
            #sequencerGetStatus,
            [],
          ),
        )),
      ) as _i8.Future<_i3.SequencerStatus>);

  @override
  _i8.Future<void> sequencerSetSimulationMode(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #sequencerSetSimulationMode,
          [enabled],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> sequencerSetDevices({
    String? cameraId,
    String? mountId,
    String? focuserId,
    String? filterwheelId,
    String? rotatorId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sequencerSetDevices,
          [],
          {
            #cameraId: cameraId,
            #mountId: mountId,
            #focuserId: focuserId,
            #filterwheelId: filterwheelId,
            #rotatorId: rotatorId,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> sequencerSetCheckpointDir(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #sequencerSetCheckpointDir,
          [path],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> hasCheckpoint() => (super.noSuchMethod(
        Invocation.method(
          #hasCheckpoint,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i3.CheckpointInfo?> getCheckpointInfo() => (super.noSuchMethod(
        Invocation.method(
          #getCheckpointInfo,
          [],
        ),
        returnValue: _i8.Future<_i3.CheckpointInfo?>.value(),
      ) as _i8.Future<_i3.CheckpointInfo?>);

  @override
  _i8.Future<void> resumeFromCheckpoint() => (super.noSuchMethod(
        Invocation.method(
          #resumeFromCheckpoint,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> discardCheckpoint() => (super.noSuchMethod(
        Invocation.method(
          #discardCheckpoint,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> saveCheckpoint() => (super.noSuchMethod(
        Invocation.method(
          #saveCheckpoint,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i5.LocationSettings> getLocationFromInternet() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocationFromInternet,
          [],
        ),
        returnValue:
            _i8.Future<_i5.LocationSettings>.value(_FakeLocationSettings_6(
          this,
          Invocation.method(
            #getLocationFromInternet,
            [],
          ),
        )),
      ) as _i8.Future<_i5.LocationSettings>);

  @override
  _i8.Future<dynamic> getCameraStatus(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #getCameraStatus,
          [deviceId],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  _i8.Future<dynamic> getMountStatus(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #getMountStatus,
          [deviceId],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  _i8.Future<dynamic> getFocuserStatus(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #getFocuserStatus,
          [deviceId],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  _i8.Future<dynamic> getFilterWheelStatus(String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFilterWheelStatus,
          [deviceId],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  _i8.Future<List<_i9.EquipmentProfile>> getProfiles() => (super.noSuchMethod(
        Invocation.method(
          #getProfiles,
          [],
        ),
        returnValue: _i8.Future<List<_i9.EquipmentProfile>>.value(
            <_i9.EquipmentProfile>[]),
      ) as _i8.Future<List<_i9.EquipmentProfile>>);

  @override
  _i8.Future<void> saveProfile(_i9.EquipmentProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProfile,
          [profile],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteProfile(String? profileId) => (super.noSuchMethod(
        Invocation.method(
          #deleteProfile,
          [profileId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> loadProfile(String? profileId) => (super.noSuchMethod(
        Invocation.method(
          #loadProfile,
          [profileId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i9.EquipmentProfile?> getActiveProfile() => (super.noSuchMethod(
        Invocation.method(
          #getActiveProfile,
          [],
        ),
        returnValue: _i8.Future<_i9.EquipmentProfile?>.value(),
      ) as _i8.Future<_i9.EquipmentProfile?>);

  @override
  _i8.Future<_i6.AppSettings> getSettings() => (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
        ),
        returnValue: _i8.Future<_i6.AppSettings>.value(_FakeAppSettings_7(
          this,
          Invocation.method(
            #getSettings,
            [],
          ),
        )),
      ) as _i8.Future<_i6.AppSettings>);

  @override
  _i8.Future<void> updateSettings(_i6.AppSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSettings,
          [settings],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i6.ObserverLocation?> getLocation() => (super.noSuchMethod(
        Invocation.method(
          #getLocation,
          [],
        ),
        returnValue: _i8.Future<_i6.ObserverLocation?>.value(),
      ) as _i8.Future<_i6.ObserverLocation?>);

  @override
  _i8.Future<void> setLocation(_i6.ObserverLocation? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLocation,
          [location],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i7.ImageStats> getImageStats(
    int? width,
    int? height,
    _i10.Uint16List? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getImageStats,
          [
            width,
            height,
            data,
          ],
        ),
        returnValue: _i8.Future<_i7.ImageStats>.value(_FakeImageStats_8(
          this,
          Invocation.method(
            #getImageStats,
            [
              width,
              height,
              data,
            ],
          ),
        )),
      ) as _i8.Future<_i7.ImageStats>);

  @override
  _i8.Future<_i10.Uint8List> autoStretchImage(
    int? width,
    int? height,
    _i10.Uint16List? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #autoStretchImage,
          [
            width,
            height,
            data,
          ],
        ),
        returnValue: _i8.Future<_i10.Uint8List>.value(_i10.Uint8List(0)),
      ) as _i8.Future<_i10.Uint8List>);

  @override
  _i8.Future<_i10.Uint8List> debayerImage(
    int? width,
    int? height,
    _i10.Uint16List? data,
    String? pattern,
    String? algorithm,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #debayerImage,
          [
            width,
            height,
            data,
            pattern,
            algorithm,
          ],
        ),
        returnValue: _i8.Future<_i10.Uint8List>.value(_i10.Uint8List(0)),
      ) as _i8.Future<_i10.Uint8List>);

  @override
  _i8.Future<void> startPolarAlignment({
    required double? exposureTime,
    required double? stepSize,
    required int? binning,
    required bool? isNorth,
    required bool? manualRotation,
    required bool? rotateEast,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startPolarAlignment,
          [],
          {
            #exposureTime: exposureTime,
            #stepSize: stepSize,
            #binning: binning,
            #isNorth: isNorth,
            #manualRotation: manualRotation,
            #rotateEast: rotateEast,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> stopPolarAlignment() => (super.noSuchMethod(
        Invocation.method(
          #stopPolarAlignment,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i7.CapturedImage>> getSessionImages(int? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionImages,
          [sessionId],
        ),
        returnValue:
            _i8.Future<List<_i7.CapturedImage>>.value(<_i7.CapturedImage>[]),
      ) as _i8.Future<List<_i7.CapturedImage>>);

  @override
  _i8.Future<_i10.Uint8List> getImageThumbnail(int? imageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getImageThumbnail,
          [imageId],
        ),
        returnValue: _i8.Future<_i10.Uint8List>.value(_i10.Uint8List(0)),
      ) as _i8.Future<_i10.Uint8List>);

  @override
  _i8.Future<void> downloadImage(
    int? imageId,
    String? localPath, {
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadImage,
          [
            imageId,
            localPath,
          ],
          {#onProgress: onProgress},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> startDeviceHeartbeat({
    required _i3.DeviceType? deviceType,
    required String? deviceId,
    required int? intervalMs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startDeviceHeartbeat,
          [],
          {
            #deviceType: deviceType,
            #deviceId: deviceId,
            #intervalMs: intervalMs,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> stopDeviceHeartbeat(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #stopDeviceHeartbeat,
          [deviceId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<(int, bool)> getDeviceHealth(String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeviceHealth,
          [deviceId],
        ),
        returnValue: _i8.Future<(int, bool)>.value((0, false)),
      ) as _i8.Future<(int, bool)>);
}
