// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../device.dart';
import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_alpaca_clients`, `parse_alpaca_id`

/// Connect to an Alpaca device
Future<void> connectAlpacaDevice(
        {required DeviceType deviceType, required String deviceId}) =>
    RustLib.instance.api.crateApiAlpacaConnectionsConnectAlpacaDevice(
        deviceType: deviceType, deviceId: deviceId);

/// Disconnect from an Alpaca device
Future<void> disconnectAlpacaDevice({required String deviceId}) =>
    RustLib.instance.api
        .crateApiAlpacaConnectionsDisconnectAlpacaDevice(deviceId: deviceId);

/// Get an Alpaca client
Future<ArcAlpacaClient?> getAlpacaClient({required String deviceId}) =>
    RustLib.instance.api
        .crateApiAlpacaConnectionsGetAlpacaClient(deviceId: deviceId);

/// Check if Alpaca is connected
Future<bool> isConnected({required String deviceId}) => RustLib.instance.api
    .crateApiAlpacaConnectionsIsConnected(deviceId: deviceId);

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < AlpacaClient >>>
abstract class ArcAlpacaClient implements RustOpaqueInterface {}
