// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../device.dart';
import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get the API version information for a connected device.
///
/// This queries the device's interface version, driver version, and supported actions.
/// For Alpaca devices, this uses the InterfaceVersion property.
/// For ASCOM devices, this uses the InterfaceVersion COM property.
/// For INDI devices, this returns the protocol version from the server greeting.
///
/// Returns cached version info if available and fresh (less than 5 minutes old),
/// otherwise queries the device directly.
Future<DeviceApiVersion> apiGetDeviceApiVersion({required String deviceId}) =>
    RustLib.instance.api
        .crateApiApiVersionApiGetDeviceApiVersion(deviceId: deviceId);

/// Check if a device supports a specific interface version.
///
/// This is useful for checking if newer API methods are available before calling them.
/// Returns true if the device reports an interface version >= the required version,
/// and false when version information is unavailable.
Future<bool> apiDeviceSupportsVersion(
        {required String deviceId, required int requiredVersion}) =>
    RustLib.instance.api.crateApiApiVersionApiDeviceSupportsVersion(
        deviceId: deviceId, requiredVersion: requiredVersion);

/// Check if a device supports a specific action.
///
/// For ASCOM/Alpaca devices, checks the SupportedActions list.
/// Returns true only when the action is explicitly reported as supported.
Future<bool> apiDeviceSupportsAction(
        {required String deviceId, required String action}) =>
    RustLib.instance.api.crateApiApiVersionApiDeviceSupportsAction(
        deviceId: deviceId, action: action);
