// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../device.dart';
import '../device_capabilities.dart';
import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_qhy_discovery_timeout_ms`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Get capabilities for any device by its device ID.
///
/// This function queries the actual device to determine what features it supports.
/// The result varies by device type (camera, mount, focuser, filter wheel).
///
/// # Arguments
/// * `device_id` - The full device ID string (e.g., "ascom:ASCOM.Camera.Simulator")
///
/// # Returns
/// * `DeviceCapabilities` - An enum containing the appropriate capability struct
///
/// # Errors
/// * Returns error if device type is unsupported or device cannot be queried
Future<DeviceCapabilities> apiGetDeviceCapabilities(
        {required String deviceId}) =>
    RustLib.instance.api
        .crateApiDiagnosticsApiGetDeviceCapabilities(deviceId: deviceId);

/// Get camera capabilities for a specific camera device.
///
/// This is a convenience wrapper that returns only camera capabilities.
///
/// # Arguments
/// * `device_id` - The camera device ID
///
/// # Returns
/// * `CameraCapabilities` - Camera-specific capability information
Future<CameraCapabilities> apiGetCameraCapabilities(
        {required String deviceId}) =>
    RustLib.instance.api
        .crateApiDiagnosticsApiGetCameraCapabilities(deviceId: deviceId);

/// Get mount capabilities for a specific mount device.
///
/// This is a convenience wrapper that returns only mount capabilities.
///
/// # Arguments
/// * `device_id` - The mount/telescope device ID
///
/// # Returns
/// * `MountCapabilities` - Mount-specific capability information
Future<MountCapabilities> apiGetMountCapabilities({required String deviceId}) =>
    RustLib.instance.api
        .crateApiDiagnosticsApiGetMountCapabilities(deviceId: deviceId);

/// Get focuser capabilities for a specific focuser device.
///
/// This is a convenience wrapper that returns only focuser capabilities.
///
/// # Arguments
/// * `device_id` - The focuser device ID
///
/// # Returns
/// * `FocuserCapabilities` - Focuser-specific capability information
Future<FocuserCapabilities> apiGetFocuserCapabilities(
        {required String deviceId}) =>
    RustLib.instance.api
        .crateApiDiagnosticsApiGetFocuserCapabilities(deviceId: deviceId);

/// Get filter wheel capabilities for a specific filter wheel device.
///
/// This is a convenience wrapper that returns only filter wheel capabilities.
///
/// # Arguments
/// * `device_id` - The filter wheel device ID
///
/// # Returns
/// * `FilterWheelCapabilities` - Filter wheel-specific capability information
Future<FilterWheelCapabilities> apiGetFilterwheelCapabilities(
        {required String deviceId}) =>
    RustLib.instance.api
        .crateApiDiagnosticsApiGetFilterwheelCapabilities(deviceId: deviceId);

/// Get rotator capabilities for a specific rotator device.
///
/// This is a convenience wrapper that returns only rotator capabilities.
///
/// # Arguments
/// * `device_id` - The rotator device ID
///
/// # Returns
/// * `RotatorCapabilities` - Rotator-specific capability information
Future<RotatorCapabilities> apiGetRotatorCapabilities(
        {required String deviceId}) =>
    RustLib.instance.api
        .crateApiDiagnosticsApiGetRotatorCapabilities(deviceId: deviceId);

/// Get dome capabilities for a specific dome device.
///
/// This is a convenience wrapper that returns only dome capabilities.
///
/// # Arguments
/// * `device_id` - The dome device ID
///
/// # Returns
/// * `DomeCapabilities` - Dome-specific capability information
Future<DomeCapabilities> apiGetDomeCapabilities({required String deviceId}) =>
    RustLib.instance.api
        .crateApiDiagnosticsApiGetDomeCapabilities(deviceId: deviceId);

/// Get cover calibrator capabilities for a specific cover calibrator device.
///
/// This is a convenience wrapper that returns only cover calibrator capabilities.
///
/// # Arguments
/// * `device_id` - The cover calibrator device ID
///
/// # Returns
/// * `CoverCalibratorCapabilities` - Cover calibrator-specific capability information
Future<CoverCalibratorCapabilities> apiGetCoverCalibratorCapabilities(
        {required String deviceId}) =>
    RustLib.instance.api.crateApiDiagnosticsApiGetCoverCalibratorCapabilities(
        deviceId: deviceId);

/// Get weather capabilities for a specific weather/observing conditions device.
///
/// This is a convenience wrapper that returns only weather capabilities.
///
/// # Arguments
/// * `device_id` - The weather device ID
///
/// # Returns
/// * `WeatherCapabilities` - Weather-specific capability information
Future<WeatherCapabilities> apiGetWeatherCapabilities(
        {required String deviceId}) =>
    RustLib.instance.api
        .crateApiDiagnosticsApiGetWeatherCapabilities(deviceId: deviceId);

/// Get safety monitor capabilities for a specific safety monitor device.
///
/// This is a convenience wrapper that returns only safety monitor capabilities.
///
/// # Arguments
/// * `device_id` - The safety monitor device ID
///
/// # Returns
/// * `SafetyMonitorCapabilities` - Safety monitor-specific capability information
Future<SafetyMonitorCapabilities> apiGetSafetyMonitorCapabilities(
        {required String deviceId}) =>
    RustLib.instance.api
        .crateApiDiagnosticsApiGetSafetyMonitorCapabilities(deviceId: deviceId);

/// Get switch capabilities for a specific switch device.
///
/// This is a convenience wrapper that returns only switch capabilities.
///
/// # Arguments
/// * `device_id` - The switch device ID
///
/// # Returns
/// * `SwitchCapabilities` - Switch-specific capability information
Future<SwitchCapabilities> apiGetSwitchCapabilities(
        {required String deviceId}) =>
    RustLib.instance.api
        .crateApiDiagnosticsApiGetSwitchCapabilities(deviceId: deviceId);

/// Get known quirks for a connected device.
///
/// Returns a list of known device characteristics and workarounds that are
/// automatically applied. This information can be displayed in the equipment
/// screen to inform users about device-specific behaviors.
///
/// # Arguments
/// * `device_id` - The device identifier (e.g., "native:zwo:ASI294MC Pro")
///
/// # Returns
/// * `Vec<QuirkInfo>` - List of quirks with categories and descriptions
List<QuirkInfo> apiGetDeviceQuirks({required String deviceId}) =>
    RustLib.instance.api
        .crateApiDiagnosticsApiGetDeviceQuirks(deviceId: deviceId);

/// Check if QHY camera discovery is enabled.
///
/// QHY discovery can be disabled if the QHY SDK causes crashes or hangs on the
/// user's system. When disabled, QHY cameras will not appear in device discovery.
///
/// # Returns
/// * `true` - QHY discovery is enabled (default)
/// * `false` - QHY discovery is disabled
bool apiIsQhyDiscoveryEnabled() =>
    RustLib.instance.api.crateApiDiagnosticsApiIsQhyDiscoveryEnabled();

/// Enable or disable QHY camera discovery.
///
/// Use this function to disable QHY discovery if it causes problems:
/// - SDK crashes during enumeration
/// - Discovery hangs and never completes
/// - Conflicts with other camera SDKs
///
/// When disabled:
/// - `discover_devices()` returns empty for QHY cameras/filter wheels
/// - Existing QHY camera connections are not affected
/// - The setting persists for the session but resets on restart
///
/// # Arguments
/// * `enabled` - Whether to enable QHY discovery
///
/// # Example Use Cases
/// 1. Disable if QHY SDK not installed to speed up discovery
/// 2. Disable if QHY SDK crashes on this system
/// 3. Disable temporarily to troubleshoot conflicts
void apiSetQhyDiscoveryEnabled({required bool enabled}) => RustLib.instance.api
    .crateApiDiagnosticsApiSetQhyDiscoveryEnabled(enabled: enabled);

/// Get information about QHY SDK availability and discovery status.
///
/// # Returns
/// * `QhyDiscoveryStatus` - Status information about QHY discovery
QhyDiscoveryStatus apiGetQhyDiscoveryStatus() =>
    RustLib.instance.api.crateApiDiagnosticsApiGetQhyDiscoveryStatus();

/// Status information about QHY discovery
class QhyDiscoveryStatus {
  /// Whether the QHY SDK DLL/SO was loaded successfully
  final bool sdkAvailable;

  /// Whether QHY discovery is currently enabled
  final bool discoveryEnabled;

  /// The timeout for discovery operations in milliseconds
  final BigInt timeoutMs;

  const QhyDiscoveryStatus({
    required this.sdkAvailable,
    required this.discoveryEnabled,
    required this.timeoutMs,
  });

  @override
  int get hashCode =>
      sdkAvailable.hashCode ^ discoveryEnabled.hashCode ^ timeoutMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QhyDiscoveryStatus &&
          runtimeType == other.runtimeType &&
          sdkAvailable == other.sdkAvailable &&
          discoveryEnabled == other.discoveryEnabled &&
          timeoutMs == other.timeoutMs;
}

/// Information about a known device quirk, suitable for UI display.
class QuirkInfo {
  /// Quirk category (e.g. "Temperature", "Timing", "Discovery")
  final String category;

  /// Human-readable description of the quirk
  final String description;

  const QuirkInfo({
    required this.category,
    required this.description,
  });

  @override
  int get hashCode => category.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuirkInfo &&
          runtimeType == other.runtimeType &&
          category == other.category &&
          description == other.description;
}
