// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../device.dart';
import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `query_indi_device_serial_from_client`, `query_indi_serials_for_server`

/// Discover available Alpaca devices on the network
Future<List<DeviceInfo>> apiDiscoverAlpacaDevices() =>
    RustLib.instance.api.crateApiDiscoveryApiDiscoverAlpacaDevices();

/// Discover Alpaca devices at a specific server address
Future<List<DeviceInfo>> apiDiscoverAlpacaAtAddress(
        {required String host, required int port}) =>
    RustLib.instance.api
        .crateApiDiscoveryApiDiscoverAlpacaAtAddress(host: host, port: port);

/// Discover INDI devices at a specific server address
Future<List<DeviceInfo>> apiDiscoverIndiAtAddress(
        {required String host, required int port}) =>
    RustLib.instance.api
        .crateApiDiscoveryApiDiscoverIndiAtAddress(host: host, port: port);

/// Auto-discover INDI servers on localhost
Future<List<DeviceInfo>> apiDiscoverIndiLocalhost() =>
    RustLib.instance.api.crateApiDiscoveryApiDiscoverIndiLocalhost();

/// Auto-discover INDI servers on common hostnames (localhost, raspberrypi, stellarmate, etc.)
Future<List<DeviceInfo>> apiDiscoverIndiCommonHosts() =>
    RustLib.instance.api.crateApiDiscoveryApiDiscoverIndiCommonHosts();

/// Auto-discover INDI servers on the local network (scans subnet)
Future<List<DeviceInfo>> apiDiscoverIndiNetwork() =>
    RustLib.instance.api.crateApiDiscoveryApiDiscoverIndiNetwork();

/// Discover available devices of a specific type.
/// Queries Windows-only ASCOM COM drivers, Alpaca network devices or bridges,
/// Native SDK paths bundled for the current release, simulator paths where
/// enabled, and reachable INDI servers. All results are cached for 60 seconds -- the FIRST call to this
/// function runs full discovery for every source and every device type, and subsequent
/// calls within the TTL simply filter the cached results by the requested `device_type`.
Future<List<DeviceInfo>> apiDiscoverDevices({required DeviceType deviceType}) =>
    RustLib.instance.api
        .crateApiDiscoveryApiDiscoverDevices(deviceType: deviceType);
