// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../device.dart';
import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Start heartbeat monitoring for a device
///
/// This will poll the device status at the specified interval and emit
/// a Disconnected event if the device becomes unresponsive.
///
/// # Arguments
/// * `device_type` - The type of device to monitor (used for validation)
/// * `device_id` - The unique identifier for the device
/// * `interval_ms` - Heartbeat interval in milliseconds (recommended: 10000)
Future<void> apiStartDeviceHeartbeat(
        {required DeviceType deviceType,
        required String deviceId,
        required BigInt intervalMs}) =>
    RustLib.instance.api.crateApiHeartbeatApiStartDeviceHeartbeat(
        deviceType: deviceType, deviceId: deviceId, intervalMs: intervalMs);

/// Stop heartbeat monitoring for a device
///
/// # Arguments
/// * `device_id` - The unique identifier for the device
Future<void> apiStopDeviceHeartbeat({required String deviceId}) =>
    RustLib.instance.api
        .crateApiHeartbeatApiStopDeviceHeartbeat(deviceId: deviceId);

/// Start heartbeat monitoring with custom configuration
///
/// This allows full control over the heartbeat behavior including:
/// - Check interval and maximum interval after backoff
/// - Number of failures before marking device as disconnected
/// - Whether to attempt auto-reconnection
/// - Reconnection attempt limits and delays
///
/// # Arguments
/// * `device_id` - The unique identifier for the device
/// * `interval_secs` - Base interval between heartbeats in seconds
/// * `failure_threshold` - Number of consecutive failures before disconnect
/// * `auto_reconnect` - Whether to attempt automatic reconnection
/// * `max_reconnect_attempts` - Maximum reconnection attempts (0 = unlimited)
Future<void> apiStartDeviceHeartbeatWithConfig(
        {required String deviceId,
        required BigInt intervalSecs,
        required int failureThreshold,
        required bool autoReconnect,
        required int maxReconnectAttempts}) =>
    RustLib.instance.api.crateApiHeartbeatApiStartDeviceHeartbeatWithConfig(
        deviceId: deviceId,
        intervalSecs: intervalSecs,
        failureThreshold: failureThreshold,
        autoReconnect: autoReconnect,
        maxReconnectAttempts: maxReconnectAttempts);

/// Get the default heartbeat configuration for a device type
///
/// Returns the recommended heartbeat settings for the specified device type.
/// Different device types have different optimal configurations based on
/// their operational characteristics.
///
/// # Arguments
/// * `device_type` - The type of device to get configuration for
///
/// # Returns
/// A tuple of (interval_secs, max_interval_secs, failure_threshold, auto_reconnect)
Future<(BigInt, BigInt, int, bool)> apiGetHeartbeatConfigForType(
        {required DeviceType deviceType}) =>
    RustLib.instance.api
        .crateApiHeartbeatApiGetHeartbeatConfigForType(deviceType: deviceType);

/// Check device health status
///
/// Returns the last successful communication timestamp and whether
/// the device is currently responding to heartbeat checks.
///
/// # Arguments
/// * `device_id` - The unique identifier for the device
///
/// # Returns
/// A tuple of (last_successful_timestamp_ms, is_healthy)
Future<(PlatformInt64, bool)> apiGetDeviceHealth({required String deviceId}) =>
    RustLib.instance.api
        .crateApiHeartbeatApiGetDeviceHealth(deviceId: deviceId);

/// Get detailed heartbeat status for a device
///
/// Returns comprehensive information about the heartbeat monitoring status
/// including configuration, last successful communication, and whether
/// monitoring is active.
///
/// # Arguments
/// * `device_id` - The unique identifier for the device
///
/// # Returns
/// DeviceHeartbeatInfo with all heartbeat details
Future<DeviceHeartbeatInfo> apiGetDeviceHeartbeatInfo(
        {required String deviceId}) =>
    RustLib.instance.api
        .crateApiHeartbeatApiGetDeviceHeartbeatInfo(deviceId: deviceId);

/// Check if heartbeat monitoring is active for a device
Future<bool> apiIsHeartbeatActive({required String deviceId}) =>
    RustLib.instance.api
        .crateApiHeartbeatApiIsHeartbeatActive(deviceId: deviceId);

/// Detailed heartbeat status for a device
class DeviceHeartbeatInfo {
  /// Device ID
  final String deviceId;

  /// Device type (e.g., "Camera", "Mount")
  final String deviceType;

  /// Whether heartbeat monitoring is currently active
  final bool heartbeatActive;

  /// Last successful communication timestamp (milliseconds since epoch)
  final PlatformInt64? lastSuccessfulCommMs;

  /// Current heartbeat interval in seconds
  final BigInt intervalSecs;

  /// Maximum interval after backoff in seconds
  final BigInt maxIntervalSecs;

  /// Number of failures before marking disconnected
  final int failureThreshold;

  /// Whether auto-reconnect is enabled
  final bool autoReconnect;

  /// Maximum reconnection attempts (0 = unlimited)
  final int maxReconnectAttempts;

  const DeviceHeartbeatInfo({
    required this.deviceId,
    required this.deviceType,
    required this.heartbeatActive,
    this.lastSuccessfulCommMs,
    required this.intervalSecs,
    required this.maxIntervalSecs,
    required this.failureThreshold,
    required this.autoReconnect,
    required this.maxReconnectAttempts,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      deviceType.hashCode ^
      heartbeatActive.hashCode ^
      lastSuccessfulCommMs.hashCode ^
      intervalSecs.hashCode ^
      maxIntervalSecs.hashCode ^
      failureThreshold.hashCode ^
      autoReconnect.hashCode ^
      maxReconnectAttempts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceHeartbeatInfo &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceType == other.deviceType &&
          heartbeatActive == other.heartbeatActive &&
          lastSuccessfulCommMs == other.lastSuccessfulCommMs &&
          intervalSecs == other.intervalSecs &&
          maxIntervalSecs == other.maxIntervalSecs &&
          failureThreshold == other.failureThreshold &&
          autoReconnect == other.autoReconnect &&
          maxReconnectAttempts == other.maxReconnectAttempts;
}
