// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Force an immediate hot-plug diff pass across every polled driver and
/// device type, independent of the 30 s slow-poll cadence.
///
/// Wired to the equipment-screen "Rescan equipment" button. Behaviour:
///   1. Invalidate the per-(type, driver) discovery cache so the next UI
///      `discoverAll()` call cannot serve stale TTL'd results.
///   2. Run `hotplug::trigger_rescan` which walks the native vendor SDKs
///      and (on Windows) the ASCOM registry, diffs against the cached
///      snapshot and emits `device_discovered` / `device_lost` events for
///      any deltas. Existing devices do NOT re-emit (the diff is
///      idempotent across calls — see `cache_diff_detects_arrival_and_removal`
///      in `hotplug::tests`).
///
/// Returns when the diff finishes. The UI uses this as the await-target for
/// its spinner / "Rescanning..." label.
///
/// Errors: individual backend scan failures are surfaced via `tracing` from
/// inside `poll_once` and do not propagate here. We do NOT bubble them as a
/// `Result` because the diff itself is total — a single backend erroring
/// out must not cancel the other backends' arrival events, and a user
/// pressing Rescan does not want to debug an ASI SDK error from a Dart
/// snackbar. Real failures show up in the rolling log.
Future<void> apiRescanDevices() =>
    RustLib.instance.api.crateApiHotplugApiRescanDevices();
