// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_config`, `describe_error`, `ensure_parent_dir`, `stitch_mosaic_impl`, `wcs_from_header`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `OutputArgs`, `PanelArgs`, `StitchConfigArgs`, `StitchMosaicArgs`, `StitchMosaicResult`, `WcsArgs`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`, `default`, `default`, `default`

/// Stitch N plate-solved panel masters into one mosaic master.
///
/// Each panel is read from FITS; its WCS is taken from the explicit `wcs` block
/// when supplied, else parsed from the header CD matrix (with a `CDELT`/`CROTA`
/// fallback). The panels are projected onto a common gnomonic canvas, optionally
/// photometrically normalized over their overlaps, and feather-blended into one
/// `F32` master via [`stitch_mosaic`]. The master is written to
/// `output.mosaicFitsPath` with the output canvas WCS stamped in the header;
/// when `coverageFitsPath` / `previewPngPath` are given the coverage plane /
/// stretched preview are written too.
///
/// `args_json` is a [`StitchMosaicArgs`]; the result is a [`StitchMosaicResult`].
/// Every failure surfaces as `Err(String)` rather than a partial mosaic.
Future<String> apiStitchMosaic({required String argsJson}) =>
    RustLib.instance.api.crateApiMosaicApiStitchMosaic(argsJson: argsJson);
