// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `calculate_rotation_center`, `emit_polar_error`, `emit_polar_image`, `emit_polar_status`, `get_polar_align_cancel`, `get_polar_align_flag`, `run_polar_alignment`, `write_temp_fits_for_solve`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PolarAlignmentMode`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

/// Start three-point polar alignment
///
/// This initiates the polar alignment process which will:
/// 1. Capture 3 images at different mount rotations
/// 2. Plate solve each image
/// 3. Calculate the center of rotation
/// 4. Enter adjustment mode with real-time error updates
///
/// Note: Requires connected camera and mount devices.
Future<void> apiStartPolarAlignment(
        {required double exposureTime,
        required double stepSize,
        required int binning,
        required bool isNorth,
        required bool manualRotation,
        required bool rotateEast,
        int? gain,
        int? offset,
        double? solveTimeout,
        bool? startFromCurrent,
        double? autoCompleteThreshold}) =>
    RustLib.instance.api.crateApiPolarAlignmentApiStartPolarAlignment(
        exposureTime: exposureTime,
        stepSize: stepSize,
        binning: binning,
        isNorth: isNorth,
        manualRotation: manualRotation,
        rotateEast: rotateEast,
        gain: gain,
        offset: offset,
        solveTimeout: solveTimeout,
        startFromCurrent: startFromCurrent,
        autoCompleteThreshold: autoCompleteThreshold);

/// Stop the polar alignment process
Future<void> apiStopPolarAlignment() =>
    RustLib.instance.api.crateApiPolarAlignmentApiStopPolarAlignment();

/// Start all-sky polar alignment.
///
/// Unlike TPPA this routine does not require the celestial pole region to
/// be visible. It takes a single exposure anywhere in the sky, plate-solves
/// it to anchor a baseline, then re-solves every `iteration_cadence_secs`
/// to measure drift relative to that baseline. From the drift signature
/// and the observer's geographic location it recovers the polar-axis
/// azimuth and altitude error.
///
/// # Arguments
/// * `exposure_time` — exposure duration per frame, seconds.
/// * `solve_timeout` — plate-solve timeout per frame, seconds.
/// * `binning` — camera binning factor (1, 2, or 4 typical).
/// * `is_north` — northern hemisphere observer flag.
/// * `acceptance_threshold_arcsec` — alignment auto-completes when the
///   total error stays below this for 3 seconds (default 30″ = good for
///   ~3-minute unguided subs).
/// * `iteration_cadence_secs` — re-solve cadence (default 3s).
/// * `gain`, `offset` — optional camera parameters.
///
/// # Errors
/// Returns `NightshadeError::OperationFailed` if a plate solver is not
/// available (the user must install ASTAP), if no camera/mount is
/// connected, or if the observer location is not configured.
Future<void> apiStartAllSkyPolarAlignment(
        {required double exposureTime,
        required double solveTimeout,
        required int binning,
        required bool isNorth,
        required double acceptanceThresholdArcsec,
        required double iterationCadenceSecs,
        int? gain,
        int? offset}) =>
    RustLib.instance.api.crateApiPolarAlignmentApiStartAllSkyPolarAlignment(
        exposureTime: exposureTime,
        solveTimeout: solveTimeout,
        binning: binning,
        isNorth: isNorth,
        acceptanceThresholdArcsec: acceptanceThresholdArcsec,
        iterationCadenceSecs: iterationCadenceSecs,
        gain: gain,
        offset: offset);
