// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `manager`, `new_secondary_session_id`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SecondaryRigManager`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Arm + start the secondary capture loop. Installs the dither barrier into the
/// sequencer's process-wide slot so the primary coordinates with it; if a
/// sequence is already running the executor will pick up the barrier on its
/// next dither (it reads `active_barrier()` at `start()` — see note below).
///
/// Best practice: arm the secondary BEFORE starting the primary sequence so the
/// barrier is installed when the executor builds its context. Arming mid-run
/// still coordinates the *secondary* side (it gates on `dither_pending`), but
/// the *primary* only consults the barrier it captured at start; a future
/// enhancement could push a live barrier into the running executor.
Future<void> apiSecondaryRigStart({required SecondaryRigConfigApi config}) =>
    RustLib.instance.api.crateApiSecondaryRigApiSecondaryRigStart(
      config: config,
    );

/// Stop the secondary capture loop and tear down the barrier. Idempotent.
Future<void> apiSecondaryRigStop() =>
    RustLib.instance.api.crateApiSecondaryRigApiSecondaryRigStop();

/// Live status snapshot of the secondary rig (for UI / headless monitoring).
Future<SecondaryRigStatusApi> apiSecondaryRigGetStatus() =>
    RustLib.instance.api.crateApiSecondaryRigApiSecondaryRigGetStatus();

/// Whether a secondary rig is currently armed.
Future<bool> apiSecondaryRigIsArmed() =>
    RustLib.instance.api.crateApiSecondaryRigApiSecondaryRigIsArmed();

/// FRB-facing configuration for arming the secondary rig. Mirrors
/// [`SecondaryRigConfig`] plus the dither-coordination policy + frame metadata.
class SecondaryRigConfigApi {
  /// Device id of the secondary camera. MUST be a second, already-connected
  /// camera distinct from the primary's.
  final String cameraId;
  final double exposureSecs;
  final int? gain;
  final int? offset;
  final int binX;
  final int binY;

  /// `None` => run until the primary sequence ends (stopped via `api_*_stop`).
  final int? frameCount;
  final String? filterName;
  final double? targetTempC;

  /// Human label for the rig, used in the save sub-folder + `NS-RIG` keyword.
  final String rigLabel;
  final String? cameraMake;
  final String? cameraModel;
  final String? telescopeName;
  final double? telescopeFocalLengthMm;
  final double? telescopeApertureMm;

  /// Max seconds the primary waits for the secondary to clear before
  /// dithering anyway (bounded so a stuck secondary never stalls the primary).
  final double ditherMaxWaitSecs;

  /// "complete_if_short" (default) or "abort_immediately".
  final String inFlightPolicy;

  /// Base directory frames are saved into. The secondary writes into a
  /// `<base>/<rig_label>/` subfolder. `None` => current working directory.
  final String? saveBasePath;

  /// Target name inherited from the primary (stamped into FITS `OBJECT`).
  final String? targetName;
  final double? targetRaHours;
  final double? targetDecDegrees;
  final String? observerName;
  final double? siteLatitudeDeg;
  final double? siteLongitudeDeg;
  final double? siteElevationM;

  const SecondaryRigConfigApi({
    required this.cameraId,
    required this.exposureSecs,
    this.gain,
    this.offset,
    required this.binX,
    required this.binY,
    this.frameCount,
    this.filterName,
    this.targetTempC,
    required this.rigLabel,
    this.cameraMake,
    this.cameraModel,
    this.telescopeName,
    this.telescopeFocalLengthMm,
    this.telescopeApertureMm,
    required this.ditherMaxWaitSecs,
    required this.inFlightPolicy,
    this.saveBasePath,
    this.targetName,
    this.targetRaHours,
    this.targetDecDegrees,
    this.observerName,
    this.siteLatitudeDeg,
    this.siteLongitudeDeg,
    this.siteElevationM,
  });

  @override
  int get hashCode =>
      cameraId.hashCode ^
      exposureSecs.hashCode ^
      gain.hashCode ^
      offset.hashCode ^
      binX.hashCode ^
      binY.hashCode ^
      frameCount.hashCode ^
      filterName.hashCode ^
      targetTempC.hashCode ^
      rigLabel.hashCode ^
      cameraMake.hashCode ^
      cameraModel.hashCode ^
      telescopeName.hashCode ^
      telescopeFocalLengthMm.hashCode ^
      telescopeApertureMm.hashCode ^
      ditherMaxWaitSecs.hashCode ^
      inFlightPolicy.hashCode ^
      saveBasePath.hashCode ^
      targetName.hashCode ^
      targetRaHours.hashCode ^
      targetDecDegrees.hashCode ^
      observerName.hashCode ^
      siteLatitudeDeg.hashCode ^
      siteLongitudeDeg.hashCode ^
      siteElevationM.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SecondaryRigConfigApi &&
          runtimeType == other.runtimeType &&
          cameraId == other.cameraId &&
          exposureSecs == other.exposureSecs &&
          gain == other.gain &&
          offset == other.offset &&
          binX == other.binX &&
          binY == other.binY &&
          frameCount == other.frameCount &&
          filterName == other.filterName &&
          targetTempC == other.targetTempC &&
          rigLabel == other.rigLabel &&
          cameraMake == other.cameraMake &&
          cameraModel == other.cameraModel &&
          telescopeName == other.telescopeName &&
          telescopeFocalLengthMm == other.telescopeFocalLengthMm &&
          telescopeApertureMm == other.telescopeApertureMm &&
          ditherMaxWaitSecs == other.ditherMaxWaitSecs &&
          inFlightPolicy == other.inFlightPolicy &&
          saveBasePath == other.saveBasePath &&
          targetName == other.targetName &&
          targetRaHours == other.targetRaHours &&
          targetDecDegrees == other.targetDecDegrees &&
          observerName == other.observerName &&
          siteLatitudeDeg == other.siteLatitudeDeg &&
          siteLongitudeDeg == other.siteLongitudeDeg &&
          siteElevationM == other.siteElevationM;
}

/// FRB-facing live status snapshot of the secondary rig.
class SecondaryRigStatusApi {
  final bool armed;
  final bool running;
  final String? cameraId;
  final String rigLabel;
  final int framesCaptured;
  final int framesAborted;
  final int? plannedFrames;
  final bool waitingForDither;
  final bool exposing;
  final bool ditherPending;
  final int forcedProceeds;
  final String? lastError;

  const SecondaryRigStatusApi({
    required this.armed,
    required this.running,
    this.cameraId,
    required this.rigLabel,
    required this.framesCaptured,
    required this.framesAborted,
    this.plannedFrames,
    required this.waitingForDither,
    required this.exposing,
    required this.ditherPending,
    required this.forcedProceeds,
    this.lastError,
  });

  static Future<SecondaryRigStatusApi> default_() =>
      RustLib.instance.api.crateApiSecondaryRigSecondaryRigStatusApiDefault();

  @override
  int get hashCode =>
      armed.hashCode ^
      running.hashCode ^
      cameraId.hashCode ^
      rigLabel.hashCode ^
      framesCaptured.hashCode ^
      framesAborted.hashCode ^
      plannedFrames.hashCode ^
      waitingForDither.hashCode ^
      exposing.hashCode ^
      ditherPending.hashCode ^
      forcedProceeds.hashCode ^
      lastError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SecondaryRigStatusApi &&
          runtimeType == other.runtimeType &&
          armed == other.armed &&
          running == other.running &&
          cameraId == other.cameraId &&
          rigLabel == other.rigLabel &&
          framesCaptured == other.framesCaptured &&
          framesAborted == other.framesAborted &&
          plannedFrames == other.plannedFrames &&
          waitingForDither == other.waitingForDither &&
          exposing == other.exposing &&
          ditherPending == other.ditherPending &&
          forcedProceeds == other.forcedProceeds &&
          lastError == other.lastError;
}
