// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_sequence_executor`, `run_sequencer_event_loop`, `serialize_node_definition`, `serialize_sequence_definition`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `api_sequencer_event_stream`

/// Load a sequence from JSON
Future<void> apiSequencerLoadJson({required String json}) =>
    RustLib.instance.api.crateApiSequencerApiSequencerLoadJson(json: json);

/// Load a sequence from a definition struct
Future<void> apiSequencerLoad({required SequenceDefinitionApi definition}) =>
    RustLib.instance.api
        .crateApiSequencerApiSequencerLoad(definition: definition);

/// Start the sequence executor
Future<void> apiSequencerStart() =>
    RustLib.instance.api.crateApiSequencerApiSequencerStart();

/// Pause the sequence executor
Future<void> apiSequencerPause() =>
    RustLib.instance.api.crateApiSequencerApiSequencerPause();

/// Resume the sequence executor
Future<void> apiSequencerResume() =>
    RustLib.instance.api.crateApiSequencerApiSequencerResume();

/// Stop the sequence executor
Future<void> apiSequencerStop() =>
    RustLib.instance.api.crateApiSequencerApiSequencerStop();

/// Skip to the next instruction
Future<void> apiSequencerSkip() =>
    RustLib.instance.api.crateApiSequencerApiSequencerSkip();

/// Reset the sequence executor
Future<void> apiSequencerReset() =>
    RustLib.instance.api.crateApiSequencerApiSequencerReset();

/// Get the current sequencer state
Future<SequencerState> apiSequencerGetState() =>
    RustLib.instance.api.crateApiSequencerApiSequencerGetState();

/// Subscribe to sequencer events and forward them to the main event stream
Future<void> apiSequencerSubscribeEvents() =>
    RustLib.instance.api.crateApiSequencerApiSequencerSubscribeEvents();

/// Set the checkpoint directory for crash recovery
Future<void> apiSequencerSetCheckpointDir({required String path}) =>
    RustLib.instance.api
        .crateApiSequencerApiSequencerSetCheckpointDir(path: path);

/// Check if a recoverable checkpoint exists
Future<bool> apiSequencerHasCheckpoint() =>
    RustLib.instance.api.crateApiSequencerApiSequencerHasCheckpoint();

/// Get info about the current checkpoint
Future<CheckpointInfoApi?> apiSequencerGetCheckpointInfo() =>
    RustLib.instance.api.crateApiSequencerApiSequencerGetCheckpointInfo();

/// Resume sequence from checkpoint
Future<void> apiSequencerResumeFromCheckpoint() =>
    RustLib.instance.api.crateApiSequencerApiSequencerResumeFromCheckpoint();

/// Save current execution state as checkpoint
Future<void> apiSequencerSaveCheckpoint() =>
    RustLib.instance.api.crateApiSequencerApiSequencerSaveCheckpoint();

/// Clear/discard checkpoint (call when sequence completes normally or user discards)
Future<void> apiSequencerClearCheckpoint() =>
    RustLib.instance.api.crateApiSequencerApiSequencerClearCheckpoint();

/// Set simulation mode (use mock devices instead of real hardware)
Future<void> apiSequencerSetSimulationMode({required bool enabled}) =>
    RustLib.instance.api
        .crateApiSequencerApiSequencerSetSimulationMode(enabled: enabled);

/// Set connected devices for the sequencer
Future<void> apiSequencerSetDevices(
        {String? cameraId,
        String? mountId,
        String? focuserId,
        String? filterwheelId,
        String? rotatorId,
        List<String>? filterNames,
        Map<String, int>? filterFocusOffsets}) =>
    RustLib.instance.api.crateApiSequencerApiSequencerSetDevices(
        cameraId: cameraId,
        mountId: mountId,
        focuserId: focuserId,
        filterwheelId: filterwheelId,
        rotatorId: rotatorId,
        filterNames: filterNames,
        filterFocusOffsets: filterFocusOffsets);

/// Set the safety fail mode for the sequencer.
/// This determines behavior when safety devices fail or are unavailable:
/// - "fail_closed": Treat unavailable safety data as unsafe (enforced)
/// - "fail_open"/"warn_only": accepted for backward compatibility and coerced to fail_closed
Future<void> apiSequencerSetSafetyFailMode({required String mode}) =>
    RustLib.instance.api
        .crateApiSequencerApiSequencerSetSafetyFailMode(mode: mode);

/// Set the save path for sequencer images.
/// This is the base directory where captured images will be saved.
/// If not set (or set to None), images will NOT be saved to disk.
Future<void> apiSequencerSetSavePath({String? path}) =>
    RustLib.instance.api.crateApiSequencerApiSequencerSetSavePath(path: path);

/// Update dither configuration at runtime while a sequence is running or paused.
/// The updated values are stored on the executor and will be used by subsequent
/// trigger-initiated dithers and checkpoint resumes.
Future<void> apiSequencerUpdateDitherConfig(
        {required double pixels,
        required double settlePixels,
        required double settleTime,
        required double settleTimeout,
        required bool raOnly}) =>
    RustLib.instance.api.crateApiSequencerApiSequencerUpdateDitherConfig(
        pixels: pixels,
        settlePixels: settlePixels,
        settleTime: settleTime,
        settleTimeout: settleTimeout,
        raOnly: raOnly);

/// Update observer location at runtime while a sequence is running or paused.
/// Updates the executor's stored latitude/longitude so altitude-based triggers
/// use the correct location on their next evaluation.
Future<void> apiSequencerUpdateLocation(
        {double? latitude, double? longitude}) =>
    RustLib.instance.api.crateApiSequencerApiSequencerUpdateLocation(
        latitude: latitude, longitude: longitude);

/// Update filter focus offsets at runtime while a sequence is running or paused.
/// Updates the executor's stored offsets so subsequent filter changes apply
/// the correct focus compensation.
Future<void> apiSequencerUpdateFilterOffsets(
        {required Map<String, int> offsets}) =>
    RustLib.instance.api
        .crateApiSequencerApiSequencerUpdateFilterOffsets(offsets: offsets);

/// Create an exposure node configuration
String apiCreateExposureNode(
        {required String id,
        required String name,
        required double durationSecs,
        required int count,
        String? filter,
        int? filterIndex,
        int? gain,
        int? offset,
        required int binning,
        int? ditherEvery}) =>
    RustLib.instance.api.crateApiSequencerApiCreateExposureNode(
        id: id,
        name: name,
        durationSecs: durationSecs,
        count: count,
        filter: filter,
        filterIndex: filterIndex,
        gain: gain,
        offset: offset,
        binning: binning,
        ditherEvery: ditherEvery);

/// Create a slew node configuration
String apiCreateSlewNode(
        {required String id,
        required String name,
        required int useTargetCoords,
        double? customRa,
        double? customDec}) =>
    RustLib.instance.api.crateApiSequencerApiCreateSlewNode(
        id: id,
        name: name,
        useTargetCoords: useTargetCoords,
        customRa: customRa,
        customDec: customDec);

/// Create a center node configuration
String apiCreateCenterNode(
        {required String id,
        required String name,
        required int useTargetCoords,
        required double accuracyArcsec,
        required int maxAttempts,
        required double exposureDuration}) =>
    RustLib.instance.api.crateApiSequencerApiCreateCenterNode(
        id: id,
        name: name,
        useTargetCoords: useTargetCoords,
        accuracyArcsec: accuracyArcsec,
        maxAttempts: maxAttempts,
        exposureDuration: exposureDuration);

/// Create an autofocus node configuration
String apiCreateAutofocusNode(
        {required String id,
        required String name,
        required int stepSize,
        required int stepsOut,
        required double exposureDuration,
        required String method}) =>
    RustLib.instance.api.crateApiSequencerApiCreateAutofocusNode(
        id: id,
        name: name,
        stepSize: stepSize,
        stepsOut: stepsOut,
        exposureDuration: exposureDuration,
        method: method);

/// Create a filter change node configuration
String apiCreateFilterNode(
        {required String id,
        required String name,
        required String filterName}) =>
    RustLib.instance.api.crateApiSequencerApiCreateFilterNode(
        id: id, name: name, filterName: filterName);

/// Create a target group node configuration (legacy - use target_header instead)
String apiCreateTargetGroupNode(
        {required String id,
        required String name,
        required String targetName,
        required double raHours,
        required double decDegrees,
        double? rotation,
        double? minAltitude,
        double? maxAltitude,
        required int priority,
        required List<String> children}) =>
    RustLib.instance.api.crateApiSequencerApiCreateTargetGroupNode(
        id: id,
        name: name,
        targetName: targetName,
        raHours: raHours,
        decDegrees: decDegrees,
        rotation: rotation,
        minAltitude: minAltitude,
        maxAltitude: maxAltitude,
        priority: priority,
        children: children);

/// Create a target header node configuration
String apiCreateTargetHeaderNode(
        {required String id,
        required String name,
        required String targetName,
        required double raHours,
        required double decDegrees,
        double? rotation,
        double? minAltitude,
        double? maxAltitude,
        required int priority,
        PlatformInt64? startAfter,
        PlatformInt64? endBefore,
        String? mosaicPanelJson,
        required List<String> children}) =>
    RustLib.instance.api.crateApiSequencerApiCreateTargetHeaderNode(
        id: id,
        name: name,
        targetName: targetName,
        raHours: raHours,
        decDegrees: decDegrees,
        rotation: rotation,
        minAltitude: minAltitude,
        maxAltitude: maxAltitude,
        priority: priority,
        startAfter: startAfter,
        endBefore: endBefore,
        mosaicPanelJson: mosaicPanelJson,
        children: children);

/// Create a loop node configuration
String apiCreateLoopNode(
        {required String id,
        required String name,
        int? iterations,
        required String condition,
        required List<String> children}) =>
    RustLib.instance.api.crateApiSequencerApiCreateLoopNode(
        id: id,
        name: name,
        iterations: iterations,
        condition: condition,
        children: children);

/// Create a delay node configuration
String apiCreateDelayNode(
        {required String id, required String name, required double seconds}) =>
    RustLib.instance.api.crateApiSequencerApiCreateDelayNode(
        id: id, name: name, seconds: seconds);

/// Create a park node configuration
String apiCreateParkNode({required String id, required String name}) =>
    RustLib.instance.api.crateApiSequencerApiCreateParkNode(id: id, name: name);

/// Create an unpark node configuration
String apiCreateUnparkNode({required String id, required String name}) =>
    RustLib.instance.api
        .crateApiSequencerApiCreateUnparkNode(id: id, name: name);

/// Create a cool camera node configuration
String apiCreateCoolCameraNode(
        {required String id,
        required String name,
        required double targetTemp,
        double? durationMins}) =>
    RustLib.instance.api.crateApiSequencerApiCreateCoolCameraNode(
        id: id, name: name, targetTemp: targetTemp, durationMins: durationMins);

/// Create a warm camera node configuration
String apiCreateWarmCameraNode(
        {required String id,
        required String name,
        required double ratePerMin,
        double? targetTemp}) =>
    RustLib.instance.api.crateApiSequencerApiCreateWarmCameraNode(
        id: id, name: name, ratePerMin: ratePerMin, targetTemp: targetTemp);

/// Create a dither node configuration
String apiCreateDitherNode(
        {required String id,
        required String name,
        required double pixels,
        required double settlePixels,
        required double settleTime,
        required double settleTimeout,
        required int raOnly}) =>
    RustLib.instance.api.crateApiSequencerApiCreateDitherNode(
        id: id,
        name: name,
        pixels: pixels,
        settlePixels: settlePixels,
        settleTime: settleTime,
        settleTimeout: settleTimeout,
        raOnly: raOnly);

/// Create a wait time node configuration
String apiCreateWaitTimeNode(
        {required String id,
        required String name,
        PlatformInt64? waitUntil,
        String? twilightType}) =>
    RustLib.instance.api.crateApiSequencerApiCreateWaitTimeNode(
        id: id, name: name, waitUntil: waitUntil, twilightType: twilightType);

/// Create a notification node configuration
String apiCreateNotificationNode(
        {required String id,
        required String name,
        required String title,
        required String message,
        required String level}) =>
    RustLib.instance.api.crateApiSequencerApiCreateNotificationNode(
        id: id, name: name, title: title, message: message, level: level);

/// Create a script node configuration
String apiCreateScriptNode(
        {required String id,
        required String name,
        required String scriptPath,
        required List<String> arguments,
        int? timeoutSecs}) =>
    RustLib.instance.api.crateApiSequencerApiCreateScriptNode(
        id: id,
        name: name,
        scriptPath: scriptPath,
        arguments: arguments,
        timeoutSecs: timeoutSecs);

/// Create a rotator node configuration
String apiCreateRotatorNode(
        {required String id,
        required String name,
        required double targetAngle,
        required int relative}) =>
    RustLib.instance.api.crateApiSequencerApiCreateRotatorNode(
        id: id, name: name, targetAngle: targetAngle, relative: relative);

/// Build a complete sequence definition from nodes
String apiBuildSequence(
        {required String id,
        required String name,
        String? description,
        required List<String> nodeJsons,
        String? rootNodeId}) =>
    RustLib.instance.api.crateApiSequencerApiBuildSequence(
        id: id,
        name: name,
        description: description,
        nodeJsons: nodeJsons,
        rootNodeId: rootNodeId);

/// Calculate mosaic panel positions given center coordinates and configuration
///
/// # Arguments
/// * `center_ra` - Center RA in hours (0-24)
/// * `center_dec` - Center Dec in degrees (-90 to +90)
/// * `panel_width_arcmin` - Panel width in arcminutes
/// * `panel_height_arcmin` - Panel height in arcminutes
/// * `overlap_percent` - Overlap percentage (0-50)
/// * `rotation` - Rotation angle in degrees
/// * `panels_horizontal` - Number of horizontal panels
/// * `panels_vertical` - Number of vertical panels
///
/// # Returns
/// Vector of MosaicPanelResult with calculated RA/Dec for each panel
List<MosaicPanelResult> apiCalculateMosaicPanels(
        {required double centerRa,
        required double centerDec,
        required double panelWidthArcmin,
        required double panelHeightArcmin,
        required double overlapPercent,
        required double rotation,
        required int panelsHorizontal,
        required int panelsVertical}) =>
    RustLib.instance.api.crateApiSequencerApiCalculateMosaicPanels(
        centerRa: centerRa,
        centerDec: centerDec,
        panelWidthArcmin: panelWidthArcmin,
        panelHeightArcmin: panelHeightArcmin,
        overlapPercent: overlapPercent,
        rotation: rotation,
        panelsHorizontal: panelsHorizontal,
        panelsVertical: panelsVertical);

/// Calculate total mosaic coverage area in square degrees
double apiCalculateMosaicArea(
        {required double panelWidthArcmin,
        required double panelHeightArcmin,
        required int panelsHorizontal,
        required int panelsVertical}) =>
    RustLib.instance.api.crateApiSequencerApiCalculateMosaicArea(
        panelWidthArcmin: panelWidthArcmin,
        panelHeightArcmin: panelHeightArcmin,
        panelsHorizontal: panelsHorizontal,
        panelsVertical: panelsVertical);

/// Estimate total imaging time for mosaic in seconds
///
/// # Arguments
/// * `total_panels` - Total number of panels
/// * `exposure_secs` - Exposure time per frame
/// * `exposures_per_panel` - Number of exposures per panel
/// * `overhead_per_panel_secs` - Overhead per panel (slew, center, settle) - defaults to 60s if 0
double apiEstimateMosaicTime(
        {required int totalPanels,
        required double exposureSecs,
        required int exposuresPerPanel,
        required double overheadPerPanelSecs}) =>
    RustLib.instance.api.crateApiSequencerApiEstimateMosaicTime(
        totalPanels: totalPanels,
        exposureSecs: exposureSecs,
        exposuresPerPanel: exposuresPerPanel,
        overheadPerPanelSecs: overheadPerPanelSecs);

/// Calculate altitude for a target at a specific time and observer location
///
/// # Arguments
/// * `ra_hours` - Right Ascension in hours (0-24)
/// * `dec_degrees` - Declination in degrees (-90 to +90)
/// * `latitude` - Observer's latitude in degrees (-90 to +90, positive is north)
/// * `longitude` - Observer's longitude in degrees (-180 to +180, positive is east)
/// * `time_unix_millis` - UTC time as Unix timestamp in milliseconds
///
/// # Returns
/// Altitude in degrees above the horizon (-90 to +90)
double apiCalculateAltitude(
        {required double raHours,
        required double decDegrees,
        required double latitude,
        required double longitude,
        required PlatformInt64 timeUnixMillis}) =>
    RustLib.instance.api.crateApiSequencerApiCalculateAltitude(
        raHours: raHours,
        decDegrees: decDegrees,
        latitude: latitude,
        longitude: longitude,
        timeUnixMillis: timeUnixMillis);

/// Checkpoint info returned to Dart
class CheckpointInfoApi {
  final String sequenceName;
  final String timestamp;
  final int completedExposures;
  final double completedIntegrationSecs;
  final bool canResume;
  final PlatformInt64 ageSeconds;

  const CheckpointInfoApi({
    required this.sequenceName,
    required this.timestamp,
    required this.completedExposures,
    required this.completedIntegrationSecs,
    required this.canResume,
    required this.ageSeconds,
  });

  @override
  int get hashCode =>
      sequenceName.hashCode ^
      timestamp.hashCode ^
      completedExposures.hashCode ^
      completedIntegrationSecs.hashCode ^
      canResume.hashCode ^
      ageSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CheckpointInfoApi &&
          runtimeType == other.runtimeType &&
          sequenceName == other.sequenceName &&
          timestamp == other.timestamp &&
          completedExposures == other.completedExposures &&
          completedIntegrationSecs == other.completedIntegrationSecs &&
          canResume == other.canResume &&
          ageSeconds == other.ageSeconds;
}

/// Result structure for mosaic panel calculations (FFI-safe)
class MosaicPanelResult {
  final double raHours;
  final double decDegrees;
  final int panelIndex;
  final int row;
  final int col;

  const MosaicPanelResult({
    required this.raHours,
    required this.decDegrees,
    required this.panelIndex,
    required this.row,
    required this.col,
  });

  @override
  int get hashCode =>
      raHours.hashCode ^
      decDegrees.hashCode ^
      panelIndex.hashCode ^
      row.hashCode ^
      col.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MosaicPanelResult &&
          runtimeType == other.runtimeType &&
          raHours == other.raHours &&
          decDegrees == other.decDegrees &&
          panelIndex == other.panelIndex &&
          row == other.row &&
          col == other.col;
}

/// Node definition for Flutter
class NodeDefinitionApi {
  final String id;
  final String name;
  final String nodeType;
  final bool enabled;
  final List<String> children;
  final String configJson;

  const NodeDefinitionApi({
    required this.id,
    required this.name,
    required this.nodeType,
    required this.enabled,
    required this.children,
    required this.configJson,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      nodeType.hashCode ^
      enabled.hashCode ^
      children.hashCode ^
      configJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NodeDefinitionApi &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          nodeType == other.nodeType &&
          enabled == other.enabled &&
          children == other.children &&
          configJson == other.configJson;
}

/// Sequence definition for Flutter
class SequenceDefinitionApi {
  final String id;
  final String name;
  final String? description;
  final List<NodeDefinitionApi> nodes;
  final String? rootNodeId;

  const SequenceDefinitionApi({
    required this.id,
    required this.name,
    this.description,
    required this.nodes,
    this.rootNodeId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      nodes.hashCode ^
      rootNodeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SequenceDefinitionApi &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          nodes == other.nodes &&
          rootNodeId == other.rootNodeId;
}

/// Sequencer state for Flutter
class SequencerState {
  final String state;
  final String? currentNodeId;
  final String? currentNodeName;
  final int totalExposures;
  final int completedExposures;
  final double totalIntegrationSecs;
  final double elapsedSecs;
  final double? estimatedRemainingSecs;
  final String? currentTarget;
  final String? currentFilter;
  final String? message;

  const SequencerState({
    required this.state,
    this.currentNodeId,
    this.currentNodeName,
    required this.totalExposures,
    required this.completedExposures,
    required this.totalIntegrationSecs,
    required this.elapsedSecs,
    this.estimatedRemainingSecs,
    this.currentTarget,
    this.currentFilter,
    this.message,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      currentNodeId.hashCode ^
      currentNodeName.hashCode ^
      totalExposures.hashCode ^
      completedExposures.hashCode ^
      totalIntegrationSecs.hashCode ^
      elapsedSecs.hashCode ^
      estimatedRemainingSecs.hashCode ^
      currentTarget.hashCode ^
      currentFilter.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SequencerState &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          currentNodeId == other.currentNodeId &&
          currentNodeName == other.currentNodeName &&
          totalExposures == other.totalExposures &&
          completedExposures == other.completedExposures &&
          totalIntegrationSecs == other.totalIntegrationSecs &&
          elapsedSecs == other.elapsedSecs &&
          estimatedRemainingSecs == other.estimatedRemainingSecs &&
          currentTarget == other.currentTarget &&
          currentFilter == other.currentFilter &&
          message == other.message;
}
