// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_sequence_executor`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// Node definition for Flutter
class NodeDefinitionApi {
  final String id;
  final String name;
  final String nodeType;
  final bool enabled;
  final List<String> children;
  final String configJson;

  const NodeDefinitionApi({
    required this.id,
    required this.name,
    required this.nodeType,
    required this.enabled,
    required this.children,
    required this.configJson,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      nodeType.hashCode ^
      enabled.hashCode ^
      children.hashCode ^
      configJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NodeDefinitionApi &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          nodeType == other.nodeType &&
          enabled == other.enabled &&
          children == other.children &&
          configJson == other.configJson;
}

/// Sequence definition for Flutter
class SequenceDefinitionApi {
  final String id;
  final String name;
  final String? description;
  final List<NodeDefinitionApi> nodes;
  final String? rootNodeId;

  const SequenceDefinitionApi({
    required this.id,
    required this.name,
    this.description,
    required this.nodes,
    this.rootNodeId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      nodes.hashCode ^
      rootNodeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SequenceDefinitionApi &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          nodes == other.nodes &&
          rootNodeId == other.rootNodeId;
}

/// Sequencer state for Flutter
class SequencerState {
  final String state;
  final String? currentNodeId;
  final String? currentNodeName;
  final int totalExposures;
  final int completedExposures;
  final double totalIntegrationSecs;
  final double elapsedSecs;
  final double? estimatedRemainingSecs;
  final String? currentTarget;
  final String? currentFilter;
  final String? message;

  const SequencerState({
    required this.state,
    this.currentNodeId,
    this.currentNodeName,
    required this.totalExposures,
    required this.completedExposures,
    required this.totalIntegrationSecs,
    required this.elapsedSecs,
    this.estimatedRemainingSecs,
    this.currentTarget,
    this.currentFilter,
    this.message,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      currentNodeId.hashCode ^
      currentNodeName.hashCode ^
      totalExposures.hashCode ^
      completedExposures.hashCode ^
      totalIntegrationSecs.hashCode ^
      elapsedSecs.hashCode ^
      estimatedRemainingSecs.hashCode ^
      currentTarget.hashCode ^
      currentFilter.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SequencerState &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          currentNodeId == other.currentNodeId &&
          currentNodeName == other.currentNodeName &&
          totalExposures == other.totalExposures &&
          completedExposures == other.completedExposures &&
          totalIntegrationSecs == other.totalIntegrationSecs &&
          elapsedSecs == other.elapsedSecs &&
          estimatedRemainingSecs == other.estimatedRemainingSecs &&
          currentTarget == other.currentTarget &&
          currentFilter == other.currentFilter &&
          message == other.message;
}
