// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_unique_temp_fits_path`, `get_discovery_cache`, `get_discovery_lock`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DiscoveryCache`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_device_manager`, `get_state`

/// Invalidate the unified discovery cache, forcing fresh discovery on next call.
/// Also invalidates the native SDK discovery cache so vendor SDKs are re-queried.
/// Called when user explicitly requests a rescan.
Future<void> apiInvalidateDiscoveryCache() =>
    RustLib.instance.api.crateApiApiInvalidateDiscoveryCache();
