// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'device.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'device_capabilities.freezed.dart';

/// Capabilities of a camera device
class CameraCapabilities {
  /// Maximum horizontal resolution in pixels
  final int maxWidth;

  /// Maximum vertical resolution in pixels
  final int maxHeight;

  /// Number of bits per pixel (e.g., 16 for 16-bit camera)
  final int bitDepth;

  /// Whether the camera has a mechanical shutter
  final bool hasShutter;

  /// Whether the camera supports cooling
  final bool canSetCcdTemperature;

  /// Whether the cooler can be turned on/off
  final bool canSetCooler;

  /// Whether the camera reports cooler power
  final bool canGetCoolerPower;

  /// Whether binning is supported
  final bool canBin;

  /// Maximum horizontal binning factor
  final int maxBinX;

  /// Maximum vertical binning factor
  final int maxBinY;

  /// Whether asymmetric binning is supported (bin_x != bin_y)
  final bool canAsymmetricBin;

  /// Whether the camera supports gain adjustment
  final bool canSetGain;

  /// Minimum gain value
  final int? gainMin;

  /// Maximum gain value
  final int? gainMax;

  /// Whether the camera supports offset adjustment
  final bool canSetOffset;

  /// Minimum offset value
  final int? offsetMin;

  /// Maximum offset value
  final int? offsetMax;

  /// Whether the camera can abort exposures
  final bool canAbortExposure;

  /// Whether the camera can stop exposures (graceful stop)
  final bool canStopExposure;

  /// Whether the camera supports subframe readout
  final bool canSubframe;

  /// Pixel size in microns (X)
  final double? pixelSizeX;

  /// Pixel size in microns (Y)
  final double? pixelSizeY;

  /// Whether the camera has a color sensor
  final bool isColor;

  /// Bayer pattern if color (e.g., "RGGB")
  final String? bayerPattern;

  /// Sensor type description
  final String? sensorType;

  /// Whether the camera supports fast readout mode
  final bool hasFastReadout;

  /// Available readout modes
  final List<String> readoutModes;

  /// Minimum exposure time in seconds
  final double? exposureMin;

  /// Maximum exposure time in seconds
  final double? exposureMax;

  /// Current sensor temperature if available
  final double? ccdTemperature;

  /// Current cooler setpoint if available
  final double? setCcdTemperature;

  /// Current cooler power percentage if available
  final double? coolerPower;

  /// Whether cooler is currently on
  final bool? coolerOn;

  const CameraCapabilities({
    required this.maxWidth,
    required this.maxHeight,
    required this.bitDepth,
    required this.hasShutter,
    required this.canSetCcdTemperature,
    required this.canSetCooler,
    required this.canGetCoolerPower,
    required this.canBin,
    required this.maxBinX,
    required this.maxBinY,
    required this.canAsymmetricBin,
    required this.canSetGain,
    this.gainMin,
    this.gainMax,
    required this.canSetOffset,
    this.offsetMin,
    this.offsetMax,
    required this.canAbortExposure,
    required this.canStopExposure,
    required this.canSubframe,
    this.pixelSizeX,
    this.pixelSizeY,
    required this.isColor,
    this.bayerPattern,
    this.sensorType,
    required this.hasFastReadout,
    required this.readoutModes,
    this.exposureMin,
    this.exposureMax,
    this.ccdTemperature,
    this.setCcdTemperature,
    this.coolerPower,
    this.coolerOn,
  });

  @override
  int get hashCode =>
      maxWidth.hashCode ^
      maxHeight.hashCode ^
      bitDepth.hashCode ^
      hasShutter.hashCode ^
      canSetCcdTemperature.hashCode ^
      canSetCooler.hashCode ^
      canGetCoolerPower.hashCode ^
      canBin.hashCode ^
      maxBinX.hashCode ^
      maxBinY.hashCode ^
      canAsymmetricBin.hashCode ^
      canSetGain.hashCode ^
      gainMin.hashCode ^
      gainMax.hashCode ^
      canSetOffset.hashCode ^
      offsetMin.hashCode ^
      offsetMax.hashCode ^
      canAbortExposure.hashCode ^
      canStopExposure.hashCode ^
      canSubframe.hashCode ^
      pixelSizeX.hashCode ^
      pixelSizeY.hashCode ^
      isColor.hashCode ^
      bayerPattern.hashCode ^
      sensorType.hashCode ^
      hasFastReadout.hashCode ^
      readoutModes.hashCode ^
      exposureMin.hashCode ^
      exposureMax.hashCode ^
      ccdTemperature.hashCode ^
      setCcdTemperature.hashCode ^
      coolerPower.hashCode ^
      coolerOn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CameraCapabilities &&
          runtimeType == other.runtimeType &&
          maxWidth == other.maxWidth &&
          maxHeight == other.maxHeight &&
          bitDepth == other.bitDepth &&
          hasShutter == other.hasShutter &&
          canSetCcdTemperature == other.canSetCcdTemperature &&
          canSetCooler == other.canSetCooler &&
          canGetCoolerPower == other.canGetCoolerPower &&
          canBin == other.canBin &&
          maxBinX == other.maxBinX &&
          maxBinY == other.maxBinY &&
          canAsymmetricBin == other.canAsymmetricBin &&
          canSetGain == other.canSetGain &&
          gainMin == other.gainMin &&
          gainMax == other.gainMax &&
          canSetOffset == other.canSetOffset &&
          offsetMin == other.offsetMin &&
          offsetMax == other.offsetMax &&
          canAbortExposure == other.canAbortExposure &&
          canStopExposure == other.canStopExposure &&
          canSubframe == other.canSubframe &&
          pixelSizeX == other.pixelSizeX &&
          pixelSizeY == other.pixelSizeY &&
          isColor == other.isColor &&
          bayerPattern == other.bayerPattern &&
          sensorType == other.sensorType &&
          hasFastReadout == other.hasFastReadout &&
          readoutModes == other.readoutModes &&
          exposureMin == other.exposureMin &&
          exposureMax == other.exposureMax &&
          ccdTemperature == other.ccdTemperature &&
          setCcdTemperature == other.setCcdTemperature &&
          coolerPower == other.coolerPower &&
          coolerOn == other.coolerOn;
}

/// Capabilities of a cover calibrator device
class CoverCalibratorCapabilities {
  /// Maximum brightness level (0 if no calibrator)
  final int maxBrightness;

  /// Whether the device has a cover
  final bool coverPresent;

  /// Whether the device has a calibrator light
  final bool calibratorPresent;

  /// Current cover state
  final CoverState? coverState;

  /// Current calibrator state
  final CalibratorState? calibratorState;

  /// Current brightness level
  final int? brightness;

  const CoverCalibratorCapabilities({
    required this.maxBrightness,
    required this.coverPresent,
    required this.calibratorPresent,
    this.coverState,
    this.calibratorState,
    this.brightness,
  });

  @override
  int get hashCode =>
      maxBrightness.hashCode ^
      coverPresent.hashCode ^
      calibratorPresent.hashCode ^
      coverState.hashCode ^
      calibratorState.hashCode ^
      brightness.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoverCalibratorCapabilities &&
          runtimeType == other.runtimeType &&
          maxBrightness == other.maxBrightness &&
          coverPresent == other.coverPresent &&
          calibratorPresent == other.calibratorPresent &&
          coverState == other.coverState &&
          calibratorState == other.calibratorState &&
          brightness == other.brightness;
}

@freezed
sealed class DeviceCapabilities with _$DeviceCapabilities {
  const DeviceCapabilities._();

  const factory DeviceCapabilities.mount(
    MountCapabilities field0,
  ) = DeviceCapabilities_Mount;
  const factory DeviceCapabilities.camera(
    CameraCapabilities field0,
  ) = DeviceCapabilities_Camera;
  const factory DeviceCapabilities.focuser(
    FocuserCapabilities field0,
  ) = DeviceCapabilities_Focuser;
  const factory DeviceCapabilities.filterWheel(
    FilterWheelCapabilities field0,
  ) = DeviceCapabilities_FilterWheel;
  const factory DeviceCapabilities.rotator(
    RotatorCapabilities field0,
  ) = DeviceCapabilities_Rotator;
  const factory DeviceCapabilities.dome(
    DomeCapabilities field0,
  ) = DeviceCapabilities_Dome;
  const factory DeviceCapabilities.coverCalibrator(
    CoverCalibratorCapabilities field0,
  ) = DeviceCapabilities_CoverCalibrator;
  const factory DeviceCapabilities.weather(
    WeatherCapabilities field0,
  ) = DeviceCapabilities_Weather;
  const factory DeviceCapabilities.safetyMonitor(
    SafetyMonitorCapabilities field0,
  ) = DeviceCapabilities_SafetyMonitor;
  const factory DeviceCapabilities.switch_(
    SwitchCapabilities field0,
  ) = DeviceCapabilities_Switch;
}

/// Capabilities of a dome device
class DomeCapabilities {
  /// Whether the dome can slew to a specific azimuth
  final bool canSetAzimuth;

  /// Whether the dome can be parked
  final bool canPark;

  /// Whether the dome can find home
  final bool canFindHome;

  /// Whether the dome has a controllable shutter
  final bool canSetShutter;

  /// Whether the dome can sync its position
  final bool canSyncAzimuth;

  /// Current azimuth in degrees (if known)
  final double? azimuth;

  /// Whether the dome is currently slewing
  final bool slewing;

  /// Whether the dome is at home
  final bool atHome;

  /// Whether the dome is at park
  final bool atPark;

  /// Current shutter status
  final ShutterStatus? shutterStatus;

  /// Whether slave mode is available
  final bool canSlave;

  /// Whether slave mode is currently enabled
  final bool slaved;

  /// Whether the dome can abort movement
  final bool canAbort;

  const DomeCapabilities({
    required this.canSetAzimuth,
    required this.canPark,
    required this.canFindHome,
    required this.canSetShutter,
    required this.canSyncAzimuth,
    this.azimuth,
    required this.slewing,
    required this.atHome,
    required this.atPark,
    this.shutterStatus,
    required this.canSlave,
    required this.slaved,
    required this.canAbort,
  });

  @override
  int get hashCode =>
      canSetAzimuth.hashCode ^
      canPark.hashCode ^
      canFindHome.hashCode ^
      canSetShutter.hashCode ^
      canSyncAzimuth.hashCode ^
      azimuth.hashCode ^
      slewing.hashCode ^
      atHome.hashCode ^
      atPark.hashCode ^
      shutterStatus.hashCode ^
      canSlave.hashCode ^
      slaved.hashCode ^
      canAbort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DomeCapabilities &&
          runtimeType == other.runtimeType &&
          canSetAzimuth == other.canSetAzimuth &&
          canPark == other.canPark &&
          canFindHome == other.canFindHome &&
          canSetShutter == other.canSetShutter &&
          canSyncAzimuth == other.canSyncAzimuth &&
          azimuth == other.azimuth &&
          slewing == other.slewing &&
          atHome == other.atHome &&
          atPark == other.atPark &&
          shutterStatus == other.shutterStatus &&
          canSlave == other.canSlave &&
          slaved == other.slaved &&
          canAbort == other.canAbort;
}

/// Capabilities of a filter wheel device
class FilterWheelCapabilities {
  /// Number of filter positions
  final int positionCount;

  /// Current filter position (0-indexed)
  final int? currentPosition;

  /// Filter names for each position
  final List<String> filterNames;

  /// Focus offsets for each filter (in focuser steps)
  final Int32List focusOffsets;

  /// Whether the wheel is currently moving
  final bool isMoving;

  /// Whether filter names can be set
  final bool canSetFilterNames;

  /// Whether focus offsets can be set
  final bool canSetFocusOffsets;

  const FilterWheelCapabilities({
    required this.positionCount,
    this.currentPosition,
    required this.filterNames,
    required this.focusOffsets,
    required this.isMoving,
    required this.canSetFilterNames,
    required this.canSetFocusOffsets,
  });

  @override
  int get hashCode =>
      positionCount.hashCode ^
      currentPosition.hashCode ^
      filterNames.hashCode ^
      focusOffsets.hashCode ^
      isMoving.hashCode ^
      canSetFilterNames.hashCode ^
      canSetFocusOffsets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FilterWheelCapabilities &&
          runtimeType == other.runtimeType &&
          positionCount == other.positionCount &&
          currentPosition == other.currentPosition &&
          filterNames == other.filterNames &&
          focusOffsets == other.focusOffsets &&
          isMoving == other.isMoving &&
          canSetFilterNames == other.canSetFilterNames &&
          canSetFocusOffsets == other.canSetFocusOffsets;
}

/// Capabilities of a focuser device
class FocuserCapabilities {
  /// Maximum position in steps
  final int maxPosition;

  /// Maximum step increment per move
  final int maxIncrement;

  /// Step size in microns (if known)
  final double? stepSize;

  /// Whether the focuser can move in absolute positions
  final bool absolute;

  /// Whether the focuser supports temperature compensation
  final bool tempCompAvailable;

  /// Whether temperature compensation is currently enabled
  final bool tempComp;

  /// Current temperature at focuser (if sensor available)
  final double? temperature;

  /// Whether the focuser is currently moving
  final bool isMoving;

  /// Current position in steps
  final int? position;

  /// Whether the focuser can halt movement
  final bool canHalt;

  /// Whether the focuser can reverse direction
  final bool canReverse;

  /// Current reverse setting
  final bool? reverse;

  const FocuserCapabilities({
    required this.maxPosition,
    required this.maxIncrement,
    this.stepSize,
    required this.absolute,
    required this.tempCompAvailable,
    required this.tempComp,
    this.temperature,
    required this.isMoving,
    this.position,
    required this.canHalt,
    required this.canReverse,
    this.reverse,
  });

  @override
  int get hashCode =>
      maxPosition.hashCode ^
      maxIncrement.hashCode ^
      stepSize.hashCode ^
      absolute.hashCode ^
      tempCompAvailable.hashCode ^
      tempComp.hashCode ^
      temperature.hashCode ^
      isMoving.hashCode ^
      position.hashCode ^
      canHalt.hashCode ^
      canReverse.hashCode ^
      reverse.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FocuserCapabilities &&
          runtimeType == other.runtimeType &&
          maxPosition == other.maxPosition &&
          maxIncrement == other.maxIncrement &&
          stepSize == other.stepSize &&
          absolute == other.absolute &&
          tempCompAvailable == other.tempCompAvailable &&
          tempComp == other.tempComp &&
          temperature == other.temperature &&
          isMoving == other.isMoving &&
          position == other.position &&
          canHalt == other.canHalt &&
          canReverse == other.canReverse &&
          reverse == other.reverse;
}

/// Capabilities of a mount/telescope device
class MountCapabilities {
  /// Whether the mount can perform slew operations
  final bool canSlew;

  /// Whether the mount supports async (non-blocking) slews
  final bool canSlewAsync;

  /// Whether the mount can sync its position to coordinates
  final bool canSync;

  /// Whether the mount can be parked
  final bool canPark;

  /// Whether the mount can be unparked
  final bool canUnpark;

  /// Whether the mount can set its park position
  final bool canSetPark;

  /// Whether the mount supports pulse guiding
  final bool canPulseGuide;

  /// Whether the mount can report side of pier
  final bool canGetSideOfPier;

  /// Whether the mount can set side of pier (for meridian flips)
  final bool canSetSideOfPier;

  /// Whether tracking can be enabled/disabled
  final bool canSetTracking;

  /// Whether the tracking rate can be changed
  final bool canSetTrackingRate;

  /// Supported tracking rates
  final List<TrackingRate> supportedTrackingRates;

  /// Whether the mount is an equatorial type (has RA/Dec)
  final bool isEquatorial;

  /// Whether the mount supports altitude/azimuth coordinates
  final bool supportsAltAz;

  /// Whether the mount can report its pointing state (normal/beyond pole)
  final bool canGetPointingState;

  /// Whether the mount has a home position
  final bool canFindHome;

  /// Whether the mount is currently tracking
  final bool? tracking;

  /// Current tracking rate if known
  final TrackingRate? trackingRate;

  /// Whether the mount can abort slews
  final bool canAbortSlew;

  /// Maximum slew rate in degrees/second, if known
  final double? maxSlewRate;

  /// Whether the mount supports move axis commands
  final bool canMoveAxis;

  /// Number of axes the mount supports (typically 2 for RA/Dec or Az/Alt)
  final int axisCount;

  const MountCapabilities({
    required this.canSlew,
    required this.canSlewAsync,
    required this.canSync,
    required this.canPark,
    required this.canUnpark,
    required this.canSetPark,
    required this.canPulseGuide,
    required this.canGetSideOfPier,
    required this.canSetSideOfPier,
    required this.canSetTracking,
    required this.canSetTrackingRate,
    required this.supportedTrackingRates,
    required this.isEquatorial,
    required this.supportsAltAz,
    required this.canGetPointingState,
    required this.canFindHome,
    this.tracking,
    this.trackingRate,
    required this.canAbortSlew,
    this.maxSlewRate,
    required this.canMoveAxis,
    required this.axisCount,
  });

  @override
  int get hashCode =>
      canSlew.hashCode ^
      canSlewAsync.hashCode ^
      canSync.hashCode ^
      canPark.hashCode ^
      canUnpark.hashCode ^
      canSetPark.hashCode ^
      canPulseGuide.hashCode ^
      canGetSideOfPier.hashCode ^
      canSetSideOfPier.hashCode ^
      canSetTracking.hashCode ^
      canSetTrackingRate.hashCode ^
      supportedTrackingRates.hashCode ^
      isEquatorial.hashCode ^
      supportsAltAz.hashCode ^
      canGetPointingState.hashCode ^
      canFindHome.hashCode ^
      tracking.hashCode ^
      trackingRate.hashCode ^
      canAbortSlew.hashCode ^
      maxSlewRate.hashCode ^
      canMoveAxis.hashCode ^
      axisCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MountCapabilities &&
          runtimeType == other.runtimeType &&
          canSlew == other.canSlew &&
          canSlewAsync == other.canSlewAsync &&
          canSync == other.canSync &&
          canPark == other.canPark &&
          canUnpark == other.canUnpark &&
          canSetPark == other.canSetPark &&
          canPulseGuide == other.canPulseGuide &&
          canGetSideOfPier == other.canGetSideOfPier &&
          canSetSideOfPier == other.canSetSideOfPier &&
          canSetTracking == other.canSetTracking &&
          canSetTrackingRate == other.canSetTrackingRate &&
          supportedTrackingRates == other.supportedTrackingRates &&
          isEquatorial == other.isEquatorial &&
          supportsAltAz == other.supportsAltAz &&
          canGetPointingState == other.canGetPointingState &&
          canFindHome == other.canFindHome &&
          tracking == other.tracking &&
          trackingRate == other.trackingRate &&
          canAbortSlew == other.canAbortSlew &&
          maxSlewRate == other.maxSlewRate &&
          canMoveAxis == other.canMoveAxis &&
          axisCount == other.axisCount;
}

/// Capabilities of a rotator device
class RotatorCapabilities {
  /// Whether the rotator can reverse direction
  final bool canReverse;

  /// Current reverse setting
  final bool reverse;

  /// Step size in degrees
  final double? stepSize;

  /// Whether the rotator is currently moving
  final bool isMoving;

  /// Current mechanical position in degrees
  final double? mechanicalPosition;

  /// Current position in degrees (may differ from mechanical due to sync)
  final double? position;

  /// Whether the rotator can move to absolute positions
  final bool canMoveAbsolute;

  /// Whether the rotator can halt movement
  final bool canHalt;

  /// Whether the rotator can sync to a position
  final bool canSync;

  const RotatorCapabilities({
    required this.canReverse,
    required this.reverse,
    this.stepSize,
    required this.isMoving,
    this.mechanicalPosition,
    this.position,
    required this.canMoveAbsolute,
    required this.canHalt,
    required this.canSync,
  });

  @override
  int get hashCode =>
      canReverse.hashCode ^
      reverse.hashCode ^
      stepSize.hashCode ^
      isMoving.hashCode ^
      mechanicalPosition.hashCode ^
      position.hashCode ^
      canMoveAbsolute.hashCode ^
      canHalt.hashCode ^
      canSync.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RotatorCapabilities &&
          runtimeType == other.runtimeType &&
          canReverse == other.canReverse &&
          reverse == other.reverse &&
          stepSize == other.stepSize &&
          isMoving == other.isMoving &&
          mechanicalPosition == other.mechanicalPosition &&
          position == other.position &&
          canMoveAbsolute == other.canMoveAbsolute &&
          canHalt == other.canHalt &&
          canSync == other.canSync;
}

/// Capabilities of a safety monitor device
class SafetyMonitorCapabilities {
  /// Current safe status
  final bool isSafe;

  /// Description of current safety state
  final String? safetyDescription;

  const SafetyMonitorCapabilities({
    required this.isSafe,
    this.safetyDescription,
  });

  @override
  int get hashCode => isSafe.hashCode ^ safetyDescription.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SafetyMonitorCapabilities &&
          runtimeType == other.runtimeType &&
          isSafe == other.isSafe &&
          safetyDescription == other.safetyDescription;
}

/// Dome shutter status
enum ShutterStatus {
  /// Shutter is fully open
  open,

  /// Shutter is fully closed
  closed,

  /// Shutter is currently opening
  opening,

  /// Shutter is currently closing
  closing,

  /// Shutter status is unknown or error state
  unknown,
  ;
}

/// Capabilities of a switch device
class SwitchCapabilities {
  /// Number of switches
  final int switchCount;

  /// Switch details
  final List<SwitchInfo> switches;

  const SwitchCapabilities({
    required this.switchCount,
    required this.switches,
  });

  @override
  int get hashCode => switchCount.hashCode ^ switches.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwitchCapabilities &&
          runtimeType == other.runtimeType &&
          switchCount == other.switchCount &&
          switches == other.switches;
}

/// Information about a single switch
class SwitchInfo {
  /// Switch index
  final int index;

  /// Switch name
  final String name;

  /// Switch description
  final String description;

  /// Whether this is a boolean switch (vs. analog)
  final bool isBoolean;

  /// Minimum value (for analog switches)
  final double minValue;

  /// Maximum value (for analog switches)
  final double maxValue;

  /// Step increment (for analog switches)
  final double step;

  /// Whether the switch can be written
  final bool canWrite;

  /// Current value
  final double value;

  const SwitchInfo({
    required this.index,
    required this.name,
    required this.description,
    required this.isBoolean,
    required this.minValue,
    required this.maxValue,
    required this.step,
    required this.canWrite,
    required this.value,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      name.hashCode ^
      description.hashCode ^
      isBoolean.hashCode ^
      minValue.hashCode ^
      maxValue.hashCode ^
      step.hashCode ^
      canWrite.hashCode ^
      value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwitchInfo &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          name == other.name &&
          description == other.description &&
          isBoolean == other.isBoolean &&
          minValue == other.minValue &&
          maxValue == other.maxValue &&
          step == other.step &&
          canWrite == other.canWrite &&
          value == other.value;
}

/// Capabilities of a weather/observing conditions device
class WeatherCapabilities {
  /// Whether cloud cover is reported
  final bool hasCloudCover;

  /// Whether dew point is reported
  final bool hasDewPoint;

  /// Whether humidity is reported
  final bool hasHumidity;

  /// Whether pressure is reported
  final bool hasPressure;

  /// Whether rain rate is reported
  final bool hasRainRate;

  /// Whether sky brightness is reported
  final bool hasSkyBrightness;

  /// Whether sky quality (mag/arcsec^2) is reported
  final bool hasSkyQuality;

  /// Whether sky temperature is reported
  final bool hasSkyTemperature;

  /// Whether seeing is reported
  final bool hasSeeing;

  /// Whether temperature is reported
  final bool hasTemperature;

  /// Whether wind direction is reported
  final bool hasWindDirection;

  /// Whether wind gust is reported
  final bool hasWindGust;

  /// Whether wind speed is reported
  final bool hasWindSpeed;

  /// Average time between sensor updates in seconds
  final double? averagePeriod;

  const WeatherCapabilities({
    required this.hasCloudCover,
    required this.hasDewPoint,
    required this.hasHumidity,
    required this.hasPressure,
    required this.hasRainRate,
    required this.hasSkyBrightness,
    required this.hasSkyQuality,
    required this.hasSkyTemperature,
    required this.hasSeeing,
    required this.hasTemperature,
    required this.hasWindDirection,
    required this.hasWindGust,
    required this.hasWindSpeed,
    this.averagePeriod,
  });

  @override
  int get hashCode =>
      hasCloudCover.hashCode ^
      hasDewPoint.hashCode ^
      hasHumidity.hashCode ^
      hasPressure.hashCode ^
      hasRainRate.hashCode ^
      hasSkyBrightness.hashCode ^
      hasSkyQuality.hashCode ^
      hasSkyTemperature.hashCode ^
      hasSeeing.hashCode ^
      hasTemperature.hashCode ^
      hasWindDirection.hashCode ^
      hasWindGust.hashCode ^
      hasWindSpeed.hashCode ^
      averagePeriod.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeatherCapabilities &&
          runtimeType == other.runtimeType &&
          hasCloudCover == other.hasCloudCover &&
          hasDewPoint == other.hasDewPoint &&
          hasHumidity == other.hasHumidity &&
          hasPressure == other.hasPressure &&
          hasRainRate == other.hasRainRate &&
          hasSkyBrightness == other.hasSkyBrightness &&
          hasSkyQuality == other.hasSkyQuality &&
          hasSkyTemperature == other.hasSkyTemperature &&
          hasSeeing == other.hasSeeing &&
          hasTemperature == other.hasTemperature &&
          hasWindDirection == other.hasWindDirection &&
          hasWindGust == other.hasWindGust &&
          hasWindSpeed == other.hasWindSpeed &&
          averagePeriod == other.averagePeriod;
}
