// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'device.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'event.freezed.dart';

@freezed
sealed class EquipmentEvent with _$EquipmentEvent {
  const EquipmentEvent._();

  const factory EquipmentEvent.connecting({
    required String deviceType,
    required String deviceId,
  }) = EquipmentEvent_Connecting;
  const factory EquipmentEvent.connected({
    required String deviceType,
    required String deviceId,
  }) = EquipmentEvent_Connected;
  const factory EquipmentEvent.disconnected({
    required String deviceType,
    required String deviceId,
  }) = EquipmentEvent_Disconnected;
  const factory EquipmentEvent.propertyChanged({
    required String deviceType,
    required String deviceId,
    required String property,
    required String value,
  }) = EquipmentEvent_PropertyChanged;
  const factory EquipmentEvent.error({
    required String deviceType,
    required String deviceId,
    required String message,
  }) = EquipmentEvent_Error;
  const factory EquipmentEvent.mountSlewStarted({
    required double ra,
    required double dec,
  }) = EquipmentEvent_MountSlewStarted;
  const factory EquipmentEvent.mountSlewCompleted({
    required double ra,
    required double dec,
  }) = EquipmentEvent_MountSlewCompleted;
  const factory EquipmentEvent.mountTrackingStarted() =
      EquipmentEvent_MountTrackingStarted;
  const factory EquipmentEvent.mountTrackingStopped() =
      EquipmentEvent_MountTrackingStopped;
  const factory EquipmentEvent.mountParkStarted() =
      EquipmentEvent_MountParkStarted;
  const factory EquipmentEvent.mountParkCompleted() =
      EquipmentEvent_MountParkCompleted;
  const factory EquipmentEvent.mountUnparked() = EquipmentEvent_MountUnparked;
  const factory EquipmentEvent.focuserMoveStarted({
    required int targetPosition,
  }) = EquipmentEvent_FocuserMoveStarted;
  const factory EquipmentEvent.focuserMoveCompleted({required int position}) =
      EquipmentEvent_FocuserMoveCompleted;
  const factory EquipmentEvent.focuserTemperatureChanged({
    required double temperature,
  }) = EquipmentEvent_FocuserTemperatureChanged;
  const factory EquipmentEvent.filterChanging({
    required int fromPosition,
    required int toPosition,
    String? filterName,
  }) = EquipmentEvent_FilterChanging;
  const factory EquipmentEvent.filterChanged({
    required int position,
    String? filterName,
  }) = EquipmentEvent_FilterChanged;
  const factory EquipmentEvent.rotatorMoveStarted({
    required double targetAngle,
  }) = EquipmentEvent_RotatorMoveStarted;
  const factory EquipmentEvent.rotatorMoveCompleted({required double angle}) =
      EquipmentEvent_RotatorMoveCompleted;
  const factory EquipmentEvent.cameraCoolingStarted({
    required double targetTemp,
  }) = EquipmentEvent_CameraCoolingStarted;
  const factory EquipmentEvent.cameraCoolingReached({
    required double temperature,
  }) = EquipmentEvent_CameraCoolingReached;
  const factory EquipmentEvent.cameraWarmingStarted() =
      EquipmentEvent_CameraWarmingStarted;
  const factory EquipmentEvent.cameraWarmingCompleted() =
      EquipmentEvent_CameraWarmingCompleted;
  const factory EquipmentEvent.heartbeatStarted({
    required String deviceType,
    required String deviceId,
    required BigInt intervalSecs,
  }) = EquipmentEvent_HeartbeatStarted;
  const factory EquipmentEvent.heartbeatStopped({
    required String deviceType,
    required String deviceId,
  }) = EquipmentEvent_HeartbeatStopped;
  const factory EquipmentEvent.heartbeatStatusChanged({
    required String deviceType,
    required String deviceId,
    required HeartbeatStatus status,
    required int consecutiveFailures,
    BigInt? lastRttMs,
  }) = EquipmentEvent_HeartbeatStatusChanged;
  const factory EquipmentEvent.heartbeatReconnecting({
    required String deviceType,
    required String deviceId,
    required int attempt,
    required int maxAttempts,
  }) = EquipmentEvent_HeartbeatReconnecting;
  const factory EquipmentEvent.heartbeatReconnected({
    required String deviceType,
    required String deviceId,
    required int afterAttempts,
  }) = EquipmentEvent_HeartbeatReconnected;
  const factory EquipmentEvent.deviceDiscovered({
    /// Canonical device class (`camera`, `mount`, `focuser`, `filterWheel`,
    /// `rotator`, …).
    required String deviceClass,

    /// Driver backend (`native`, `ascom`, `alpaca`, `indi`, `simulator`).
    required String driver,

    /// Backend-scoped device id used to connect.
    required String id,

    /// Raw device name as reported by the SDK / driver.
    required String name,

    /// User-facing display name (may equal `name`).
    required String displayName,

    /// Stable hardware identity (USB serial, etc.) when the backend exposes
    /// one; `None` otherwise.
    String? uniqueId,
  }) = EquipmentEvent_DeviceDiscovered;
  const factory EquipmentEvent.deviceLost({
    required String deviceClass,
    required String driver,
    required String id,
  }) = EquipmentEvent_DeviceLost;
}

/// Categories of events
enum EventCategory {
  equipment,
  imaging,
  guiding,
  sequencer,
  safety,
  system,
  polarAlignment,
}

@freezed
sealed class EventPayload with _$EventPayload {
  const EventPayload._();

  const factory EventPayload.equipment(EquipmentEvent field0) =
      EventPayload_Equipment;
  const factory EventPayload.imaging(ImagingEvent field0) =
      EventPayload_Imaging;
  const factory EventPayload.guiding(GuidingEvent field0) =
      EventPayload_Guiding;
  const factory EventPayload.sequencer(SequencerEvent field0) =
      EventPayload_Sequencer;
  const factory EventPayload.safety(SafetyEvent field0) = EventPayload_Safety;
  const factory EventPayload.system(SystemEvent field0) = EventPayload_System;
  const factory EventPayload.polarAlignment(PolarAlignmentEvent field0) =
      EventPayload_PolarAlignment;
  const factory EventPayload.polarAlignmentStatus(PolarAlignmentStatus field0) =
      EventPayload_PolarAlignmentStatus;
  const factory EventPayload.polarAlignmentImage(
    PolarAlignmentImageEvent field0,
  ) = EventPayload_PolarAlignmentImage;
}

/// Event severity levels
enum EventSeverity { info, warning, error, critical }

/// Per-frame capture truth carried across FRB on the frame events. Mirrors
/// `nightshade_sequencer::scheduling::FrameCaptureMetadata` field for field,
/// living in the bridge crate for the same reason [`SchedulerScoreEntry`] does.
///
/// Every one of these values is already in the FITS header the sequencer wrote
/// for the same exposure. Shipping them on the event is what lets Dart write
/// the `captured_images` row from the header's own source instead of
/// reconstructing a second, thinner version of the frame from the sequence
/// tree — the reconstruction that left rows with NULL gain, offset, sensor
/// temperature, pointing, focuser position and rotator angle.
class FrameCaptureMetadata {
  final int? gain;
  final int? offset;
  final double? sensorTempC;
  final double? coolerPowerPercent;

  /// Mount right ascension in HOURS, matching `captured_images.mount_ra`.
  /// The FITS `RA` card is degrees; do not copy this into a degrees-valued
  /// field without multiplying by 15.
  final double? mountRaHours;
  final double? mountDecDegrees;
  final double? mountAltitudeDeg;
  final double? mountAzimuthDeg;

  /// `"East"` / `"West"`, or `None` when no mount answered.
  final String? pierSide;
  final int? focuserPosition;
  final double? focuserTemperatureC;
  final double? rotatorAngleDeg;
  final double exposureSecs;
  final int binX;
  final int binY;

  /// "Light" / "Dark" / "Flat" / "Bias" — the FITS `IMAGETYP` string.
  final String frameType;
  final String? targetId;

  const FrameCaptureMetadata({
    this.gain,
    this.offset,
    this.sensorTempC,
    this.coolerPowerPercent,
    this.mountRaHours,
    this.mountDecDegrees,
    this.mountAltitudeDeg,
    this.mountAzimuthDeg,
    this.pierSide,
    this.focuserPosition,
    this.focuserTemperatureC,
    this.rotatorAngleDeg,
    required this.exposureSecs,
    required this.binX,
    required this.binY,
    required this.frameType,
    this.targetId,
  });

  @override
  int get hashCode =>
      gain.hashCode ^
      offset.hashCode ^
      sensorTempC.hashCode ^
      coolerPowerPercent.hashCode ^
      mountRaHours.hashCode ^
      mountDecDegrees.hashCode ^
      mountAltitudeDeg.hashCode ^
      mountAzimuthDeg.hashCode ^
      pierSide.hashCode ^
      focuserPosition.hashCode ^
      focuserTemperatureC.hashCode ^
      rotatorAngleDeg.hashCode ^
      exposureSecs.hashCode ^
      binX.hashCode ^
      binY.hashCode ^
      frameType.hashCode ^
      targetId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrameCaptureMetadata &&
          runtimeType == other.runtimeType &&
          gain == other.gain &&
          offset == other.offset &&
          sensorTempC == other.sensorTempC &&
          coolerPowerPercent == other.coolerPowerPercent &&
          mountRaHours == other.mountRaHours &&
          mountDecDegrees == other.mountDecDegrees &&
          mountAltitudeDeg == other.mountAltitudeDeg &&
          mountAzimuthDeg == other.mountAzimuthDeg &&
          pierSide == other.pierSide &&
          focuserPosition == other.focuserPosition &&
          focuserTemperatureC == other.focuserTemperatureC &&
          rotatorAngleDeg == other.rotatorAngleDeg &&
          exposureSecs == other.exposureSecs &&
          binX == other.binX &&
          binY == other.binY &&
          frameType == other.frameType &&
          targetId == other.targetId;
}

@freezed
sealed class GuidingEvent with _$GuidingEvent {
  const GuidingEvent._();

  const factory GuidingEvent.connected() = GuidingEvent_Connected;
  const factory GuidingEvent.disconnected() = GuidingEvent_Disconnected;
  const factory GuidingEvent.guidingStarted() = GuidingEvent_GuidingStarted;
  const factory GuidingEvent.guidingStopped() = GuidingEvent_GuidingStopped;
  const factory GuidingEvent.paused() = GuidingEvent_Paused;
  const factory GuidingEvent.resumed() = GuidingEvent_Resumed;
  const factory GuidingEvent.settled({required double rms}) =
      GuidingEvent_Settled;
  const factory GuidingEvent.lostStar() = GuidingEvent_LostStar;
  const factory GuidingEvent.ditherStarted({required double pixels}) =
      GuidingEvent_DitherStarted;
  const factory GuidingEvent.ditherCompleted() = GuidingEvent_DitherCompleted;
  const factory GuidingEvent.correction({
    required double ra,
    required double dec,
    required double raRaw,
    required double decRaw,
  }) = GuidingEvent_Correction;

  /// Looping exposures without guiding
  const factory GuidingEvent.looping() = GuidingEvent_Looping;

  /// Settling after dither or guide start
  const factory GuidingEvent.settling() = GuidingEvent_Settling;

  /// Calibration in progress
  const factory GuidingEvent.calibrating() = GuidingEvent_Calibrating;

  /// Calibration completed successfully
  const factory GuidingEvent.calibrationComplete() =
      GuidingEvent_CalibrationComplete;

  /// Guide star selected at position
  const factory GuidingEvent.starSelected({
    required double x,
    required double y,
  }) = GuidingEvent_StarSelected;

  /// PHD2 app state change (for states not covered by other events)
  const factory GuidingEvent.appState({required String state}) =
      GuidingEvent_AppState;

  /// SNR and star mass update from guide step
  const factory GuidingEvent.guideStats({
    required double snr,
    required double starMass,
  }) = GuidingEvent_GuideStats;
}

/// Heartbeat status for device health monitoring
enum HeartbeatStatus {
  /// Device is responding normally
  healthy,

  /// Device has failed some health checks but not yet marked disconnected
  degraded,

  /// Device is not responding and marked as disconnected
  disconnected,

  /// Attempting to reconnect to the device
  reconnecting,

  /// Successfully reconnected after failures
  reconnected,
}

@freezed
sealed class ImagingEvent with _$ImagingEvent {
  const ImagingEvent._();

  const factory ImagingEvent.exposureStarted({
    required double durationSecs,
    required FrameType frameType,
  }) = ImagingEvent_ExposureStarted;
  const factory ImagingEvent.exposureStartedWithFrame({
    required double durationSecs,
    required FrameType frameType,
    required int frameNumber,
    int? totalFrames,
  }) = ImagingEvent_ExposureStartedWithFrame;
  const factory ImagingEvent.exposureProgress({
    required double progress,
    required double remainingSecs,
  }) = ImagingEvent_ExposureProgress;
  const factory ImagingEvent.exposureCompleted({
    String? filePath,
    required double hfr,
    required int starsDetected,
  }) = ImagingEvent_ExposureCompleted;
  const factory ImagingEvent.exposureCompletedWithFrame({
    required int frameNumber,
    int? totalFrames,
    required double hfr,
    required int starsDetected,
  }) = ImagingEvent_ExposureCompletedWithFrame;
  const factory ImagingEvent.exposureFailed({required String error}) =
      ImagingEvent_ExposureFailed;
  const factory ImagingEvent.exposureCancelled() =
      ImagingEvent_ExposureCancelled;
  const factory ImagingEvent.downloadStarted() = ImagingEvent_DownloadStarted;
  const factory ImagingEvent.downloadCompleted() =
      ImagingEvent_DownloadCompleted;
  const factory ImagingEvent.imageReady({
    required int width,
    required int height,
  }) = ImagingEvent_ImageReady;
  const factory ImagingEvent.imageSaved({required String filePath}) =
      ImagingEvent_ImageSaved;

  /// Progress update from the offline batch-integration pipeline
  /// ([`crate::api::post_session::api_integrate_session`]). Emitted at every
  /// phase boundary and, during the per-frame register loop, per frame —
  /// never per pixel. The UI filters these by `category == Imaging` +
  /// `eventType == "IntegrationProgress"` and drives a progress bar from
  /// `fraction`.
  const factory ImagingEvent.integrationProgress({
    /// Current pipeline phase: one of `"calibrating"`, `"registering"`,
    /// `"normalizing"`, `"weighting"`, `"integrating"`, `"writing"`, or
    /// `"preview"`.
    required String phase,

    /// Overall completion fraction in `0.0..=1.0`, monotonically advancing
    /// across the phase sequence above.
    required double fraction,

    /// Frames processed so far in the current phase (`None` when the phase
    /// has no per-frame granularity, e.g. `integrating`/`writing`).
    int? framesDone,

    /// Total frames in the current phase (`None` when N/A).
    int? framesTotal,
  }) = ImagingEvent_IntegrationProgress;
  const factory ImagingEvent.temperatureChanged({
    required double tempCelsius,
    required double coolerPower,
  }) = ImagingEvent_TemperatureChanged;
  const factory ImagingEvent.exposureComplete({required bool success}) =
      ImagingEvent_ExposureComplete;
  const factory ImagingEvent.exposureFailedOld({required String reason}) =
      ImagingEvent_ExposureFailedOld;
}

/// A unified event that can be any category
class NightshadeEvent {
  /// Unique event ID (monotonically increasing sequence number)
  final BigInt eventId;

  /// Timestamp when the event was created (milliseconds since Unix epoch)
  final PlatformInt64 timestamp;

  /// Severity level of the event
  final EventSeverity severity;

  /// Category of the event
  final EventCategory category;

  /// The actual event data
  final EventPayload payload;

  /// Event ID that caused this event (for causality tracking)
  /// None if this is a root event (no causal parent)
  final BigInt? causedBy;

  /// Correlation ID for grouping related events (e.g., all events from one exposure)
  final String? correlationId;

  /// Device ID if this event is device-related
  final String? deviceId;

  const NightshadeEvent({
    required this.eventId,
    required this.timestamp,
    required this.severity,
    required this.category,
    required this.payload,
    this.causedBy,
    this.correlationId,
    this.deviceId,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      timestamp.hashCode ^
      severity.hashCode ^
      category.hashCode ^
      payload.hashCode ^
      causedBy.hashCode ^
      correlationId.hashCode ^
      deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NightshadeEvent &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          timestamp == other.timestamp &&
          severity == other.severity &&
          category == other.category &&
          payload == other.payload &&
          causedBy == other.causedBy &&
          correlationId == other.correlationId &&
          deviceId == other.deviceId;
}

/// Polar alignment error data
class PolarAlignmentEvent {
  final double azimuthError;
  final double altitudeError;
  final double totalError;
  final double currentRa;
  final double currentDec;
  final double targetRa;
  final double targetDec;

  const PolarAlignmentEvent({
    required this.azimuthError,
    required this.altitudeError,
    required this.totalError,
    required this.currentRa,
    required this.currentDec,
    required this.targetRa,
    required this.targetDec,
  });

  @override
  int get hashCode =>
      azimuthError.hashCode ^
      altitudeError.hashCode ^
      totalError.hashCode ^
      currentRa.hashCode ^
      currentDec.hashCode ^
      targetRa.hashCode ^
      targetDec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PolarAlignmentEvent &&
          runtimeType == other.runtimeType &&
          azimuthError == other.azimuthError &&
          altitudeError == other.altitudeError &&
          totalError == other.totalError &&
          currentRa == other.currentRa &&
          currentDec == other.currentDec &&
          targetRa == other.targetRa &&
          targetDec == other.targetDec;
}

/// Polar alignment image data for UI display
class PolarAlignmentImageEvent {
  /// JPEG-encoded image bytes for display
  final Uint8List imageData;

  /// Image width
  final int width;

  /// Image height
  final int height;

  /// Plate solve result (if available)
  final double? solvedRa;
  final double? solvedDec;

  /// Current measurement point (1-3) or 0 for adjustment phase
  final int point;

  /// Phase: "measuring" or "adjusting"
  final String phase;

  const PolarAlignmentImageEvent({
    required this.imageData,
    required this.width,
    required this.height,
    this.solvedRa,
    this.solvedDec,
    required this.point,
    required this.phase,
  });

  @override
  int get hashCode =>
      imageData.hashCode ^
      width.hashCode ^
      height.hashCode ^
      solvedRa.hashCode ^
      solvedDec.hashCode ^
      point.hashCode ^
      phase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PolarAlignmentImageEvent &&
          runtimeType == other.runtimeType &&
          imageData == other.imageData &&
          width == other.width &&
          height == other.height &&
          solvedRa == other.solvedRa &&
          solvedDec == other.solvedDec &&
          point == other.point &&
          phase == other.phase;
}

/// Polar alignment status update
class PolarAlignmentStatus {
  final String status;
  final String phase;
  final int point;

  const PolarAlignmentStatus({
    required this.status,
    required this.phase,
    required this.point,
  });

  @override
  int get hashCode => status.hashCode ^ phase.hashCode ^ point.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PolarAlignmentStatus &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          phase == other.phase &&
          point == other.point;
}

@freezed
sealed class SafetyEvent with _$SafetyEvent {
  const SafetyEvent._();

  const factory SafetyEvent.weatherUnsafe({required String reason}) =
      SafetyEvent_WeatherUnsafe;
  const factory SafetyEvent.weatherSafe() = SafetyEvent_WeatherSafe;
  const factory SafetyEvent.emergencyStop({required String reason}) =
      SafetyEvent_EmergencyStop;
  const factory SafetyEvent.parkInitiated({required String reason}) =
      SafetyEvent_ParkInitiated;
  const factory SafetyEvent.parkCompleted() = SafetyEvent_ParkCompleted;
}

/// flat scheduler score row exposed across FRB. Mirrors
/// `nightshade_sequencer::node::logic::target_scheduler::SchedulerScoreSummary`
/// but lives in the bridge crate so we don't have to expose the sequencer
/// type to FRB. The Dart side consumes this directly in the run-dashboard
/// scheduler panel.
class SchedulerScoreEntry {
  final String targetId;
  final String targetName;

  /// Total score (0..=100) the scheduler computed.
  final double totalScore;

  /// True when the target was eligible to run (cleared
  /// `min_score_to_run` and any altitude / window gates).
  final bool runnable;

  /// Human-readable reason, populated when `runnable == false`
  /// (e.g. "below altitude limit", "before start window").
  final String? reason;

  const SchedulerScoreEntry({
    required this.targetId,
    required this.targetName,
    required this.totalScore,
    required this.runnable,
    this.reason,
  });

  @override
  int get hashCode =>
      targetId.hashCode ^
      targetName.hashCode ^
      totalScore.hashCode ^
      runnable.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SchedulerScoreEntry &&
          runtimeType == other.runtimeType &&
          targetId == other.targetId &&
          targetName == other.targetName &&
          totalScore == other.totalScore &&
          runnable == other.runnable &&
          reason == other.reason;
}

@freezed
sealed class SequencerEvent with _$SequencerEvent {
  const SequencerEvent._();

  const factory SequencerEvent.started({required String sequenceName}) =
      SequencerEvent_Started;
  const factory SequencerEvent.paused() = SequencerEvent_Paused;
  const factory SequencerEvent.resumed() = SequencerEvent_Resumed;
  const factory SequencerEvent.stopped() = SequencerEvent_Stopped;
  const factory SequencerEvent.completed() = SequencerEvent_Completed;

  /// The run ended in FAILURE. Terminal, and the counterpart of
  /// [`SequencerEvent::Completed`] / [`SequencerEvent::Stopped`].
  ///
  /// `ExecutorEvent::SequenceFailed` used to be flattened onto
  /// `SequencerEvent::Error`, which the Dart executor handles as a
  /// *non-terminal* mid-run error. The consequence was that Dart's
  /// `case 'SequenceFailed'` branch — the one that drives
  /// `_onTerminalEvent` — was unreachable dead code, so a failed run NEVER
  /// finalized: `sequence_runs.status` stayed `'running'` with a null
  /// `ended_at`, the imaging session stayed active, and the next start was
  /// refused with `active_session_exists` until the operator manually reset
  /// the sequencer.
  const factory SequencerEvent.failed({required String error}) =
      SequencerEvent_Failed;
  const factory SequencerEvent.nodeStarted({
    required String nodeId,
    required String nodeType,
  }) = SequencerEvent_NodeStarted;
  const factory SequencerEvent.nodeCompleted({
    required String nodeId,

    /// Completion status: "success", "failed", "cancelled", or "skipped"
    required String status,
  }) = SequencerEvent_NodeCompleted;
  const factory SequencerEvent.progress({
    required int current,
    required int total,
  }) = SequencerEvent_Progress;
  const factory SequencerEvent.targetChanged({
    required String targetName,

    /// Right Ascension in hours (0-24), if available from the target header
    double? ra,

    /// Declination in degrees (-90 to +90), if available from the target header
    double? dec,
  }) = SequencerEvent_TargetChanged;
  const factory SequencerEvent.targetCompleted({required String targetName}) =
      SequencerEvent_TargetCompleted;
  const factory SequencerEvent.exposureStarted({
    required int frame,
    required int total,
    String? filter,
    required double durationSecs,
  }) = SequencerEvent_ExposureStarted;
  const factory SequencerEvent.exposureCompleted({
    required int frame,
    required int total,
    required double durationSecs,
  }) = SequencerEvent_ExposureCompleted;
  const factory SequencerEvent.error({required String message}) =
      SequencerEvent_Error;

  /// A meridian flip finished. Mirrors
  /// `ExecutorEvent::MeridianFlipOutcome`.
  ///
  /// The flip is the single most dangerous thing the app does unattended and
  /// it used to be entirely absent from the wire: the run vitals reported
  /// `meridianFlips: 0` after a flip that had physically swapped pier sides,
  /// and a flip whose post-flip plate-solve recenter FAILED left
  /// `errorMessages: []` on a run reported as `completed`. This variant is
  /// the typed verdict the Dart run-stats layer consumes — deliberately
  /// typed rather than string-sniffed off the log, matching the Pack-H
  /// migration away from regex-parsed `detail` strings.
  const factory SequencerEvent.meridianFlipOutcome({
    /// `"success"`, `"failed"`, or `"aborted"`.
    required String outcome,

    /// Target the flip was performed for.
    required String targetName,

    /// Pier side reported after the flip (`East` / `West` / `Unknown`).
    required String newPierSide,

    /// Wall-clock seconds for the whole flip, retries included.
    required double durationSecs,

    /// Attempts made; `> 1` means the flip was DEGRADED.
    required int attempts,

    /// One `"<step>: <error>"` per failed attempt, oldest first.
    required List<String> failedSteps,

    /// Terminal error. `None` on a clean success.
    String? error,

    /// Failure action executed (`"PauseAndAlert"` / `"AbortAndPark"`).
    String? actionTaken,
  }) = SequencerEvent_MeridianFlipOutcome;

  /// A trigger watchdog fired during sequence execution
  const factory SequencerEvent.triggerFired({
    /// Unique trigger identifier
    required String triggerId,

    /// Human-readable trigger name
    required String triggerName,

    /// Action taken (e.g., "Autofocus", "Dither", "PauseSequence")
    required String action,
  }) = SequencerEvent_TriggerFired;

  /// Progress update for long-running instructions (cooling, autofocus, slewing)
  const factory SequencerEvent.instructionProgress({
    /// Node ID for mapping progress to the correct tree node
    required String nodeId,

    /// Name of the instruction (e.g., "Cool Camera", "Autofocus")
    required String instruction,

    /// Progress percentage (0.0 to 100.0)
    required double progressPercent,

    /// Detailed status message
    required String detail,
  }) = SequencerEvent_InstructionProgress;

  /// Structured progress update for long-running instructions. This is
  /// emitted alongside `InstructionProgress` so legacy consumers keep their
  /// string detail while newer UI panels can bind to explicit fields.
  const factory SequencerEvent.instructionProgressStructured({
    /// Node ID for mapping progress to the correct tree node
    required String nodeId,

    /// Name of the instruction (e.g., "Cool Camera", "Autofocus")
    required String instruction,

    /// Progress percentage (0.0 to 100.0)
    required double progressPercent,

    /// `ProgressDetail` variant name (e.g. `Exposure`, `Autofocus`)
    required String detailKind,

    /// JSON-stringified inner payload for the variant.
    required String detailJson,
  }) = SequencerEvent_InstructionProgressStructured;

  /// Image Grading: a frame passed every configured
  /// quality threshold and was saved to the normal output folder.
  /// Mirrors `ProgressDetail::FrameAccepted`.
  const factory SequencerEvent.frameAccepted({
    required String nodeId,

    /// 1-based frame index within the current TakeExposure burst.
    required int frame,
    required int total,
    double? hfr,
    double? eccentricity,
    int? starCount,

    /// Running count of accepted frames for the whole run.
    required int acceptedTotal,

    /// Running count of rejected frames for the whole run.
    required int rejectedTotal,

    /// on-disk save path of the accepted frame, so
    /// the thumbnail strip can render an inline preview of
    /// accepted frames the same way it already does for rejected
    /// frames via `FrameRejected.reject_path`. `None` for legacy /
    /// non-grading emit sites that did not thread the path through.
    String? savePath,

    /// Per-frame capture truth, taken from the `FrameContext` the FITS
    /// writer stamped this frame's header from. Dart persists it straight
    /// into `captured_images`, which is why the row and the file agree:
    /// both are written from one struct rather than two independent
    /// reconstructions of the same exposure.
    required FrameCaptureMetadata capture,
  }) = SequencerEvent_FrameAccepted;

  /// Image Grading: a frame failed at least one
  /// quality threshold and was routed to the reject folder. Mirrors
  /// `ProgressDetail::FrameRejected`. The consecutive-reject pause
  /// behaviour is unchanged; this event surfaces the metrics so the
  /// dashboard can render them without parsing.
  const factory SequencerEvent.frameRejected({
    required String nodeId,
    required int frame,
    required int total,
    required String reason,
    double? hfr,
    double? eccentricity,
    int? starCount,
    required String rejectPath,

    /// Running consecutive-rejects counter. When this reaches the
    /// configured `max_consecutive_rejects`, the executor pauses
    /// the sequence and emits an additional `Error` event.
    required int consecutiveRejects,
    required int acceptedTotal,
    required int rejectedTotal,

    /// Classified cause label (wire-stable snake_case string from
    /// `LikelyCause::label()`). `None` when the classifier was not
    /// consulted or could not pick a single best guess. Dart maps
    /// this back to its `LikelyCause` enum via
    /// `LikelyCauseExt.fromLabel`.
    String? likelyCauseLabel,

    /// Human-readable evidence bullets the dashboard surfaces in
    /// the Forensics panel and Frame Detail dialog. Empty list
    /// when no telemetry was available.
    required List<String> evidence,

    /// Sky brightness reading at capture time (mag/arcsec²).
    double? skyBrightnessAtCapture,

    /// Cloud cover percentage (0-100) at capture time.
    double? cloudCoverAtCapture,

    /// Wind speed at capture time (km/h). `None` when no weather
    /// feed is wired through to the sequencer.
    double? windAtCapture,

    /// Guide RMS (arc-seconds) sampled at capture time.
    double? guideRmsAtCapture,

    /// Sensor temperature (°C) at capture time.
    double? sensorTempAtCapture,

    /// Per-frame capture truth — see [`SequencerEvent::FrameAccepted`].
    /// A rejected frame is still on disk and still gets a row, so it is
    /// stamped from the same struct.
    required FrameCaptureMetadata capture,
  }) = SequencerEvent_FrameRejected;

  /// TargetScheduler decision. Mirrors
  /// `ProgressDetail::Scheduler`. The score table is exposed as a
  /// flat `Vec<SchedulerScoreEntry>` so FRB doesn't have to bridge
  /// the internal `SchedulerScoreSummary` type.
  const factory SequencerEvent.schedulerDecision({
    required String nodeId,

    /// 1-based decision counter for this scheduler instance.
    required int decisionCounter,

    /// `None` when no target cleared `min_score_to_run`.
    String? pickedTargetId,
    String? pickedTargetName,

    /// Picked target's total score (0..=100). `None` when nothing
    /// was picked.
    double? pickedScore,

    /// Flat score table (runnable first, then by descending total).
    required List<SchedulerScoreEntry> scores,
  }) = SequencerEvent_SchedulerDecision;

  /// per-target integration budget tick.
  /// Mirrors `ProgressDetail::IntegrationBudget`.
  const factory SequencerEvent.integrationBudget({
    /// The TargetHeader node id this budget belongs to.
    required String targetId,

    /// Filter the credit was applied to (`""` for no-filter cameras).
    required String filter,
    required double completedSecs,
    required double budgetSecs,
    required double fraction,
    required bool budgetMet,
  }) = SequencerEvent_IntegrationBudget;

  /// sky-brightness adaptive exposure decision.
  /// Mirrors `ProgressDetail::ExposureAdjusted`. Emitted before every
  /// exposure burst whenever the adapter was consulted (regardless of
  /// whether the duration actually changed), so the Run Dashboard can
  /// surface live sky brightness + the most recent nominal/adapted
  /// pair and the user understands why the camera is running longer
  /// (or shorter) than configured.
  const factory SequencerEvent.exposureAdjusted({
    required String nodeId,

    /// Adapted (effective) exposure duration in seconds.
    required double adaptedSecs,

    /// User-configured nominal duration in seconds.
    required double nominalSecs,

    /// Live sky brightness used in the decision (mag/arcsec²). `None`
    /// when the adapter fell back due to missing telemetry.
    double? skyBrightnessMag,

    /// Filter being captured through. `None` for monochrome / no
    /// filter wheel rigs.
    String? filter,

    /// Lowercase tag: `adapted`, `clamped_min`, `clamped_max`,
    /// `unavailable`, `disabled`, `out_of_nominal_bounds`.
    required String reason,
  }) = SequencerEvent_ExposureAdjusted;

  /// Science: per-frame photometry payload from the
  /// `SciencePhotometryInstruction`. Mirrors
  /// `ProgressDetail::PhotometryFrame`. The Dart science pipeline writes a row
  /// to `photometry_measurements` and updates the live light-curve chart on
  /// the Run Dashboard.
  const factory SequencerEvent.photometryFrame({
    /// Node ID for mapping progress to the correct tree node.
    required String nodeId,

    /// Resolved target designation (e.g. `"V* DY Peg"`).
    required String targetDesignation,

    /// Reference / comparison star designations used for differential
    /// photometry. Empty when differential photometry is disabled.
    required List<String> referenceStars,

    /// 1-based frame index within the current photometry burst.
    required int frame,
    required int total,
    required String filter,
    required double exposureSecs,

    /// Airmass at exposure midpoint. `None` when no WCS / pointing was
    /// available to compute it.
    double? airmass,

    /// Measured stellar FWHM (arc-seconds). `None` when the frame yielded
    /// no usable star measurement.
    double? fwhmArcsec,

    /// Signal-to-noise ratio of the target aperture. `None` when not
    /// measured.
    double? snr,

    /// Modified Julian Date at exposure midpoint (FITS `MJD-OBS`).
    required double mjdObs,

    /// Unix epoch seconds at exposure start.
    required double frameStartUnix,

    /// True when the frame passed every quality gate
    /// (`PhotometryFrameVerdict::Pass`).
    required bool accepted,

    /// Rejection reason when `accepted == false`
    /// (`PhotometryFrameVerdict::Reject { reason }`); `None` when accepted.
    String? rejectReason,

    /// True when live reduction was performed for this frame.
    required bool reduceLive,

    /// True when differential photometry was applied for this frame.
    required bool applyDifferential,
  }) = SequencerEvent_PhotometryFrame;

  /// Science: cadence-violation event emitted whenever the inter-frame
  /// start-to-start gap exceeds the configured ceiling. Mirrors
  /// `ProgressDetail::PhotometryCadenceBroken`. Surfaced by the dashboard
  /// photometry panel; does NOT abort the burst.
  const factory SequencerEvent.photometryCadenceBroken({
    /// Node ID for mapping progress to the correct tree node.
    required String nodeId,

    /// 1-based frame index whose start broke the cadence.
    required int frame,
    required int total,

    /// Observed start-to-start gap (seconds).
    required double gapSecs,

    /// Configured maximum allowed gap (seconds).
    required double maxGapSecs,

    /// Cumulative cadence breaks for the current node run.
    required int cadenceBreaks,
  }) = SequencerEvent_PhotometryCadenceBroken;

  /// Science: end-of-burst summary for the photometry node. Mirrors
  /// `ProgressDetail::PhotometrySummary`.
  const factory SequencerEvent.photometrySummary({
    /// Node ID for mapping progress to the correct tree node.
    required String nodeId,
    required String targetDesignation,
    required String filter,

    /// Number of frames captured during the burst (accepted + rejected).
    required int framesCaptured,

    /// Total cadence breaks observed during the burst.
    required int cadenceBreaks,

    /// Last rejection reason seen during the burst; `None` when no frame
    /// was rejected.
    String? lastRejectReason,
  }) = SequencerEvent_PhotometrySummary;

  /// Recovery Mode: the executor just entered the `Recovering`
  /// state. Subscribers (dashboard banner, audible alert player,
  /// push-notification service) render the cause / attempt counter
  /// / countdown without reaching back into the executor.
  const factory SequencerEvent.recoveryStarted({
    required String startedAtIso,
    required String causeKind,
    String? causeCustomLabel,
    String? lastAttemptAtIso,
    required int attemptCount,
    required int maxAttempts,
    required double retryIntervalSecs,
    required double maxDurationSecs,
    required String phase,
    String? lastError,
  }) = SequencerEvent_RecoveryStarted;

  /// Recovery Mode: periodic update of the live recovery context
  /// (attempt counter incremented, phase changed, last_error updated).
  /// Subscribers refresh the dashboard banner from this; the
  /// `RecoveryStarted` / `RecoveryCompleted` / `RecoveryGaveUp` events
  /// bookend the loop while this carries deltas inside the loop.
  const factory SequencerEvent.recoveryProgress({
    required String startedAtIso,
    required String causeKind,
    String? causeCustomLabel,
    String? lastAttemptAtIso,
    required int attemptCount,
    required int maxAttempts,
    required double retryIntervalSecs,
    required double maxDurationSecs,
    required String phase,
    String? lastError,
  }) = SequencerEvent_RecoveryProgress;

  /// Recovery Mode: recovery succeeded. The executor will
  /// transition back to `Running`; subscribers clear the dashboard
  /// banner and append to the history list.
  const factory SequencerEvent.recoveryCompleted({
    required String startedAtIso,
    required String causeKind,
    String? causeCustomLabel,
    String? lastAttemptAtIso,
    required int attemptCount,
    required int maxAttempts,
    required double retryIntervalSecs,
    required double maxDurationSecs,
    required String phase,
    String? lastError,
  }) = SequencerEvent_RecoveryCompleted;

  /// Recovery Mode: recovery exhausted attempts / time / was
  /// aborted by the user. The executor will transition to `Failed` (or
  /// run the configured ParkAndAbort policy). Subscribers append the
  /// history entry and emit a critical-severity event.
  const factory SequencerEvent.recoveryGaveUp({
    required String startedAtIso,
    required String causeKind,
    String? causeCustomLabel,
    String? lastAttemptAtIso,
    required int attemptCount,
    required int maxAttempts,
    required double retryIntervalSecs,
    required double maxDurationSecs,
    required String phase,
    String? lastError,

    /// True when the loop exited because the user pressed Abort.
    /// Distinct from exhaustion so the UI can render different copy
    /// ("Aborted by operator" vs "Exhausted retries").
    required bool abortedByUser,
  }) = SequencerEvent_RecoveryGaveUp;

  /// the executor is waiting for the Dart side to
  /// dispatch a plugin node and reply with the verdict.
  const factory SequencerEvent.pluginNodeRequested({
    /// Executor-side node identifier. The reply MUST echo this.
    required String nodeId,

    /// Stable plugin identifier (e.g. `com.example.pushover`).
    required String pluginId,

    /// Stable per-plugin node type identifier (e.g. `pushover.notify`).
    required String nodeTypeId,

    /// Opaque JSON payload the plugin author authored on the Dart
    /// side. Rust forwards verbatim.
    required String configJson,

    /// Optional human-readable label. `None` => UI uses
    /// `node_type_id`.
    String? displayName,

    /// Effective timeout (seconds) the Rust side will wait. Dart
    /// MUST honour this; a longer run on the Dart side will be
    /// timed out by Rust first and surfaced as a failure.
    required int timeoutSecs,
  }) = SequencerEvent_PluginNodeRequested;

  /// live plugin-node progress payload. Mirrors
  /// `ProgressDetail::PluginNode`. The JSON detail is serialised as a
  /// string at the bridge boundary because FRB does not transport
  /// `serde_json::Value` directly; Dart parses it with
  /// `jsonDecode(detail_json)`.
  const factory SequencerEvent.pluginNodeProgress({
    required String nodeId,
    required String pluginId,
    required String nodeTypeId,

    /// Stringified plugin-authored payload. Empty string when the
    /// plugin emitted no payload.
    required String detailJson,
  }) = SequencerEvent_PluginNodeProgress;

  /// Replay Debug — a structured decision emitted by the
  /// sequencer (scheduler pick, trigger fire, recovery transition,
  /// frame verdict, adaptive swap, plugin invocation, manual operator
  /// action, or system event). Subscribers persist these to the
  /// `sequence_decisions` Drift table and the Replay screen scrubs
  /// chronologically through them.
  ///
  /// `details_json` is the JSON-stringified payload — FRB does not
  /// bridge `serde_json::Value` directly, so the Dart side does
  /// `jsonDecode(details_json)` to recover the structured map.
  ///
  /// `category` is the stable wire key (`scheduler_pick`,
  /// `trigger_fired`, etc.) — see
  /// `nightshade_sequencer::DecisionCategory::wire_key`.
  const factory SequencerEvent.decisionLogged({
    /// ISO-8601 UTC timestamp when the decision was made.
    required String timestampIso,

    /// Stable wire key for the underlying DecisionCategory variant.
    required String category,

    /// One-line human-readable summary.
    required String summary,

    /// JSON-stringified opaque details payload.
    required String detailsJson,

    /// Optional associated node id (scheduler / target / exposure
    /// node).
    String? nodeId,

    /// `sequence_runs.id` this decision belongs to, if the executor
    /// has been stamped with one.
    PlatformInt64? sequenceRunId,
  }) = SequencerEvent_DecisionLogged;
}

@freezed
sealed class SystemEvent with _$SystemEvent {
  const SystemEvent._();

  const factory SystemEvent.initialized() = SystemEvent_Initialized;
  const factory SystemEvent.shuttingDown() = SystemEvent_ShuttingDown;
  const factory SystemEvent.error({required String message}) =
      SystemEvent_Error;
  const factory SystemEvent.diskSpaceLow({required double availableGb}) =
      SystemEvent_DiskSpaceLow;
  const factory SystemEvent.notification({
    required String title,
    required String message,
    required String level,

    /// per-NotificationNode override list of
    /// NotificationTransportKind names (Dart enum, serialised as strings).
    /// The Dart NotificationRouter consumes this field to bypass the
    /// matrix's `custom` rule and dispatch to the user-picked transports
    /// directly. `None` or empty = use matrix routing.
    List<String>? explicitTransports,
  }) = SystemEvent_Notification;

  /// Notification that events were dropped due to slow consumer
  /// This is sent after the stream recovers to inform the Dart side
  const factory SystemEvent.eventsDropped({
    /// Number of events that were dropped/skipped
    required BigInt droppedCount,

    /// Total number of events dropped since app start
    required BigInt totalDropped,
  }) = SystemEvent_EventsDropped;
}
