// Typed display helpers for [NightshadeEvent].
//
// `event.dart` is auto-generated by flutter_rust_bridge and we cannot
// extend it in place. Instead, this file provides exhaustive
// `switch (event.payload)` mappings on the freezed union variants and
// returns short title + detail strings the UI can render directly.
//
// Why we need this:
//   * The Run Dashboard's "Recent events" feed previously used
//     `RegExp(r'[,)]')` on the freezed `toString()` output to scrape a
//     `message:` field. Any payload field containing a comma broke the
//     scrape and the user saw garbage in the feed.
//   * The new helpers read actual fields off each variant, so adding a
//     new event variant is an exhaustive-switch compiler error rather
//     than a silent runtime regression.
//
// Both helpers are intentionally pure and side-effect free; they take a
// const `NightshadeEvent` and return strings.

import 'event.dart';

/// Returns a short headline-style title for the event suitable for the
/// trigger feed row. Examples:
///   * `EquipmentEvent_Connected(deviceType: ZWO, ...)` → `"Connected"`
///   * `ImagingEvent_ExposureFailed(error: ...)` → `"Exposure failed"`
///
/// The title is constant-length and stable across runs — it never depends
/// on field values, only on the variant.
String nightshadeEventDisplayTitle(NightshadeEvent event) {
  final payload = event.payload;
  switch (payload) {
    case EventPayload_Equipment(field0: final v):
      return _equipmentTitle(v);
    case EventPayload_Imaging(field0: final v):
      return _imagingTitle(v);
    case EventPayload_Guiding(field0: final v):
      return _guidingTitle(v);
    case EventPayload_Sequencer(field0: final v):
      return _sequencerTitle(v);
    case EventPayload_Safety(field0: final v):
      return _safetyTitle(v);
    case EventPayload_System(field0: final v):
      return _systemTitle(v);
    case EventPayload_PolarAlignment():
      return 'Polar alignment update';
    case EventPayload_PolarAlignmentStatus(field0: final v):
      return 'Polar alignment: ${v.status}';
    case EventPayload_PolarAlignmentImage(field0: final v):
      return 'Polar alignment ${v.phase}';
  }
}

/// Returns a longer, field-derived detail line. May be empty when there
/// is no useful per-event detail. Empty results are rendered as a
/// title-only row.
String nightshadeEventDisplayDetail(NightshadeEvent event) {
  final payload = event.payload;
  switch (payload) {
    case EventPayload_Equipment(field0: final v):
      return _equipmentDetail(v);
    case EventPayload_Imaging(field0: final v):
      return _imagingDetail(v);
    case EventPayload_Guiding(field0: final v):
      return _guidingDetail(v);
    case EventPayload_Sequencer(field0: final v):
      return _sequencerDetail(v);
    case EventPayload_Safety(field0: final v):
      return _safetyDetail(v);
    case EventPayload_System(field0: final v):
      return _systemDetail(v);
    case EventPayload_PolarAlignment(field0: final v):
      return 'Total error ${v.totalError.toStringAsFixed(2)}\'';
    case EventPayload_PolarAlignmentStatus(field0: final v):
      return 'Phase ${v.phase} (point ${v.point})';
    case EventPayload_PolarAlignmentImage(field0: final v):
      return v.phase == 'measuring'
          ? 'Measurement ${v.point}/3'
          : 'Adjustment phase';
  }
}

/// True when the event is operationally critical and the dashboard
/// should escalate it to a persistent banner / push notification rather
/// than letting it scroll off the recent-events feed.
///
/// The classification is driven first by the bridge's [EventSeverity]
/// (Rust sets `critical` on park failures, mount errors, FITS save
/// failures, disk exhaustion, etc.) and then by a small set of variant
/// patterns the bridge currently emits at `error` severity but which the
/// user must not miss (e.g. an exposure failure mid-sequence).
bool isCriticalEvent(NightshadeEvent event) {
  if (event.severity == EventSeverity.critical) return true;

  // A small allow-list of error-severity events that the operator needs
  // a persistent banner for — these are the events that, if missed,
  // result in a wasted night.
  final payload = event.payload;
  return switch (payload) {
    EventPayload_Imaging(field0: final v) => switch (v) {
        ImagingEvent_ExposureFailed() => true,
        ImagingEvent_ExposureFailedOld() => true,
        _ => false,
      },
    EventPayload_Safety(field0: final v) => switch (v) {
        SafetyEvent_EmergencyStop() => true,
        SafetyEvent_WeatherUnsafe() => true,
        _ => false,
      },
    EventPayload_System(field0: final v) => switch (v) {
        SystemEvent_DiskSpaceLow() => true,
        SystemEvent_Error() => true,
        _ => false,
      },
    EventPayload_Sequencer(field0: final v) => switch (v) {
        SequencerEvent_Error() => true,
        _ => false,
      },
    _ => false,
  };
}

// ---------------------------------------------------------------------------
// Variant-specific title/detail mapping.
// ---------------------------------------------------------------------------

String _equipmentTitle(EquipmentEvent v) {
  return switch (v) {
    EquipmentEvent_Connecting() => 'Connecting',
    EquipmentEvent_Connected() => 'Connected',
    EquipmentEvent_Disconnected() => 'Disconnected',
    EquipmentEvent_PropertyChanged() => 'Property changed',
    EquipmentEvent_Error() => 'Device error',
    EquipmentEvent_MountSlewStarted() => 'Mount slew started',
    EquipmentEvent_MountSlewCompleted() => 'Mount slew complete',
    EquipmentEvent_MountTrackingStarted() => 'Tracking started',
    EquipmentEvent_MountTrackingStopped() => 'Tracking stopped',
    EquipmentEvent_MountParkStarted() => 'Park initiated',
    EquipmentEvent_MountParkCompleted() => 'Mount parked',
    EquipmentEvent_MountUnparked() => 'Mount unparked',
    EquipmentEvent_FocuserMoveStarted() => 'Focuser move started',
    EquipmentEvent_FocuserMoveCompleted() => 'Focuser move complete',
    EquipmentEvent_FocuserTemperatureChanged() => 'Focuser temperature',
    EquipmentEvent_FilterChanging() => 'Filter changing',
    EquipmentEvent_FilterChanged() => 'Filter changed',
    EquipmentEvent_RotatorMoveStarted() => 'Rotator move started',
    EquipmentEvent_RotatorMoveCompleted() => 'Rotator move complete',
    EquipmentEvent_CameraCoolingStarted() => 'Cooling started',
    EquipmentEvent_CameraCoolingReached() => 'Cooling reached target',
    EquipmentEvent_CameraWarmingStarted() => 'Warming started',
    EquipmentEvent_CameraWarmingCompleted() => 'Warming complete',
    EquipmentEvent_HeartbeatStarted() => 'Heartbeat started',
    EquipmentEvent_HeartbeatStopped() => 'Heartbeat stopped',
    EquipmentEvent_HeartbeatStatusChanged() => 'Heartbeat status',
    EquipmentEvent_HeartbeatReconnecting() => 'Reconnecting',
    EquipmentEvent_HeartbeatReconnected() => 'Reconnected',
  };
}

String _equipmentDetail(EquipmentEvent v) {
  return switch (v) {
    EquipmentEvent_Connecting(deviceType: final t, deviceId: final id) =>
      '$t · $id',
    EquipmentEvent_Connected(deviceType: final t, deviceId: final id) =>
      '$t · $id',
    EquipmentEvent_Disconnected(deviceType: final t, deviceId: final id) =>
      '$t · $id',
    EquipmentEvent_PropertyChanged(
      deviceType: final t,
      property: final p,
      value: final val
    ) =>
      '$t · $p=$val',
    EquipmentEvent_Error(
      deviceType: final t,
      deviceId: final id,
      message: final m
    ) =>
      '$t/$id: $m',
    EquipmentEvent_MountSlewStarted(ra: final ra, dec: final dec) =>
      'RA ${ra.toStringAsFixed(3)}h Dec ${dec.toStringAsFixed(2)}°',
    EquipmentEvent_MountSlewCompleted(ra: final ra, dec: final dec) =>
      'RA ${ra.toStringAsFixed(3)}h Dec ${dec.toStringAsFixed(2)}°',
    EquipmentEvent_MountTrackingStarted() => '',
    EquipmentEvent_MountTrackingStopped() => '',
    EquipmentEvent_MountParkStarted() => '',
    EquipmentEvent_MountParkCompleted() => '',
    EquipmentEvent_MountUnparked() => '',
    EquipmentEvent_FocuserMoveStarted(targetPosition: final p) =>
      'Target $p',
    EquipmentEvent_FocuserMoveCompleted(position: final p) => 'At $p',
    EquipmentEvent_FocuserTemperatureChanged(temperature: final t) =>
      '${t.toStringAsFixed(1)}°C',
    EquipmentEvent_FilterChanging(
      fromPosition: final from,
      toPosition: final to,
      filterName: final name
    ) =>
      name != null && name.isNotEmpty
          ? '$from → $to ($name)'
          : '$from → $to',
    EquipmentEvent_FilterChanged(position: final p, filterName: final name) =>
      name != null && name.isNotEmpty ? '$name (pos $p)' : 'Position $p',
    EquipmentEvent_RotatorMoveStarted(targetAngle: final a) =>
      'Target ${a.toStringAsFixed(2)}°',
    EquipmentEvent_RotatorMoveCompleted(angle: final a) =>
      '${a.toStringAsFixed(2)}°',
    EquipmentEvent_CameraCoolingStarted(targetTemp: final t) =>
      'Target ${t.toStringAsFixed(1)}°C',
    EquipmentEvent_CameraCoolingReached(temperature: final t) =>
      'At ${t.toStringAsFixed(1)}°C',
    EquipmentEvent_CameraWarmingStarted() => '',
    EquipmentEvent_CameraWarmingCompleted() => '',
    EquipmentEvent_HeartbeatStarted(deviceType: final t, deviceId: final id) =>
      '$t · $id',
    EquipmentEvent_HeartbeatStopped(deviceType: final t, deviceId: final id) =>
      '$t · $id',
    EquipmentEvent_HeartbeatStatusChanged(
      deviceType: final t,
      deviceId: final id,
      status: final s,
      consecutiveFailures: final failures,
    ) =>
      '$t/$id: ${s.name} ($failures fails)',
    EquipmentEvent_HeartbeatReconnecting(
      deviceType: final t,
      deviceId: final id,
      attempt: final n,
      maxAttempts: final max,
    ) =>
      '$t/$id: attempt $n/$max',
    EquipmentEvent_HeartbeatReconnected(
      deviceType: final t,
      deviceId: final id,
      afterAttempts: final n,
    ) =>
      '$t/$id after $n attempts',
  };
}

String _imagingTitle(ImagingEvent v) {
  return switch (v) {
    ImagingEvent_ExposureStarted() => 'Exposure started',
    ImagingEvent_ExposureStartedWithFrame() => 'Exposure started',
    ImagingEvent_ExposureProgress() => 'Exposure progress',
    ImagingEvent_ExposureCompleted() => 'Exposure complete',
    ImagingEvent_ExposureCompletedWithFrame() => 'Exposure complete',
    ImagingEvent_ExposureFailed() => 'Exposure failed',
    ImagingEvent_ExposureCancelled() => 'Exposure cancelled',
    ImagingEvent_DownloadStarted() => 'Download started',
    ImagingEvent_DownloadCompleted() => 'Download complete',
    ImagingEvent_ImageReady() => 'Image ready',
    ImagingEvent_ImageSaved() => 'Image saved',
    ImagingEvent_TemperatureChanged() => 'Camera temperature',
    ImagingEvent_ExposureComplete() => 'Exposure complete',
    ImagingEvent_ExposureFailedOld() => 'Exposure failed',
  };
}

String _imagingDetail(ImagingEvent v) {
  return switch (v) {
    ImagingEvent_ExposureStarted(
      durationSecs: final d,
      frameType: final t
    ) =>
      '${d.toStringAsFixed(1)}s ${t.name}',
    ImagingEvent_ExposureStartedWithFrame(
      durationSecs: final d,
      frameType: final t,
      frameNumber: final n,
      totalFrames: final total,
    ) =>
      total != null
          ? '$n/$total · ${d.toStringAsFixed(1)}s ${t.name}'
          : '#$n · ${d.toStringAsFixed(1)}s ${t.name}',
    ImagingEvent_ExposureProgress(
      progress: final p,
      remainingSecs: final r
    ) =>
      '${(p * 100).toStringAsFixed(0)}% · ${r.toStringAsFixed(0)}s remaining',
    ImagingEvent_ExposureCompleted(
      hfr: final h,
      starsDetected: final stars
    ) =>
      'HFR ${h.toStringAsFixed(2)} · $stars stars',
    ImagingEvent_ExposureCompletedWithFrame(
      frameNumber: final n,
      totalFrames: final total,
      hfr: final h,
      starsDetected: final stars,
    ) =>
      total != null
          ? '$n/$total · HFR ${h.toStringAsFixed(2)} · $stars stars'
          : '#$n · HFR ${h.toStringAsFixed(2)} · $stars stars',
    ImagingEvent_ExposureFailed(error: final err) => err,
    ImagingEvent_ExposureCancelled() => '',
    ImagingEvent_DownloadStarted() => '',
    ImagingEvent_DownloadCompleted() => '',
    ImagingEvent_ImageReady(width: final w, height: final h) => '$w × $h',
    ImagingEvent_ImageSaved(filePath: final p) => p,
    ImagingEvent_TemperatureChanged(
      tempCelsius: final t,
      coolerPower: final pw
    ) =>
      '${t.toStringAsFixed(1)}°C · ${pw.toStringAsFixed(0)}% cooler',
    ImagingEvent_ExposureComplete(success: final s) => s ? 'OK' : 'Failed',
    ImagingEvent_ExposureFailedOld(reason: final r) => r,
  };
}

String _guidingTitle(GuidingEvent v) {
  return switch (v) {
    GuidingEvent_Connected() => 'Guider connected',
    GuidingEvent_Disconnected() => 'Guider disconnected',
    GuidingEvent_GuidingStarted() => 'Guiding started',
    GuidingEvent_GuidingStopped() => 'Guiding stopped',
    GuidingEvent_Paused() => 'Guiding paused',
    GuidingEvent_Resumed() => 'Guiding resumed',
    GuidingEvent_Settled() => 'Guiding settled',
    GuidingEvent_LostStar() => 'Guide star lost',
    GuidingEvent_DitherStarted() => 'Dither started',
    GuidingEvent_DitherCompleted() => 'Dither complete',
    GuidingEvent_Correction() => 'Guiding correction',
    GuidingEvent_Looping() => 'Guider looping',
    GuidingEvent_Settling() => 'Settling',
    GuidingEvent_Calibrating() => 'Calibrating',
    GuidingEvent_CalibrationComplete() => 'Calibration complete',
    GuidingEvent_StarSelected() => 'Star selected',
    GuidingEvent_AppState() => 'PHD2 state',
    GuidingEvent_GuideStats() => 'Guide stats',
  };
}

String _guidingDetail(GuidingEvent v) {
  return switch (v) {
    GuidingEvent_Connected() => '',
    GuidingEvent_Disconnected() => '',
    GuidingEvent_GuidingStarted() => '',
    GuidingEvent_GuidingStopped() => '',
    GuidingEvent_Paused() => '',
    GuidingEvent_Resumed() => '',
    GuidingEvent_Settled(rms: final rms) => 'RMS ${rms.toStringAsFixed(2)}"',
    GuidingEvent_LostStar() => '',
    GuidingEvent_DitherStarted(pixels: final p) =>
      '${p.toStringAsFixed(2)} px',
    GuidingEvent_DitherCompleted() => '',
    GuidingEvent_Correction(ra: final ra, dec: final dec) =>
      'RA ${ra.toStringAsFixed(2)}" Dec ${dec.toStringAsFixed(2)}"',
    GuidingEvent_Looping() => '',
    GuidingEvent_Settling() => '',
    GuidingEvent_Calibrating() => '',
    GuidingEvent_CalibrationComplete() => '',
    GuidingEvent_StarSelected(x: final x, y: final y) =>
      '(${x.toStringAsFixed(1)}, ${y.toStringAsFixed(1)})',
    GuidingEvent_AppState(state: final s) => s,
    GuidingEvent_GuideStats(snr: final snr, starMass: final mass) =>
      'SNR ${snr.toStringAsFixed(1)} · mass ${mass.toStringAsFixed(0)}',
  };
}

String _sequencerTitle(SequencerEvent v) {
  return switch (v) {
    SequencerEvent_Started() => 'Sequence started',
    SequencerEvent_Paused() => 'Sequence paused',
    SequencerEvent_Resumed() => 'Sequence resumed',
    SequencerEvent_Stopped() => 'Sequence stopped',
    SequencerEvent_Completed() => 'Sequence complete',
    SequencerEvent_NodeStarted() => 'Step started',
    SequencerEvent_NodeCompleted() => 'Step finished',
    SequencerEvent_Progress() => 'Progress',
    SequencerEvent_TargetChanged() => 'Target changed',
    SequencerEvent_TargetCompleted() => 'Target complete',
    SequencerEvent_ExposureStarted() => 'Exposure started',
    SequencerEvent_ExposureCompleted() => 'Exposure complete',
    SequencerEvent_Error() => 'Sequencer error',
    SequencerEvent_TriggerFired() => 'Trigger fired',
    SequencerEvent_InstructionProgress() => 'Instruction progress',
  };
}

String _sequencerDetail(SequencerEvent v) {
  return switch (v) {
    SequencerEvent_Started(sequenceName: final n) => n,
    SequencerEvent_Paused() => '',
    SequencerEvent_Resumed() => '',
    SequencerEvent_Stopped() => '',
    SequencerEvent_Completed() => '',
    SequencerEvent_NodeStarted(nodeType: final t) => t,
    SequencerEvent_NodeCompleted(status: final s) => s,
    SequencerEvent_Progress(current: final c, total: final t) => '$c / $t',
    SequencerEvent_TargetChanged(targetName: final n) => n,
    SequencerEvent_TargetCompleted(targetName: final n) => n,
    SequencerEvent_ExposureStarted(
      frame: final f,
      total: final t,
      filter: final flt,
      durationSecs: final d,
    ) =>
      flt != null && flt.isNotEmpty
          ? '$f/$t · $flt · ${d.toStringAsFixed(1)}s'
          : '$f/$t · ${d.toStringAsFixed(1)}s',
    SequencerEvent_ExposureCompleted(
      frame: final f,
      total: final t,
      durationSecs: final d,
    ) =>
      '$f/$t · ${d.toStringAsFixed(1)}s',
    SequencerEvent_Error(message: final m) => m,
    SequencerEvent_TriggerFired(triggerName: final n, action: final a) =>
      '$n → $a',
    SequencerEvent_InstructionProgress(
      instruction: final i,
      progressPercent: final p,
      detail: final d,
    ) =>
      d.isNotEmpty
          ? '$i: $d (${p.toStringAsFixed(0)}%)'
          : '$i (${p.toStringAsFixed(0)}%)',
  };
}

String _safetyTitle(SafetyEvent v) {
  return switch (v) {
    SafetyEvent_WeatherUnsafe() => 'Weather unsafe',
    SafetyEvent_WeatherSafe() => 'Weather safe',
    SafetyEvent_EmergencyStop() => 'Emergency stop',
    SafetyEvent_ParkInitiated() => 'Park initiated',
    SafetyEvent_ParkCompleted() => 'Park complete',
  };
}

String _safetyDetail(SafetyEvent v) {
  return switch (v) {
    SafetyEvent_WeatherUnsafe(reason: final r) => r,
    SafetyEvent_WeatherSafe() => '',
    SafetyEvent_EmergencyStop(reason: final r) => r,
    SafetyEvent_ParkInitiated(reason: final r) => r,
    SafetyEvent_ParkCompleted() => '',
  };
}

String _systemTitle(SystemEvent v) {
  return switch (v) {
    SystemEvent_Initialized() => 'System ready',
    SystemEvent_ShuttingDown() => 'Shutting down',
    SystemEvent_Error() => 'System error',
    SystemEvent_DiskSpaceLow() => 'Disk space low',
    SystemEvent_Notification(title: final t) => t,
    SystemEvent_EventsDropped() => 'Events dropped',
  };
}

String _systemDetail(SystemEvent v) {
  return switch (v) {
    SystemEvent_Initialized() => '',
    SystemEvent_ShuttingDown() => '',
    SystemEvent_Error(message: final m) => m,
    SystemEvent_DiskSpaceLow(availableGb: final gb) =>
      '${gb.toStringAsFixed(1)} GB free',
    SystemEvent_Notification(message: final m, level: final lvl) =>
      lvl.isNotEmpty ? '$m ($lvl)' : m,
    SystemEvent_EventsDropped(droppedCount: final n, totalDropped: final tot) =>
      '$n events dropped (total: $tot)',
  };
}
