// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Image metadata for mobile client
class ImageInfo {
  final PlatformInt64 imageId;
  final PlatformInt64? sessionId;
  final String filePath;
  final String fileName;
  final String fileFormat;
  final PlatformInt64? fileSize;
  final String frameType;
  final double exposureDuration;
  final int? gain;
  final int? offset;
  final int binX;
  final int binY;
  final String? filter;
  final double? hfr;
  final int? starCount;
  final PlatformInt64 capturedAt;
  final bool isAccepted;

  const ImageInfo({
    required this.imageId,
    this.sessionId,
    required this.filePath,
    required this.fileName,
    required this.fileFormat,
    this.fileSize,
    required this.frameType,
    required this.exposureDuration,
    this.gain,
    this.offset,
    required this.binX,
    required this.binY,
    this.filter,
    this.hfr,
    this.starCount,
    required this.capturedAt,
    required this.isAccepted,
  });

  @override
  int get hashCode =>
      imageId.hashCode ^
      sessionId.hashCode ^
      filePath.hashCode ^
      fileName.hashCode ^
      fileFormat.hashCode ^
      fileSize.hashCode ^
      frameType.hashCode ^
      exposureDuration.hashCode ^
      gain.hashCode ^
      offset.hashCode ^
      binX.hashCode ^
      binY.hashCode ^
      filter.hashCode ^
      hfr.hashCode ^
      starCount.hashCode ^
      capturedAt.hashCode ^
      isAccepted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageInfo &&
          runtimeType == other.runtimeType &&
          imageId == other.imageId &&
          sessionId == other.sessionId &&
          filePath == other.filePath &&
          fileName == other.fileName &&
          fileFormat == other.fileFormat &&
          fileSize == other.fileSize &&
          frameType == other.frameType &&
          exposureDuration == other.exposureDuration &&
          gain == other.gain &&
          offset == other.offset &&
          binX == other.binX &&
          binY == other.binY &&
          filter == other.filter &&
          hfr == other.hfr &&
          starCount == other.starCount &&
          capturedAt == other.capturedAt &&
          isAccepted == other.isAccepted;
}
