#!/usr/bin/env python3
"""One-off generator: Dart variable_star_catalog.dart -> Rust STARS table."""
from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[4]
DART = (
    REPO
    / "packages/nightshade_planetarium/lib/src/catalogs/variable_star_catalog.dart"
)
OUT = Path(__file__).resolve().parents[1] / "src/catalog/variable_stars_data.inc.rs"

TYPE_MAP = {
    "VariableStarType.mira": "VariableStarKind::Mira",
    "VariableStarType.cepheid": "VariableStarKind::Cepheid",
    "VariableStarType.rrLyrae": "VariableStarKind::RrLyrae",
    "VariableStarType.eclipsingAlgol": "VariableStarKind::EclipsingAlgol",
    "VariableStarType.eclipsingBetaLyr": "VariableStarKind::EclipsingBetaLyr",
    "VariableStarType.eclipsingWUma": "VariableStarKind::EclipsingWUma",
    "VariableStarType.semiRegular": "VariableStarKind::SemiRegular",
    "VariableStarType.irregular": "VariableStarKind::Irregular",
    "VariableStarType.deltaScuti": "VariableStarKind::DeltaScuti",
    "VariableStarType.gammaCas": "VariableStarKind::GammaCas",
    "VariableStarType.rCrB": "VariableStarKind::RCrB",
    "VariableStarType.nova": "VariableStarKind::Nova",
    "VariableStarType.dwarfNova": "VariableStarKind::DwarfNova",
    "VariableStarType.rsCVn": "VariableStarKind::RsCVn",
    "VariableStarType.byDra": "VariableStarKind::ByDra",
    "VariableStarType.spb": "VariableStarKind::Spb",
    "VariableStarType.other": "VariableStarKind::Other",
}


def field(block: str, pat: str) -> str | None:
    m = re.search(pat, block, re.S)
    return m.group(1) if m else None


def main() -> None:
    dart = DART.read_text(encoding="utf-8")
    blocks = re.split(r"\s*VariableStarData\(\s*\n", dart)
    entries: list[str] = []
    for block in blocks[1:]:
        if "name:" not in block:
            continue
        name = field(block, r"name:\s*'([^']*)'")
        desig = field(block, r"designation:\s*'([^']*)'")
        const = field(block, r"constellation:\s*'([^']*)'")
        ra = field(block, r"ra:\s*(-?[0-9.]+)")
        dec = field(block, r"dec:\s*(-?[0-9.]+)")
        typ = field(block, r"type:\s*(VariableStarType\.\w+)")
        period = field(block, r"periodDays:\s*(null|-?[0-9.]+)")
        mag_max = field(block, r"magMax:\s*(-?[0-9.]+)")
        mag_min = field(block, r"magMin:\s*(-?[0-9.]+)")
        spec = field(block, r"spectralType:\s*'([^']*)'")
        if not all([name, const, ra, dec, typ, mag_max, mag_min]):
            raise RuntimeError(f"incomplete entry: {name!r}")
        period_rust = "None" if period in (None, "null") else f"Some({period}f32)"
        desig_rust = "None" if not desig else f'Some("{desig}")'
        spec_rust = "None" if not spec else f'Some("{spec}")'
        kind = TYPE_MAP[typ]
        entries.append(
            "    VariableStar {\n"
            f'        name: "{name}",\n'
            f"        designation: {desig_rust},\n"
            f'        constellation: "{const}",\n'
            f"        ra_hours: {ra}f32,\n"
            f"        dec_deg: {dec}f32,\n"
            f"        kind: {kind},\n"
            f"        period_days: {period_rust},\n"
            f"        mag_max: {mag_max}f32,\n"
            f"        mag_min: {mag_min}f32,\n"
            f"        spectral_type: {spec_rust},\n"
            "    },"
        )

    OUT.write_text(
        "// @generated by scripts/gen_variable_stars.py — do not edit by hand\n"
        "/// Curated variable-star table (ported from v1 Dart catalog).\n"
        f"pub const STARS: &[VariableStar] = &[\n"
        + "\n".join(entries)
        + "\n];\n",
        encoding="utf-8",
    )
    print(f"wrote {len(entries)} stars to {OUT}")


if __name__ == "__main__":
    main()
