// A science report is shared with the AAVSO and the MPC. Every instant in it
// has to be in one stated convention.
//
// Observed: the Session block read "**Started:** 2026-07-31T23:00:00.000" —
// ISO-8601 in shape but with no offset and no Z — while the footer a few lines
// down read "_Generated by Nightshade 6.1.0 on 2026-08-02T14:42:11.518312Z._"
// and the light-curve block was explicitly labelled "(UTC)". Drift returns
// LOCAL DateTimes, so the unlabelled one was local wall time: a reader in
// another timezone is off by up to a day.

import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:nightshade_core/nightshade_core.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late NightshadeDatabase db;
  late ScienceReportExporter exporter;

  setUp(() {
    db = NightshadeDatabase.forTesting(NativeDatabase.memory());
    exporter = ScienceReportExporter(
      imagesDao: ImagesDao(db),
      scienceDao: ScienceDao(db),
      sessionsDao: SessionsDao(db),
      targetsDao: TargetsDao(db),
    );
  });

  tearDown(() async => db.close());

  test('the session block prints UTC, with the Z, like the footer', () async {
    final sessionId = await db.sessionsDao.startSession(name: 'Night D');
    // A definite instant, then closed at another one.
    await db.sessionsDao.endSession(sessionId);

    final md = await exporter.buildMarkdown(sessionId);

    final started = RegExp(r'\*\*Started \(UTC\):\*\* (\S+)').firstMatch(md);
    expect(
      started,
      isNotNull,
      reason: 'the field has to name its timezone, not just carry one',
    );
    final stamp = started!.group(1)!;
    expect(
      stamp,
      endsWith('Z'),
      reason:
          'an unlabelled local ISO timestamp beside a labelled UTC one '
          'invites a whole-night error',
    );
    expect(DateTime.parse(stamp).isUtc, isTrue);

    final ended = RegExp(r'\*\*Ended \(UTC\):\*\* (\S+)').firstMatch(md);
    expect(ended, isNotNull);
    expect(ended!.group(1)!, endsWith('Z'));

    // And nothing in the Session block is left in the bare-local shape.
    expect(
      RegExp(r'\*\*(Started|Ended):\*\*').hasMatch(md),
      isFalse,
      reason: 'the unlabelled field must be gone, not merely joined',
    );
  });

  test(
    'the stamp is the real instant, not the local wall clock relabelled',
    () async {
      final sessionId = await db.sessionsDao.startSession(name: 'Night E');
      final session = await db.sessionsDao.getSessionById(sessionId);
      final md = await exporter.buildMarkdown(sessionId);

      final stamp = RegExp(
        r'\*\*Started \(UTC\):\*\* (\S+)',
      ).firstMatch(md)!.group(1)!;
      expect(
        DateTime.parse(stamp).millisecondsSinceEpoch,
        session!.startTime.millisecondsSinceEpoch,
        reason:
            'converting to UTC must move the field values, not just append '
            'a Z to the local ones',
      );
    },
  );
}
