import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:nightshade_core/src/models/hips/hips_properties.dart';
import 'package:nightshade_core/src/models/hips/hips_survey_registry.dart';
import 'package:nightshade_core/src/models/hips/hips_tile_id.dart';
import 'package:nightshade_core/src/providers/framing_provider.dart'
    show SurveySource;

/// Live CDS/P/DSS2/red `properties` document (captured verbatim from
/// https://alasky.cds.unistra.fr/DSS/DSS2Merged/properties). Used as the
/// real-world parser fixture for the verification artifact.
const _liveDss2RedProperties = r'''
hips_doi             = 10.26093/cds/aladin/wenz-vg
creator_did          = ivo://CDS/P/DSS2/red
obs_collection       = DSS2 Red (F+R)
obs_title            = DSS2 Red (F+R)
obs_copyright        = Digitized Sky Survey - STScI/NASA, Healpixed by CDS
obs_copyright_url    = http://archive.stsci.edu/dss/copyright.html
hips_creation_date   = 2012-07-13T14:03Z
hips_release_date    = 2019-05-07T10:59Z
hips_builder         = Aladin/HipsGen v10.123
hips_creator         = Boch T. (CDS)
hips_version         = 1.4
hips_order           = 9
hips_frame           = equatorial
hips_tile_width      = 512
hips_tile_format     = jpeg fits
hips_pixel_cut       = 1000 10000
dataproduct_type     = image
hips_status          = public master clonableOnce
''';

void main() {
  test('writes a HiPS C0 verification artifact exercising the real models', () {
    final props = HipsProperties.parse(_liveDss2RedProperties);

    final buffer = StringBuffer()
      ..writeln('HiPS C0 — protocol + survey-registry verification artifact')
      ..writeln('Generated by hips_models_artifact_test.dart')
      ..writeln('============================================================')
      ..writeln()
      ..writeln('--- HipsProperties.parse(live CDS/P/DSS2/red properties) ---')
      ..writeln('hips_order          : ${props.hipsOrder}')
      ..writeln('hips_order_min      : ${props.hipsOrderMin} '
          '(default applied: ${props.hipsOrderMin == HipsProperties.defaultOrderMin && !_documentHasKey(_liveDss2RedProperties, "hips_order_min")})')
      ..writeln('hips_tile_width     : ${props.tileWidth} '
          '(defaulted: ${props.tileWidthWasDefaulted})')
      ..writeln('hips_tile_format    : ${props.tileFormats.map((f) => f.wireValue).join(", ")}')
      ..writeln('preferred format    : ${props.preferredFormat.wireValue} '
          '(ext .${props.preferredFormat.fileExtension})')
      ..writeln('hips_frame          : ${props.frame.wireValue}')
      ..writeln('obs_copyright       : ${props.obsCopyright}')
      ..writeln('obs_copyright_url   : ${props.obsCopyrightUrl}')
      ..writeln('hips_creator        : ${props.creator}')
      ..writeln()
      ..writeln('--- HipsTileId addressing (Norder/Dir/Npix + Allsky) ---');

    final sampleTiles = [
      HipsTileId(survey: 'CDS/P/DSS2/red', norder: 3, npix: 42),
      HipsTileId(survey: 'CDS/P/DSS2/red', norder: 6, npix: 25000),
      HipsTileId(survey: 'CDS/P/DSS2/red', norder: 9, npix: 123456),
    ];
    const verifiedBase = 'https://alasky.cds.unistra.fr/DSS/DSS2Merged';
    for (final tile in sampleTiles) {
      buffer
        ..writeln('Norder${tile.norder} Npix${tile.npix}: '
            'Dir=${tile.directoryBucket}, '
            'path=${tile.relativePath(props.preferredFormat)}')
        ..writeln('    url=${tile.tileUrl(verifiedBase, props.preferredFormat)}');
    }
    buffer
      ..writeln('Allsky(Norder3): '
          '${HipsTileId.allskyUrl(verifiedBase, 3, props.preferredFormat)}')
      ..writeln('tile counts: '
          'N0=${HipsTileId.numberOfTiles(0)}, '
          'N3=${HipsTileId.numberOfTiles(3)}, '
          'N9=${HipsTileId.numberOfTiles(9)}')
      ..writeln()
      ..writeln('--- HipsSurveyRegistry (SurveySource -> CDS HiPS) ---')
      ..writeln('exhaustive entries  : '
          '${HipsSurveyRegistry.debugAssertExhaustive()} / '
          '${SurveySource.values.length}');
    for (final source in SurveySource.values) {
      final entry = HipsSurveyRegistry.entryFor(source);
      buffer.writeln(
        '${source.name.padRight(10)} -> ${entry.hipsId.padRight(18)} '
        '${entry.hasVerifiedBaseUrl ? "VERIFIED ${entry.baseUrl}" : "resolve@runtime (candidate ${HipsSurveyRegistry.candidateBaseUrlFor(source)})"}',
      );
    }

    final outDir = Directory('../../.hips_verify');
    outDir.createSync(recursive: true);
    final outFile = File('${outDir.path}/hips_c0_models.txt');
    outFile.writeAsStringSync(buffer.toString());

    // Surface the absolute path so the verification step can report it.
    // ignore: avoid_print
    print('HiPS C0 artifact written to: ${outFile.absolute.path}');

    expect(outFile.existsSync(), isTrue);
    expect(outFile.readAsStringSync(), contains('VERIFIED'));
  });
}

bool _documentHasKey(String doc, String key) =>
    doc.split('\n').any((l) => l.trimLeft().startsWith('$key '));
