// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'system.freezed.dart';

@freezed
sealed class SafetyEvent with _$SafetyEvent {
  const SafetyEvent._();

  const factory SafetyEvent.weatherUnsafe({required String reason}) =
      SafetyEvent_WeatherUnsafe;
  const factory SafetyEvent.weatherSafe() = SafetyEvent_WeatherSafe;
  const factory SafetyEvent.emergencyStop({required String reason}) =
      SafetyEvent_EmergencyStop;
  const factory SafetyEvent.parkInitiated({required String reason}) =
      SafetyEvent_ParkInitiated;
  const factory SafetyEvent.parkCompleted() = SafetyEvent_ParkCompleted;
}

@freezed
sealed class SystemEvent with _$SystemEvent {
  const SystemEvent._();

  const factory SystemEvent.initialized() = SystemEvent_Initialized;
  const factory SystemEvent.shuttingDown() = SystemEvent_ShuttingDown;
  const factory SystemEvent.error({required String message}) =
      SystemEvent_Error;
  const factory SystemEvent.diskSpaceLow({required double availableGb}) =
      SystemEvent_DiskSpaceLow;
  const factory SystemEvent.notification({
    required String title,
    required String message,
    required String level,

    /// per-NotificationNode override list of
    /// NotificationTransportKind names (Dart enum, serialised as strings).
    /// The Dart NotificationRouter consumes this field to bypass the
    /// matrix's `custom` rule and dispatch to the user-picked transports
    /// directly. `None` or empty = use matrix routing.
    List<String>? explicitTransports,
  }) = SystemEvent_Notification;

  /// Notification that events were dropped due to slow consumer
  /// This is sent after the stream recovers to inform the Dart side
  const factory SystemEvent.eventsDropped({
    /// Number of events that were dropped/skipped
    required BigInt droppedCount,

    /// Total number of events dropped since app start
    required BigInt totalDropped,
  }) = SystemEvent_EventsDropped;
}
