// Part of ../templates_tab.dart -- extracted for maintainability.
//
// All hand-built SequenceNode-tree literals that ship as first-run templates. Pure data factory; no widget code. Owns _getBuiltInTemplates() plus its _createXxxNodes() helpers.
part of '../templates_tab.dart';

List<Sequence> _getBuiltInTemplates() {
  return [
    // Beginner templates first for discoverability
    Sequence(
      id: 'template-first-light',
      name: 'First Light',
      description:
          'Simple sequence for absolute beginners - just point and shoot',
      isTemplate: true,
      createdAt: DateTime.now().subtract(const Duration(days: 35)),
      modifiedAt: DateTime.now().subtract(const Duration(days: 35)),
      nodes: _createFirstLightNodes(),
      rootNodeId: 'fl-root',
    ),
    Sequence(
      id: 'template-osc',
      name: 'One-Shot Color (OSC)',
      description: 'For color cameras without filter wheels',
      isTemplate: true,
      createdAt: DateTime.now().subtract(const Duration(days: 33)),
      modifiedAt: DateTime.now().subtract(const Duration(days: 33)),
      nodes: _createOscNodes(),
      rootNodeId: 'osc-root',
    ),
    Sequence(
      id: 'template-quick-capture',
      name: 'Quick Capture',
      description: 'Simple sequence for quick test shots',
      isTemplate: true,
      createdAt: DateTime.now().subtract(const Duration(days: 31)),
      modifiedAt: DateTime.now().subtract(const Duration(days: 31)),
      nodes: _createQuickCaptureNodes(),
      rootNodeId: 'quick-root',
    ),
    Sequence(
      id: 'template-dso-beginner',
      name: 'DSO Beginner',
      description:
          'Beginner-friendly sequence with comprehensive safety checks',
      isTemplate: true,
      createdAt: DateTime.now().subtract(const Duration(days: 29)),
      modifiedAt: DateTime.now().subtract(const Duration(days: 29)),
      nodes: _createBeginnerTemplateNodes(),
      rootNodeId: 'beginner-root',
    ),
    // Intermediate templates
    Sequence(
      id: 'template-basic-lrgb',
      name: 'Basic LRGB Sequence',
      description:
          'Standard LRGB imaging sequence with autofocus and dithering',
      isTemplate: true,
      createdAt: DateTime.now().subtract(const Duration(days: 27)),
      modifiedAt: DateTime.now().subtract(const Duration(days: 27)),
      nodes: _createLrgbTemplateNodes(),
      rootNodeId: 'lrgb-root',
    ),
    Sequence(
      id: 'template-narrowband',
      name: 'Narrowband (SHO)',
      description:
          'Hubble Palette narrowband imaging with SII, Ha, and OIII filters',
      isTemplate: true,
      createdAt: DateTime.now().subtract(const Duration(days: 25)),
      modifiedAt: DateTime.now().subtract(const Duration(days: 25)),
      nodes: _createNarrowbandTemplateNodes(),
      rootNodeId: 'nb-root',
    ),
    Sequence(
      id: 'template-mosaic-panel',
      name: 'Mosaic Panel',
      description: 'Template for a single mosaic panel with multiple filters',
      isTemplate: true,
      createdAt: DateTime.now().subtract(const Duration(days: 23)),
      modifiedAt: DateTime.now().subtract(const Duration(days: 23)),
      nodes: _createMosaicTemplateNodes(),
      rootNodeId: 'mosaic-root',
    ),
    // Intermediate-tier templates with condition-aware features
    Sequence(
      id: 'template-ha-oiii',
      name: 'Ha-OIII Bicolor',
      description: 'Two-filter narrowband imaging with guiding and dithering',
      isTemplate: true,
      createdAt: DateTime.now().subtract(const Duration(days: 19)),
      modifiedAt: DateTime.now().subtract(const Duration(days: 19)),
      nodes: _createHaOiiiNodes(),
      rootNodeId: 'haoiii-root',
    ),
    Sequence(
      id: 'template-sho',
      name: 'SHO Hubble Palette',
      description:
          'Full Hubble Palette narrowband with weather safety conditional',
      isTemplate: true,
      createdAt: DateTime.now().subtract(const Duration(days: 17)),
      modifiedAt: DateTime.now().subtract(const Duration(days: 17)),
      nodes: _createShoNodes(),
      rootNodeId: 'sho-root',
    ),
    Sequence(
      id: 'template-lrgb-ha',
      name: 'LRGB + Ha Enhanced',
      description: 'Broadband imaging with hydrogen-alpha enhancement layer',
      isTemplate: true,
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
      modifiedAt: DateTime.now().subtract(const Duration(days: 15)),
      nodes: _createLrgbHaNodes(),
      rootNodeId: 'lrgbha-root',
    ),
    Sequence(
      id: 'template-multi-target',
      name: 'Multi-Target Night',
      description: 'Image multiple targets with altitude-based switching',
      isTemplate: true,
      createdAt: DateTime.now().subtract(const Duration(days: 13)),
      modifiedAt: DateTime.now().subtract(const Duration(days: 13)),
      nodes: _createMultiTargetNodes(),
      rootNodeId: 'multi-root',
    ),
    // Specialized templates
    Sequence(
      id: 'template-planetary',
      name: 'Planetary Capture',
      description: 'High frame rate lucky imaging for planets and moon',
      isTemplate: true,
      createdAt: DateTime.now().subtract(const Duration(days: 11)),
      modifiedAt: DateTime.now().subtract(const Duration(days: 11)),
      nodes: _createPlanetaryNodes(),
      rootNodeId: 'planet-root',
    ),
    // Advanced templates with complex logic
    Sequence(
      id: 'template-unattended',
      name: 'Unattended All-Night',
      description:
          'Fully automated dusk-to-dawn imaging with weather and HFR recovery',
      isTemplate: true,
      createdAt: DateTime.now().subtract(const Duration(days: 9)),
      modifiedAt: DateTime.now().subtract(const Duration(days: 9)),
      nodes: _createUnattendedNodes(),
      rootNodeId: 'unattended-root',
    ),
    Sequence(
      id: 'template-mosaic',
      name: 'Mosaic Multi-Panel',
      description: 'Large field mosaic with per-panel centering',
      isTemplate: true,
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      modifiedAt: DateTime.now().subtract(const Duration(days: 8)),
      nodes: _createMosaicMultiPanelNodes(),
      rootNodeId: 'mosaic-mp-root',
    ),
    Sequence(
      id: 'template-comet',
      name: 'Comet/Asteroid Tracking',
      description: 'Moving target imaging with periodic re-centering',
      isTemplate: true,
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      modifiedAt: DateTime.now().subtract(const Duration(days: 7)),
      nodes: _createCometNodes(),
      rootNodeId: 'comet-root',
    ),
    Sequence(
      id: 'template-solar',
      name: 'Solar Ha',
      description: 'Daytime solar imaging with frequent autofocus',
      isTemplate: true,
      createdAt: DateTime.now().subtract(const Duration(days: 6)),
      modifiedAt: DateTime.now().subtract(const Duration(days: 6)),
      nodes: _createSolarNodes(),
      rootNodeId: 'solar-root',
    ),
    Sequence(
      id: 'template-lunar',
      name: 'Lunar Surface',
      description: 'High-resolution lunar imaging with lucky imaging bursts',
      isTemplate: true,
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      modifiedAt: DateTime.now().subtract(const Duration(days: 5)),
      nodes: _createLunarNodes(),
      rootNodeId: 'lunar-root',
    ),
    Sequence(
      id: 'template-remote',
      name: 'Remote Observatory',
      description: 'Full remote operation with safety monitors',
      isTemplate: true,
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
      modifiedAt: DateTime.now().subtract(const Duration(days: 4)),
      nodes: _createRemoteObservatoryNodes(),
      rootNodeId: 'remote-root',
    ),
  ];
}
