// GENERATED FILE - DO NOT EDIT BY HAND.
//
// Regenerate with:
//   dart run tools/production/settings_search_index_gen.dart
//
// Source of truth is the `title:` of every row each settings section
// actually renders, so typing a setting's visible name finds it. See
// tools/production/settings_search_index_gen.dart for why.

/// Settings section key -> the row titles that section renders.
const Map<String, List<String>> kSettingsSearchTerms = {
  'about': [
    'About',
  ],
  'adaptive-conditions': [
    'Adaptive Conditions',
    'Cloud weight',
    'Enabled for new schedulers',
    'Influence of cloud cover and opacity estimates.',
    'Influence of cloudless, clear-sky transparency in the composed conditions score.',
    'Influence of star sharpness and atmospheric steadiness.',
    'Influence of wind speed when choosing whether to stay on target.',
    'Minimum seconds between adaptive target swaps. Range 0-3600.',
    'New TargetScheduler nodes start with adaptive swap enabled and use the score floor below. Existing nodes are not changed.',
    'Score floor',
    'Score weights',
    'Seeing weight',
    'Swap defaults',
    'Swap hysteresis',
    'Transparency weight',
    'When the live conditions score falls below this 0-100 floor, the scheduler can swap to a better target.',
    'Wind weight',
  ],
  'adaptive-exposure': [
    'Global maximum exposure (s)',
    'Global minimum exposure (s)',
    'max s',
    'min s',
    'Reference (mag/arcsec²)',
  ],
  'annotations': [
    'Animation speed in milliseconds',
    'Annotations',
    'Auto-annotate images',
    'Automatically annotate plate-solved images',
    'Automation',
    'Brightest objects to show (lower = brighter)',
    'Brightness when mouse is over image',
    'Brightness when mouse leaves image',
    'Click on image to identify objects',
    'Click to Identify',
    'Dim annotations when mouse leaves image',
    'Display',
    'Display magnitude values with labels',
    'Display object names next to markers',
    'Distance to search for objects (arcseconds)',
    'Enable annotations',
    'Enable click to identify',
    'Fade duration',
    'Fade Effects',
    'Fade when not hovering',
    'Faintest objects to show (higher = fainter)',
    'Galaxies',
    'Grid overlay',
    'Grid type: pixel, celestial RA/Dec, or off',
    'Hover opacity',
    'Idle opacity',
    'Label font size',
    'Larger objects get larger markers',
    'Limit number of annotations for performance',
    'Magnitude Filter',
    'Marker Styles',
    'Max objects to display',
    'Maximum magnitude',
    'Minimum magnitude',
    'Nebulae',
    'Object Types',
    'Other Objects',
    'Planetary Nebulae',
    'Scale by object size',
    'Search radius',
    'Show labels',
    'Show magnitudes',
    'Show object annotations on images',
    'Size of text labels',
    'Star Clusters',
    'Stars',
    'Stroke width',
    'Thickness of marker outlines',
  ],
  'appearance': [
    'Accent color',
    'Appearance',
    'Dark, Light, or Red night — red night preserves',
    'Display',
    'Font size',
    'Interface text size',
    'Primary accent color',
    'Scale controls and layout density',
    'Sidebar collapsed by default',
    'Theme',
    'UI scale',
  ],
  'autofocus': [
    '0 = use all detected stars',
    'Application Data',
    'Apply focus offsets when changing filters',
    'Auto-learn focus models',
    'Autofocus',
    'Autofocus Filter Settings',
    'Autofocus method',
    'Automatic backup scheduling is stored and executed on',
    'Automatic Backups',
    'Backlash compensation',
    'Backlash IN',
    'Backlash OUT',
    'Backup interval',
    'Bad runs before warning',
    'Below this count, even a high-R² model still forces a',
    'Binning',
    'Central exclusion; must be smaller than outer',
    'Configure on the host',
    'Connect a filter wheel to configure per-filter autofocus settings.',
    'Consecutive bad predictions required before the app',
    'Curve fitting strategy',
    'Database and logs',
    'Default AF frame exposure',
    'Designated autofocus filter',
    'Disable guiding during AF',
    'Drift threshold (steps)',
    'Enable automatic backups',
    'Enable sequence auto-save',
    'Exposure time',
    'Exposures per point',
    'File Paths',
    'Filter to switch to for AF runs',
    'Focuser settle time',
    'Focuser steps between measurement points',
    'Frames to average per focus position',
    'Gates',
    'High-confidence threshold (R²)',
    'Host-owned setting',
    'How many focuser steps a prediction can be off before',
    'How often to create backups (hours)',
    'How often to save pending sequence edits',
    'Initial offset steps',
    'Inner crop ratio',
    'Last backup',
    'Last error',
    'Learned models',
    'Low-confidence threshold (R²)',
    'Managed automatically in Nightshade’s application',
    'Maximum backups',
    'Minimum acceptable curve fit quality',
    'Minimum samples for trust',
    'Must be greater than the inner crop ratio',
    'No filter wheel connected',
    'Number of attempts',
    'Number of auto-save backups to retain',
    'Outer crop ratio',
    'Periodically create full database backups',
    'Persist local sequence edits in the background',
    'Predictive Autofocus',
    'R threshold',
    'Retry count on failure',
    'R² < this → force a real AF sweep.',
    'R² ≥ this → apply prediction directly.',
    'Select host folder',
    'Sequence Auto-Save',
    'Sequence save interval',
    'Status',
    'Step size',
    'Steps out from center for V-curve',
    'Stop autoguider while focusing',
    'Storage',
    'Use brightest n stars',
    'Use filter offsets',
    'Wait after focuser move',
    'When enabled, each successful AF run appends a sample',
  ],
  'backup': [
    'Backup & Restore',
    'Restore Remote Backup?',
  ],
  'calibration': [
    'Apply dark, flat, and bias correction to captured images automatically',
    'Auto-calibrate light frames',
    'Auto-Calibration',
    'Auto-match from dark library',
    'Calibration',
    'Calibration Frame Status',
    'Dark Frame',
    'Find the best matching dark frame based on exposure parameters',
    'Manual dark frame',
    'Master Bias',
    'Master bias file',
    'Master Flat',
    'Master flat file',
    'Master frame on host',
  ],
  'calibration-library': [
    'Calibration Library',
    'Matching Preview',
  ],
  'captured-images': [
    'Captured Images',
  ],
  'catalogs': [
    'Delete Annotation Catalog',
    'Delete Catalogs',
    'Delete Deep-Star Tiles',
    'HYG Star Database',
    'OpenNGC',
  ],
  'connection': [
    'Connection',
    'Connection Status',
    'Current host and port for this Nightshade server',
    'Discovery',
    'Include the configured Alpaca server in automatic startup discovery',
    'Include the configured INDI server in automatic startup discovery',
    'INDI Server Address',
    'Query Alpaca on startup',
    'Query INDI on startup',
    'Refresh Host Settings',
    'Reload this screen from the connected Nightshade host',
    'Remote Features',
    'Server Address',
    'Server Status',
  ],
  'dark-library': [
    'All Entries',
    'Auto dark subtraction',
    'Auto-Calibration',
    'Automatically subtract matching darks from light frames',
    'Dark Library',
    'Frame Groups',
    'Library Management',
    'Library Statistics',
    'Maximum temperature difference for dark matching',
    'Temperature tolerance',
  ],
  'equipment-profiles': [
    'Could not load profiles',
    'Select a profile',
  ],
  'files-storage': [
    '0 = use all detected stars',
    'Application Data',
    'Apply focus offsets when changing filters',
    'Auto-learn focus models',
    'Autofocus',
    'Autofocus Filter Settings',
    'Autofocus method',
    'Automatic backup scheduling is stored and executed on',
    'Automatic Backups',
    'Backlash compensation',
    'Backlash IN',
    'Backlash OUT',
    'Backup interval',
    'Bad runs before warning',
    'Below this count, even a high-R² model still forces a',
    'Binning',
    'Central exclusion; must be smaller than outer',
    'Configure on the host',
    'Connect a filter wheel to configure per-filter autofocus settings.',
    'Consecutive bad predictions required before the app',
    'Curve fitting strategy',
    'Database and logs',
    'Default AF frame exposure',
    'Designated autofocus filter',
    'Disable guiding during AF',
    'Drift threshold (steps)',
    'Enable automatic backups',
    'Enable sequence auto-save',
    'Exposure time',
    'Exposures per point',
    'File Paths',
    'Filter to switch to for AF runs',
    'Focuser settle time',
    'Focuser steps between measurement points',
    'Frames to average per focus position',
    'Gates',
    'High-confidence threshold (R²)',
    'Host-owned setting',
    'How many focuser steps a prediction can be off before',
    'How often to create backups (hours)',
    'How often to save pending sequence edits',
    'Initial offset steps',
    'Inner crop ratio',
    'Last backup',
    'Last error',
    'Learned models',
    'Low-confidence threshold (R²)',
    'Managed automatically in Nightshade’s application',
    'Maximum backups',
    'Minimum acceptable curve fit quality',
    'Minimum samples for trust',
    'Must be greater than the inner crop ratio',
    'No filter wheel connected',
    'Number of attempts',
    'Number of auto-save backups to retain',
    'Outer crop ratio',
    'Periodically create full database backups',
    'Persist local sequence edits in the background',
    'Predictive Autofocus',
    'R threshold',
    'Retry count on failure',
    'R² < this → force a real AF sweep.',
    'R² ≥ this → apply prediction directly.',
    'Select host folder',
    'Sequence Auto-Save',
    'Sequence save interval',
    'Status',
    'Step size',
    'Steps out from center for V-curve',
    'Stop autoguider while focusing',
    'Storage',
    'Use brightest n stars',
    'Use filter offsets',
    'Wait after focuser move',
    'When enabled, each successful AF run appends a sample',
  ],
  'general': [
    'Auto-connect equipment',
    'Behavior',
    'Choose the language used for app chrome',
    'Confirm before closing',
    'Connects the default startup profile on launch, falling back to the',
    'General',
    'Language',
    'Launch app minimized to system tray',
    'Show confirmation when closing during capture',
    'Start minimized',
    'Startup',
  ],
  'help': [
    '7-step guided wizard for your first imaging session —',
    'Advanced Features',
    'Automated Imaging',
    'Calibration Frames',
    'Capture your first light',
    'Clear all tutorial progress and start fresh',
    'Enable tutorials',
    'Equipment Setup',
    'First Night Walkthrough',
    'Generate Diagnostic Dump',
    'Guided Flows',
    'Help & Tutorials',
    'Package logs, settings, profile metadata, and system details for support.',
    'Re-run equipment setup',
    'Re-run onboarding tour',
    'Replay the first-launch spotlight tour that highlights',
    'Reset All Progress',
    'Reset Progress',
    'Run the one-click first-light flow again — short exposure,',
    'Settings',
    'Show tutorial prompts and guided tours',
    'Target Planning',
    'Tutorial Tours',
    'Walk back through the equipment onboarding wizard to scan',
  ],
  'image-grading': [
    'Auto-integrate at end of run',
    'Eccentricity max',
    'Enable image grading',
    'Escalation',
    'Focus thresholds',
    'HFR absolute (pixels)',
    'HFR baseline percent',
    'Image Grading',
    'Master toggle',
    'Max consecutive rejects',
    'Pause the sequence after this many consecutive rejected frames — the safety valve when something is systematically wrong (drifted focus, clouds, dome misalignment).',
    'Post-session integration',
    'Reject folder',
    'Reject folder path',
    'Reject if detected star count drops below this value. Trips when clouds roll in or the dome slit drifts off-target. Leave blank to disable.',
    'Reject if HFR > baseline × (1 + percent/100). The baseline is the median of the first 5 accepted frames of each target.',
    'Reject if measured HFR exceeds this absolute value. Leave blank to disable.',
    'Reject if star eccentricity exceeds this value. 0.6 catches trailed frames; 0.8 catches catastrophic tracking failure. Leave blank to disable.',
    'Star count min',
    'Star shape thresholds',
    'When on, every captured frame is scored against the thresholds below. Bad frames are moved to the reject folder.',
    'When on, the accepted subs are integrated into an',
    'Where rejected frames go. Leave blank for the default <save_path>/Reject/. Relative paths resolve against save_path; absolute paths are honoured verbatim.',
  ],
  'imaging': [
    'Archive format',
    'Captured images are saved as lossless 16-bit FITS files',
    'File Format',
    'File naming pattern',
    'Imaging',
  ],
  'integrations': [
    'Imaging host',
    'Integrations',
    'Managed on the imaging host',
    'Open Nightshade on the rig to enable plugins and enter',
  ],
  'location': [
    'Bortle Class',
    'Coordinates',
    'Elevation',
    'Fetch location from Headless Server',
    'Get location from GPS',
    'Height above sea level',
    'Latitude',
    'Limiting Magnitude',
    'Local Horizon Mask',
    'Location',
    'Longitude',
    'Observing Environment',
    'Positive for East, negative for West',
    'Positive for North, negative for South',
    'Sync from Server',
    'Sync time from operating system',
    'Time',
    'Timezone',
    'Use Device Location',
    'Use system time',
  ],
  'notifications': [
    'Alert sound',
    'API Key',
    'Audible alert on critical events',
    'Autofocus failed',
    'Configure push on the Nightshade host',
    'Configure routing on the Nightshade host',
    'Could not load push configuration',
    'Critical events (unattended imaging)',
    'Discord',
    'Discord channel webhook for notifications',
    'Email, webhook, Pushover, Telegram, Discord, and MQTT',
    'Enable notifications',
    'Enable push to mobile',
    'Equipment disconnected',
    'Errors',
    'Exposure failed',
    'General',
    'Guiding lost',
    'Loading push configuration…',
    'Meridian flip',
    'Notification Events',
    'Notification routing',
    'Notification routing enabled',
    'Notifications',
    'Notify on errors and failures',
    'Notify when meridian flip occurs',
    'Notify when sequence finishes',
    'Per-event routing',
    'Play sounds for notifications',
    'Play the system bell when a critical error fires',
    'Push controls will be available when the',
    'Push critical alerts to mobile',
    'Push on meridian flip events',
    'Push on sequence errors or stops',
    'Push to Mobile',
    'Push when a device disconnects',
    'Push when autofocus fails',
    'Push when camera exposure fails',
    'Push when guide star is lost',
    'Push when safety monitor reports unsafe',
    'Push when sequence finishes',
    'Pushover',
    'Pushover application API key',
    'Pushover user/group key',
    'Queue a test to the active transport (host logs report cloud failures)',
    'Routing master switch',
    'Send a test notification to your device',
    'Send a test notification to your Discord channel',
    'Send alerts to connected mobile devices',
    'Send notifications for important events',
    'Sequence complete',
    'Sequence completed',
    'Sequence failed',
    'Sound alerts',
    'Test Discord',
    'Test push notification',
    'Test Pushover',
    'The master push gate and event toggles are',
    'User Key',
    'Weather unsafe',
    'Webhook URL',
    'When off, no per-category routing fires (legacy push still works)',
    'Which sound to play when critical events fire',
  ],
  'phd2-guiding': [
    'Host',
    'Information',
    'PHD2 Connection',
    'PHD2 executable on imaging host',
    'PHD2 executable path',
    'PHD2 Guiding',
    'PHD2 server hostname or IP address',
    'PHD2 server port (default: 4400)',
    'Port',
  ],
  'plate-solving': [
    'Active solver',
    'Always ignore position hints (slower, but useful',
    'ASTAP',
    'ASTAP catalog directory',
    'ASTAP catalog directory on imaging host',
    'ASTAP detected — catalog missing',
    'ASTAP executable',
    'ASTAP executable on imaging host',
    'Astrometry.net',
    'Blind solve',
    'Click Re-scan',
    'Download a star catalog',
    'Failed to load solve parameters',
    'Fast offline solver — recommended for almost all setups.',
    'How far around the expected position to search',
    'Install ASTAP',
    'Loading…',
    'Local solve-field. Slower but useful on Linux/macOS.',
    'Maximum time to attempt a solve before giving up',
    'Plate Solving',
    'Reading saved solve parameters',
    'Search radius',
    'Selected Astrometry.net solver is not installed',
    'Solve Parameters',
    'solve-field executable',
    'solve-field executable on imaging host',
    'Timeout',
    'Try ASTAP first; fall back to Astrometry.net if ASTAP',
    'Verify ASTAP',
    'Verify Astrometry.net',
  ],
  'preflight': [
    'Lax',
    'Normal',
    'Polar alignment',
    'Polar alignment max age',
    'Pre-flight Checks',
    'Sequence pre-flight flags the polar alignment if the last recorded run is older than this. Set to 0 to disable the check.',
    'Strict',
    'Strictness',
  ],
  'remote-access': [
    'Enable Remote Access',
    'Open on this computer',
    'Pair Remote Browsers',
    'Port for the remote-access server. Changes rebind the server automatically.',
    'Remote Access',
    'Remote access is running on your host',
    'Remote access needs attention',
    'Serve the dashboard and control API for authenticated LAN access.',
    'Server Port',
    'Share on your network',
    'Web Server',
  ],
  'replay-debug': [
    'Decisions older than this are pruned daily. Range',
    'Logging',
    'Maintenance',
    'Replay Debug',
    'Replay decision logging',
    'Retention (days)',
    'When enabled, every adaptive-swap pick, trigger',
  ],
  'rig-catalogs': [
    'Appliance Catalogs',
  ],
  'science': [
    '3D science surfaces',
    'AAVSO',
    'AAVSO observer code',
    'Adds PSF, residual, and tile-map layers to the Imaging overlays menu.',
    'After each light frame, reject captures that exceed',
    'Analyze field-wide seeing and tilt patterns',
    'Astrometric catalog',
    'Astrometric residuals',
    'Auto-configure from camera',
    'Auto-reject bad frames',
    'Bot API key',
    'Bot id',
    'Bot name',
    'Build residual heatmaps and mount feedback',
    'Camera',
    'Camera gain (e⁻/ADU)',
    'Camera read noise (e⁻)',
    'Compute clipping, uniformity, background and SNR tile maps',
    'Compute zeropoint and limiting magnitude',
    'Converts sky background to electrons for limiting',
    'Data source id',
    'Deep catalog lookups (APASS DR9)',
    'Detect and track moving candidates',
    'Enable overlays such as PSF map, residual vectors, and tracks',
    'Enable surface explorer and interactive mesh rendering',
    'Features',
    'Fetch B/V photometry to ~mag 16 from VizieR for zero-point',
    'Frame quality maps',
    'Generate SII/Ha, OIII/Ha, and SII/OIII products',
    'Live differential photometry',
    'Minor Planet Center (MPC)',
    'Mode',
    'Moving object mode',
    'MPC observatory code',
    'Narrowband line ratios',
    'Observer identity',
    'Observer name',
    'Per-frame photometric calibration',
    'Photometric catalog',
    'PSF field map',
    'Reference catalog your solver uses (ADES astCat, e.g.',
    'Reporter name',
    'Reporter shown on TNS (falls back to observer',
    'Reporting group id',
    'Saturation level (ADU)',
    'Science',
    'Science overlays',
    'Show advanced overlay controls',
    'Stamp MAGZP / MAGZPERR / TRANSPAR back into the FITS',
    'Submit to the TNS sandbox instead of production (no public record).',
    'Target/comparison tracking and live light curves',
    'Track atmospheric transparency over time',
    'Transient Name Server (TNS)',
    'Transparency and extinction',
    'Use TNS sandbox',
    'Used for limiting magnitude calculations (default 3.5)',
    'White level used to reject saturated stars from',
    'Write science keywords to FITS',
    'Written into MPC ADES headers and the TNS reporter',
    'Your TNS bot id (tns_marker tns_id).',
    'Your TNS bot name (tns_marker name).',
    'Your TNS discovery_data_source_id.',
    'Your TNS reporting_group_id.',
  ],
  'sequencer': [
    'Append per-filter flats when the active',
    'Auto Focus',
    'Auto focus every N frames',
    'Auto focus interval',
    'Auto focus on filter change',
    'Autofocus cadence (frames)',
    'Automatically park mount before astronomical dawn',
    'Automatically park mount when weather becomes unsafe',
    'Average is fastest; Median + Rejection and Sigma',
    'Dashboard auto-prompt',
    'Default broadcast port',
    'Default per-target imaging budget the wizard uses.',
    'Default stack method',
    'Default thumbnail size',
    'Default watermark template',
    'Delay after tracking limit detected (0 = flip immediately)',
    'Development',
    'Disable broadcast everywhere',
    'Dither every',
    'Dithering',
    'Enable dithering',
    'Flip after target crosses meridian by this amount',
    'Flip before mount reaches tracking limit',
    'Flip when hour angle exceeds this value',
    'Hour angle threshold',
    'How many exposures between autofocus runs',
    'If the last polar alignment is older than',
    'Include flats at end',
    'Integration budget per target',
    'Live Stacking & Broadcast',
    'Master kill switch — every LiveStacking node will',
    'Max retries',
    'Meridian Flip',
    'Minutes before limit',
    'Minutes past meridian',
    'Move mount slightly between exposures',
    'Notes & Journal',
    'Number of frames between dithers',
    'Number of retry attempts if flip fails',
    'Off → new nodes start with auth required. Turn on',
    'On failure',
    'Output dimensions for the broadcast JPEG. Smaller',
    'Park before dawn',
    'Park on unsafe weather',
    'Pause guiding before flip',
    'Plate solve and re-center target after flip',
    'Play sound when flip starts/completes/fails',
    'Polar alignment stale after',
    'Port used by newly-created LiveStacking nodes.',
    'Prompt for notes after run',
    'Public by default',
    'Push notification',
    'Recenter after flip',
    'Refocus after flip',
    'Rendered on the broadcast JPEG. Variable interpolation',
    'Restart autoguider if it was running',
    'Resume guiding after flip',
    'Run auto focus periodically',
    'Run auto focus when switching filters',
    'Run autofocus after flip completes',
    'Run autofocus every N completed exposures (frames-based)',
    'Safety',
    'Safety fail mode',
    'Scheduler for multi-target nights',
    'Scheduler threshold (targets)',
    'Send notification to mobile app',
    'Sequencer',
    'Settle time',
    'Show a quick journal-entry dialog when a sequence',
    'Show the Smart Night prompt on the dashboard',
    'Simulation mode',
    'Smart Night Defaults',
    'Sound alert',
    'Standalone monitoring',
    'Temporarily stop autoguider during flip',
    'Trigger method',
    'Use simulated devices instead of real hardware',
    'Use the scheduler when target count reaches this',
    'Wait before flip',
    'Wait time after flip before resuming',
    'Wrap multi-target plans in a TargetScheduler so',
  ],
  'updates': [
    'Appliance Updates',
    'Roll back this rig?',
  ],
  'weather-safety': [
    'Alert distance',
    'Alert Timing',
    'Auto-park mount',
    'Auto-resume after clear',
    'Enable weather safety',
    'Generate radar alerts within this distance of your site',
    'Hardware Thresholds',
    'Lead time',
    'Max cloud cover',
    'Max humidity',
    'Max wind speed',
    'Park automatically when the safety monitor trips',
    'Pause imaging when unsafe weather is detected',
    'Pause when cloud cover exceeds this amount',
    'Pause when sensor humidity exceeds this value',
    'Pause when wind exceeds this speed',
    'Resume once all weather sources return safe',
    'Safety Actions',
    'Warn this many minutes before weather reaches the site',
    'Weather Safety',
  ],
};
