part of '../star_catalog.dart';

/// Convert constellation name to genitive form (for Bayer designations)
String _getConstellationGenitive(String constellation) {
  return _constellationGenitives[constellation.toUpperCase()] ?? constellation;
}

const Map<String, String> _constellationGenitives = {
  'AND': 'Andromedae',
  'ANT': 'Antliae',
  'APS': 'Apodis',
  'AQR': 'Aquarii',
  'AQL': 'Aquilae',
  'ARA': 'Arae',
  'ARI': 'Arietis',
  'AUR': 'Aurigae',
  'BOO': 'Bootis',
  'CAE': 'Caeli',
  'CAM': 'Camelopardalis',
  'CNC': 'Cancri',
  'CVN': 'Canum Venaticorum',
  'CMA': 'Canis Majoris',
  'CMI': 'Canis Minoris',
  'CAP': 'Capricorni',
  'CAR': 'Carinae',
  'CAS': 'Cassiopeiae',
  'CEN': 'Centauri',
  'CEP': 'Cephei',
  'CET': 'Ceti',
  'CHA': 'Chamaeleontis',
  'CIR': 'Circini',
  'COL': 'Columbae',
  'COM': 'Comae Berenices',
  'CRA': 'Coronae Australis',
  'CRB': 'Coronae Borealis',
  'CRV': 'Corvi',
  'CRT': 'Crateris',
  'CRU': 'Crucis',
  'CYG': 'Cygni',
  'DEL': 'Delphini',
  'DOR': 'Doradus',
  'DRA': 'Draconis',
  'EQU': 'Equulei',
  'ERI': 'Eridani',
  'FOR': 'Fornacis',
  'GEM': 'Geminorum',
  'GRU': 'Gruis',
  'HER': 'Herculis',
  'HOR': 'Horologii',
  'HYA': 'Hydrae',
  'HYI': 'Hydri',
  'IND': 'Indi',
  'LAC': 'Lacertae',
  'LEO': 'Leonis',
  'LMI': 'Leonis Minoris',
  'LEP': 'Leporis',
  'LIB': 'Librae',
  'LUP': 'Lupi',
  'LYN': 'Lyncis',
  'LYR': 'Lyrae',
  'MEN': 'Mensae',
  'MIC': 'Microscopii',
  'MON': 'Monocerotis',
  'MUS': 'Muscae',
  'NOR': 'Normae',
  'OCT': 'Octantis',
  'OPH': 'Ophiuchi',
  'ORI': 'Orionis',
  'PAV': 'Pavonis',
  'PEG': 'Pegasi',
  'PER': 'Persei',
  'PHE': 'Phoenicis',
  'PIC': 'Pictoris',
  'PSC': 'Piscium',
  'PSA': 'Piscis Austrini',
  'PUP': 'Puppis',
  'PYX': 'Pyxidis',
  'RET': 'Reticuli',
  'SGE': 'Sagittae',
  'SGR': 'Sagittarii',
  'SCO': 'Scorpii',
  'SCL': 'Sculptoris',
  'SCT': 'Scuti',
  'SER': 'Serpentis',
  'SEX': 'Sextantis',
  'TAU': 'Tauri',
  'TEL': 'Telescopii',
  'TRA': 'Trianguli Australis',
  'TRI': 'Trianguli',
  'TUC': 'Tucanae',
  'UMA': 'Ursae Majoris',
  'UMI': 'Ursae Minoris',
  'VEL': 'Velorum',
  'VIR': 'Virginis',
  'VOL': 'Volantis',
  'VUL': 'Vulpeculae',
};
