part of '../star_catalog.dart';

/// Fallback bright stars when catalog is not installed
/// Contains ~100 brightest/most important stars for basic functionality
final List<Star> _fallbackBrightStars = [
  // Magnitude < 0
  const Star(
    id: 'HIP32349',
    name: 'Sirius',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 101.286,
      decDegrees: -16.7161,
    ),
    magnitude: -1.46,
    spectralType: 'A1V',
    constellation: 'CMA',
  ),
  const Star(
    id: 'HIP30438',
    name: 'Canopus',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 95.985,
      decDegrees: -52.6957,
    ),
    magnitude: -0.72,
    spectralType: 'F0II',
    constellation: 'CAR',
  ),
  const Star(
    id: 'HIP71683',
    name: 'Rigil Kentaurus',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 219.899,
      decDegrees: -60.8354,
    ),
    magnitude: -0.29,
    spectralType: 'G2V',
    constellation: 'CEN',
  ),
  const Star(
    id: 'HIP69673',
    name: 'Arcturus',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 213.918,
      decDegrees: 19.1825,
    ),
    magnitude: -0.05,
    spectralType: 'K1.5III',
    constellation: 'BOO',
  ),

  // Magnitude 0-1
  const Star(
    id: 'HIP91262',
    name: 'Vega',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 279.234,
      decDegrees: 38.7837,
    ),
    magnitude: 0.03,
    spectralType: 'A0V',
    constellation: 'LYR',
  ),
  const Star(
    id: 'HIP24608',
    name: 'Capella',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 79.176,
      decDegrees: 45.9980,
    ),
    magnitude: 0.08,
    spectralType: 'G8III',
    constellation: 'AUR',
  ),
  const Star(
    id: 'HIP24436',
    name: 'Rigel',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 78.633,
      decDegrees: -8.2017,
    ),
    magnitude: 0.13,
    spectralType: 'B8Ia',
    constellation: 'ORI',
  ),
  const Star(
    id: 'HIP37279',
    name: 'Procyon',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 114.828,
      decDegrees: 5.2250,
    ),
    magnitude: 0.34,
    spectralType: 'F5IV',
    constellation: 'CMI',
  ),
  const Star(
    id: 'HIP27989',
    name: 'Betelgeuse',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 88.793,
      decDegrees: 7.4070,
    ),
    magnitude: 0.42,
    spectralType: 'M2Ib',
    constellation: 'ORI',
  ),
  const Star(
    id: 'HIP7588',
    name: 'Achernar',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 24.428,
      decDegrees: -57.2367,
    ),
    magnitude: 0.46,
    spectralType: 'B3V',
    constellation: 'ERI',
  ),
  const Star(
    id: 'HIP80763',
    name: 'Hadar',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 210.956,
      decDegrees: -60.3730,
    ),
    magnitude: 0.60,
    spectralType: 'B1III',
    constellation: 'CEN',
  ),
  const Star(
    id: 'HIP97649',
    name: 'Altair',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 297.696,
      decDegrees: 8.8683,
    ),
    magnitude: 0.77,
    spectralType: 'A7V',
    constellation: 'AQL',
  ),
  const Star(
    id: 'HIP60718',
    name: 'Acrux',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 186.650,
      decDegrees: -63.0990,
    ),
    magnitude: 0.76,
    spectralType: 'B0.5IV',
    constellation: 'CRU',
  ),
  const Star(
    id: 'HIP21421',
    name: 'Aldebaran',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 68.982,
      decDegrees: 16.5093,
    ),
    magnitude: 0.85,
    spectralType: 'K5III',
    constellation: 'TAU',
  ),
  const Star(
    id: 'HIP80763',
    name: 'Antares',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 247.352,
      decDegrees: -26.4320,
    ),
    magnitude: 1.06,
    spectralType: 'M1.5Ib',
    constellation: 'SCO',
  ),
  const Star(
    id: 'HIP65474',
    name: 'Spica',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 201.298,
      decDegrees: -11.1614,
    ),
    magnitude: 0.97,
    spectralType: 'B1V',
    constellation: 'VIR',
  ),
  const Star(
    id: 'HIP37826',
    name: 'Pollux',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 116.330,
      decDegrees: 28.0262,
    ),
    magnitude: 1.14,
    spectralType: 'K0III',
    constellation: 'GEM',
  ),
  const Star(
    id: 'HIP102098',
    name: 'Fomalhaut',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 344.412,
      decDegrees: -29.6223,
    ),
    magnitude: 1.16,
    spectralType: 'A3V',
    constellation: 'PSA',
  ),
  const Star(
    id: 'HIP102488',
    name: 'Deneb',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 310.358,
      decDegrees: 45.2803,
    ),
    magnitude: 1.25,
    spectralType: 'A2Ia',
    constellation: 'CYG',
  ),
  const Star(
    id: 'HIP62434',
    name: 'Mimosa',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 191.930,
      decDegrees: -59.6888,
    ),
    magnitude: 1.25,
    spectralType: 'B0.5IV',
    constellation: 'CRU',
  ),
  const Star(
    id: 'HIP54061',
    name: 'Regulus',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 152.093,
      decDegrees: 11.9672,
    ),
    magnitude: 1.40,
    spectralType: 'B8IV',
    constellation: 'LEO',
  ),
  const Star(
    id: 'HIP31592',
    name: 'Adhara',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 104.656,
      decDegrees: -28.9722,
    ),
    magnitude: 1.50,
    spectralType: 'B2II',
    constellation: 'CMA',
  ),
  const Star(
    id: 'HIP36850',
    name: 'Castor',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 113.650,
      decDegrees: 31.8884,
    ),
    magnitude: 1.58,
    spectralType: 'A1V',
    constellation: 'GEM',
  ),
  const Star(
    id: 'HIP78820',
    name: 'Shaula',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 263.402,
      decDegrees: -37.1038,
    ),
    magnitude: 1.63,
    spectralType: 'B2IV',
    constellation: 'SCO',
  ),
  const Star(
    id: 'HIP63003',
    name: 'Gacrux',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 187.791,
      decDegrees: -57.1132,
    ),
    magnitude: 1.64,
    spectralType: 'M3.5III',
    constellation: 'CRU',
  ),
  const Star(
    id: 'HIP41037',
    name: 'Miaplacidus',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 138.300,
      decDegrees: -69.7172,
    ),
    magnitude: 1.68,
    spectralType: 'A1III',
    constellation: 'CAR',
  ),
  const Star(
    id: 'HIP25336',
    name: 'Bellatrix',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 81.282,
      decDegrees: 6.3497,
    ),
    magnitude: 1.64,
    spectralType: 'B2III',
    constellation: 'ORI',
  ),
  const Star(
    id: 'HIP27366',
    name: 'Elnath',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 81.573,
      decDegrees: 28.6074,
    ),
    magnitude: 1.65,
    spectralType: 'B7III',
    constellation: 'TAU',
  ),
  const Star(
    id: 'HIP26311',
    name: 'Alnilam',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 84.054,
      decDegrees: -1.2019,
    ),
    magnitude: 1.70,
    spectralType: 'B0Ia',
    constellation: 'ORI',
  ),

  // Important navigation and constellation stars
  const Star(
    id: 'HIP11767',
    name: 'Polaris',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 37.953,
      decDegrees: 89.2641,
    ),
    magnitude: 1.98,
    spectralType: 'F7Ib',
    constellation: 'UMI',
  ),
  const Star(
    id: 'HIP26727',
    name: 'Alnitak',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 85.190,
      decDegrees: -1.9426,
    ),
    magnitude: 1.77,
    spectralType: 'O9.7Ib',
    constellation: 'ORI',
  ),
  const Star(
    id: 'HIP15863',
    name: 'Mirfak',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 51.081,
      decDegrees: 49.8612,
    ),
    magnitude: 1.79,
    spectralType: 'F5Ib',
    constellation: 'PER',
  ),
  const Star(
    id: 'HIP59774',
    name: 'Dubhe',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 165.932,
      decDegrees: 61.7510,
    ),
    magnitude: 1.79,
    spectralType: 'K0III',
    constellation: 'UMA',
  ),
  const Star(
    id: 'HIP90185',
    name: 'Kaus Australis',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 276.044,
      decDegrees: -34.3847,
    ),
    magnitude: 1.80,
    spectralType: 'B9.5III',
    constellation: 'SGR',
  ),
  const Star(
    id: 'HIP65378',
    name: 'Alioth',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 193.506,
      decDegrees: 55.9598,
    ),
    magnitude: 1.77,
    spectralType: 'A0p',
    constellation: 'UMA',
  ),
  const Star(
    id: 'HIP62956',
    name: 'Alkaid',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 206.885,
      decDegrees: 49.3133,
    ),
    magnitude: 1.86,
    spectralType: 'B3V',
    constellation: 'UMA',
  ),
  const Star(
    id: 'HIP31681',
    name: 'Alhena',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 99.428,
      decDegrees: 16.3993,
    ),
    magnitude: 1.93,
    spectralType: 'A0IV',
    constellation: 'GEM',
  ),
  const Star(
    id: 'HIP82273',
    name: 'Atria',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 252.164,
      decDegrees: -69.0277,
    ),
    magnitude: 1.92,
    spectralType: 'K2IIb',
    constellation: 'TRA',
  ),
  const Star(
    id: 'HIP46390',
    name: 'Alphard',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 141.896,
      decDegrees: -8.6586,
    ),
    magnitude: 1.98,
    spectralType: 'K3III',
    constellation: 'HYA',
  ),
  const Star(
    id: 'HIP9884',
    name: 'Hamal',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 31.794,
      decDegrees: 23.4624,
    ),
    magnitude: 2.00,
    spectralType: 'K2III',
    constellation: 'ARI',
  ),
  const Star(
    id: 'HIP14135',
    name: 'Diphda',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 10.898,
      decDegrees: -17.9866,
    ),
    magnitude: 2.02,
    spectralType: 'K0III',
    constellation: 'CET',
  ),
  const Star(
    id: 'HIP89931',
    name: 'Nunki',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 283.816,
      decDegrees: -26.2967,
    ),
    magnitude: 2.02,
    spectralType: 'B2.5V',
    constellation: 'SGR',
  ),
  const Star(
    id: 'HIP677',
    name: 'Alpheratz',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 2.097,
      decDegrees: 29.0904,
    ),
    magnitude: 2.06,
    spectralType: 'B9p',
    constellation: 'AND',
  ),
  const Star(
    id: 'HIP1067',
    name: 'Mirach',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 17.432,
      decDegrees: 35.6206,
    ),
    magnitude: 2.06,
    spectralType: 'M0III',
    constellation: 'AND',
  ),
  const Star(
    id: 'HIP86032',
    name: 'Rasalhague',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 263.735,
      decDegrees: 12.5600,
    ),
    magnitude: 2.07,
    spectralType: 'A5III',
    constellation: 'OPH',
  ),
  const Star(
    id: 'HIP14576',
    name: 'Algol',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 47.046,
      decDegrees: 40.9557,
    ),
    magnitude: 2.12,
    spectralType: 'B8V',
    constellation: 'PER',
  ),
  const Star(
    id: 'HIP49669',
    name: 'Denebola',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 177.266,
      decDegrees: 14.5720,
    ),
    magnitude: 2.13,
    spectralType: 'A3V',
    constellation: 'LEO',
  ),
  const Star(
    id: 'HIP44816',
    name: 'Suhail',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 137.000,
      decDegrees: -43.4326,
    ),
    magnitude: 2.21,
    spectralType: 'K4Ib',
    constellation: 'VEL',
  ),
  const Star(
    id: 'HIP3419',
    name: 'Schedar',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 10.128,
      decDegrees: 56.5373,
    ),
    magnitude: 2.23,
    spectralType: 'K0II',
    constellation: 'CAS',
  ),
  const Star(
    id: 'HIP76267',
    name: 'Alphecca',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 233.673,
      decDegrees: 26.7147,
    ),
    magnitude: 2.23,
    spectralType: 'A0V',
    constellation: 'CRB',
  ),
  const Star(
    id: 'HIP87833',
    name: 'Eltanin',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 269.150,
      decDegrees: 51.4889,
    ),
    magnitude: 2.23,
    spectralType: 'K5III',
    constellation: 'DRA',
  ),
  const Star(
    id: 'HIP25930',
    name: 'Mintaka',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 83.002,
      decDegrees: -0.2991,
    ),
    magnitude: 2.23,
    spectralType: 'O9.5II',
    constellation: 'ORI',
  ),
  const Star(
    id: 'HIP5447',
    name: 'Almach',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 30.975,
      decDegrees: 42.3297,
    ),
    magnitude: 2.26,
    spectralType: 'K3II',
    constellation: 'AND',
  ),
  const Star(
    id: 'HIP39757',
    name: 'Naos',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 120.891,
      decDegrees: -40.0033,
    ),
    magnitude: 2.25,
    spectralType: 'O5If',
    constellation: 'PUP',
  ),
  const Star(
    id: 'HIP67301',
    name: 'Mizar',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 200.982,
      decDegrees: 54.9254,
    ),
    magnitude: 2.27,
    spectralType: 'A1V',
    constellation: 'UMA',
  ),
  const Star(
    id: 'HIP4427',
    name: 'Caph',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 2.295,
      decDegrees: 59.1498,
    ),
    magnitude: 2.27,
    spectralType: 'F2III',
    constellation: 'CAS',
  ),
  const Star(
    id: 'HIP53910',
    name: 'Merak',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 165.459,
      decDegrees: 56.3824,
    ),
    magnitude: 2.37,
    spectralType: 'A1V',
    constellation: 'UMA',
  ),
  const Star(
    id: 'HIP113368',
    name: 'Scheat',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 345.944,
      decDegrees: 28.0828,
    ),
    magnitude: 2.42,
    spectralType: 'M2.5II',
    constellation: 'PEG',
  ),
  const Star(
    id: 'HIP58001',
    name: 'Phecda',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 178.452,
      decDegrees: 53.6948,
    ),
    magnitude: 2.44,
    spectralType: 'A0V',
    constellation: 'UMA',
  ),
  const Star(
    id: 'HIP105199',
    name: 'Alderamin',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 319.644,
      decDegrees: 62.5856,
    ),
    magnitude: 2.44,
    spectralType: 'A7IV',
    constellation: 'CEP',
  ),
  const Star(
    id: 'HIP8886',
    name: 'Navi',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 14.180,
      decDegrees: 60.7167,
    ),
    magnitude: 2.47,
    spectralType: 'B0IV',
    constellation: 'CAS',
  ),
  const Star(
    id: 'HIP113881',
    name: 'Markab',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 346.197,
      decDegrees: 15.2053,
    ),
    magnitude: 2.49,
    spectralType: 'A0IV',
    constellation: 'PEG',
  ),
  const Star(
    id: 'HIP8645',
    name: 'Menkar',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 45.573,
      decDegrees: 4.0897,
    ),
    magnitude: 2.53,
    spectralType: 'M1.5III',
    constellation: 'CET',
  ),
  const Star(
    id: 'HIP88635',
    name: 'Ascella',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 285.656,
      decDegrees: -29.8801,
    ),
    magnitude: 2.59,
    spectralType: 'A2IV',
    constellation: 'SGR',
  ),
  const Star(
    id: 'HIP61084',
    name: 'Gienah',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 183.951,
      decDegrees: -17.5419,
    ),
    magnitude: 2.59,
    spectralType: 'B8III',
    constellation: 'CRV',
  ),
  const Star(
    id: 'HIP8903',
    name: 'Sheratan',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 28.659,
      decDegrees: 20.8080,
    ),
    magnitude: 2.64,
    spectralType: 'A5V',
    constellation: 'ARI',
  ),
  const Star(
    id: 'HIP77070',
    name: 'Unukalhai',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 236.065,
      decDegrees: 6.4256,
    ),
    magnitude: 2.65,
    spectralType: 'K2III',
    constellation: 'SER',
  ),
  const Star(
    id: 'HIP746',
    name: 'Ruchbah',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 21.459,
      decDegrees: 60.2352,
    ),
    magnitude: 2.68,
    spectralType: 'A5IV',
    constellation: 'CAS',
  ),
  const Star(
    id: 'HIP59747',
    name: 'Imai',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 183.786,
      decDegrees: -58.7489,
    ),
    magnitude: 2.77,
    spectralType: 'B2IV',
    constellation: 'CRU',
  ),
  const Star(
    id: 'HIP84345',
    name: 'Kornephoros',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 247.557,
      decDegrees: 21.4897,
    ),
    magnitude: 2.77,
    spectralType: 'G7IIIa',
    constellation: 'HER',
  ),
  const Star(
    id: 'HIP83207',
    name: 'Rasalgethi',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 258.662,
      decDegrees: 14.3902,
    ),
    magnitude: 2.81,
    spectralType: 'M5Ib',
    constellation: 'HER',
  ),
  const Star(
    id: 'HIP112158',
    name: 'Algenib',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 3.302,
      decDegrees: 15.1836,
    ),
    magnitude: 2.83,
    spectralType: 'B2IV',
    constellation: 'PEG',
  ),
  const Star(
    id: 'HIP109074',
    name: 'Sadalsuud',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 322.890,
      decDegrees: -5.5712,
    ),
    magnitude: 2.91,
    spectralType: 'G0Ib',
    constellation: 'AQR',
  ),
  const Star(
    id: 'HIP109139',
    name: 'Sadalmelik',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 331.446,
      decDegrees: -0.3199,
    ),
    magnitude: 2.96,
    spectralType: 'G2Ib',
    constellation: 'AQR',
  ),
  const Star(
    id: 'HIP10826',
    name: 'Mira',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 34.838,
      decDegrees: -2.9776,
    ),
    magnitude: 3.04,
    spectralType: 'M7IIIe',
    constellation: 'CET',
  ),
  const Star(
    id: 'HIP107315',
    name: 'Albireo',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 292.680,
      decDegrees: 27.9597,
    ),
    magnitude: 3.18,
    spectralType: 'K3II',
    constellation: 'CYG',
  ),
  const Star(
    id: 'HIP59774',
    name: 'Megrez',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 183.857,
      decDegrees: 57.0326,
    ),
    magnitude: 3.31,
    spectralType: 'A3V',
    constellation: 'UMA',
  ),
  const Star(
    id: 'HIP6686',
    name: 'Segin',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 28.598,
      decDegrees: 63.6700,
    ),
    magnitude: 3.37,
    spectralType: 'B3III',
    constellation: 'CAS',
  ),
  const Star(
    id: 'HIP9487',
    name: 'Eta Piscium',
    coordinates: CelestialCoordinate.fromDegrees(
      raDegrees: 22.880,
      decDegrees: 15.3458,
    ),
    magnitude: 3.62,
    spectralType: 'G7III',
    constellation: 'PSC',
  ),
];
