import 'dart:async';
import 'dart:math' as math;

import 'package:uuid/uuid.dart';

import '../../models/scheduler/integration_goal.dart';
import '../../models/scheduler/scheduler_decision.dart';
import '../../models/scheduler/scheduler_status.dart';
import '../../models/scheduler/target_constraint.dart';
import '../../models/sequence/sequence_models.dart';
import 'horizon_profile.dart';

/// Snapshot of a candidate target plus the live data the engine needs to
/// score it. The engine doesn't read the Targets DAO directly; the caller
/// (provider layer) builds this from drift rows so the engine remains
/// database-agnostic and easily unit-testable.
class SchedulerCandidate {
  /// Drift `targets.id`.
  final int targetId;
  final String name;
  final double raHours;
  final double decDegrees;

  /// User-set priority on the target row (higher = better).
  final int userPriority;

  /// Integration goals attached to this target.
  final List<IntegrationGoal> goals;

  /// Per-(goal) captured-frame counts, in the same order as `goals`.
  /// Length must match `goals.length`.
  final List<int> capturedCounts;

  /// Hard constraints attached to this target.
  final List<TargetConstraint> constraints;

  /// Resolved horizon profiles keyed by HorizonProfiles.id, for any
  /// constraint referencing one. May be empty if none used.
  final Map<int, HorizonProfile> horizonProfiles;

  /// Filters available in the current equipment profile (case-preserved).
  /// A target needing a filter not in this list fails the equipment
  /// availability hard constraint.
  final List<String> availableFilters;

  SchedulerCandidate({
    required this.targetId,
    required this.name,
    required this.raHours,
    required this.decDegrees,
    required this.userPriority,
    required this.goals,
    required this.capturedCounts,
    required this.constraints,
    required this.horizonProfiles,
    required this.availableFilters,
  }) {
    if (capturedCounts.length != goals.length) {
      throw ArgumentError(
        'capturedCounts length (${capturedCounts.length}) must match goals length (${goals.length})',
      );
    }
  }
}

/// Site location used for altitude/azimuth and twilight math.
class SchedulerSite {
  final double latitudeDegrees;
  final double longitudeDegrees;

  /// User's local-timezone offset used to evaluate timeWindow constraints
  /// in the operator's clock rather than UTC.
  final Duration localOffset;

  const SchedulerSite({
    required this.latitudeDegrees,
    required this.longitudeDegrees,
    required this.localOffset,
  });
}

/// Sink for sequences generated by the engine. Concrete implementations
/// hand off to `SequencerService.startSequence(...)` or the
/// `SequenceExecutor.start()` provider. Tests inject a fake.
abstract class SchedulerSequenceSink {
  /// Called when the engine has selected a target and wants to start
  /// imaging. Implementations must persist or load the sequence and start
  /// it; the future completes once the sequencer accepts the sequence.
  Future<void> dispatchSequence(Sequence sequence);

  /// Called when the engine wants to pause whatever is currently running.
  Future<void> pauseSequence();

  /// Called when the engine wants to resume from pause.
  Future<void> resumeSequence();

  /// Called when the engine wants to stop the active sequence (e.g. on
  /// engine stop or a hard target swap).
  Future<void> stopSequence();
}

/// The dynamic RoboTarget-class scheduler.
///
/// Pure-logic core. Wiring to Riverpod, the database, and the sequencer
/// lives in `providers/scheduler_provider.dart`. The engine owns:
///   * a periodic timer (the tick loop)
///   * a single re-evaluation lock so concurrent triggers don't interleave
///   * a `SchedulerStatus` stream (for the UI status panel)
///   * a `SchedulerDecision` stream (each tick emits the full breakdown)
class SchedulerEngine {
  SchedulerEngine({
    required SchedulerSite site,
    required SchedulerSequenceSink sequenceSink,
    SchedulerConfig config = SchedulerConfig.defaults,
    Future<List<SchedulerCandidate>> Function()? candidateLoader,
    Stream<SchedulerTriggerEvent>? triggerStream,
    DateTime Function()? clock,
  })  : _config = config,
        _sequenceSink = sequenceSink,
        _site = site,
        _candidateLoader = candidateLoader ?? (() async => const []),
        _clock = clock ?? DateTime.now {
    if (triggerStream != null) {
      _triggerSubscription = triggerStream.listen((evt) {
        _evaluateWithReason('trigger: ${evt.name}');
      });
    }
  }

  SchedulerConfig _config;
  SchedulerSite _site;
  final SchedulerSequenceSink _sequenceSink;
  Future<List<SchedulerCandidate>> Function() _candidateLoader;
  final DateTime Function() _clock;
  StreamSubscription<SchedulerTriggerEvent>? _triggerSubscription;
  Timer? _tickTimer;
  bool _evaluating = false;
  final List<Completer<void>> _pendingEvaluations = [];
  // Debounce window used by [requestReevaluation]. A burst of provider
  // emissions (e.g. a goal upsert that also touches the constraint table)
  // should fire ONE re-evaluation, not N.
  static const Duration _reevaluationDebounce = Duration(milliseconds: 500);
  Timer? _reevaluationDebounceTimer;

  SchedulerStatus _status = const SchedulerStatus();
  final _statusController =
      StreamController<SchedulerStatus>.broadcast(sync: false);
  final _decisionController =
      StreamController<SchedulerDecision>.broadcast(sync: false);
  SchedulerDecision? _lastDecision;

  SchedulerStatus get status => _status;
  SchedulerDecision? get lastDecision => _lastDecision;
  SchedulerConfig get config => _config;
  SchedulerSite get site => _site;
  Stream<SchedulerStatus> get statusStream => _statusController.stream;
  Stream<SchedulerDecision> get decisionStream => _decisionController.stream;

  void updateConfig(SchedulerConfig config) {
    _config = config;
    if (_status.state == SchedulerState.running) {
      _restartTimer();
    }
  }

  void updateSite(SchedulerSite site) {
    _site = site;
  }

  void setCandidateLoader(
      Future<List<SchedulerCandidate>> Function() loader) {
    _candidateLoader = loader;
  }

  Future<void> start() async {
    if (_status.state == SchedulerState.running) return;
    _updateStatus(_status.copyWith(
      state: SchedulerState.running,
      clearError: true,
      nextEvaluationAt: _clock().add(_config.tickInterval),
    ));
    _restartTimer();
    await _evaluateWithReason('engine start');
  }

  Future<void> pause() async {
    if (_status.state != SchedulerState.running) return;
    _tickTimer?.cancel();
    _tickTimer = null;
    _updateStatus(_status.copyWith(
      state: SchedulerState.paused,
      clearNextEvaluation: true,
    ));
    await _sequenceSink.pauseSequence();
  }

  Future<void> resume() async {
    if (_status.state != SchedulerState.paused) return;
    _updateStatus(_status.copyWith(
      state: SchedulerState.running,
      nextEvaluationAt: _clock().add(_config.tickInterval),
    ));
    await _sequenceSink.resumeSequence();
    _restartTimer();
    await _evaluateWithReason('engine resume');
  }

  Future<void> stop() async {
    _tickTimer?.cancel();
    _tickTimer = null;
    _updateStatus(_status.copyWith(
      state: SchedulerState.idle,
      clearCurrentTarget: true,
      clearNextEvaluation: true,
    ));
    await _sequenceSink.stopSequence();
  }

  /// Trigger an immediate re-evaluation. Returns when the evaluation
  /// (including any queued evaluations behind it) has completed.
  Future<void> evaluateNow({String reason = 'manual'}) {
    return _evaluateWithReason(reason);
  }

  /// Debounced re-evaluation hook for data-change listeners (target catalog,
  /// integration goals, constraints). Multiple calls inside the
  /// [_reevaluationDebounce] window coalesce into a single evaluation.
  void requestReevaluation({String reason = 'data change'}) {
    _reevaluationDebounceTimer?.cancel();
    _reevaluationDebounceTimer = Timer(_reevaluationDebounce, () {
      _reevaluationDebounceTimer = null;
      // Errors must propagate to the engine's lifecycle so we don't
      // swallow background re-eval failures (silent fallbacks hide bugs);
      // _evaluateWithReason already serializes via the same lock the tick
      // timer uses, so this is safe to fire-and-forget.
      _evaluateWithReason(reason);
    });
  }

  Future<void> dispose() async {
    _tickTimer?.cancel();
    _reevaluationDebounceTimer?.cancel();
    _reevaluationDebounceTimer = null;
    await _triggerSubscription?.cancel();
    await _statusController.close();
    await _decisionController.close();
  }

  void _restartTimer() {
    _tickTimer?.cancel();
    _tickTimer = Timer.periodic(_config.tickInterval, (_) {
      _updateStatus(_status.copyWith(
        nextEvaluationAt: _clock().add(_config.tickInterval),
      ));
      _evaluateWithReason('tick');
    });
  }

  Future<void> _evaluateWithReason(String reason) async {
    if (_evaluating) {
      // Queue this caller; they'll be released after the in-flight
      // evaluation finishes. This serializes evaluations without dropping
      // a triggering event.
      final c = Completer<void>();
      _pendingEvaluations.add(c);
      return c.future;
    }
    _evaluating = true;
    try {
      await _evaluateOnce(reason);
    } finally {
      _evaluating = false;
      if (_pendingEvaluations.isNotEmpty) {
        final next = _pendingEvaluations.removeAt(0);
        // Run the next evaluation in a microtask so the completer for the
        // current caller resolves first.
        scheduleMicrotask(() async {
          try {
            await _evaluateWithReason('coalesced');
            next.complete();
          } catch (e, st) {
            next.completeError(e, st);
          }
        });
      }
    }
  }

  Future<void> _evaluateOnce(String reason) async {
    final now = _clock();
    final candidates = await _candidateLoader();
    if (candidates.isEmpty) {
      final decision = SchedulerDecision(
        chosenTargetId: null,
        chosenTargetName: null,
        score: 0,
        reasoning: const ['No candidate targets available'],
        scoredCandidates: const [],
        rejected: const [],
        evaluatedAt: now,
        isSwitch: _status.currentTargetId != null,
      );
      _publishDecision(decision);
      if (_status.currentTargetId != null) {
        _updateStatus(_status.copyWith(clearCurrentTarget: true));
        if (_status.state == SchedulerState.running) {
          await _sequenceSink.stopSequence();
        }
      }
      return;
    }

    final scored = <TargetScore>[];
    // Tracks which candidates fall inside an active scheduledWindow at
    // this tick. The first such target (preferring the higher base score
    // when multiple overlap) wins regardless of hysteresis.
    final scheduledWindowHits = <int>{};
    for (final c in candidates) {
      scored.add(_scoreCandidate(c, now));
      if (_hasActiveScheduledWindow(c, now)) {
        scheduledWindowHits.add(c.targetId);
      }
    }

    final eligible = scored.where((s) => !s.hardConstraintFailed).toList();
    eligible.sort((a, b) => b.totalScore.compareTo(a.totalScore));

    if (eligible.isEmpty) {
      final reasons = <String>[
        'No eligible candidates at ${now.toIso8601String()} ($reason)',
        ...scored
            .where((s) => s.rejectionReasons.isNotEmpty)
            .take(3)
            .map((s) => '${s.targetName}: ${s.rejectionReasons.first}'),
      ];
      final rejectedAll = scored
          .map((s) => _buildRejection(
                s,
                chosenScore: 0,
                primaryReasonOverride:
                    s.hardConstraintFailed ? null : 'no eligible winner',
              ))
          .toList();
      final decision = SchedulerDecision(
        chosenTargetId: null,
        chosenTargetName: null,
        score: 0,
        reasoning: reasons,
        scoredCandidates: scored,
        rejected: rejectedAll,
        evaluatedAt: now,
        isSwitch: _status.currentTargetId != null,
      );
      _publishDecision(decision);
      if (_status.currentTargetId != null) {
        _updateStatus(_status.copyWith(clearCurrentTarget: true));
        if (_status.state == SchedulerState.running) {
          await _sequenceSink.stopSequence();
        }
      }
      return;
    }

    final challenger = eligible.first;
    final currentId = _status.currentTargetId;
    TargetScore winner;
    bool isSwitch;
    // True when the chosen target was forced by an active scheduled
    // window — the UI labels this distinctly ("Forced by scheduled
    // window …") and we skip hysteresis.
    bool forcedByScheduledWindow = false;

    // Scheduled-window override path: any eligible candidate that has an
    // active scheduledWindow constraint MUST be selected, bypassing
    // hysteresis. When multiple targets are inside their windows at the
    // same instant, the higher base score (already applied in scoring)
    // wins — eligible[0] is sorted by totalScore so the first eligible
    // entry whose id is in scheduledWindowHits is the right pick.
    TargetScore? forced;
    for (final s in eligible) {
      if (scheduledWindowHits.contains(s.targetId)) {
        forced = s;
        break;
      }
    }

    if (forced != null) {
      winner = forced;
      isSwitch = currentId != forced.targetId;
      forcedByScheduledWindow = true;
    } else if (currentId == null) {
      winner = challenger;
      isSwitch = true;
    } else {
      final currentEntry =
          eligible.where((s) => s.targetId == currentId).toList();
      if (currentEntry.isEmpty) {
        // Current target is no longer eligible: forced switch.
        winner = challenger;
        isSwitch = true;
      } else {
        final current = currentEntry.first;
        final ratio = current.totalScore > 0
            ? challenger.totalScore / current.totalScore
            : double.infinity;
        if (challenger.targetId == current.targetId) {
          winner = current;
          isSwitch = false;
        } else if (ratio >= _config.hysteresisRatio) {
          winner = challenger;
          isSwitch = true;
        } else {
          winner = current;
          isSwitch = false;
        }
      }
    }

    final reasoning = <String>[];
    reasoning.add(
        'Chose ${winner.targetName} (score ${winner.totalScore.toStringAsFixed(3)}) at ${now.toIso8601String()} ($reason)');
    for (final f in winner.factors) {
      reasoning.add(
          '  ${f.name}: value=${f.value.toStringAsFixed(3)} weight=${f.weight.toStringAsFixed(2)} -> ${f.weighted.toStringAsFixed(3)}${f.detail != null ? "  ${f.detail}" : ""}');
    }
    if (forcedByScheduledWindow) {
      reasoning.add(
          'Forced by scheduled window (hysteresis bypassed) on ${winner.targetName}');
    }
    if (eligible.length > 1) {
      final next = eligible.firstWhere(
        (s) => s.targetId != winner.targetId,
        orElse: () => eligible[1],
      );
      reasoning.add(
          'Runner-up: ${next.targetName} score ${next.totalScore.toStringAsFixed(3)}');
    }
    if (isSwitch && currentId != null && !forcedByScheduledWindow) {
      reasoning.add(
          'Switching from previous target id=$currentId (hysteresis ratio=${_config.hysteresisRatio.toStringAsFixed(2)} exceeded)');
    }

    final orderedAll = [
      ...eligible,
      ...scored.where((s) => s.hardConstraintFailed),
    ];

    final rejected = <RejectedCandidate>[];
    for (final s in orderedAll) {
      if (s.targetId == winner.targetId) continue;
      rejected.add(_buildRejection(s, chosenScore: winner.totalScore));
    }

    final decision = SchedulerDecision(
      chosenTargetId: winner.targetId,
      chosenTargetName: winner.targetName,
      score: winner.totalScore,
      reasoning: reasoning,
      scoredCandidates: orderedAll,
      rejected: rejected,
      evaluatedAt: now,
      isSwitch: isSwitch,
    );
    _publishDecision(decision);

    if (isSwitch) {
      _updateStatus(_status.copyWith(
        currentTargetId: winner.targetId,
        currentTargetName: winner.targetName,
      ));
      if (_status.state == SchedulerState.running) {
        final chosenCandidate =
            candidates.firstWhere((c) => c.targetId == winner.targetId);
        final seq = buildSequenceForCandidate(chosenCandidate);
        await _sequenceSink.dispatchSequence(seq);
      }
    }
  }

  /// Returns true if the candidate has an enabled scheduledWindow
  /// constraint whose absolute UTC range contains [now]. Caller uses this
  /// to bypass hysteresis and to surface the forced-selection state on
  /// the decision panel.
  bool _hasActiveScheduledWindow(SchedulerCandidate c, DateTime now) {
    for (final ct in c.constraints.where((x) => x.enabled)) {
      if (ct.kind != TargetConstraintKind.scheduledWindow) continue;
      final sw = ct.scheduledWindow;
      if (sw == null) continue;
      if (sw.containsUtc(now)) return true;
    }
    return false;
  }

  /// Build a [RejectedCandidate] entry that the UI will render under the
  /// "Other candidates considered" section. The reason text is derived
  /// from the same hard-constraint / soft-score logic that filtered them
  /// out of [_scoreCandidate].
  RejectedCandidate _buildRejection(
    TargetScore s, {
    required double chosenScore,
    String? primaryReasonOverride,
  }) {
    final String primary;
    if (primaryReasonOverride != null) {
      primary = primaryReasonOverride;
    } else if (s.hardConstraintFailed) {
      primary = _summarizeRejection(s.rejectionReasons);
    } else {
      // Eligible-but-lower-scoring. Expose the score gap as a percentage
      // so operators can sanity-check tight calls.
      if (chosenScore > 0) {
        final pct = (s.totalScore / chosenScore * 100).clamp(0, 999);
        primary =
            'lower score than chosen (${pct.toStringAsFixed(0)}% of winner)';
      } else {
        primary = 'lower score than chosen';
      }
    }
    return RejectedCandidate(
      targetId: s.targetId,
      targetName: s.targetName,
      score: s.totalScore,
      primaryReason: primary,
      hardConstraintFailures: List<String>.unmodifiable(s.rejectionReasons),
      factors: List<ScoreFactor>.unmodifiable(s.factors),
    );
  }

  /// Map the first per-constraint failure into a compact operator-facing
  /// chip. Falls back to the raw text when no shorter form fits.
  String _summarizeRejection(List<String> reasons) {
    if (reasons.isEmpty) return 'rejected';
    final first = reasons.first;
    if (first.contains('altitude') && first.contains('below site minimum')) {
      return 'below horizon';
    }
    if (first.contains('altitude') && first.contains('horizon profile')) {
      return 'behind custom horizon';
    }
    if (first.contains('moon illumination')) {
      return first; // already includes the "X% > Y%" detail
    }
    if (first.contains('outside time window')) {
      return first;
    }
    if (first.contains('filter')) {
      return 'required filter not in wheel';
    }
    if (first.contains('goals complete')) {
      return 'all integration goals complete';
    }
    return first;
  }

  /// Public so tests and the UI's "Preview" button can compute a decision
  /// without mutating state. Pass a pre-fetched candidate list.
  TargetScore scoreCandidate(SchedulerCandidate c, DateTime now) =>
      _scoreCandidate(c, now);

  TargetScore _scoreCandidate(SchedulerCandidate c, DateTime now) {
    final rejections = <String>[];

    // Altitude / azimuth.
    final (alt, az) = _calculateAltAz(
      raHours: c.raHours,
      decDegrees: c.decDegrees,
      time: now,
    );

    // Hard constraint: minimum altitude.
    if (alt < _config.minAltitudeDegrees) {
      rejections.add(
          'altitude ${alt.toStringAsFixed(1)}° below site minimum ${_config.minAltitudeDegrees.toStringAsFixed(1)}°');
    }

    // Hard constraint: equipment / filter availability.
    final remainingByGoal = <IntegrationGoalProgress>[];
    for (var i = 0; i < c.goals.length; i++) {
      remainingByGoal.add(IntegrationGoalProgress(
        goal: c.goals[i],
        capturedCount: c.capturedCounts[i],
      ));
    }
    final stillNeeded =
        remainingByGoal.where((p) => p.remainingFrames > 0).toList();
    if (stillNeeded.isEmpty && c.goals.isNotEmpty) {
      rejections.add('all integration goals complete');
    }
    final filtersOnEquipmentLower =
        c.availableFilters.map((f) => f.toLowerCase()).toSet();
    final hasUsableGoal = stillNeeded.isEmpty
        ? c.goals.isEmpty // no goals at all is fine - free-form imaging
        : stillNeeded.any((p) =>
            filtersOnEquipmentLower.contains(p.goal.filter.toLowerCase()));
    if (c.goals.isNotEmpty && !hasUsableGoal && stillNeeded.isNotEmpty) {
      rejections.add(
          'required filter(s) not in equipment wheel (${stillNeeded.map((p) => p.goal.filter).toSet().join(", ")})');
    }

    // Hard constraint: time-window / moon / horizon.
    final localTime = now.toUtc().add(_site.localOffset);
    double scheduledWindowBoost = 0.0;
    for (final ct in c.constraints.where((x) => x.enabled)) {
      switch (ct.kind) {
        case TargetConstraintKind.timeWindow:
          if (ct.timeWindow != null &&
              !ct.timeWindow!.containsLocal(localTime)) {
            rejections.add(
                'outside time window ${ct.timeWindow!.startMinutes ~/ 60}:${(ct.timeWindow!.startMinutes % 60).toString().padLeft(2, '0')}-${ct.timeWindow!.endMinutes ~/ 60}:${(ct.timeWindow!.endMinutes % 60).toString().padLeft(2, '0')}');
          }
          break;
        case TargetConstraintKind.moonIlluminationMax:
          final moon = _moonPosition(now);
          if (ct.moonIlluminationMax != null &&
              moon.illumination > ct.moonIlluminationMax!) {
            rejections.add(
                'moon illumination ${(moon.illumination * 100).toStringAsFixed(0)}% exceeds max ${(ct.moonIlluminationMax! * 100).toStringAsFixed(0)}%');
          }
          break;
        case TargetConstraintKind.customHorizon:
          final profile = c.horizonProfiles[ct.customHorizonId];
          if (profile == null) {
            rejections.add(
                'horizon profile ${ct.customHorizonId} not loaded (orchestrator bug)');
          } else {
            final minAlt = profile.minAltitudeAt(az);
            if (alt < minAlt) {
              rejections.add(
                  'altitude ${alt.toStringAsFixed(1)}° below horizon profile "${profile.name}" (${minAlt.toStringAsFixed(1)}° at az ${az.toStringAsFixed(0)}°)');
            }
          }
          break;
        case TargetConstraintKind.scheduledWindow:
          // Never a hard-fail — the window adds a score boost during its
          // active range and is silent otherwise. Selection forcing is
          // handled in _evaluateOnce via [_hasActiveScheduledWindow]. We
          // accumulate the boost here so an inactive window contributes
          // nothing.
          final sw = ct.scheduledWindow;
          if (sw != null && sw.containsUtc(now)) {
            scheduledWindowBoost += sw.priorityBoost.clamp(0.0, 1.0);
          }
          break;
      }
    }

    // Compute factors regardless so the UI can show them even on rejected
    // candidates.
    final altitudeFactor = _altitudeFactor(alt);
    final meridianFactor = _meridianFactor(
      raHours: c.raHours,
      now: now,
    );
    final (moonFactor, moonDetail) = _moonFactor(
      raHours: c.raHours,
      decDegrees: c.decDegrees,
      now: now,
    );
    final (timeFactor, timeDetail) = _timeRemainingFactor(
      raHours: c.raHours,
      decDegrees: c.decDegrees,
      now: now,
    );
    final filterFactor =
        _filterCoverageFactor(remainingByGoal, c.availableFilters);
    final priorityFactor = _userPriorityFactor(c.userPriority);

    final w = _config.weights;
    final factors = <ScoreFactor>[
      ScoreFactor(
          name: 'altitude',
          value: altitudeFactor,
          weight: w.altitude,
          weighted: altitudeFactor * w.altitude,
          detail: 'alt ${alt.toStringAsFixed(1)}°'),
      ScoreFactor(
          name: 'meridian',
          value: meridianFactor,
          weight: w.meridian,
          weighted: meridianFactor * w.meridian),
      ScoreFactor(
          name: 'moon',
          value: moonFactor,
          weight: w.moon,
          weighted: moonFactor * w.moon,
          detail: moonDetail),
      ScoreFactor(
          name: 'timeRemaining',
          value: timeFactor,
          weight: w.timeRemaining,
          weighted: timeFactor * w.timeRemaining,
          detail: timeDetail),
      ScoreFactor(
          name: 'filterCoverage',
          value: filterFactor,
          weight: w.filterCoverage,
          weighted: filterFactor * w.filterCoverage),
      ScoreFactor(
          name: 'userPriority',
          value: priorityFactor,
          weight: w.userPriority,
          weighted: priorityFactor * w.userPriority),
      if (scheduledWindowBoost > 0)
        ScoreFactor(
          name: 'scheduledWindow',
          value: scheduledWindowBoost.clamp(0.0, 1.0),
          weight: 1.0,
          weighted: scheduledWindowBoost.clamp(0.0, 1.0),
          detail: 'forced-window boost',
        ),
    ];
    final total = factors.fold<double>(0.0, (s, f) => s + f.weighted);

    return TargetScore(
      targetId: c.targetId,
      targetName: c.name,
      totalScore: total,
      factors: factors,
      hardConstraintFailed: rejections.isNotEmpty,
      rejectionReasons: rejections,
    );
  }

  /// Altitude factor: 0 at minAltitude, 1 at 90°, sin² ramp between.
  double _altitudeFactor(double altDeg) {
    final minAlt = _config.minAltitudeDegrees;
    if (altDeg <= minAlt) return 0.0;
    if (altDeg >= 90.0) return 1.0;
    final normalized = (altDeg - minAlt) / (90.0 - minAlt);
    final s = math.sin(normalized * math.pi / 2);
    return s * s;
  }

  /// Meridian-proximity factor: 1 at the meridian, falling linearly to 0
  /// when hour angle reaches ±6h.
  double _meridianFactor({required double raHours, required DateTime now}) {
    final lst = _localSiderealTime(now);
    var ha = lst - raHours;
    while (ha > 12) {
      ha -= 24;
    }
    while (ha < -12) {
      ha += 24;
    }
    final absH = ha.abs();
    if (absH >= 6.0) return 0.0;
    return 1.0 - (absH / 6.0);
  }

  /// Moon factor: penalty for being close to the moon, weighted by lunar
  /// illumination. Returns 1.0 when target is outside the avoidance
  /// radius OR the moon is dark (illumination ~0).
  (double, String) _moonFactor({
    required double raHours,
    required double decDegrees,
    required DateTime now,
  }) {
    final moon = _moonPosition(now);
    final sep = _angularSeparation(
      ra1Hours: raHours,
      dec1Degrees: decDegrees,
      ra2Hours: moon.raHours,
      dec2Degrees: moon.decDegrees,
    );
    final radius = _config.moonAvoidanceRadiusDegrees;
    if (sep >= radius) {
      return (1.0,
          'sep ${sep.toStringAsFixed(0)}° ill ${(moon.illumination * 100).toStringAsFixed(0)}%');
    }
    final closeness = 1.0 - (sep / radius);
    final penalty = closeness * moon.illumination;
    final factor = (1.0 - penalty).clamp(0.0, 1.0);
    return (
      factor,
      'sep ${sep.toStringAsFixed(0)}° ill ${(moon.illumination * 100).toStringAsFixed(0)}%'
    );
  }

  /// Time-remaining factor: how many hours the target stays above the
  /// engine's min altitude tonight, divided by 10 (saturating at 1.0).
  /// Targets with <30 minutes left score very low.
  (double, String) _timeRemainingFactor({
    required double raHours,
    required double decDegrees,
    required DateTime now,
  }) {
    final endHorizon = _hoursUntilSettingBelowMin(
      raHours: raHours,
      decDegrees: decDegrees,
      now: now,
    );
    final hours = endHorizon.clamp(0.0, 10.0);
    final factor = hours / 10.0;
    return (factor, 'visible ${hours.toStringAsFixed(2)} h');
  }

  /// Hours from `now` until the target's altitude drops below min.
  /// Returns 0 if already below, 24 if circumpolar above the threshold.
  double _hoursUntilSettingBelowMin({
    required double raHours,
    required double decDegrees,
    required DateTime now,
  }) {
    final lat = _site.latitudeDegrees * math.pi / 180.0;
    final dec = decDegrees * math.pi / 180.0;
    final minAlt = _config.minAltitudeDegrees * math.pi / 180.0;

    final sinThresh = math.sin(minAlt);
    final center = math.sin(dec) * math.sin(lat);
    final amplitude = (math.cos(dec) * math.cos(lat)).abs();
    final minSin = center - amplitude;
    final maxSin = center + amplitude;
    if (maxSin < sinThresh) return 0.0;
    if (minSin >= sinThresh) return 24.0;

    final denominator = math.cos(dec) * math.cos(lat);
    if (denominator.abs() < 1e-12) return 24.0;
    final cosH = (sinThresh - center) / denominator;
    if (cosH <= -1.0) return 24.0;
    if (cosH >= 1.0) return 0.0;
    final haHorizon = math.acos(cosH) * 180.0 / math.pi / 15.0; // hours

    final lst = _localSiderealTime(now);
    var ha = lst - raHours;
    while (ha > 12) {
      ha -= 24;
    }
    while (ha < -12) {
      ha += 24;
    }
    if (ha.abs() >= haHorizon) return 0.0;
    final hoursToSet = (haHorizon - ha) * 0.9972695663;
    if (hoursToSet < 0) return 0.0;
    return hoursToSet;
  }

  double _localSiderealTime(DateTime time) {
    final utc = time.toUtc();
    int y = utc.year;
    int m = utc.month;
    final d = utc.day +
        utc.hour / 24.0 +
        utc.minute / 1440.0 +
        utc.second / 86400.0;
    if (m <= 2) {
      y -= 1;
      m += 12;
    }
    final a = (y / 100).floor();
    final b = 2 - a + (a / 4).floor();
    final jd = (365.25 * (y + 4716)).floor() +
        (30.6001 * (m + 1)).floor() +
        d +
        b -
        1524.5;
    final t = (jd - 2451545.0) / 36525.0;
    var gmst = 280.46061837 +
        360.98564736629 * (jd - 2451545.0) +
        0.000387933 * t * t -
        t * t * t / 38710000.0;
    gmst = gmst % 360.0;
    if (gmst < 0) gmst += 360.0;
    var lst = gmst / 15.0 + _site.longitudeDegrees / 15.0;
    while (lst < 0) {
      lst += 24.0;
    }
    while (lst >= 24) {
      lst -= 24.0;
    }
    return lst;
  }

  /// Filter coverage factor: fraction of total goal frames still needed,
  /// gated by whether the equipment wheel can produce those filters.
  /// 1.0 when the target has the most uncaptured data available; 0.0 when
  /// fully imaged. Targets with no goals at all score a neutral 0.5 so
  /// they aren't ranked above an actively-incomplete target.
  double _filterCoverageFactor(
    List<IntegrationGoalProgress> progress,
    List<String> availableFilters,
  ) {
    if (progress.isEmpty) return 0.5;
    final available = availableFilters.map((f) => f.toLowerCase()).toSet();
    var totalNeeded = 0;
    var totalGoal = 0;
    for (final p in progress) {
      totalGoal += p.goal.frameCount;
      if (!available.contains(p.goal.filter.toLowerCase())) continue;
      totalNeeded += p.remainingFrames;
    }
    if (totalGoal <= 0) return 0.5;
    return (totalNeeded / totalGoal).clamp(0.0, 1.0);
  }

  /// User priority factor: priority field (assumed 0..10) scaled into [0, 1].
  /// Values outside 0..10 are clamped — they're still meaningful, just
  /// saturated.
  double _userPriorityFactor(int priority) {
    final v = priority.clamp(0, 10);
    return v / 10.0;
  }

  void _updateStatus(SchedulerStatus next) {
    _status = next;
    if (!_statusController.isClosed) {
      _statusController.add(next);
    }
  }

  void _publishDecision(SchedulerDecision decision) {
    _lastDecision = decision;
    if (!_decisionController.isClosed) {
      _decisionController.add(decision);
    }
  }

  /// Build a single-target sequence: slew → center → expose loop on the
  /// currently most-needed filter. This is what the engine hands to the
  /// SequencerService when it picks a target.
  Sequence buildSequenceForCandidate(SchedulerCandidate c) {
    final goalProgress = <IntegrationGoalProgress>[];
    for (var i = 0; i < c.goals.length; i++) {
      goalProgress.add(IntegrationGoalProgress(
        goal: c.goals[i],
        capturedCount: c.capturedCounts[i],
      ));
    }
    final pending = goalProgress
        .where((p) => p.remainingFrames > 0)
        .where((p) => c.availableFilters
            .map((f) => f.toLowerCase())
            .contains(p.goal.filter.toLowerCase()))
        .toList()
      ..sort((a, b) {
        final cmp = b.remainingFrames.compareTo(a.remainingFrames);
        if (cmp != 0) return cmp;
        return b.goal.priority.compareTo(a.goal.priority);
      });

    final uuid = const Uuid();
    final targetId = uuid.v4();
    final slewId = uuid.v4();
    final centerId = uuid.v4();

    final nodes = <String, SequenceNode>{};

    final exposureIds = <String>[];

    if (pending.isEmpty) {
      // No goals or all complete; build a one-shot 30s luminance to keep
      // the operator productive. This is rare because the engine rejects
      // candidates with no usable goals, but we handle it defensively.
      final expId = uuid.v4();
      exposureIds.add(expId);
      nodes[expId] = ExposureNode(
        id: expId,
        name: 'Expose',
        durationSecs: 30.0,
        count: 1,
        filter: c.availableFilters.isNotEmpty ? c.availableFilters.first : null,
      );
    } else {
      final top = pending.first;
      final expId = uuid.v4();
      exposureIds.add(expId);
      nodes[expId] = ExposureNode(
        id: expId,
        name: 'Expose ${top.goal.filter}',
        durationSecs: top.goal.exposureSeconds,
        count: top.remainingFrames,
        filter: top.goal.filter,
      );
    }

    nodes[slewId] = SlewNode(
      id: slewId,
      name: 'Slew to ${c.name}',
      useTargetCoords: true,
    );
    nodes[centerId] = CenterNode(
      id: centerId,
      name: 'Center on ${c.name}',
      useTargetCoords: true,
    );

    final target = TargetHeaderNode(
      id: targetId,
      name: c.name,
      targetName: c.name,
      raHours: c.raHours,
      decDegrees: c.decDegrees,
      priority: c.userPriority,
      childIds: [slewId, centerId, ...exposureIds],
    );
    nodes[targetId] = target;

    return Sequence(
      name: 'Scheduler / ${c.name}',
      description:
          'Auto-generated by the dynamic scheduler at ${_clock().toIso8601String()}',
      nodes: nodes,
      rootNodeId: targetId,
    );
  }
}

extension on SchedulerEngine {
  (double altitude, double azimuth) _calculateAltAz({
    required double raHours,
    required double decDegrees,
    required DateTime time,
  }) {
    final dec = decDegrees * math.pi / 180.0;
    final lat = _site.latitudeDegrees * math.pi / 180.0;
    final lst = _localSiderealTime(time);
    final ha = (lst - raHours) * 15.0 * math.pi / 180.0;
    final sinAlt =
        math.sin(dec) * math.sin(lat) + math.cos(dec) * math.cos(lat) * math.cos(ha);
    final alt = math.asin(sinAlt.clamp(-1.0, 1.0));
    final y = -math.sin(ha) * math.cos(dec);
    final x = math.sin(dec) * math.cos(lat) -
        math.cos(dec) * math.sin(lat) * math.cos(ha);
    var az = math.atan2(y, x);
    if (az < 0) az += 2 * math.pi;
    return (alt * 180.0 / math.pi, az * 180.0 / math.pi);
  }

  /// Meeus low-precision lunar ephemeris, matching the established static
  /// scheduler (`scheduler_service.dart`) so unit-tested moon-illumination
  /// behaviour stays in sync.
  _MoonPosition _moonPosition(DateTime time) {
    final utc = time.toUtc();
    int y = utc.year;
    int m = utc.month;
    final d = utc.day +
        utc.hour / 24.0 +
        utc.minute / 1440.0 +
        utc.second / 86400.0;
    if (m <= 2) {
      y -= 1;
      m += 12;
    }
    final a = (y / 100).floor();
    final b = 2 - a + (a / 4).floor();
    final jd = (365.25 * (y + 4716)).floor() +
        (30.6001 * (m + 1)).floor() +
        d +
        b -
        1524.5;
    final t = (jd - 2451545.0) / 36525.0;
    final l = (218.3164477 + 481267.88123421 * t) % 360.0;
    final dEl = (297.8501921 + 445267.1114034 * t) % 360.0;
    final mp = (134.9633964 + 477198.8675055 * t) % 360.0;
    final mpRad = mp * math.pi / 180.0;
    final dRad = dEl * math.pi / 180.0;
    final lambda = l + 6.289 * math.sin(mpRad);
    final lambdaRad = lambda * math.pi / 180.0;
    final beta = 5.128 * math.sin(mpRad);
    final betaRad = beta * math.pi / 180.0;
    const epsilon = 23.439;
    final epsRad = epsilon * math.pi / 180.0;
    final ra = math.atan2(
      math.sin(lambdaRad) * math.cos(epsRad) -
          math.tan(betaRad) * math.sin(epsRad),
      math.cos(lambdaRad),
    );
    final dec = math.asin(math.sin(betaRad) * math.cos(epsRad) +
        math.cos(betaRad) * math.sin(epsRad) * math.sin(lambdaRad));
    var raHours = (ra * 180.0 / math.pi) / 15.0;
    if (raHours < 0) raHours += 24.0;
    final illumination = (1.0 - math.cos(dRad)) / 2.0;
    return _MoonPosition(
      raHours: raHours,
      decDegrees: dec * 180.0 / math.pi,
      illumination: illumination,
    );
  }

  double _angularSeparation({
    required double ra1Hours,
    required double dec1Degrees,
    required double ra2Hours,
    required double dec2Degrees,
  }) {
    final ra1 = ra1Hours * 15.0 * math.pi / 180.0;
    final ra2 = ra2Hours * 15.0 * math.pi / 180.0;
    final dec1 = dec1Degrees * math.pi / 180.0;
    final dec2 = dec2Degrees * math.pi / 180.0;
    final cosSep = math.sin(dec1) * math.sin(dec2) +
        math.cos(dec1) * math.cos(dec2) * math.cos(ra1 - ra2);
    return math.acos(cosSep.clamp(-1.0, 1.0)) * 180.0 / math.pi;
  }
}

class _MoonPosition {
  final double raHours;
  final double decDegrees;
  final double illumination;
  const _MoonPosition({
    required this.raHours,
    required this.decDegrees,
    required this.illumination,
  });
}
