part of '../variable_star_catalog.dart';

const List<VariableStarData> variableStarCatalogStarsPart1 = [
  // Mira long-period variables
  VariableStarData(
    name: 'Mira',
    designation: 'omi Cet',
    constellation: 'Cet',
    ra: 2.3219,
    dec: -2.9776,
    type: VariableStarType.mira,
    periodDays: 331.96,
    magMax: 2.0,
    magMin: 10.1,
    spectralType: 'M5e-M9e',
  ),
  VariableStarData(
    name: 'Chi Cygni',
    designation: 'chi Cyg',
    constellation: 'Cyg',
    ra: 19.8409,
    dec: 32.9135,
    type: VariableStarType.mira,
    periodDays: 408.05,
    magMax: 3.3,
    magMin: 14.2,
    spectralType: 'S6-S10',
  ),
  VariableStarData(
    name: 'R Leonis',
    constellation: 'Leo',
    ra: 9.7924,
    dec: 11.4286,
    type: VariableStarType.mira,
    periodDays: 309.95,
    magMax: 4.4,
    magMin: 11.3,
    spectralType: 'M6e-M9.5e',
  ),
  VariableStarData(
    name: 'R Hydrae',
    constellation: 'Hya',
    ra: 13.4898,
    dec: -23.2699,
    type: VariableStarType.mira,
    periodDays: 389.0,
    magMax: 3.5,
    magMin: 10.9,
    spectralType: 'M6e-M9e',
  ),
  VariableStarData(
    name: 'R Cassiopeiae',
    constellation: 'Cas',
    ra: 23.9645,
    dec: 51.3936,
    type: VariableStarType.mira,
    periodDays: 430.46,
    magMax: 4.7,
    magMin: 13.5,
    spectralType: 'M6e-M10e',
  ),
  VariableStarData(
    name: 'R Andromedae',
    constellation: 'And',
    ra: 0.4064,
    dec: 38.5856,
    type: VariableStarType.mira,
    periodDays: 409.33,
    magMax: 5.8,
    magMin: 14.9,
    spectralType: 'S3-S8',
  ),
  VariableStarData(
    name: 'R Aquarii',
    constellation: 'Aqr',
    ra: 23.7226,
    dec: -15.2867,
    type: VariableStarType.mira,
    periodDays: 386.96,
    magMax: 5.8,
    magMin: 12.4,
    spectralType: 'M5e-M8.5e',
  ),
  VariableStarData(
    name: 'R Serpentis',
    constellation: 'Ser',
    ra: 15.8364,
    dec: 15.1205,
    type: VariableStarType.mira,
    periodDays: 356.41,
    magMax: 5.2,
    magMin: 14.4,
    spectralType: 'M5e-M9e',
  ),
  VariableStarData(
    name: 'R Leporis',
    constellation: 'Lep',
    ra: 4.9936,
    dec: -14.8071,
    type: VariableStarType.mira,
    periodDays: 427.07,
    magMax: 5.5,
    magMin: 11.7,
    spectralType: 'C7,6e',
  ),
  VariableStarData(
    name: 'R Virginis',
    constellation: 'Vir',
    ra: 12.6500,
    dec: 6.9500,
    type: VariableStarType.mira,
    periodDays: 145.63,
    magMax: 6.1,
    magMin: 12.1,
    spectralType: 'M3.5e-M8.5e',
  ),
  VariableStarData(
    name: 'R Bootis',
    constellation: 'Boo',
    ra: 14.8117,
    dec: 26.7217,
    type: VariableStarType.mira,
    periodDays: 223.4,
    magMax: 6.2,
    magMin: 13.1,
    spectralType: 'M3e-M8e',
  ),
  VariableStarData(
    name: 'R Trianguli',
    constellation: 'Tri',
    ra: 2.5886,
    dec: 34.3117,
    type: VariableStarType.mira,
    periodDays: 266.9,
    magMax: 5.4,
    magMin: 12.6,
    spectralType: 'M4e-M8e',
  ),
  VariableStarData(
    name: 'R Cancri',
    constellation: 'Cnc',
    ra: 8.2806,
    dec: 11.6378,
    type: VariableStarType.mira,
    periodDays: 361.6,
    magMax: 6.1,
    magMin: 11.8,
    spectralType: 'M6e-M9e',
  ),
  VariableStarData(
    name: 'T Cephei',
    constellation: 'Cep',
    ra: 21.1586,
    dec: 68.4848,
    type: VariableStarType.mira,
    periodDays: 388.14,
    magMax: 5.2,
    magMin: 11.3,
    spectralType: 'M5.5e-M8.8e',
  ),
  VariableStarData(
    name: 'U Orionis',
    constellation: 'Ori',
    ra: 5.9064,
    dec: 20.1736,
    type: VariableStarType.mira,
    periodDays: 368.3,
    magMax: 4.8,
    magMin: 13.0,
    spectralType: 'M6.5e-M9.5e',
  ),
  VariableStarData(
    name: 'R Cygni',
    constellation: 'Cyg',
    ra: 19.6167,
    dec: 50.2450,
    type: VariableStarType.mira,
    periodDays: 426.45,
    magMax: 6.1,
    magMin: 14.4,
    spectralType: 'S2.5e-S6e',
  ),
  VariableStarData(
    name: 'R Aquilae',
    constellation: 'Aql',
    ra: 19.1100,
    dec: 8.2428,
    type: VariableStarType.mira,
    periodDays: 284.2,
    magMax: 5.5,
    magMin: 12.0,
    spectralType: 'M5e-M9e',
  ),
  VariableStarData(
    name: 'R Centauri',
    constellation: 'Cen',
    ra: 14.2800,
    dec: -59.9528,
    type: VariableStarType.mira,
    periodDays: 546.2,
    magMax: 5.3,
    magMin: 11.8,
    spectralType: 'M4e-M8e',
  ),
  VariableStarData(
    name: 'R Carinae',
    constellation: 'Car',
    ra: 9.5411,
    dec: -62.7858,
    type: VariableStarType.mira,
    periodDays: 308.71,
    magMax: 3.9,
    magMin: 10.5,
    spectralType: 'M4e-M8e',
  ),
  VariableStarData(
    name: 'R Horologii',
    constellation: 'Hor',
    ra: 2.9200,
    dec: -49.8833,
    type: VariableStarType.mira,
    periodDays: 407.6,
    magMax: 4.7,
    magMin: 14.3,
    spectralType: 'M5e-M8eII',
  ),

  // Cepheids
  VariableStarData(
    name: 'Delta Cephei',
    designation: 'del Cep',
    constellation: 'Cep',
    ra: 22.4880,
    dec: 58.4153,
    type: VariableStarType.cepheid,
    periodDays: 5.3663,
    magMax: 3.48,
    magMin: 4.37,
    spectralType: 'F5Ib-G2Ib',
  ),
  VariableStarData(
    name: 'Eta Aquilae',
    designation: 'eta Aql',
    constellation: 'Aql',
    ra: 19.8750,
    dec: 1.0054,
    type: VariableStarType.cepheid,
    periodDays: 7.1767,
    magMax: 3.48,
    magMin: 4.39,
    spectralType: 'F6Ib-G4Ib',
  ),
  VariableStarData(
    name: 'Zeta Geminorum',
    designation: 'zet Gem',
    constellation: 'Gem',
    ra: 7.0686,
    dec: 20.5703,
    type: VariableStarType.cepheid,
    periodDays: 10.1508,
    magMax: 3.62,
    magMin: 4.18,
    spectralType: 'F7Ib-G3Ib',
  ),
  VariableStarData(
    name: 'Beta Doradus',
    designation: 'bet Dor',
    constellation: 'Dor',
    ra: 5.5606,
    dec: -62.4900,
    type: VariableStarType.cepheid,
    periodDays: 9.8426,
    magMax: 3.46,
    magMin: 4.08,
    spectralType: 'F4-G4Ia/Ib',
  ),
  VariableStarData(
    name: 'l Carinae',
    designation: 'l Car',
    constellation: 'Car',
    ra: 9.2200,
    dec: -62.5100,
    type: VariableStarType.cepheid,
    periodDays: 35.5518,
    magMax: 3.28,
    magMin: 4.18,
    spectralType: 'G5Iab/Ib',
  ),
  VariableStarData(
    name: 'Polaris',
    designation: 'alp UMi',
    constellation: 'UMi',
    ra: 2.5302,
    dec: 89.2641,
    type: VariableStarType.cepheid,
    periodDays: 3.9696,
    magMax: 1.86,
    magMin: 2.13,
    spectralType: 'F7Ib-F8Ib',
  ),
  VariableStarData(
    name: 'T Vulpeculae',
    constellation: 'Vul',
    ra: 20.5139,
    dec: 28.2508,
    type: VariableStarType.cepheid,
    periodDays: 4.4356,
    magMax: 5.41,
    magMin: 6.09,
    spectralType: 'F5Ib-G0Ib',
  ),
  VariableStarData(
    name: 'S Sagittae',
    constellation: 'Sge',
    ra: 19.9383,
    dec: 16.6311,
    type: VariableStarType.cepheid,
    periodDays: 8.3821,
    magMax: 5.24,
    magMin: 6.04,
    spectralType: 'F6Ib-G5Ib',
  ),
  VariableStarData(
    name: 'X Sagittarii',
    constellation: 'Sgr',
    ra: 17.7267,
    dec: -27.8314,
    type: VariableStarType.cepheid,
    periodDays: 7.0129,
    magMax: 4.20,
    magMin: 4.90,
    spectralType: 'F5-G2II',
  ),
  VariableStarData(
    name: 'W Sagittarii',
    constellation: 'Sgr',
    ra: 18.0543,
    dec: -29.5802,
    type: VariableStarType.cepheid,
    periodDays: 7.5950,
    magMax: 4.29,
    magMin: 5.14,
    spectralType: 'F4-G2Ib',
  ),
  VariableStarData(
    name: 'Y Sagittarii',
    constellation: 'Sgr',
    ra: 18.2183,
    dec: -18.8628,
    type: VariableStarType.cepheid,
    periodDays: 5.7734,
    magMax: 5.25,
    magMin: 6.24,
    spectralType: 'F8Ib-G0Ib',
  ),
  VariableStarData(
    name: 'U Sagittarii',
    constellation: 'Sgr',
    ra: 18.5467,
    dec: -19.1525,
    type: VariableStarType.cepheid,
    periodDays: 6.7453,
    magMax: 6.28,
    magMin: 7.15,
    spectralType: 'F5-G1.5Ib',
  ),
  VariableStarData(
    name: 'FF Aquilae',
    constellation: 'Aql',
    ra: 18.9745,
    dec: 17.3575,
    type: VariableStarType.cepheid,
    periodDays: 4.4710,
    magMax: 5.18,
    magMin: 5.68,
    spectralType: 'F5Ia-F8Ia',
  ),
  VariableStarData(
    name: 'RT Aurigae',
    constellation: 'Aur',
    ra: 6.2867,
    dec: 30.4933,
    type: VariableStarType.cepheid,
    periodDays: 3.7283,
    magMax: 5.00,
    magMin: 5.82,
    spectralType: 'F4Ib-G1Ib',
  ),
  VariableStarData(
    name: 'SU Cassiopeiae',
    constellation: 'Cas',
    ra: 2.0992,
    dec: 68.6875,
    type: VariableStarType.cepheid,
    periodDays: 1.9493,
    magMax: 5.70,
    magMin: 6.24,
    spectralType: 'F5-F8Ib/II',
  ),

  // Eclipsing binaries
  VariableStarData(
    name: 'Algol',
    designation: 'bet Per',
    constellation: 'Per',
    ra: 3.1361,
    dec: 40.9556,
    type: VariableStarType.eclipsingAlgol,
    periodDays: 2.8673,
    magMax: 2.12,
    magMin: 3.39,
    spectralType: 'B8V',
  ),
  VariableStarData(
    name: 'Beta Lyrae',
    designation: 'bet Lyr',
    constellation: 'Lyr',
    ra: 18.8347,
    dec: 33.3628,
    type: VariableStarType.eclipsingBetaLyr,
    periodDays: 12.9414,
    magMax: 3.25,
    magMin: 4.36,
    spectralType: 'B8.5II',
  ),
  VariableStarData(
    name: 'Lambda Tauri',
    designation: 'lam Tau',
    constellation: 'Tau',
    ra: 4.0109,
    dec: 12.4903,
    type: VariableStarType.eclipsingAlgol,
    periodDays: 3.9529,
    magMax: 3.37,
    magMin: 3.91,
    spectralType: 'B3V',
  ),
  VariableStarData(
    name: 'Delta Librae',
    designation: 'del Lib',
    constellation: 'Lib',
    ra: 15.0714,
    dec: -8.5185,
    type: VariableStarType.eclipsingAlgol,
    periodDays: 2.3274,
    magMax: 4.91,
    magMin: 5.90,
    spectralType: 'B9.5V',
  ),
  VariableStarData(
    name: 'U Cephei',
    constellation: 'Cep',
    ra: 1.0175,
    dec: 81.5833,
    type: VariableStarType.eclipsingAlgol,
    periodDays: 2.4930,
    magMax: 6.75,
    magMin: 9.24,
    spectralType: 'B7Ve+G8III',
  ),
  VariableStarData(
    name: 'U Sagittae',
    constellation: 'Sge',
    ra: 19.3158,
    dec: 19.6378,
    type: VariableStarType.eclipsingAlgol,
    periodDays: 3.3806,
    magMax: 6.45,
    magMin: 9.28,
    spectralType: 'B8V+K0II',
  ),
  VariableStarData(
    name: 'TX UMa',
    constellation: 'UMa',
    ra: 10.7853,
    dec: 45.1331,
    type: VariableStarType.eclipsingAlgol,
    periodDays: 3.0633,
    magMax: 7.06,
    magMin: 8.80,
    spectralType: 'B8V',
  ),
  VariableStarData(
    name: 'W UMa',
    constellation: 'UMa',
    ra: 9.7233,
    dec: 55.9867,
    type: VariableStarType.eclipsingWUma,
    periodDays: 0.3336,
    magMax: 7.75,
    magMin: 8.48,
    spectralType: 'F8Vp',
  ),
  VariableStarData(
    name: 'Epsilon Aurigae',
    designation: 'eps Aur',
    constellation: 'Aur',
    ra: 5.0322,
    dec: 43.8233,
    type: VariableStarType.eclipsingAlgol,
    periodDays: 9884.0,
    magMax: 2.92,
    magMin: 3.83,
    spectralType: 'F0Iab',
  ),
  VariableStarData(
    name: 'Zeta Aurigae',
    designation: 'zet Aur',
    constellation: 'Aur',
    ra: 5.0430,
    dec: 41.0756,
    type: VariableStarType.eclipsingAlgol,
    periodDays: 972.16,
    magMax: 3.70,
    magMin: 4.00,
    spectralType: 'K4Ib+B5V',
  ),
  VariableStarData(
    name: 'VV Cephei',
    constellation: 'Cep',
    ra: 21.5639,
    dec: 63.6153,
    type: VariableStarType.eclipsingAlgol,
    periodDays: 7430.5,
    magMax: 4.80,
    magMin: 5.36,
    spectralType: 'M2eIab+B0-2V',
  ),

  // Semi-regular variables
  VariableStarData(
    name: 'Betelgeuse',
    designation: 'alp Ori',
    constellation: 'Ori',
    ra: 5.9195,
    dec: 7.4070,
    type: VariableStarType.semiRegular,
    periodDays: 400.0,
    magMax: 0.0,
    magMin: 1.6,
    spectralType: 'M1-M2Ia-Iab',
  ),
  VariableStarData(
    name: 'Antares',
    designation: 'alp Sco',
    constellation: 'Sco',
    ra: 16.4901,
    dec: -26.4320,
    type: VariableStarType.semiRegular,
    periodDays: 1733.0,
    magMax: 0.6,
    magMin: 1.6,
    spectralType: 'M1.5Iab-Ib',
  ),
];
