part of '../variable_star_catalog.dart';

const List<VariableStarData> variableStarCatalogStarsPart2 = [
  VariableStarData(
    name: 'Mu Cephei',
    designation: 'mu Cep',
    constellation: 'Cep',
    ra: 21.7256,
    dec: 58.7830,
    type: VariableStarType.semiRegular,
    periodDays: 860.0,
    magMax: 3.43,
    magMin: 5.1,
    spectralType: 'M2eIa',
  ),
  VariableStarData(
    name: 'Rasalgethi',
    designation: 'alp Her',
    constellation: 'Her',
    ra: 17.2441,
    dec: 14.3904,
    type: VariableStarType.semiRegular,
    periodDays: 128.0,
    magMax: 2.74,
    magMin: 4.0,
    spectralType: 'M5Ib-II',
  ),
  VariableStarData(
    name: 'Gamma Crucis',
    designation: 'gam Cru',
    constellation: 'Cru',
    ra: 12.5194,
    dec: -57.1133,
    type: VariableStarType.semiRegular,
    periodDays: null,
    magMax: 1.63,
    magMin: 1.73,
    spectralType: 'M3.5III',
  ),
  VariableStarData(
    name: 'R Doradus',
    constellation: 'Dor',
    ra: 4.5528,
    dec: -62.0794,
    type: VariableStarType.semiRegular,
    periodDays: 338.0,
    magMax: 4.8,
    magMin: 6.6,
    spectralType: 'M8IIIe',
  ),
  VariableStarData(
    name: 'W Cygni',
    constellation: 'Cyg',
    ra: 21.6117,
    dec: 45.2294,
    type: VariableStarType.semiRegular,
    periodDays: 131.1,
    magMax: 5.0,
    magMin: 7.6,
    spectralType: 'M4e-M6eIII',
  ),
  VariableStarData(
    name: 'AF Cygni',
    constellation: 'Cyg',
    ra: 19.2975,
    dec: 46.1400,
    type: VariableStarType.semiRegular,
    periodDays: 92.5,
    magMax: 7.0,
    magMin: 9.4,
    spectralType: 'M5III',
  ),
  VariableStarData(
    name: 'R Lyrae',
    constellation: 'Lyr',
    ra: 18.9667,
    dec: 43.9467,
    type: VariableStarType.semiRegular,
    periodDays: 46.0,
    magMax: 3.88,
    magMin: 5.0,
    spectralType: 'M5III',
  ),
  VariableStarData(
    name: 'EU Delphini',
    constellation: 'Del',
    ra: 20.7083,
    dec: 18.1583,
    type: VariableStarType.semiRegular,
    periodDays: 59.7,
    magMax: 5.79,
    magMin: 6.90,
    spectralType: 'M6III',
  ),
  VariableStarData(
    name: 'TX Piscium',
    constellation: 'Psc',
    ra: 23.7661,
    dec: 3.5119,
    type: VariableStarType.semiRegular,
    periodDays: 220.0,
    magMax: 4.79,
    magMin: 5.20,
    spectralType: 'C5II',
  ),
  VariableStarData(
    name: 'RR Coronae Borealis',
    constellation: 'CrB',
    ra: 16.0367,
    dec: 33.8667,
    type: VariableStarType.semiRegular,
    periodDays: 60.8,
    magMax: 7.3,
    magMin: 8.2,
    spectralType: 'M3III',
  ),

  // ===== RR LYRAE VARIABLES =====
  VariableStarData(
    name: 'RR Lyrae',
    constellation: 'Lyr',
    ra: 19.4401,
    dec: 42.7841,
    type: VariableStarType.rrLyrae,
    periodDays: 0.5669,
    magMax: 7.06,
    magMin: 8.12,
    spectralType: 'A8-F7',
  ),
  VariableStarData(
    name: 'XZ Cygni',
    constellation: 'Cyg',
    ra: 19.5483,
    dec: 56.3933,
    type: VariableStarType.rrLyrae,
    periodDays: 0.4667,
    magMax: 8.9,
    magMin: 10.1,
    spectralType: 'A6-F5',
  ),
  VariableStarData(
    name: 'SU Draconis',
    constellation: 'Dra',
    ra: 17.6417,
    dec: 67.4289,
    type: VariableStarType.rrLyrae,
    periodDays: 0.6604,
    magMax: 9.0,
    magMin: 10.3,
    spectralType: 'A7-F2',
  ),
  VariableStarData(
    name: 'AR Herculis',
    constellation: 'Her',
    ra: 16.1358,
    dec: 46.9467,
    type: VariableStarType.rrLyrae,
    periodDays: 0.4700,
    magMax: 10.4,
    magMin: 11.5,
    spectralType: 'A7-F5',
  ),
  VariableStarData(
    name: 'T Sextantis',
    constellation: 'Sex',
    ra: 9.8744,
    dec: -1.4508,
    type: VariableStarType.rrLyrae,
    periodDays: 0.4535,
    magMax: 9.5,
    magMin: 10.5,
    spectralType: 'A5-F4',
  ),

  // ===== ERUPTIVE AND OTHER TYPES =====
  VariableStarData(
    name: 'Gamma Cassiopeiae',
    designation: 'gam Cas',
    constellation: 'Cas',
    ra: 0.9452,
    dec: 60.7167,
    type: VariableStarType.gammaCas,
    periodDays: null,
    magMax: 1.6,
    magMin: 3.0,
    spectralType: 'B0IVe',
  ),
  VariableStarData(
    name: 'P Cygni',
    constellation: 'Cyg',
    ra: 20.2949,
    dec: 38.0328,
    type: VariableStarType.irregular,
    periodDays: null,
    magMax: 3.0,
    magMin: 6.0,
    spectralType: 'B1Ia+pe',
  ),
  VariableStarData(
    name: 'R Coronae Borealis',
    constellation: 'CrB',
    ra: 15.8297,
    dec: 28.1489,
    type: VariableStarType.rCrB,
    periodDays: null,
    magMax: 5.71,
    magMin: 14.8,
    spectralType: 'C0,0(F8pep)',
  ),
  VariableStarData(
    name: 'T Coronae Borealis',
    constellation: 'CrB',
    ra: 15.9927,
    dec: 25.9194,
    type: VariableStarType.nova,
    periodDays: null,
    magMax: 2.0,
    magMin: 10.8,
    spectralType: 'M3III+pec',
  ),
  VariableStarData(
    name: 'SS Cygni',
    constellation: 'Cyg',
    ra: 21.7019,
    dec: 43.5863,
    type: VariableStarType.dwarfNova,
    periodDays: 49.5,
    magMax: 7.7,
    magMin: 12.4,
    spectralType: 'K5V+pec',
  ),
  VariableStarData(
    name: 'U Geminorum',
    constellation: 'Gem',
    ra: 7.9344,
    dec: 22.0014,
    type: VariableStarType.dwarfNova,
    periodDays: 102.7,
    magMax: 8.2,
    magMin: 14.9,
    spectralType: 'sdBe+M4V',
  ),
  VariableStarData(
    name: 'Z Camelopardalis',
    constellation: 'Cam',
    ra: 8.4100,
    dec: 73.0972,
    type: VariableStarType.dwarfNova,
    periodDays: 22.0,
    magMax: 9.6,
    magMin: 13.5,
    spectralType: 'DA+dM4.5e',
  ),

  // ===== DELTA SCUTI VARIABLES =====
  VariableStarData(
    name: 'Delta Scuti',
    designation: 'del Sct',
    constellation: 'Sct',
    ra: 18.7066,
    dec: -9.0508,
    type: VariableStarType.deltaScuti,
    periodDays: 0.1938,
    magMax: 4.60,
    magMin: 4.79,
    spectralType: 'F2IIIp',
  ),
  VariableStarData(
    name: 'Beta Cassiopeiae',
    designation: 'bet Cas',
    constellation: 'Cas',
    ra: 0.1528,
    dec: 59.1497,
    type: VariableStarType.deltaScuti,
    periodDays: 0.1005,
    magMax: 2.25,
    magMin: 2.31,
    spectralType: 'F2III',
  ),
  VariableStarData(
    name: 'Rho Puppis',
    designation: 'rho Pup',
    constellation: 'Pup',
    ra: 8.1256,
    dec: -24.3042,
    type: VariableStarType.deltaScuti,
    periodDays: 0.1409,
    magMax: 2.68,
    magMin: 2.87,
    spectralType: 'F6IIp',
  ),

  // ===== RS CVN AND BY DRA (ACTIVE BINARIES / SPOTTED STARS) =====
  VariableStarData(
    name: 'RS CVn',
    constellation: 'CVn',
    ra: 13.1715,
    dec: 35.9631,
    type: VariableStarType.rsCVn,
    periodDays: 4.7979,
    magMax: 7.93,
    magMin: 9.14,
    spectralType: 'F4IV-V+K0IV',
  ),
  VariableStarData(
    name: 'AR Lacertae',
    constellation: 'Lac',
    ra: 22.1506,
    dec: 45.7406,
    type: VariableStarType.rsCVn,
    periodDays: 1.9832,
    magMax: 6.08,
    magMin: 6.77,
    spectralType: 'G2IV+K0IV',
  ),
  VariableStarData(
    name: 'II Pegasi',
    constellation: 'Peg',
    ra: 23.5525,
    dec: 28.6810,
    type: VariableStarType.rsCVn,
    periodDays: 6.7243,
    magMax: 7.2,
    magMin: 7.6,
    spectralType: 'K2-3V-IV',
  ),
  VariableStarData(
    name: 'V711 Tauri',
    constellation: 'Tau',
    ra: 3.6047,
    dec: 0.5947,
    type: VariableStarType.rsCVn,
    periodDays: 2.8377,
    magMax: 5.64,
    magMin: 5.94,
    spectralType: 'G5IV+K1IV',
  ),
  VariableStarData(
    name: 'BY Draconis',
    constellation: 'Dra',
    ra: 18.3394,
    dec: 51.6917,
    type: VariableStarType.byDra,
    periodDays: 3.836,
    magMax: 8.07,
    magMin: 8.41,
    spectralType: 'dM0e',
  ),

  // ===== ADDITIONAL BRIGHT INTERESTING VARIABLES =====
  VariableStarData(
    name: 'Eta Carinae',
    designation: 'eta Car',
    constellation: 'Car',
    ra: 10.7513,
    dec: -59.6844,
    type: VariableStarType.irregular,
    periodDays: 2022.7,
    magMax: -1.0,
    magMin: 7.9,
    spectralType: 'pec',
  ),
  VariableStarData(
    name: 'R Scuti',
    constellation: 'Sct',
    ra: 18.6758,
    dec: -5.7103,
    type: VariableStarType.semiRegular,
    periodDays: 146.5,
    magMax: 4.2,
    magMin: 8.6,
    spectralType: 'G0-K2Ibe',
  ),
  VariableStarData(
    name: 'V Hydrae',
    constellation: 'Hya',
    ra: 10.8500,
    dec: -21.2453,
    type: VariableStarType.semiRegular,
    periodDays: 530.0,
    magMax: 6.0,
    magMin: 12.3,
    spectralType: 'C6-C7',
  ),
  VariableStarData(
    name: 'W Orionis',
    constellation: 'Ori',
    ra: 5.0544,
    dec: 1.1742,
    type: VariableStarType.semiRegular,
    periodDays: 212.0,
    magMax: 5.88,
    magMin: 7.7,
    spectralType: 'C5,4',
  ),
  VariableStarData(
    name: 'S Persei',
    constellation: 'Per',
    ra: 2.3856,
    dec: 58.5917,
    type: VariableStarType.semiRegular,
    periodDays: 822.0,
    magMax: 7.9,
    magMin: 12.0,
    spectralType: 'M4eIa',
  ),
  VariableStarData(
    name: 'Z Ursae Majoris',
    constellation: 'UMa',
    ra: 11.5803,
    dec: 57.8706,
    type: VariableStarType.semiRegular,
    periodDays: 195.5,
    magMax: 6.2,
    magMin: 9.4,
    spectralType: 'M5III',
  ),
  VariableStarData(
    name: 'Y Canum Venaticorum',
    constellation: 'CVn',
    ra: 12.7578,
    dec: 45.4461,
    type: VariableStarType.semiRegular,
    periodDays: 157.3,
    magMax: 4.80,
    magMin: 6.3,
    spectralType: 'C5,4J',
  ),
  VariableStarData(
    name: 'SX Herculis',
    constellation: 'Her',
    ra: 16.1256,
    dec: 24.2700,
    type: VariableStarType.rrLyrae,
    periodDays: 0.7091,
    magMax: 9.8,
    magMin: 10.8,
    spectralType: 'A7-F3',
  ),
  VariableStarData(
    name: 'R Aquarii',
    constellation: 'Aqr',
    ra: 23.7226,
    dec: -15.2867,
    type: VariableStarType.mira,
    periodDays: 386.96,
    magMax: 5.8,
    magMin: 12.4,
    spectralType: 'M5e-M8.5e+pec',
  ),
  VariableStarData(
    name: 'Eta Geminorum',
    designation: 'eta Gem',
    constellation: 'Gem',
    ra: 6.2479,
    dec: 22.5068,
    type: VariableStarType.semiRegular,
    periodDays: 232.9,
    magMax: 3.15,
    magMin: 3.90,
    spectralType: 'M3IIIab',
  ),
  VariableStarData(
    name: 'Alpha Herculis',
    designation: 'alp1 Her',
    constellation: 'Her',
    ra: 17.2441,
    dec: 14.3904,
    type: VariableStarType.semiRegular,
    periodDays: 128.0,
    magMax: 2.74,
    magMin: 4.0,
    spectralType: 'M5Ib-II',
  ),
  VariableStarData(
    name: 'CE Tauri',
    constellation: 'Tau',
    ra: 5.5508,
    dec: 18.5944,
    type: VariableStarType.semiRegular,
    periodDays: 165.0,
    magMax: 4.19,
    magMin: 4.54,
    spectralType: 'M2Iab-Ib',
  ),
  VariableStarData(
    name: 'RZ Cassiopeiae',
    constellation: 'Cas',
    ra: 2.7956,
    dec: 69.6375,
    type: VariableStarType.eclipsingAlgol,
    periodDays: 1.1953,
    magMax: 6.18,
    magMin: 7.72,
    spectralType: 'A3V',
  ),
  VariableStarData(
    name: 'AW UMa',
    constellation: 'UMa',
    ra: 11.5494,
    dec: 29.9581,
    type: VariableStarType.eclipsingWUma,
    periodDays: 0.4387,
    magMax: 6.83,
    magMin: 7.13,
    spectralType: 'F2V',
  ),
  VariableStarData(
    name: 'S Cephei',
    constellation: 'Cep',
    ra: 21.4578,
    dec: 78.7844,
    type: VariableStarType.mira,
    periodDays: 486.84,
    magMax: 7.4,
    magMin: 12.9,
    spectralType: 'C6,4e-C7,2e',
  ),
  VariableStarData(
    name: 'T Tauri',
    constellation: 'Tau',
    ra: 4.3650,
    dec: 19.5350,
    type: VariableStarType.irregular,
    periodDays: null,
    magMax: 9.3,
    magMin: 13.5,
    spectralType: 'F8Ve-K1Ve',
  ),
  VariableStarData(
    name: 'FG Sagittae',
    constellation: 'Sge',
    ra: 20.0634,
    dec: 20.1949,
    type: VariableStarType.irregular,
    periodDays: null,
    magMax: 9.0,
    magMin: 13.8,
    spectralType: 'B4Ieq-K2Ib',
  ),
  VariableStarData(
    name: 'UV Ceti',
    constellation: 'Cet',
    ra: 1.6541,
    dec: -17.9517,
    type: VariableStarType.byDra,
    periodDays: null,
    magMax: 6.8,
    magMin: 13.0,
    spectralType: 'M5.5Ve',
  ),
  VariableStarData(
    name: 'AG Draconis',
    constellation: 'Dra',
    ra: 16.0200,
    dec: 66.8058,
    type: VariableStarType.nova,
    periodDays: 554.0,
    magMax: 8.6,
    magMin: 12.0,
    spectralType: 'K3IIIep',
  ),
];
