import 'dart:io';
import 'dart:math' as math;

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

import '../../database/daos/images_dao.dart';
import '../../database/daos/science_dao.dart';
import '../../database/daos/sessions_dao.dart';
import '../../database/daos/targets_dao.dart';
import '../../database/database.dart';
import '../../providers/database_provider.dart';

/// Markdown science-report exporter.
///
/// Produces a single self-contained markdown document for one session that
/// captures everything an astronomer would want to share with collaborators
/// or paste into a sky-cloud forum post:
///   * Session header (target, dates, duration, integration)
///   * Frame counts (light/dark/flat/bias, accepted vs rejected)
///   * Photometric snapshot (latest ZP + mean ZP + spread, limiting mag,
///     catalog used, comparison-frame count)
///   * Transparency snapshot (latest, range, dominant bucket)
///   * Field quality (FWHM, eccentricity, uniformity, top-3 issues)
///   * Per-filter integration breakdown
///   * Any moving-object candidates flagged tonight
///
/// The file lands in the platform "documents" directory under
/// `Nightshade/science-reports/<sessionId>-<timestamp>.md`. We never
/// silently truncate; if a section has no data, it's emitted explicitly
/// (e.g. "No photometric calibration produced this session.") so the
/// recipient can tell the difference between "we ran nothing" and "we
/// produced nothing because conditions were bad".
class ScienceReportExporter {
  final ImagesDao _imagesDao;
  final ScienceDao _scienceDao;
  final SessionsDao _sessionsDao;
  final TargetsDao _targetsDao;

  const ScienceReportExporter({
    required ImagesDao imagesDao,
    required ScienceDao scienceDao,
    required SessionsDao sessionsDao,
    required TargetsDao targetsDao,
  }) : _imagesDao = imagesDao,
       _scienceDao = scienceDao,
       _sessionsDao = sessionsDao,
       _targetsDao = targetsDao;

  /// Build a markdown string for [sessionId]. Public so callers can ship
  /// the report somewhere other than disk (Slack DM, email, etc.) without
  /// going through `exportToDisk`.
  Future<String> buildMarkdown(int sessionId) async {
    final session = await _sessionsDao.getSessionById(sessionId);
    if (session == null) {
      throw StateError('Session $sessionId not found');
    }
    Target? target;
    if (session.targetId != null) {
      target = await _targetsDao.getTargetById(session.targetId!);
    }
    final images = await _imagesDao.getImagesForSession(sessionId);
    final calibrations = await _scienceDao.getCalibrationsForSession(sessionId);
    final transparency = await _scienceDao.getTransparencyForSession(sessionId);
    final frameMetrics = await _scienceDao.getFrameQualityMetricsForSession(
      sessionId,
    );
    final movingObjects = await _scienceDao.getMovingObjectsForSession(
      sessionId,
    );

    final b = StringBuffer();
    b.writeln('# Nightshade Science Report — Session #$sessionId');
    b.writeln();
    b.writeln(_sessionHeader(session, target));
    b.writeln();
    b.writeln(_frameCounts(images));
    b.writeln();
    b.writeln(_photometrySnapshot(calibrations));
    b.writeln();
    b.writeln(_transparencySnapshot(transparency));
    b.writeln();
    b.writeln(_fieldQuality(frameMetrics));
    b.writeln();
    b.writeln(_filterBreakdown(images));
    b.writeln();
    b.writeln(_movingObjectCandidates(movingObjects));
    b.writeln();
    b.writeln('---');
    b.writeln(
      '_Generated by Nightshade 2.6.0 on ${DateTime.now().toUtc().toIso8601String()}._',
    );
    return b.toString();
  }

  /// Write the report to a file under the platform documents directory.
  /// Returns the absolute path the user can hand off to share / open. The
  /// returned [File] is always flushed to disk so external apps can open
  /// it immediately.
  Future<File> exportToDisk(int sessionId) async {
    final markdown = await buildMarkdown(sessionId);
    final dir = await _ensureReportsDirectory();
    final stamp = DateTime.now().toUtc().toIso8601String().replaceAll(
      RegExp(r'[:.]'),
      '-',
    ); // Filesystem-safe across Windows / macOS.
    final file = File(p.join(dir.path, 'session-$sessionId-$stamp.md'));
    await file.writeAsString(markdown, flush: true);
    return file;
  }

  Future<Directory> _ensureReportsDirectory() async {
    final base = await getApplicationDocumentsDirectory();
    final dir = Directory(p.join(base.path, 'Nightshade', 'science-reports'));
    if (!await dir.exists()) {
      await dir.create(recursive: true);
    }
    return dir;
  }

  String _sessionHeader(ImagingSession session, Target? target) {
    final lines = <String>[
      '## Session',
      '- **Target:** ${target?.name ?? '(no target bound)'}',
      if (target?.constellation != null && target!.constellation!.isNotEmpty)
        '- **Constellation:** ${target.constellation}',
      '- **Started:** ${session.startTime.toIso8601String()}',
      if (session.endTime != null)
        '- **Ended:** ${session.endTime!.toIso8601String()}',
      if (session.endTime != null)
        '- **Wall-clock:** ${_humanDuration(session.endTime!.difference(session.startTime))}',
    ];
    return lines.join('\n');
  }

  String _frameCounts(List<CapturedImage> images) {
    final lights = images
        .where((i) => i.frameType.toLowerCase() == 'light')
        .toList(growable: false);
    final accepted = lights.where((i) => i.isAccepted).length;
    final integrationSeconds = lights
        .where((i) => i.isAccepted)
        .map((i) => i.exposureDuration)
        .fold<double>(0.0, (acc, v) => acc + v);
    final solved = lights.where((i) => i.isPlateSolved).length;
    return '## Frames\n'
        '| Frame type | Total | Accepted | Plate-solved |\n'
        '| --- | ---: | ---: | ---: |\n'
        '| Light | ${lights.length} | $accepted | $solved |\n'
        '| Dark | ${_countOf(images, "dark")} | — | — |\n'
        '| Flat | ${_countOf(images, "flat")} | — | — |\n'
        '| Bias | ${_countOf(images, "bias")} | — | — |\n'
        '\n'
        '**Accepted integration time:** ${_humanDuration(Duration(seconds: integrationSeconds.round()))}.';
  }

  int _countOf(List<CapturedImage> images, String type) =>
      images.where((i) => i.frameType.toLowerCase() == type).length;

  String _photometrySnapshot(
    List<FramePhotometricCalibrationRow> calibrations,
  ) {
    final calibrated = calibrations
        .where(
          (c) => c.isCalibrated && c.zeroPoint != null && c.zeroPoint!.isFinite,
        )
        .toList(growable: false);
    if (calibrated.isEmpty) {
      return '## Photometry\n'
          'No photometric calibration produced this session. This usually means '
          'too few frames solved against the catalog (need ≥ 5–10 calibrated '
          'frames before a transparency model stabilises).';
    }
    final zps = calibrated.map((c) => c.zeroPoint!).toList()..sort();
    final median = zps[zps.length ~/ 2];
    final mean = zps.reduce((a, b) => a + b) / zps.length;
    final range = zps.last - zps.first;
    final latest = calibrated.last;
    final lim5 =
        calibrated
            .map((c) => c.limitingMag5Sigma)
            .whereType<double>()
            .where((v) => v.isFinite)
            .toList()
          ..sort();
    final limStr = lim5.isEmpty
        ? '—'
        : 'median ${lim5[lim5.length ~/ 2].toStringAsFixed(2)} mag';
    final catalog = calibrated.map((c) => c.catalogSource).toSet().join(', ');
    return '## Photometry\n'
        '- **Latest zero point:** ${latest.zeroPoint!.toStringAsFixed(2)} mag '
        '(${latest.matchedStarCount} catalog stars matched, RMS '
        '${latest.calibrationRms.toStringAsFixed(3)})\n'
        '- **Median ZP across ${calibrated.length} frames:** ${median.toStringAsFixed(2)} mag '
        '(mean ${mean.toStringAsFixed(2)}, range ${range.toStringAsFixed(2)} mag)\n'
        '- **Limiting magnitude (5σ):** $limStr\n'
        '- **Catalog source(s):** $catalog\n';
  }

  String _transparencySnapshot(List<TransparencySampleRow> samples) {
    if (samples.isEmpty) {
      return '## Transparency\n'
          'No transparency samples produced. A transparency estimate needs '
          'at least 5 calibrated frames to stabilise — likely few frames '
          'reached calibration tonight.';
    }
    final values = samples
        .map((s) => s.transparencyPercent)
        .toList(growable: false);
    final mean = values.reduce((a, b) => a + b) / values.length;
    final minV = values.reduce(math.min);
    final maxV = values.reduce(math.max);
    final latest = samples.last;
    final buckets = <String, int>{};
    for (final s in samples) {
      buckets[s.qualityBucket] = (buckets[s.qualityBucket] ?? 0) + 1;
    }
    final dominant = buckets.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));
    return '## Transparency\n'
        '- **Latest:** ${latest.transparencyPercent.toStringAsFixed(0)}% '
        '(${latest.qualityBucket})\n'
        '- **Mean / range:** ${mean.toStringAsFixed(0)}% '
        '(${minV.toStringAsFixed(0)}% – ${maxV.toStringAsFixed(0)}%)\n'
        '- **Dominant bucket:** ${dominant.first.key} (${dominant.first.value} of ${samples.length} samples)\n';
  }

  String _fieldQuality(List<ScienceFrameQualityMetricsRow> metrics) {
    if (metrics.isEmpty) {
      return '## Field quality\n'
          'No frame-quality metrics produced. Either frame-quality maps are '
          'disabled in settings or no eligible light frames reached the '
          'pipeline.';
    }
    final latest = metrics.last;
    final allCv = metrics.map((m) => m.uniformityCv).toList(growable: false);
    final meanCv = allCv.reduce((a, b) => a + b) / allCv.length;
    final clipFrames = metrics
        .where((m) => m.highClipPercent > 0.5 || m.lowClipPercent > 0.5)
        .length;
    return '## Field quality\n'
        '- **Latest frame:** background ${latest.background.toStringAsFixed(0)} ADU, '
        'SNR ${latest.snr.toStringAsFixed(1)}, uniformity CV '
        '${latest.uniformityCv.toStringAsFixed(3)}\n'
        '- **Mean uniformity CV across session:** ${meanCv.toStringAsFixed(3)} '
        '(>0.28 is a gradient warning)\n'
        '- **Frames with clipping:** $clipFrames of ${metrics.length}\n';
  }

  String _filterBreakdown(List<CapturedImage> images) {
    final perFilter = <String, ({int frames, double seconds})>{};
    for (final image in images) {
      if (image.frameType.toLowerCase() != 'light' || !image.isAccepted) {
        continue;
      }
      final filter = (image.filter ?? '').isEmpty
          ? '(no filter)'
          : image.filter!;
      final existing = perFilter[filter] ?? (frames: 0, seconds: 0.0);
      perFilter[filter] = (
        frames: existing.frames + 1,
        seconds: existing.seconds + image.exposureDuration,
      );
    }
    if (perFilter.isEmpty) {
      return '## Filter breakdown\n'
          'No accepted light frames to break out.';
    }
    final rows = perFilter.entries
        .map((entry) {
          return '| ${entry.key} | ${entry.value.frames} | ${_humanDuration(Duration(seconds: entry.value.seconds.round()))} |';
        })
        .join('\n');
    return '## Filter breakdown\n'
        '| Filter | Frames | Integration |\n'
        '| --- | ---: | ---: |\n$rows';
  }

  String _movingObjectCandidates(List<MovingObjectCandidateRow> rows) {
    if (rows.isEmpty) {
      return '## Moving objects\n'
          'No candidates flagged tonight.';
    }
    final lines = StringBuffer('## Moving objects\n');
    lines.writeln(
      '| Candidate | RA (deg) | Dec (deg) | Motion ("/min) | Confidence |',
    );
    lines.writeln('| --- | ---: | ---: | ---: | ---: |');
    for (final r in rows) {
      lines.writeln(
        '| ${r.objectName ?? r.candidateId} | ${r.raDegrees.toStringAsFixed(4)} | ${r.decDegrees.toStringAsFixed(4)} | ${r.motionArcsecPerMinute.toStringAsFixed(2)} | ${(r.confidence * 100).toStringAsFixed(0)}% |',
      );
    }
    return lines.toString();
  }

  String _humanDuration(Duration d) {
    if (d.inSeconds <= 0) return '0s';
    final hours = d.inHours;
    final minutes = d.inMinutes.remainder(60);
    final seconds = d.inSeconds.remainder(60);
    if (hours > 0) return '${hours}h ${minutes}m ${seconds}s';
    if (minutes > 0) return '${minutes}m ${seconds}s';
    return '${seconds}s';
  }
}

/// Riverpod provider — the exporter is stateless beyond its DAO refs, so
/// we can construct it on every read with no performance penalty.
final scienceReportExporterProvider = Provider<ScienceReportExporter>((ref) {
  return ScienceReportExporter(
    imagesDao: ref.watch(imagesDaoProvider),
    scienceDao: ref.watch(scienceDaoProvider),
    sessionsDao: ref.watch(sessionsDaoProvider),
    targetsDao: ref.watch(targetsDaoProvider),
  );
});
