// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../error.dart';
import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `run_decision_event_loop`, `run_sequencer_event_loop`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `api_sequencer_event_stream`

/// Subscribe to sequencer events and forward them to the main event stream
Future<void> apiSequencerSubscribeEvents() => RustLib.instance.api
    .crateApiSequencerEventBridgeApiSequencerSubscribeEvents();
