// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../error.dart';
import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `serialize_node_definition`, `serialize_sequence_definition`

/// Create an exposure node configuration
String apiCreateExposureNode({
  required String id,
  required String name,
  required double durationSecs,
  required int count,
  String? filter,
  int? filterIndex,
  int? gain,
  int? offset,
  required int binning,
  int? ditherEvery,
}) => RustLib.instance.api.crateApiSequencerNodeFactoryApiCreateExposureNode(
  id: id,
  name: name,
  durationSecs: durationSecs,
  count: count,
  filter: filter,
  filterIndex: filterIndex,
  gain: gain,
  offset: offset,
  binning: binning,
  ditherEvery: ditherEvery,
);

/// Create a slew node configuration
String apiCreateSlewNode({
  required String id,
  required String name,
  required int useTargetCoords,
  double? customRa,
  double? customDec,
}) => RustLib.instance.api.crateApiSequencerNodeFactoryApiCreateSlewNode(
  id: id,
  name: name,
  useTargetCoords: useTargetCoords,
  customRa: customRa,
  customDec: customDec,
);

/// Create a center node configuration
String apiCreateCenterNode({
  required String id,
  required String name,
  required int useTargetCoords,
  required double accuracyArcsec,
  required int maxAttempts,
  required double exposureDuration,
}) => RustLib.instance.api.crateApiSequencerNodeFactoryApiCreateCenterNode(
  id: id,
  name: name,
  useTargetCoords: useTargetCoords,
  accuracyArcsec: accuracyArcsec,
  maxAttempts: maxAttempts,
  exposureDuration: exposureDuration,
);

/// Create an autofocus node configuration
String apiCreateAutofocusNode({
  required String id,
  required String name,
  required int stepSize,
  required int stepsOut,
  required double exposureDuration,
  required String method,
}) => RustLib.instance.api.crateApiSequencerNodeFactoryApiCreateAutofocusNode(
  id: id,
  name: name,
  stepSize: stepSize,
  stepsOut: stepsOut,
  exposureDuration: exposureDuration,
  method: method,
);

/// Create a filter change node configuration
String apiCreateFilterNode({
  required String id,
  required String name,
  required String filterName,
}) => RustLib.instance.api.crateApiSequencerNodeFactoryApiCreateFilterNode(
  id: id,
  name: name,
  filterName: filterName,
);

/// Create a target group node configuration (legacy - use target_header instead)
String apiCreateTargetGroupNode({
  required String id,
  required String name,
  required String targetName,
  required double raHours,
  required double decDegrees,
  double? rotation,
  double? minAltitude,
  double? maxAltitude,
  required int priority,
  required List<String> children,
}) => RustLib.instance.api.crateApiSequencerNodeFactoryApiCreateTargetGroupNode(
  id: id,
  name: name,
  targetName: targetName,
  raHours: raHours,
  decDegrees: decDegrees,
  rotation: rotation,
  minAltitude: minAltitude,
  maxAltitude: maxAltitude,
  priority: priority,
  children: children,
);

/// Create a target header node configuration
///
/// `integration_budget_json` (optional) is a JSON-encoded
/// [`nightshade_sequencer::IntegrationBudget`] payload mirroring the
/// Dart-side `IntegrationBudget` model. Passing `None` leaves the
/// target without a budget (current behaviour); passing a valid JSON
/// string installs the budget on the TargetHeader.
String apiCreateTargetHeaderNode({
  required String id,
  required String name,
  required String targetName,
  required double raHours,
  required double decDegrees,
  double? rotation,
  double? minAltitude,
  double? maxAltitude,
  required int priority,
  PlatformInt64? startAfter,
  PlatformInt64? endBefore,
  String? mosaicPanelJson,
  String? integrationBudgetJson,
  required List<String> children,
}) =>
    RustLib.instance.api.crateApiSequencerNodeFactoryApiCreateTargetHeaderNode(
      id: id,
      name: name,
      targetName: targetName,
      raHours: raHours,
      decDegrees: decDegrees,
      rotation: rotation,
      minAltitude: minAltitude,
      maxAltitude: maxAltitude,
      priority: priority,
      startAfter: startAfter,
      endBefore: endBefore,
      mosaicPanelJson: mosaicPanelJson,
      integrationBudgetJson: integrationBudgetJson,
      children: children,
    );

/// Create a loop node configuration
String apiCreateLoopNode({
  required String id,
  required String name,
  int? iterations,
  required String condition,
  required List<String> children,
}) => RustLib.instance.api.crateApiSequencerNodeFactoryApiCreateLoopNode(
  id: id,
  name: name,
  iterations: iterations,
  condition: condition,
  children: children,
);

/// Create a delay node configuration
String apiCreateDelayNode({
  required String id,
  required String name,
  required double seconds,
}) => RustLib.instance.api.crateApiSequencerNodeFactoryApiCreateDelayNode(
  id: id,
  name: name,
  seconds: seconds,
);

/// Create a park node configuration
String apiCreateParkNode({required String id, required String name}) => RustLib
    .instance
    .api
    .crateApiSequencerNodeFactoryApiCreateParkNode(id: id, name: name);

/// Create an unpark node configuration
String apiCreateUnparkNode({required String id, required String name}) =>
    RustLib.instance.api.crateApiSequencerNodeFactoryApiCreateUnparkNode(
      id: id,
      name: name,
    );

/// Create a cool camera node configuration
String apiCreateCoolCameraNode({
  required String id,
  required String name,
  required double targetTemp,
  double? durationMins,
}) => RustLib.instance.api.crateApiSequencerNodeFactoryApiCreateCoolCameraNode(
  id: id,
  name: name,
  targetTemp: targetTemp,
  durationMins: durationMins,
);

/// Create a warm camera node configuration
String apiCreateWarmCameraNode({
  required String id,
  required String name,
  required double ratePerMin,
  double? targetTemp,
}) => RustLib.instance.api.crateApiSequencerNodeFactoryApiCreateWarmCameraNode(
  id: id,
  name: name,
  ratePerMin: ratePerMin,
  targetTemp: targetTemp,
);

/// Create a dither node configuration
String apiCreateDitherNode({
  required String id,
  required String name,
  required double pixels,
  required double settlePixels,
  required double settleTime,
  required double settleTimeout,
  required int raOnly,
}) => RustLib.instance.api.crateApiSequencerNodeFactoryApiCreateDitherNode(
  id: id,
  name: name,
  pixels: pixels,
  settlePixels: settlePixels,
  settleTime: settleTime,
  settleTimeout: settleTimeout,
  raOnly: raOnly,
);

/// Create a wait time node configuration
String apiCreateWaitTimeNode({
  required String id,
  required String name,
  PlatformInt64? waitUntil,
  String? twilightType,
}) => RustLib.instance.api.crateApiSequencerNodeFactoryApiCreateWaitTimeNode(
  id: id,
  name: name,
  waitUntil: waitUntil,
  twilightType: twilightType,
);

/// Create a notification node configuration
String apiCreateNotificationNode({
  required String id,
  required String name,
  required String title,
  required String message,
  required String level,
}) =>
    RustLib.instance.api.crateApiSequencerNodeFactoryApiCreateNotificationNode(
      id: id,
      name: name,
      title: title,
      message: message,
      level: level,
    );

/// Create a script node configuration
String apiCreateScriptNode({
  required String id,
  required String name,
  required String scriptPath,
  required List<String> arguments,
  int? timeoutSecs,
}) => RustLib.instance.api.crateApiSequencerNodeFactoryApiCreateScriptNode(
  id: id,
  name: name,
  scriptPath: scriptPath,
  arguments: arguments,
  timeoutSecs: timeoutSecs,
);

/// Create a rotator node configuration
String apiCreateRotatorNode({
  required String id,
  required String name,
  required double targetAngle,
  required int relative,
}) => RustLib.instance.api.crateApiSequencerNodeFactoryApiCreateRotatorNode(
  id: id,
  name: name,
  targetAngle: targetAngle,
  relative: relative,
);

/// Build a complete sequence definition from nodes
String apiBuildSequence({
  required String id,
  required String name,
  String? description,
  required List<String> nodeJsons,
  String? rootNodeId,
}) => RustLib.instance.api.crateApiSequencerNodeFactoryApiBuildSequence(
  id: id,
  name: name,
  description: description,
  nodeJsons: nodeJsons,
  rootNodeId: rootNodeId,
);
