// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../error.dart';
import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Set simulation mode (use mock devices instead of real hardware)
Future<void> apiSequencerSetSimulationMode({required bool enabled}) => RustLib
    .instance
    .api
    .crateApiSequencerRuntimeConfigApiSequencerSetSimulationMode(
      enabled: enabled,
    );

/// Set connected devices for the sequencer
Future<void> apiSequencerSetDevices({
  String? cameraId,
  String? mountId,
  String? focuserId,
  String? filterwheelId,
  String? rotatorId,
  List<String>? filterNames,
  Map<String, int>? filterFocusOffsets,
}) => RustLib.instance.api.crateApiSequencerRuntimeConfigApiSequencerSetDevices(
  cameraId: cameraId,
  mountId: mountId,
  focuserId: focuserId,
  filterwheelId: filterwheelId,
  rotatorId: rotatorId,
  filterNames: filterNames,
  filterFocusOffsets: filterFocusOffsets,
);

/// Set the safety fail mode for the sequencer.
/// This determines behavior when safety devices fail or are unavailable:
/// - "fail_closed": Treat unavailable safety data as unsafe
/// - "fail_open": Treat unavailable safety data as safe
/// - "warn_only": Preserve the previous safety state and emit a warning event
Future<void> apiSequencerSetSafetyFailMode({required String mode}) => RustLib
    .instance
    .api
    .crateApiSequencerRuntimeConfigApiSequencerSetSafetyFailMode(mode: mode);

/// Set the safety/humidity polling interval for the sequencer.
/// Must be between 5 seconds and 3600 seconds. The executor applies the
/// update live without restarting the current sequence.
Future<void> apiSequencerSetSafetyCheckIntervalSeconds({
  required int seconds,
}) => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerSetSafetyCheckIntervalSeconds(
      seconds: seconds,
    );

/// Set the save path for sequencer images.
/// This is the base directory where captured images will be saved.
/// If not set (or set to None), images will NOT be saved to disk.
Future<void> apiSequencerSetSavePath({String? path}) => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerSetSavePath(path: path);

/// Update dither configuration at runtime while a sequence is running or paused.
/// The updated values are stored on the executor and will be used by subsequent
/// trigger-initiated dithers and checkpoint resumes.
Future<void> apiSequencerUpdateDitherConfig({
  required double pixels,
  required double settlePixels,
  required double settleTime,
  required double settleTimeout,
  required bool raOnly,
}) => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerUpdateDitherConfig(
      pixels: pixels,
      settlePixels: settlePixels,
      settleTime: settleTime,
      settleTimeout: settleTimeout,
      raOnly: raOnly,
    );

/// Push the operator's meridian-flip settings onto the standard
/// `meridian_flip` trigger.
///
/// `config_json` is a serialised `MeridianFlipConfig` — the SAME shape the Dart
/// side already builds for a `MeridianFlipNode`, so there is exactly one
/// wire format for meridian settings and one place to keep in sync.
///
/// Why JSON rather than a typed FRB struct: `MeridianFlipConfig` has 21 fields
/// including a `Vec<f64>` retry ladder and two enums, and every one of them is
/// already covered by the serde contract the sequence JSON uses. Mirroring it
/// as an FRB struct would duplicate that contract and give it two places to
/// drift.
///
/// Without this call the trigger keeps `MeridianFlipConfig::default()` for the
/// whole run and the user's Settings → Meridian Flip panel is inert on the
/// trigger path.
Future<void> apiSequencerUpdateMeridianFlipConfig({
  required String configJson,
}) => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerUpdateMeridianFlipConfig(
      configJson: configJson,
    );

/// Update observer location at runtime while a sequence is running or paused.
/// Updates the executor's stored latitude/longitude so altitude-based triggers
/// use the correct location on their next evaluation.
Future<void> apiSequencerUpdateLocation({
  double? latitude,
  double? longitude,
}) => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerUpdateLocation(
      latitude: latitude,
      longitude: longitude,
    );

/// stage per-target / per-filter carry-over integration so the
/// next `sequencerStart()` seeds the IntegrationBudget tracker with frames
/// already captured in prior sessions. The Dart `SequenceExecutor.start()`
/// calls this once per target after reading `sessionHandoffDecisionProvider`:
///
///   * `Resume`      → supply the prior per-filter totals.
///   * `Restart`     → supply an empty inner map (zeroes the carry-over).
///   * `ContinueNew` → omit the target from the call (default behaviour).
///
/// `carry_over` shape: `target_id` -> { `filter_name` -> `seconds` }.
/// The Rust side merges entries (last-write-wins per target_id), then drains
/// the staged map on the next `start()`.
Future<void> apiSequencerUpdatePendingIntegrationCarryOver({
  required Map<String, Map<String, double>> carryOver,
}) => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerUpdatePendingIntegrationCarryOver(
      carryOver: carryOver,
    );

/// Update filter focus offsets at runtime while a sequence is running or paused.
/// Updates the executor's stored offsets so subsequent filter changes apply
/// the correct focus compensation.
Future<void> apiSequencerUpdateFilterOffsets({
  required Map<String, int> offsets,
}) => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerUpdateFilterOffsets(
      offsets: offsets,
    );

/// update the autofocus-interval trigger cadence at runtime.
/// The default in `default_autofocus_interval_frames()` is 25 frames; this
/// is wrong for both very-short (5 s) and very-long (5 min) subs, so the UI
/// must let the user override it. `every_n_frames == 0` is rejected because
/// the trigger evaluator disables the periodic AF when the cadence is zero,
/// which would silently turn AF off ("errors are a feature").
Future<void> apiSequencerUpdateAutofocusInterval({required int everyNFrames}) =>
    RustLib.instance.api
        .crateApiSequencerRuntimeConfigApiSequencerUpdateAutofocusInterval(
          everyNFrames: everyNFrames,
        );

/// Push the operator's autofocus settings so trigger-fired refocus uses them.
///
/// The only source of trigger-autofocus tuning used to be an Autofocus node
/// inside the sequence. A sequence without one — which is exactly the sequence
/// whose interval trigger fires unattended — therefore ran every refocus on
/// library defaults, ignoring the operator's step size, exposure, backlash,
/// failure tolerance and failure action. An Autofocus node still wins at
/// `start()`: a node is a per-sequence decision, this is a global one.
///
/// Takes the same JSON shape the sequence's Autofocus node carries, so the
/// Dart side has exactly one serializer to keep correct.
Future<void> apiSequencerUpdateAutofocusConfig({required String configJson}) =>
    RustLib.instance.api
        .crateApiSequencerRuntimeConfigApiSequencerUpdateAutofocusConfig(
          configJson: configJson,
        );

/// update the global default image-grading thresholds at runtime.
///
/// All fields are optional; when `enabled` is `false` an `ImageQualityCheck`
/// is NOT constructed (grading disabled globally — per-node `quality_check`
/// on TakeExposure still wins). The Dart `enableImageGrading` toggle on
/// app settings drives this directly.
Future<void> apiSequencerUpdateDefaultQualityCheck({
  double? hfrThreshold,
  double? hfrBaselinePercent,
  double? eccentricityThreshold,
  int? starCountMin,
  required int maxConsecutiveRejects,
  required bool enabled,
}) => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerUpdateDefaultQualityCheck(
      hfrThreshold: hfrThreshold,
      hfrBaselinePercent: hfrBaselinePercent,
      eccentricityThreshold: eccentricityThreshold,
      starCountMin: starCountMin,
      maxConsecutiveRejects: maxConsecutiveRejects,
      enabled: enabled,
    );

/// update the reject-folder override at runtime. Empty string =>
/// None (i.e. fall back to `<save_path>/Reject/`).
Future<void> apiSequencerUpdateRejectFolderPath({String? path}) => RustLib
    .instance
    .api
    .crateApiSequencerRuntimeConfigApiSequencerUpdateRejectFolderPath(
      path: path,
    );

/// push observer / equipment identification to the executor so
/// the next FITS save stamps real keywords (OBSERVER, TELESCOP, FOCALLEN,
/// APTDIA, INSTRUME, SITEELEV). Every field is optional because in
/// headless / no-profile runs we'd rather omit the keyword than emit a
/// sentinel — silent fallbacks are bugs.
Future<void> apiSequencerUpdateObserverProfile({
  String? observerName,
  double? siteElevationM,
  String? cameraMake,
  String? cameraModel,
  String? telescopeName,
  double? telescopeFocalLengthMm,
  double? telescopeApertureMm,
}) => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerUpdateObserverProfile(
      observerName: observerName,
      siteElevationM: siteElevationM,
      cameraMake: cameraMake,
      cameraModel: cameraModel,
      telescopeName: telescopeName,
      telescopeFocalLengthMm: telescopeFocalLengthMm,
      telescopeApertureMm: telescopeApertureMm,
    );

/// Push the latest cloud-motion analyzer reading into the executor.
///
/// All fields are optional because the Dart analyzer may not yet have
/// enough radar history to produce every quantity. `None` values disable
/// the corresponding evaluator branch rather than firing on a default —
/// silently picking a sentinel would mask analyzer failures.
///
/// `predicted_clear_sky_alt` / `predicted_clear_sky_az` must be either
/// both `Some` or both `None`; a half-specified direction is logged at
/// WARN and treated as no-direction.
Future<void> apiSequencerUpdateCloudMotion({
  double? currentCoverPercent,
  double? predictedArrivalMinutes,
  double? predictedOpeningMinutes,
  double? predictedOpeningDurationSecs,
  double? predictedClearSkyAlt,
  double? predictedClearSkyAz,
}) => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerUpdateCloudMotion(
      currentCoverPercent: currentCoverPercent,
      predictedArrivalMinutes: predictedArrivalMinutes,
      predictedOpeningMinutes: predictedOpeningMinutes,
      predictedOpeningDurationSecs: predictedOpeningDurationSecs,
      predictedClearSkyAlt: predictedClearSkyAlt,
      predictedClearSkyAz: predictedClearSkyAz,
    );

/// Full-night audit 2026-06-04 (defense-in-depth) — push the Dart-side
/// weather-safety verdict into the executor.
///
/// The in-sequencer `WeatherUnsafe` trigger keys off the hardware
/// `safety_is_safe` poll only; a rig WITHOUT a hardware safety device never
/// aborts via that trigger even when `weatherSafetyProvider` computed UNSAFE
/// from the user's configured thresholds + API/cloud sources. This carries
/// that verdict as an additional unsafe source folded (OR-of-unsafe) into the
/// trigger evaluation — it can only make the rig safer, never less safe than
/// the hardware reading.
///
/// `unsafe_override = Some(true)` => Dart computed UNSAFE; `Some(false)` =>
/// Dart computed SAFE; `None` => Dart abstains (provider disabled / no data)
/// and this layer is inert.
Future<void> apiSequencerUpdateWeatherVerdict({bool? unsafeOverride}) => RustLib
    .instance
    .api
    .crateApiSequencerRuntimeConfigApiSequencerUpdateWeatherVerdict(
      unsafeOverride: unsafeOverride,
    );

/// JSON-serialised cloud-motion snapshot for the run
/// dashboard. Returns `Ok(None)` when no data has been pushed yet.
Future<String?> apiSequencerGetCloudMotionJson() => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerGetCloudMotionJson();

/// Push the latest live sky-brightness reading to the executor.
///
/// `mag` is the sky brightness in mag/arcsec² (bigger = darker). Pass
/// `None` when the tracker has lost lock — the adapter then falls back to
/// the nominal duration and emits a structured `Unavailable` event.
Future<void> apiSequencerUpdateSkyBrightness({double? mag}) => RustLib
    .instance
    .api
    .crateApiSequencerRuntimeConfigApiSequencerUpdateSkyBrightness(mag: mag);

/// Push the global default sky-brightness adaptive-exposure config to the
/// executor. Per-node `ExposureConfig.adaptive_exposure` still wins; this
/// is the runtime fallback applied to TakeExposure nodes that have no
/// own block.
///
/// Pass `enabled = false` to disable the feature globally. The per-filter
/// maps are flattened into parallel arrays because FRB cannot bridge
/// `HashMap<String, T>` directly — Dart serialises its own filter map to
/// the (`*_filters`, `*_values`) pair shape.
Future<void> apiSequencerUpdateDefaultAdaptiveExposure({
  required bool enabled,
  required double targetSnr,
  required double referenceSkyBrightnessMag,
  required double minExposureSecs,
  required double maxExposureSecs,
  required List<String> perFilterEnabledKeys,
  required List<bool> perFilterEnabledValues,
  required List<String> perFilterMinKeys,
  required List<double> perFilterMinValues,
  required List<String> perFilterMaxKeys,
  required List<double> perFilterMaxValues,
}) => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerUpdateDefaultAdaptiveExposure(
      enabled: enabled,
      targetSnr: targetSnr,
      referenceSkyBrightnessMag: referenceSkyBrightnessMag,
      minExposureSecs: minExposureSecs,
      maxExposureSecs: maxExposureSecs,
      perFilterEnabledKeys: perFilterEnabledKeys,
      perFilterEnabledValues: perFilterEnabledValues,
      perFilterMinKeys: perFilterMinKeys,
      perFilterMinValues: perFilterMinValues,
      perFilterMaxKeys: perFilterMaxKeys,
      perFilterMaxValues: perFilterMaxValues,
    );

/// disable the global default adaptive-exposure config
/// (push `None`). Convenience entry-point so the Dart side doesn't have
/// to pass a sentinel struct just to disable.
Future<void> apiSequencerClearDefaultAdaptiveExposure() => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerClearDefaultAdaptiveExposure();

/// Operator pressed "Try Now" on the Run Dashboard banner — punch through
/// the wait timer and force the next recovery attempt immediately. No-op
/// when the executor is not currently in `Recovering`.
Future<void> apiSequencerRecoveryTryNow() => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerRecoveryTryNow();

/// Operator pressed "Abort" on the Run Dashboard banner — exits the recovery
/// loop and transitions the executor to `Failed`. No-op when not in
/// `Recovering`.
Future<void> apiSequencerRecoveryAbort() => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerRecoveryAbort();

/// Push updated recovery defaults into the executor's runtime config. The
/// next recovery entry uses these values; an in-flight loop continues with
/// the values that were live when it entered.
///
/// Validation here matches the gate the Rust sequencer applies internally:
/// both `retry_interval_secs` and `max_duration_secs` must be > 0. We
/// surface a structured InvalidParameter error so the Dart settings page
/// can render a precise validation message instead of "unknown error".
Future<void> apiSequencerUpdateRecoveryConfig({
  required RecoveryConfigUpdate update,
}) => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerUpdateRecoveryConfig(
      update: update,
    );

/// JSON-serialised snapshot of the current in-flight `RecoveryContext`.
/// Returns `None` when the executor is not currently in `Recovering`.
///
/// JSON-string-over-bridge is intentional: the Dart side already owns a
/// hand-written `RecoveryStatus.fromJson` mirror (see
/// `nightshade_core/lib/src/models/sequencer/recovery_status.dart`) so
/// piping serde JSON across is cheaper than asking FRB to bridge the
/// chrono-dependent `RecoveryContext` Rust struct.
Future<String?> apiSequencerGetCurrentRecoveryJson() => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerGetCurrentRecoveryJson();

/// JSON-serialised dump of every completed recovery loop since the executor
/// was constructed. Surfaced for the post-session report dialog. Returns an
/// empty JSON array `"[]"` when no recoveries have completed yet.
Future<String> apiSequencerGetRecoveryHistoryJson() => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerGetRecoveryHistoryJson();

/// Replay Debug — stamp the active `sequence_runs.id` onto the
/// executor so every subsequent emitted DecisionEvent carries it as
/// `sequence_run_id`. Called by the Dart side immediately after the
/// `sequence_runs` row is inserted.
///
/// Pass `None` (Dart `null`) to clear the slot — useful at run end /
/// reset.
Future<void> apiSequencerSetActiveSequenceRunId({
  PlatformInt64? sequenceRunId,
}) => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerSetActiveSequenceRunId(
      sequenceRunId: sequenceRunId,
    );

/// Replay Debug — read back the currently-stamped
/// `sequence_runs.id`. Used by tests and as a sanity check from the
/// Dart side.
Future<PlatformInt64?> apiSequencerGetActiveSequenceRunId() => RustLib
    .instance
    .api
    .crateApiSequencerRuntimeConfigApiSequencerGetActiveSequenceRunId();

/// Replay Debug — runtime toggle for decision emission. When
/// `enabled = false`, the executor short-circuits all decision sends
/// (no channel publish, no allocation) so power users who don't want
/// the replay log can opt out. Defaults to ON.
Future<void> apiSequencerSetDecisionLoggingEnabled({required bool enabled}) =>
    RustLib.instance.api
        .crateApiSequencerRuntimeConfigApiSequencerSetDecisionLoggingEnabled(
          enabled: enabled,
        );

/// Replay Debug — readback for the runtime toggle.
Future<bool> apiSequencerGetDecisionLoggingEnabled() => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerGetDecisionLoggingEnabled();

/// Push the latest composite sky-conditions score to the executor. All
/// fields are optional because the Dart composer may not have every axis
/// (e.g. no weather station => `wind_score = None`); the score itself
/// is computed by Dart from the available axes using
/// [`ConditionsScoreWeights`].
///
/// Pass `score = None` to clear the slot (telemetry lost — the
/// scheduler then falls back to the ordinary ranking).
Future<void> apiSequencerUpdateConditionsScore({
  double? score,
  double? transparencyScore,
  double? seeingScore,
  double? cloudScore,
  double? windScore,
  required double transparencyWeight,
  required double seeingWeight,
  required double cloudWeight,
  required double windWeight,
  required PlatformInt64 generatedUnixSecs,
}) => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerUpdateConditionsScore(
      score: score,
      transparencyScore: transparencyScore,
      seeingScore: seeingScore,
      cloudScore: cloudScore,
      windScore: windScore,
      transparencyWeight: transparencyWeight,
      seeingWeight: seeingWeight,
      cloudWeight: cloudWeight,
      windWeight: windWeight,
      generatedUnixSecs: generatedUnixSecs,
    );

/// JSON-serialised snapshot of the live conditions score + adaptive
/// swap accounting (last swap timestamp, current tier, hysteresis
/// countdown info) for the Run Dashboard "Adaptive Conditions" panel.
/// Returns `Ok(None)` when no telemetry has been pushed since startup.
Future<String?> apiSequencerGetAdaptiveSwapJson() => RustLib.instance.api
    .crateApiSequencerRuntimeConfigApiSequencerGetAdaptiveSwapJson();

/// User-tunable recovery defaults pushed from the Settings > Recovery Mode
/// page. Field-for-field mirror of
/// `nightshade_sequencer::recovery::RecoveryRuntimeConfig` so the FRB wire
/// shape stays stable across regen cycles.
class RecoveryConfigUpdate {
  final double retryIntervalSecs;
  final double maxDurationSecs;
  final bool stopTrackingDuringRecovery;
  final bool abortOnMeridian;
  final bool audibleAlertWhenEntered;

  const RecoveryConfigUpdate({
    required this.retryIntervalSecs,
    required this.maxDurationSecs,
    required this.stopTrackingDuringRecovery,
    required this.abortOnMeridian,
    required this.audibleAlertWhenEntered,
  });

  @override
  int get hashCode =>
      retryIntervalSecs.hashCode ^
      maxDurationSecs.hashCode ^
      stopTrackingDuringRecovery.hashCode ^
      abortOnMeridian.hashCode ^
      audibleAlertWhenEntered.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecoveryConfigUpdate &&
          runtimeType == other.runtimeType &&
          retryIntervalSecs == other.retryIntervalSecs &&
          maxDurationSecs == other.maxDurationSecs &&
          stopTrackingDuringRecovery == other.stopTrackingDuringRecovery &&
          abortOnMeridian == other.abortOnMeridian &&
          audibleAlertWhenEntered == other.audibleAlertWhenEntered;
}
