part of '../scheduler_engine.dart';

/// Snapshot of a candidate target plus the live data the engine needs to
/// score it. The engine doesn't read the Targets DAO directly; the caller
/// (provider layer) builds this from drift rows so the engine remains
/// database-agnostic and easily unit-testable.
class SchedulerCandidate {
  /// Drift `targets.id`.
  final int targetId;
  final String name;
  final double raHours;
  final double decDegrees;

  /// User-set priority on the target row (higher = better).
  final int userPriority;

  /// Integration goals attached to this target.
  final List<IntegrationGoal> goals;

  /// Per-(goal) captured-frame counts, in the same order as `goals`.
  /// Length must match `goals.length`.
  final List<int> capturedCounts;

  /// Hard constraints attached to this target.
  final List<TargetConstraint> constraints;

  /// Resolved horizon profiles keyed by HorizonProfiles.id, for any
  /// constraint referencing one. May be empty if none used.
  final Map<int, HorizonProfile> horizonProfiles;

  /// Filters available in the current equipment profile (case-preserved).
  /// A target needing a filter not in this list fails the equipment
  /// availability hard constraint.
  final List<String> availableFilters;

  /// True when the target represents a multi-panel mosaic plan.
  final bool isMosaicTarget;

  SchedulerCandidate({
    required this.targetId,
    required this.name,
    required this.raHours,
    required this.decDegrees,
    required this.userPriority,
    required this.goals,
    required this.capturedCounts,
    required this.constraints,
    required this.horizonProfiles,
    required this.availableFilters,
    this.isMosaicTarget = false,
  }) {
    if (capturedCounts.length != goals.length) {
      throw ArgumentError(
        'capturedCounts length (${capturedCounts.length}) must match goals length (${goals.length})',
      );
    }
  }
}

/// Site location used for altitude/azimuth and twilight math.
class SchedulerSite {
  final double latitudeDegrees;
  final double longitudeDegrees;

  /// User's local-timezone offset used to evaluate timeWindow constraints
  /// in the operator's clock rather than UTC.
  final Duration localOffset;

  const SchedulerSite({
    required this.latitudeDegrees,
    required this.longitudeDegrees,
    required this.localOffset,
  });
}

/// Sink for sequences generated by the engine. Concrete implementations
/// hand off to `SequencerService.startSequence(...)` or the
/// `SequenceExecutor.start()` provider. Tests inject a fake.
abstract class SchedulerSequenceSink {
  /// Called when the engine has selected a target and wants to start
  /// imaging. Implementations must persist or load the sequence and start
  /// it; the future completes once the sequencer accepts the sequence.
  Future<void> dispatchSequence(Sequence sequence);

  /// Called when the engine wants to pause whatever is currently running.
  Future<void> pauseSequence();

  /// Called when the engine wants to resume from pause.
  Future<void> resumeSequence();

  /// Called when the engine wants to stop the active sequence (e.g. on
  /// engine stop or a hard target swap).
  Future<void> stopSequence();
}
