part of '../scheduler_engine.dart';

/// An operator-correctable admission failure that leaves the scheduler idle.
class SchedulerStartException implements Exception {
  final String message;

  const SchedulerStartException(this.message);

  @override
  String toString() => message;
}

/// Snapshot of a candidate target plus the live data the engine needs to
/// score it. The engine doesn't read the Targets DAO directly; the caller
/// (provider layer) builds this from drift rows so the engine remains
/// database-agnostic and easily unit-testable.
class SchedulerCandidate {
  /// Drift `targets.id`.
  final int targetId;
  final String name;
  final double raHours;
  final double decDegrees;

  /// User-set priority on the target row (higher = better).
  final int userPriority;

  /// Integration goals attached to this target.
  final List<IntegrationGoal> goals;

  /// Per-(goal) captured-frame counts, in the same order as `goals`.
  /// Length must match `goals.length`.
  final List<int> capturedCounts;

  /// Hard constraints attached to this target.
  final List<TargetConstraint> constraints;

  /// Resolved horizon profiles keyed by HorizonProfiles.id, for any
  /// constraint referencing one. May be empty if none used.
  final Map<int, HorizonProfile> horizonProfiles;

  /// Filters available in the current equipment profile (case-preserved).
  /// A target needing a filter not in this list fails the equipment
  /// availability hard constraint.
  final List<String> availableFilters;

  /// True when the target represents a multi-panel mosaic plan.
  final bool isMosaicTarget;

  SchedulerCandidate({
    required this.targetId,
    required this.name,
    required this.raHours,
    required this.decDegrees,
    required this.userPriority,
    required this.goals,
    required this.capturedCounts,
    required this.constraints,
    required this.horizonProfiles,
    required this.availableFilters,
    this.isMosaicTarget = false,
  }) {
    if (capturedCounts.length != goals.length) {
      throw ArgumentError(
        'capturedCounts length (${capturedCounts.length}) must match goals length (${goals.length})',
      );
    }
  }
}

/// Result of the engine's pure [SchedulerEngine._evaluate] step: the fully
/// built [SchedulerDecision] plus the structured outcome the side-effecting
/// caller ([SchedulerEngine._evaluateOnce]) needs to act on.
///
/// [winner] is null when no candidate is eligible (the no-eligible/empty
/// paths). [isSwitch] mirrors `decision.isSwitch` and is the signal to
/// dispatch + re-arm the end-of-night park. Keeping these alongside the
/// decision lets the read-only preview path reuse [SchedulerEngine._evaluate]
/// without re-deriving them or touching engine state.
class _EvaluationOutcome {
  final SchedulerDecision decision;
  final TargetScore? winner;
  final bool isSwitch;

  const _EvaluationOutcome({
    required this.decision,
    required this.winner,
    required this.isSwitch,
  });
}

/// Site location used for altitude/azimuth and twilight math.
class SchedulerSite {
  final double latitudeDegrees;
  final double longitudeDegrees;

  /// User's local-timezone offset used to evaluate timeWindow constraints
  /// in the operator's clock rather than UTC.
  final Duration localOffset;

  const SchedulerSite({
    required this.latitudeDegrees,
    required this.longitudeDegrees,
    required this.localOffset,
  });
}

/// Sink for sequences generated by the engine. Concrete implementations
/// hand off to `SequencerService.startSequence(...)` or the
/// `SequenceExecutor.start()` provider. Tests inject a fake.
abstract class SchedulerSequenceSink {
  /// Called when the engine has selected a target and wants to start
  /// imaging. Implementations must persist or load the sequence and start
  /// it; the future completes once the sequencer accepts the sequence.
  Future<void> dispatchSequence(Sequence sequence);

  /// Called when the engine wants to pause whatever is currently running.
  Future<void> pauseSequence();

  /// Called when the engine wants to resume from pause.
  Future<void> resumeSequence();

  /// Called when the engine wants to stop the active sequence (e.g. on
  /// engine stop or a hard target swap).
  Future<void> stopSequence();

  /// Called exactly once when the autopilot is fully DISENGAGED (engine
  /// `stop()` / `dispose()`), as opposed to a mid-night target swap or a
  /// transient no-eligible tick (which use [stopSequence] and keep the
  /// autopilot engaged).
  ///
  /// Implementations restore manual ownership of the editor slot, returning the
  /// operator's stashed unsaved sequence that [dispatchSequence] preserved when
  /// the autopilot first took over. Default no-op so test/headless sinks that
  /// don't model editor ownership need no change.
  Future<void> releaseSequenceOwnership() async {}

  /// Called exactly once when the engine determines the observing night is
  /// genuinely over — every candidate is rejected AND the Sun has risen above
  /// the configured darkness limit ([SchedulerConfig.maxSunAltitudeDegrees]).
  ///
  /// This is the distinct end-of-night hook: [stopSequence] is also invoked on
  /// every mid-night target swap and on a transient no-eligible tick (clouds,
  /// all goals momentarily complete), so it cannot be used to park — that would
  /// park the mount on every swap. Implementations park the mount (stop
  /// tracking into the ground at dawn) and notify the operator. The engine
  /// guarantees this is called at most once per dawn transition; it re-arms
  /// only after the engine successfully dispatches another target (a new
  /// night begins).
  Future<void> parkForEndOfNight();
}
