/// IAU constellation abbreviation → full name.
///
/// Catalog rows (OpenNGC and the target library that mirrors them) store the
/// three-letter IAU abbreviation, which is what any UI listing constellations
/// would otherwise show the user — "CVn", "Cam", "Cep". Every surface that
/// puts a constellation in front of a human should resolve it through here so
/// there is exactly one spelling of "Canes Venatici" in the app.
const Map<String, String> kConstellationNamesByAbbreviation = {
  'AND': 'Andromeda',
  'ANT': 'Antlia',
  'APS': 'Apus',
  'AQR': 'Aquarius',
  'AQL': 'Aquila',
  'ARA': 'Ara',
  'ARI': 'Aries',
  'AUR': 'Auriga',
  'BOO': 'Boötes',
  'CAE': 'Caelum',
  'CAM': 'Camelopardalis',
  'CNC': 'Cancer',
  'CVN': 'Canes Venatici',
  'CMA': 'Canis Major',
  'CMI': 'Canis Minor',
  'CAP': 'Capricornus',
  'CAR': 'Carina',
  'CAS': 'Cassiopeia',
  'CEN': 'Centaurus',
  'CEP': 'Cepheus',
  'CET': 'Cetus',
  'CHA': 'Chamaeleon',
  'CIR': 'Circinus',
  'COL': 'Columba',
  'COM': 'Coma Berenices',
  'CRA': 'Corona Australis',
  'CRB': 'Corona Borealis',
  'CRV': 'Corvus',
  'CRT': 'Crater',
  'CRU': 'Crux',
  'CYG': 'Cygnus',
  'DEL': 'Delphinus',
  'DOR': 'Dorado',
  'DRA': 'Draco',
  'EQU': 'Equuleus',
  'ERI': 'Eridanus',
  'FOR': 'Fornax',
  'GEM': 'Gemini',
  'GRU': 'Grus',
  'HER': 'Hercules',
  'HOR': 'Horologium',
  'HYA': 'Hydra',
  'HYI': 'Hydrus',
  'IND': 'Indus',
  'LAC': 'Lacerta',
  'LEO': 'Leo',
  'LMI': 'Leo Minor',
  'LEP': 'Lepus',
  'LIB': 'Libra',
  'LUP': 'Lupus',
  'LYN': 'Lynx',
  'LYR': 'Lyra',
  'MEN': 'Mensa',
  'MIC': 'Microscopium',
  'MON': 'Monoceros',
  'MUS': 'Musca',
  'NOR': 'Norma',
  'OCT': 'Octans',
  'OPH': 'Ophiuchus',
  'ORI': 'Orion',
  'PAV': 'Pavo',
  'PEG': 'Pegasus',
  'PER': 'Perseus',
  'PHE': 'Phoenix',
  'PIC': 'Pictor',
  'PSC': 'Pisces',
  'PSA': 'Piscis Austrinus',
  'PUP': 'Puppis',
  'PYX': 'Pyxis',
  'RET': 'Reticulum',
  'SGE': 'Sagitta',
  'SGR': 'Sagittarius',
  'SCO': 'Scorpius',
  'SCL': 'Sculptor',
  'SCT': 'Scutum',
  'SER': 'Serpens',
  'SEX': 'Sextans',
  'TAU': 'Taurus',
  'TEL': 'Telescopium',
  'TRA': 'Triangulum Australe',
  'TRI': 'Triangulum',
  'TUC': 'Tucana',
  'UMA': 'Ursa Major',
  'UMI': 'Ursa Minor',
  'VEL': 'Vela',
  'VIR': 'Virgo',
  'VOL': 'Volans',
  'VUL': 'Vulpecula',
};

/// Full constellation name for [abbreviation], or the input unchanged when it
/// is not a recognised IAU abbreviation (some catalogs already store the full
/// name, and a few carry junk — neither should render as an empty label).
String constellationFullName(String abbreviation) {
  final key = abbreviation.trim().toUpperCase();
  return kConstellationNamesByAbbreviation[key] ?? abbreviation.trim();
}
