// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../device.dart';
import '../../error.dart';
import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Start camera exposure
/// This delegates to api_camera_start_exposure which handles the full exposure
/// workflow including waiting for completion, image processing, and storage.
Future<void> startExposure(
        {required String deviceId,
        required double durationSecs,
        required int gain,
        required int offset,
        required int binX,
        required int binY}) =>
    RustLib.instance.api.crateApiDevicesCameraStartExposure(
        deviceId: deviceId,
        durationSecs: durationSecs,
        gain: gain,
        offset: offset,
        binX: binX,
        binY: binY);

/// Abort/cancel camera exposure
Future<void> cancelExposure({required String deviceId}) => RustLib.instance.api
    .crateApiDevicesCameraCancelExposure(deviceId: deviceId);

/// Get camera status
Future<CameraStatus> getCameraStatus({required String deviceId}) =>
    RustLib.instance.api
        .crateApiDevicesCameraGetCameraStatus(deviceId: deviceId);

/// Set camera cooler
Future<void> setCameraCooler(
        {required String deviceId, required int enabled, double? targetTemp}) =>
    RustLib.instance.api.crateApiDevicesCameraSetCameraCooler(
        deviceId: deviceId, enabled: enabled, targetTemp: targetTemp);

/// Set camera readout mode by index
///
/// mode_index: 0 = default/high quality, 1 = fast readout, etc.
/// The available modes are camera-dependent.
Future<void> apiCameraSetReadoutMode(
        {required String deviceId, required int modeIndex}) =>
    RustLib.instance.api.crateApiDevicesCameraApiCameraSetReadoutMode(
        deviceId: deviceId, modeIndex: modeIndex);

/// Set camera binning
Future<void> apiSetCameraBinning(
        {required String deviceId, required int binX, required int binY}) =>
    RustLib.instance.api.crateApiDevicesCameraApiSetCameraBinning(
        deviceId: deviceId, binX: binX, binY: binY);
