// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../device.dart';
import '../../error.dart';
import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `abort_sim_exposure`, `advance_sim_cooler`, `advance_sim_guide_pulse`, `advance_sim_slew`, `angular_separation_deg`, `apply_offset_delta`, `begin_sim_exposure`, `begin_sim_slew`, `cancel_sim_slew`, `drift_step_secs`, `filter_wheel_status_poll_states`, `get_sim_camera`, `get_sim_dome`, `get_sim_filterwheel`, `get_sim_last_exposure`, `get_sim_mount`, `get_sim_safety_monitor`, `get_sim_weather`, `interpolate_ra`, `next_sim_frame_seed`, `pier_side_after_slew_to`, `poll_filter_wheel_position`, `reset_sim_guide_offset`, `sim_camera_state`, `sim_cooler_last_tick`, `sim_drift_last_tick`, `sim_exposure_elapsed_is_complete`, `sim_exposure_is_complete`, `sim_exposure_phase`, `sim_guide_offset_px`, `sim_guide_offset`, `sim_local_sidereal_time`, `sim_park_position`, `sim_pulse_delta`, `sim_slew_duration_secs`, `sim_slew`, `take_sim_exposure_for_download`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FilterWheelStatusPollState`, `SimExposurePhase`, `SimExposureRequest`, `SimSlew`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_sim_focuser`, `get_sim_rotator`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`, `default`

/// Get camera status
Future<CameraStatus> apiGetCameraStatus({required String deviceId}) => RustLib
    .instance
    .api
    .crateApiDevicesSimulationApiGetCameraStatus(deviceId: deviceId);

/// Set camera cooling target
Future<void> apiSetCameraCooler({
  required String deviceId,
  required int enabled,
  double? targetTemp,
}) => RustLib.instance.api.crateApiDevicesSimulationApiSetCameraCooler(
  deviceId: deviceId,
  enabled: enabled,
  targetTemp: targetTemp,
);

/// Set camera gain
Future<void> apiSetCameraGain({required String deviceId, required int gain}) =>
    RustLib.instance.api.crateApiDevicesSimulationApiSetCameraGain(
      deviceId: deviceId,
      gain: gain,
    );

/// Set camera offset
Future<void> apiSetCameraOffset({
  required String deviceId,
  required int offset,
}) => RustLib.instance.api.crateApiDevicesSimulationApiSetCameraOffset(
  deviceId: deviceId,
  offset: offset,
);

/// Get mount status
Future<MountStatus> apiGetMountStatus({required String deviceId}) => RustLib
    .instance
    .api
    .crateApiDevicesSimulationApiGetMountStatus(deviceId: deviceId);

/// Slew mount to coordinates
Future<void> apiMountSlewToCoordinates({
  required String deviceId,
  required double ra,
  required double dec,
}) => RustLib.instance.api.crateApiDevicesSimulationApiMountSlewToCoordinates(
  deviceId: deviceId,
  ra: ra,
  dec: dec,
);

/// Sync mount to coordinates
Future<void> apiMountSyncToCoordinates({
  required String deviceId,
  required double ra,
  required double dec,
}) => RustLib.instance.api.crateApiDevicesSimulationApiMountSyncToCoordinates(
  deviceId: deviceId,
  ra: ra,
  dec: dec,
);

/// Park the mount
Future<void> apiMountPark({required String deviceId}) => RustLib.instance.api
    .crateApiDevicesSimulationApiMountPark(deviceId: deviceId);

/// Unpark the mount
Future<void> apiMountUnpark({required String deviceId}) => RustLib.instance.api
    .crateApiDevicesSimulationApiMountUnpark(deviceId: deviceId);

/// Set mount tracking
Future<void> apiMountSetTracking({
  required String deviceId,
  required int enabled,
}) => RustLib.instance.api.crateApiDevicesSimulationApiMountSetTracking(
  deviceId: deviceId,
  enabled: enabled,
);

/// Slew mount to alt/az coordinates (simulator handler)
Future<void> apiMountSlewAltAz({
  required String deviceId,
  required double altitude,
  required double azimuth,
}) => RustLib.instance.api.crateApiDevicesSimulationApiMountSlewAltAz(
  deviceId: deviceId,
  altitude: altitude,
  azimuth: azimuth,
);

/// Find mount home position (simulator handler)
Future<void> apiMountFindHome({required String deviceId}) => RustLib
    .instance
    .api
    .crateApiDevicesSimulationApiMountFindHome(deviceId: deviceId);

/// Pulse guide the mount in a direction for a duration
Future<void> apiMountPulseGuide({
  required String deviceId,
  required String direction,
  required int durationMs,
}) => RustLib.instance.api.crateApiDevicesSimulationApiMountPulseGuide(
  deviceId: deviceId,
  direction: direction,
  durationMs: durationMs,
);

/// Get focuser status
Future<FocuserStatus> apiGetFocuserStatus({required String deviceId}) => RustLib
    .instance
    .api
    .crateApiDevicesSimulationApiGetFocuserStatus(deviceId: deviceId);

/// Move focuser to position
Future<void> apiFocuserMoveTo({
  required String deviceId,
  required int position,
}) => RustLib.instance.api.crateApiDevicesSimulationApiFocuserMoveTo(
  deviceId: deviceId,
  position: position,
);

/// Move focuser by relative amount
Future<void> apiFocuserMoveRelative({
  required String deviceId,
  required int delta,
}) => RustLib.instance.api.crateApiDevicesSimulationApiFocuserMoveRelative(
  deviceId: deviceId,
  delta: delta,
);

/// Halt focuser
Future<void> apiFocuserHalt({required String deviceId}) => RustLib.instance.api
    .crateApiDevicesSimulationApiFocuserHalt(deviceId: deviceId);

/// Get filter wheel status
Future<FilterWheelStatus> apiGetFilterwheelStatus({required String deviceId}) =>
    RustLib.instance.api.crateApiDevicesSimulationApiGetFilterwheelStatus(
      deviceId: deviceId,
    );

/// Set filter wheel position
Future<void> apiFilterwheelSetPosition({
  required String deviceId,
  required int position,
}) => RustLib.instance.api.crateApiDevicesSimulationApiFilterwheelSetPosition(
  deviceId: deviceId,
  position: position,
);

/// Get filter names
Future<List<String>> apiFilterwheelGetNames({required String deviceId}) =>
    RustLib.instance.api.crateApiDevicesSimulationApiFilterwheelGetNames(
      deviceId: deviceId,
    );

/// Set filter by name
Future<void> apiFilterwheelSetByName({
  required String deviceId,
  required String name,
}) => RustLib.instance.api.crateApiDevicesSimulationApiFilterwheelSetByName(
  deviceId: deviceId,
  name: name,
);

/// Set filter names on a filter wheel
/// This pushes user-defined filter names from the equipment profile to the hardware driver.
Future<void> apiFilterwheelSetFilterNames({
  required String deviceId,
  required List<String> names,
}) =>
    RustLib.instance.api.crateApiDevicesSimulationApiFilterwheelSetFilterNames(
      deviceId: deviceId,
      names: names,
    );

/// Get rotator status
Future<RotatorStatus> apiGetRotatorStatus({required String deviceId}) => RustLib
    .instance
    .api
    .crateApiDevicesSimulationApiGetRotatorStatus(deviceId: deviceId);

/// Move rotator to angle
Future<void> apiRotatorMoveTo({
  required String deviceId,
  required double angle,
}) => RustLib.instance.api.crateApiDevicesSimulationApiRotatorMoveTo(
  deviceId: deviceId,
  angle: angle,
);

/// Move rotator relative
Future<void> apiRotatorMoveRelative({
  required String deviceId,
  required double delta,
}) => RustLib.instance.api.crateApiDevicesSimulationApiRotatorMoveRelative(
  deviceId: deviceId,
  delta: delta,
);

/// Set the rotator's reverse-direction flag (IRotatorV3 `Reverse`, Alpaca
/// `reverse`, INDI `ROTATOR_REVERSE`).
Future<void> apiRotatorSetReverse({
  required String deviceId,
  required bool reverse,
}) => RustLib.instance.api.crateApiDevicesSimulationApiRotatorSetReverse(
  deviceId: deviceId,
  reverse: reverse,
);

/// Halt rotator
Future<void> apiRotatorHalt({required String deviceId}) => RustLib.instance.api
    .crateApiDevicesSimulationApiRotatorHalt(deviceId: deviceId);

/// Sync rotator's reported sky angle to the supplied position angle without
/// moving the hardware. Used by the "Sync to image PA" workflow after a plate
/// solve: the solver returns the astrometric PA of the captured frame and
/// this call aligns the rotator's reported PA so subsequent absolute moves
/// land at the correct sky angle.
Future<void> apiRotatorSyncToPa({
  required String deviceId,
  required double pa,
}) => RustLib.instance.api.crateApiDevicesSimulationApiRotatorSyncToPa(
  deviceId: deviceId,
  pa: pa,
);

class SimulatedCamera {
  final CameraStatus status;

  const SimulatedCamera({required this.status});

  static Future<SimulatedCamera> default_() =>
      RustLib.instance.api.crateApiDevicesSimulationSimulatedCameraDefault();

  @override
  int get hashCode => status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimulatedCamera &&
          runtimeType == other.runtimeType &&
          status == other.status;
}

class SimulatedDome {
  final DomeStatus status;

  const SimulatedDome({required this.status});

  static Future<SimulatedDome> default_() =>
      RustLib.instance.api.crateApiDevicesSimulationSimulatedDomeDefault();

  @override
  int get hashCode => status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimulatedDome &&
          runtimeType == other.runtimeType &&
          status == other.status;
}

class SimulatedFilterWheel {
  final FilterWheelStatus status;

  const SimulatedFilterWheel({required this.status});

  static Future<SimulatedFilterWheel> default_() => RustLib.instance.api
      .crateApiDevicesSimulationSimulatedFilterWheelDefault();

  @override
  int get hashCode => status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimulatedFilterWheel &&
          runtimeType == other.runtimeType &&
          status == other.status;
}

class SimulatedFocuser {
  final FocuserStatus status;

  const SimulatedFocuser({required this.status});

  static Future<SimulatedFocuser> default_() =>
      RustLib.instance.api.crateApiDevicesSimulationSimulatedFocuserDefault();

  @override
  int get hashCode => status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimulatedFocuser &&
          runtimeType == other.runtimeType &&
          status == other.status;
}

class SimulatedMount {
  final MountStatus status;

  const SimulatedMount({required this.status});

  static Future<SimulatedMount> default_() =>
      RustLib.instance.api.crateApiDevicesSimulationSimulatedMountDefault();

  @override
  int get hashCode => status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimulatedMount &&
          runtimeType == other.runtimeType &&
          status == other.status;
}

class SimulatedRotator {
  final RotatorStatus status;

  const SimulatedRotator({required this.status});

  static Future<SimulatedRotator> default_() =>
      RustLib.instance.api.crateApiDevicesSimulationSimulatedRotatorDefault();

  @override
  int get hashCode => status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimulatedRotator &&
          runtimeType == other.runtimeType &&
          status == other.status;
}

class SimulatedSafetyMonitor {
  final SafetyStatus status;

  const SimulatedSafetyMonitor({required this.status});

  static Future<SimulatedSafetyMonitor> default_() => RustLib.instance.api
      .crateApiDevicesSimulationSimulatedSafetyMonitorDefault();

  @override
  int get hashCode => status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimulatedSafetyMonitor &&
          runtimeType == other.runtimeType &&
          status == other.status;
}

class SimulatedWeather {
  final bool connected;
  final WeatherConditions conditions;

  const SimulatedWeather({required this.connected, required this.conditions});

  static Future<SimulatedWeather> default_() =>
      RustLib.instance.api.crateApiDevicesSimulationSimulatedWeatherDefault();

  @override
  int get hashCode => connected.hashCode ^ conditions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimulatedWeather &&
          runtimeType == other.runtimeType &&
          connected == other.connected &&
          conditions == other.conditions;
}
