import 'dart:convert';
import 'dart:io';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:nightshade_desktop/headless_api/handlers/flat_wizard_handlers.dart';
import 'package:shelf/shelf.dart';

void main() {
  group('FlatWizardHandlers', () {
    late ProviderContainer container;
    late FlatWizardHandlers handlers;

    setUp(() {
      container = ProviderContainer();
      handlers = FlatWizardHandlers(container);
    });

    tearDown(() {
      container.dispose();
    });

    test('generate sequence returns JSON helper response', () async {
      final response = await handlers.handleGenerateSequence(
        Request(
          'POST',
          Uri.parse('http://localhost/api/flat-wizard/generate-sequence'),
          body: jsonEncode({
            'calibrations': [
              {
                'filter': 'L',
                'exposure': 1.5,
                'adu': 30000.0,
                'success': true,
                'iterations': 3,
              },
              {
                'filter': 'R',
                'exposure': 2.0,
                'adu': 29000.0,
                'success': false,
                'iterations': 5,
                'errorMessage': 'outside tolerance',
              },
            ],
            'framesPerFilter': 20,
            'sequenceName': 'Test Flats',
            'description': 'Generated by handler test',
            'onlySuccessful': true,
          }),
        ),
      );

      expect(response.statusCode, HttpStatus.ok);
      expect(response.headers['content-type'], 'application/json');
      final body = jsonDecode(await response.readAsString()) as Map;
      final sequence = body['sequence'] as Map;
      expect(sequence['name'], 'Test Flats');
      expect(sequence['rootNodeId'], isA<String>());
      final nodes = sequence['nodes'] as Map;
      expect(nodes.length, 2);
      expect(
        nodes.values.where(
          (node) => node is Map && node['type'] == 'ExposureNode',
        ),
        hasLength(1),
      );
    });

    test('calibrate filter malformed body returns JSON internal server error',
        () async {
      final response = await handlers.handleCalibrateFilter(
        Request(
          'POST',
          Uri.parse('http://localhost/api/flat-wizard/calibrate'),
          body: jsonEncode({'deviceId': 'camera-1'}),
        ),
      );

      expect(response.statusCode, HttpStatus.internalServerError);
      expect(response.headers['content-type'], 'application/json');
      final body = jsonDecode(await response.readAsString()) as Map;
      expect(body['error'], isA<String>());
    });

    test('quick calibrate malformed body returns JSON internal server error',
        () async {
      final response = await handlers.handleQuickCalibrate(
        Request(
          'POST',
          Uri.parse('http://localhost/api/flat-wizard/quick-calibrate'),
          body: jsonEncode({'deviceId': 'camera-1'}),
        ),
      );

      expect(response.statusCode, HttpStatus.internalServerError);
      expect(response.headers['content-type'], 'application/json');
      final body = jsonDecode(await response.readAsString()) as Map;
      expect(body['error'], isA<String>());
    });
  });
}
